### ISSUE TITLE
Provide a container builder to use with ConfigureHostBuilder.ConfigureContainer<TContainerBuilder> Method

### ISSUE THREAD

**Issue by paulomorgado** [simpleinjector/SimpleInjector#1004]
Currently, SimpleInjector in .NET feels like an afterthought.

By providing a container builder to use [`ConfigureHostBuilder.ConfigureContainer<TContainerBuilder>` Method](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.configurehostbuilder.configurecontainer), it will be possible to plug into the host and web application creation pipeline to change service registrations (e.g. for tests).

**Comment by dotnetjunkie** [comment]
It might feel like an afterthought, but it certainly isn't. Our current implementation is a very well-thought carefully designed implementation considering the constraints we're dealing with.

To understand why this is, please make yourself acquaintable with the following posts:

* [What’s wrong with the ASP.NET Core DI abstraction?](https://blog.simpleinjector.org/2016/06/whats-wrong-with-the-asp-net-core-di-abstraction/)
* [Working around the ASP.NET Core DI abstraction](https://blog.simpleinjector.org/2016/07/working-around-the-asp-net-core-di-abstraction/)

Because of the above, we simply can't implement your feature request and I will, therefore, close this issue.
