### ISSUE TITLE
Registering Boo via IFactory<Boo> and then verifying causes factory to be called

### ISSUE THREAD

**Issue by abatishchev** [simpleinjector/SimpleInjector#107]
I have the following code:
```csharp
class Program
{
	static void Main()
	{
		var container = new Container();

		container.Register<IFactory<Boo>, BooFactory>(Lifestyle.Singleton);
		container.Register<Boo>(() => container.GetInstance<BooFactory>().Create(),
			Lifestyle.Singleton);

		container.Verify();

		var boo = container.GetInstance<Boo>();
	}
}

interface IFactory<T>
{
	T Create();
}

class Boo
{
}

class BooFactory : IFactory<Boo>
{
	public Boo Create()
	{
		Console.WriteLine("Runtime!");
		return new Boo();
	}
}
```

that makes possible to inject `Boo` but `IFactory<Boo>.Create()` will be called instead,

I have two issues with it:

- When call `Verify(VerificationOption.VerifyOnly)`, the factory will be called prematurely. If `Create()` by some reason may be called only in runtime, this will complicate the testing environment.
- When call `Verify(VerificationOption.VerifyAndDiagnose)` I'm getting the following errors:

>-[Ambiguous Lifestyles] The registration for IFactory<Boo> (**Singleton**) maps to the same implementation (BooFactory) as the registration for BooFactory (**Transient**) does, but the registration maps to a different lifestyle. This will cause each registration to resolve to a different instance.
>-[Ambiguous Lifestyles] The registration for BooFactory (**Transient**) maps to the same implementation (BooFactory) as the registration for IFactory<Boo> (**Singleton**) does, but the registration maps to a different lifestyle. This will cause each registration to resolve to a different instance.

**Comment by abatishchev** [comment]
If I change the registration to this (note Singleton on the end):
```
container.Register<Boo>(() => container.GetInstance<BooFactory>().Create(), Lifestyle.Singleton);
```
I'm still getting the same errors:
>-[Ambiguous Lifestyles] The registration for IFactory<Boo> (**Singleton**) maps to the same implementation (BooFactory) as the registration for BooFactory (**Transient**) does, but the registration maps to a different lifestyle. This will cause each registration to resolve to a different instance.
>-[Ambiguous Lifestyles] The registration for BooFactory (**Transient**) maps to the same implementation (BooFactory) as the registration for IFactory<Boo> (**Singleton**) does, but the registration maps to a different lifestyle. This will cause each registration to resolve to a different instance.

**Comment by abatishchev** [comment]
If I change the registration to this (not the concrete class but an interface):
```csharp
container.Register<Boo>(() => container.GetInstance<IFactory<Boo>>().Create(), Lifestyle.Transient);
```
The error are gone. What is the design behind this?

**Comment by dotnetjunkie** [comment]
> When call Verify(VerificationOption.VerifyOnly), the factory will be called prematurely.

That's because Simple Injector will verify all registrations, including the registrations that are registered with a delegate, such as `Register<T>(Func<T>)`. Simple Injector expects to be in control over the created instances; this means that properties get injected, initializers (`RegisterInitializer<T>`) are applied, and the instance is disposed in case it has a scoped or singleton lifestyle.

In case the `Boo` instance is really something that can't be created during application startup, either you are violating the [Injection Constructors Should Be Simple](http://blog.ploeh.dk/2011/03/03/InjectionConstructorsshouldbesimple/) principle or the class should not be part of your object graph and should be resolved using a factory or provider.

And using a factory is of course what you are already doing, so that means that consumer simply should get the factory injected and call its `Create` method.

> The registration for IFactory (Singleton) maps to the same implementation (BooFactory) as the registration for BooFactory (Transient) does, but the registration maps to a different lifestyle. This will cause each registration to resolve to a different instance.

The warning message is correct. It tells you you are resolving the unregistered type `BooFactory`. Since this `BooFactory` is unregistered, Simple Injector will return you a transient instance. But Simple Injector detects that there is actually a registration for `IFactory<Boo>` that maps to `BooFactory` but with a different lifestyle. Although you might not really care about the lifestyle, accidentally having a transient `BooFactory` could as well cause problems (especially since you explicitly registered `BooFactory` as singleton), so its correct that Simple Injector warns you about this.

What's happening here is that the supplied `TService` for any given registration is used as key in the internal dictionary. This means that when some type is resolved, the requested type is looked up in the internal dictionary. In your case you registered an `IFactory<Boo>`, but later on you requested a `BooFactory` which is no available as key in the internal dictionary. Most containers behave the same. Only Microsoft's Unity has different behavior.

You can solve this by changing your code to the following:

``` c#
// Note that we're now calling GetInstance<IFactory<Boo>>() instead of GetInstance<BooFactory>().
container.Register<Boo>(() => container.GetInstance<IFactory<Boo>>().Create(),
    Lifestyle.Singleton);
```

**Comment by abatishchev** [comment]
Thanks a lot!

This was the answer:

>Since this BooFactory is unregistered, Simple Injector will return you a transient instance.

And this was the solution:

```csharp
container.Register<Boo>(() => container.GetInstance<IFactory<Boo>>().Create(), Lifestyle.Singleton);
```

I found it by myself, too. The properly phrased question is the halfway to the answer :)

**Comment by abatishchev** [comment]
Is there a way to skip particular service verification?

**Comment by dotnetjunkie** [comment]
Nope.

**Comment by dotnetjunkie** [comment]
The need to suppress verification of a component, this is an indication that there is something wrong with the registration. The two most common errors are:
- The constructor of the component does too much.
- The component should not be part of the object graph.

Constructors of components that are part of your object graphs should be really simple, as Mark Seemann clearly explained [here](http://blog.ploeh.dk/2011/03/03/InjectionConstructorsshouldbesimple/).

Components that are out of your control (such as third-party library components) do not belong in the object graph. Injecting them into the object graph will violate the [DIP](https://en.wikipedia.org/wiki/Dependency_inversion_principle) and often [ISP](https://en.wikipedia.org/wiki/Interface_segregation_principle) as well. Those objects often contain request-specific state which causes the whole object graph to become transient.

Instead of injecting those third-party components into constructors of your components, hide them behind one or multiple application-specific abstractions. This way you can implement an [Adapter](https://en.wikipedia.org/wiki/Adapter_pattern). If the third-party component is costly to create, impossible to verify during startup, isn't thread-safe, or contains request specific data, you can inject a provider delegate (such as `Func<ThirdParty.Comp>`) into the adapter. This allows the adapter to get the correct instance at runtime.
