### ISSUE TITLE
Updated from 3.0.3 to 3.0.4, exception using open generics and AllowOverridingRegistrations.

### ISSUE THREAD

**Issue by theonlylawislove** [simpleinjector/SimpleInjector#116]
> Exception thrown: 'System.NotSupportedException' in SimpleInjector.dll
Additional information: The making of conditional registrations is not supported when AllowOverridingRegistrations is set, because it is impossible for the container to detect whether the registration should replace a different registration or not.

```
var container = new Container();
container.Options.AllowOverridingRegistrations = true;
...
container.RegisterSingleton(typeof (ISettingsProvider<>), typeof (JsonFileSettingsProvider<>));
```

Why is this not supported? It worked on 3.0.3 just fine.

**Comment by theonlylawislove** [comment]
If it wasn't clear, this worked in 3.0.3.

**Comment by theonlylawislove** [comment]
This relates to #114, I believe.

**Comment by dotnetjunkie** [comment]
I think the detection mechanism is a bit too strict here. What's happening is that the supplied generic type has type constraints, making it a conditional registration. Simple Injector can't determine if this registration should override another registration or append the existing set of registrations.

In your case however, the check should have been ignored, because there are no overlapping registrations for the fiveb registration.

**Comment by dotnetjunkie** [comment]
I've pushed v3.0.5 of the SimpleInjector.Extensions.ExecutionContextScoping library to Github and Nuget. The assembly now contains the correct version number (and will continue to do so in future versions).

**Comment by theonlylawislove** [comment]
Thanks!
