### ISSUE TITLE
Does Simple Injector support Aggregate Services?

### ISSUE THREAD

**Issue by CrisisWhatCrisis** [simpleinjector/SimpleInjector#124]
I have a solution that uses an aggregate service (simple example is shown below) to hold a number of interfaces, does Simple Injector support the registration of aggregate services?

``` c#
    public interface IExtractorContainer
    {
        IMhs001Extractor Mhs001Extractor { get; }
        IMhs101Extractor Mhs101Extractor { get; }
    }
```

So, I really want to do something like:

`container.RegisterAggregateService<IExtractorContainer>();`

Thanks in advance
Mick

**Comment by dotnetjunkie** [comment]
If I correctly understand, you want to define an interface and let Simple Injector automatically generate an implementation on the background for you that injects the required dependencies and map that to the properties of the abstraction. 

Simple Injector does not have an ability to auto-generate types for you. As you probably know, doing this by hand is usually very easy and would look like this:

``` c#
public class ExtractorContainer : IExtractorContainer {
    public ExtractorContainer(IMhs001Extractor a, IMhs101Extractor b) {
        this.Mhs001Extractor = a;
        this.Mhs101Extractor = b;
    }
    public IMhs001Extractor Mhs001Extractor { get; private set; }
    public IMhs101Extractor Mhs101Extractor { get; private set; }
}

// Registration
container.Register<IExtractorContainer, ExtractorContainer>();
```

Do note that if you are referring to the [Aggregate Services definition](blog.ploeh.dk/2010/02/02/RefactoringtoAggregateServices/) as Mark Seemann describes them, what you are defining is not an aggregate service. To be an aggregate service, the component should encapsulate the logic of the aggregated services and define a new API for the consumer to use, without exposing the its aggregates services to its consumers. So in that case an aggregate service is nothing more than a regular service, and it's in fact a refactoring pattern; after you are done with the refactoring you can't really see that you extracted the logic into an aggregate service.

Wrapping services together and exposing them through properties of another service, as you are doing, is typically a bad idea, because it doesn't really solve anything. Although you fix constructor over-injection issues, you don't address the root cause, which is a violating the Single Responsibility Principle. So although you reduce the number of injected dependencies, you don't reduce the actual number of dependencies a class has, nor its complexity. To make this clear, look at it from a testing perspective. When we test the consuming class, we have to supply it with the aggregate service, in the test we still have to supply the aggregate with all the fake versions of all the dependencies the class needs as well. Instead of making our code easier to test, we actually make it harder to do so.

Because of this, I would advice to go with the real Aggregate Service approach that Mark Seemann describes, and prevent exposing the aggregated services from the Aggregate Service. In general I would even say that you should *never* expose a service in another service's contract. Do don't return serices from other services. Service abstractions that expose other services, don't lower the complexity for the consumer (which is what an abstraction is supposed to do); it only increases complexity because it increases the number of dependencies a consumer has to know about. For this same reason, having abstract factory classes that return services is a bad idea; you just increase complexity.
