### ISSUE TITLE
Simple Injector with Web API in .NET 4.0

### ISSUE THREAD

**Issue by emilianionascu** [simpleinjector/SimpleInjector#134]
Is there a way to use SimpleInjector with WebApi in .NET 4.0?

**Comment by dotnetjunkie** [comment]
As [expressed in the integration guide](https://simpleinjector.readthedocs.org/en/latest/webapiintegration.html), the Web API integration package for Simple Injector requires .NET 4.5 or later. Main reason for this is that the `WebApiRequestLifestyle` makes use of the framework's `CallContext.LogicalGetData` method, which behaves different under .NET 4.0, as explained [here](https://stackoverflow.com/a/22404267/264697).

The `WebApiRequestLifestyle` is designed to work with Web API regardless of how it is hosted (both in IIS or self-hosted). If however your intention is to use Web API solely in an IIS-hosted environment, you can as well use the `WebRequestLifestyle`, which actually supports .NET 4.0. The differences between both lifestyles are explained [here](https://simpleinjector.readthedocs.org/en/latest/lifetimes.html#web-api-request-lifestyle-vs-web-request-lifestyle).

So to get Web API working under .NET 4.0, you only need to do two things:

 1. Create your own `IDependencyResolver` implementation that resolves instances from the container.
 2. Register scoped instances using the `WebRequestLifestyle`, preferably by setting the lifestyle as the default scoped lifestyle using `Container.Options.DefaultScopedLifestyle`.

Your custom dependency resolver will look as follows:

``` c#
public class SimpleInjectorHttpDependencyResolver : IDependencyResolver {
    private readonly IServiceProvider provider; 
    public SimpleInjectorHttpDependencyResolver(Container container) { 
        this.provider = container; 
    } 
    public System.Web.Http.Dependencies.IDependencyScope BeginScope() { 
        return this; 
    } 
    public object GetService(Type serviceType) { 
        return this.provider.GetService(serviceType);
    } 
    public IEnumerable<object> GetServices(Type serviceType) {
        Type collectionType = typeof(IEnumerable<>).MakeGenericType(serviceType);
        var collection = (IEnumerable<object>)this.provider.GetService(collectionType);
        return collection ?? Enumerable.Empty<object>();
    }
    public void Dispose() { } 
}
```
This `SimpleInjectorHttpDependencyResolver` can be hooked into Web API as follows:

``` c#
GlobalConfiguration.Configuration.DependencyResolver =
    new SimpleInjectorHttpDependencyResolver(container);
```

This custom `IDependencyResolver` does not begin or end any scope, because the `WebRequestLifestyle` will do this automatically for you on the beginning and ending of the web request. The only thing you will have to do is make the `WebRequestLifestyle` the default scoped lifestyle:

``` c#
var container = new Container();
container.Options.DefaultScopedLifestyle = new WebRequestLifestyle();

// Use Lifestyle.Scoped to make registrations using the web request lifestyle
container.Register<IUnitOfWork, EfUnitOfWork>(Lifestyle.Scoped);
```
