### ISSUE TITLE
SimpleInjectorServiceHostFactory Doesn't Provide Decorated Instance

### ISSUE THREAD

**Issue by JarrodJ83** [simpleinjector/SimpleInjector#139]
I'm having an issue in a WCF service where I apply some decorators but when I call the service the decorated instance is not returned by the `SimpleInjectorServiceHostFactory`. My registration  takes place in `Application_Start` and looks like this:

``` c#
var container = new Container();
container.Options.DefaultScopedLifestyle = new WcfOperationLifestyle();

// other registrations...

container.Register(typeof(IRaiseAlertByEvent), typeof(AlertInstanceManager));
container.RegisterDecorator(typeof(IRaiseAlertByEvent), typeof(TimedRaiseAlertByEventDecorator));
            
SimpleInjectorServiceHostFactory.SetContainer(container); 
```

If I call `container.GetInstance<IRaiseAlertByEvent>()` right after this I get a `TimedRaiseAlertByEventDecorator` instance as expected. However, when I invoke the service I do not hit any breakpoints in my `TimedRaiseAlertByEventDecorator` leading me to believe the `AlertInstanceManager` type is what was created by the host factory instead of my decorated type.

Any ideas? I believe I'm doing things correctly and have used decorators before without issue. This is the first time I've used them with a WCF service though. I've double checked and the `Factory="SimpleInjector.Integration.Wcf.SimpleInjectorServiceHostFactory, SimpleInjector.Integration.Wcf"` is specified in my svc file.

Thanks in advance!
- Jarrod

**Comment by dotnetjunkie** [comment]
Please show the code for the WCF service. Also make sure that:

 - You register all your WCF service classes in Simple Injector explicitly.
 - You verify the container by calling `container.Verify()`.

**Comment by JarrodJ83** [comment]
I was not calling RegisterWcfServices before. I've added this right after I register my decorators but it has not resolved the issue. I also called Verify and got some warnings about "Potential Single Responsibility Violations" and "Disposable Transient Components" but no exception was thrown by the call.

Here is the contract:

    [ServiceContract(Namespace = Namespaces.V1)]
    public interface IRaiseAlertByEvent
    {
        [OperationContract]
        void HandleRaiseAlertFromEvent(RaiseAlertFromEventData dto);
    }

Here is the decorator:

    public class TimedRaiseAlertByEventDecorator : IRaiseAlertByEvent
    {
        ILogger Logger;
        IRaiseAlertByEvent DecoratedSvc;
        public TimedRaiseAlertByEventDecorator(ILogger logger, 
            IRaiseAlertByEvent decoratedSvc)
        {
            this.Logger = logger;
            this.DecoratedSvc = decoratedSvc;
        }

        public void HandleRaiseAlertFromEvent(RaiseAlertFromEventData dto)
        {
            Logger.Debug("TimedRaiseAlertByEventDecorator");
            this.DecoratedSvc.HandleRaiseAlertFromEvent(dto);         
        }
    }

Here is a slimmed down version of the service:

    public class AlertInstanceManager : IDismissAlertByEvent, IDismissAlertBySystem, IRaiseAlertByEvent
    {
        void IRaiseAlertByEvent.HandleRaiseAlertFromEvent(RaiseAlertFromEventData raiseAlertData)
        {
              // breakpoint here gets hit but not decorator
        }
    }

**Comment by dotnetjunkie** [comment]
How does the constructor of `AlertInstanceManager` look like?

**Comment by JarrodJ83** [comment]
It's rather large. I probably need to refactor but haven't had time.

    public AlertInstanceManager(
            IReadOnlyContextFactory readContextFactory,
            IWritableContextFactory readWriteContextFactory,
            IQueryHandler<Queries.AlertTypeForTransition,     DomainModel.AlertTypeCorrelationInfoForTransition> qryAlertTypeForTransition,            
            IQueryHandler<Queries.ActiveAlertInstanceByCorrelationKeyAndAction, DomainModel.ActiveAlertInstanceInfo> qryActiveAlertInstanceByCorrelationKeyAndAction,
            IQueryHandler<Queries.ExtendedDataKeyValuePairs, Dictionary<string, string>> qryExtendedDataKeyValuePairs,
            ICommandHandler<Command.RaiseAlertInstance, AlertInstanceState> raiseAlertInstanceHandler,
            ICommandHandler<Command.DismissActiveAlertInstance> dismissActiveAlertInstanceHandler,
            ICommandHandler<Command.AppendEventDataToActiveInstnace> appendEventDataToActiveInstnaceHandler,
            IQueryHandler<Queries.ActiveInstanceByAlertInstanceId, DomainModel.ActiveAlertInstanceInfo> qryActiveInstanceByAlertInstanceId,
            IIvmsEventHandler<SendAlertInstanceStateChangedEvent> sendAlertInstanceStateChangedEventHandler,
            IQueryHandler<Queries.CorrelationKeyInfoByCorrelationKeyAlertType, int?> qryCorrelationKeyInfoByCorrelationKeyAlertType,
            Serilog.ILogger logger,
            IContextInterogator contextInterogator
            )
        {
            this.ReadOnlyContextFactory = readContextFactory;
            this.WritableContextFactory = readWriteContextFactory;
            this.QryActiveAlertInstanceByCorrelationKeyAndAction = qryActiveAlertInstanceByCorrelationKeyAndAction;
            this.QryExtendedDataKeyValuePairs = qryExtendedDataKeyValuePairs;
            this.SendAlertInstanceStateChangedEventHandler = sendAlertInstanceStateChangedEventHandler;
            this.QryActiveInstanceByAlertInstanceId = qryActiveInstanceByAlertInstanceId;
            this.RaiseAlertInstanceHandler = raiseAlertInstanceHandler;
            this.QryAlertTypeForTransition = qryAlertTypeForTransition;
            this.DismissActiveAlertInstanceHandler = dismissActiveAlertInstanceHandler;
            this.AppendEventDataToActiveInstnaceHandler = appendEventDataToActiveInstnaceHandler;
            this.QryCorrelationKeyInfoByCorrelationKeyAlertType = qryCorrelationKeyInfoByCorrelationKeyAlertType;
            this.Logger = logger;
            this.ContextInterogator = contextInterogator;
        }

**Comment by dotnetjunkie** [comment]
Ah, I see, the `AlertInstanceManager` is your WCF service. Registering decorators for abstractions that your WCF service defines have no effect, because WCF asks Simple Injector for the `AlertInstanceManager` directly, instead of asking for the `IAlertInstanceManager`. WCF asks for an `AlertInstanceManager`, since you configured the service using `<%@ ServiceHost Service="AlertInstanceManager" %>`. 

Since Simple Injector is asked for a concrete type, it is forced to return that concrete type (or one of its sub types). Your `TimedRaiseAlertByEventDecorator` however, does not implement `AlertInstanceManager` (instead it implements the `IAlertInstanceManager` abstraction).

Although you could try to change the `Service` property of the `ServiceHost` tag to point at the interface, this will not work, because both the default WCF ServiceHostFactory and the `SimpleInjectorServiceHostFactory` are limited to working with concrete types. Changing the `Service` property to the interface will cause your application to fail at runtime.

But not all hope is lost, because you are already applying the [command handler](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=91) and [query handler](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=92) patterns. While you choose your achitecture to be highly flexible, maintainable and SOLID, you unfortunately didn't choose to do so at the web service boundary. At the WCF layer you still have an enormous layer of overhead. The WCF classes are big, are hard to maintain (because Single Responsibility Principle is violated) and need constant updating. So what you are missing here is the advice laid out in [this article](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=95). 

After applying the advice from that article, you will have a WCF service that will require no constant maintenance and as such does not require any decorators to be applied. Instead, decorators can be applied at the level of the command handlers and query handlers.

I apply this technique for several years now and it allowed massive WCF service to be built and maintained without ANY effort. The overhead is close to 0, and I can highly advice moving into that direction.

**Comment by JarrodJ83** [comment]
Thanks for the insight! This all makes sense. Your quick and helpful responses are much appreciated!

**Comment by dotnetjunkie** [comment]
I'm not sure what has changed since the last message in this conversation, but decorators can (now) be applied to WCF services without any problem.

To allows this, you need to do two things:

- Make sure the svc file points at the abstraction using the `Service` tag
- Register the WCF service using its abstraction.

Example:

``` asp
<%@ ServiceHost 
    Language="C#" 
    Debug="true" 
    Service="WcfService1.IService1" 
    Factory="SimpleInjector.Integration.Wcf.SimpleInjectorServiceHostFactory,
SimpleInjector.Integration.Wcf"
    CodeBehind="Service1.svc.cs" %>
```

``` c#
var container = new Container();

container.RegisterWcfServices(Assembly.GetExecutingAssembly());

// Register WCF service by its abstraction
container.Register<IService1, Service1>();

// Register decorator to be wrapped around service abstraction
container.RegisterDecorator<IService1, ServiceDecorator>();

container.Verify();
            
SimpleInjectorServiceHostFactory.SetContainer(container);
```
