### ISSUE TITLE
Best way to inject ASP.NET 5 configuration values into dependencies registered in Simple Injector?

### ISSUE THREAD

**Issue by danludwig** [simpleinjector/SimpleInjector#143]
So vNext is changing quite a bit in version 5 of their framework. Two notable changes are the introduction of a default dependency injection framework (via `IServiceCollection`) and a new `IConfigurationBuilder` API (goodbye to web.config and app.config files).

Issue #41 recommends using SI side-by-side with the framework's `IServiceCollection` instead of replacing it. The idea is to use SI as an application-level container, and let IServiceCollection stay in place as a framework-level container. It's looking like that's the only approach that will be supported by SI, since @dotnetjunkie has announced there will be no (official) adapter for it. 

So far I am liking most of the new `IConfiguration` API, specifically the [Options Pattern](http://docs.asp.net/en/latest/fundamentals/configuration.html#using-options-and-configuration-objects). For example I implemented an application-level connection factory for the [EventStore](http://docs.geteventstore.com/dotnet-api/3.2.0/connecting-to-a-server/) database. Although its `EventStoreConnection` has sensible defaults, there are a lot of options that can be configured via the `EventStore.ClientAPI`'s `ConnectionSettings` and `ClusterSettings` types when creating such connections. The ASP.NET framework's configuration & options patterns make it pretty easy to specify a json (or .xml or .ini) file for only the connection options that I want to override, and to deserialize only this configuration data when I need to construct a new `EventStoreConnection` at runtime. I can also have environment-level configurations that could, for example, specify the use an EventStore cluster in Staging and Production, but only a single node in Development.

The framework configuration does a lot of things I like, though it does do 1 thing I am not a fan of: It tells me to use the `Microsoft.Framework.OptionsModel.IOptions<T>` framework type when I want to use it my config data as a dependency. Why should I have to do this:

``` c#
using Microsoft.Framework.OptionsModel;
public class EventStoreConnectionFactory : IConstructEventStoreConnection {
    public EventStoreConnectionFactory(IOptions<EventStoreConfiguration> configAccessor) {...}
}
```

... when I should just be able to do this:

``` c#
public class EventStoreConnectionFactory : IConstructEventStoreConnections {
    public EventStoreConnectionFactory(EventStoreConfiguration config) {...}
}
```

What needs to be done at boostrap so that SI can take advantage of the good parts of the new framework configuration system and inject configuration POCO's into my application dependencies?

**Comment by dotnetjunkie** [comment]
Cross-wiring your configuration in Simple Injector can be done by simply adding this line:

``` c#
container.Register(
    app.ApplicationServices.GetRequiredService<IOptions<EventStoreConfiguration>>);
```

This registers a delegate that will call back into the ASP.NET configuration sub system to get that particular `IOptions<T>` service. But before you take this route, please consider the downsides and alternatives described below.
 
I think that the new configuration system in vNext gives a lot of flexibility and maintainability because of the way it divides configuration files and use any arbitrary serialization format. The design around `IOptions<T>` on the other hand is really awful and you should avoid letting your classes depend on `IOptions<T>`.
 
It’s really funny that ASP.NET documentation about `IOptions<T>` that [you are referring to](https://docs.asp.net/en/latest/fundamentals/configuration.html#using-options-and-configuration-objects) notes the Interface Segregation Principle (ISP), while completely ignoring the Dependency Inversion Principle (DIP). Although the grouping of configuration into small objects can help adhering to the ISP, supplying a framework abstraction causes users to violate the DIP, because abstractions should be defined by the application itself. Letting your components depend on `IOptions<T>` creates an unnecessary dependency on a framework abstraction which make your components harder to maintain, test and understand.
 
But, besides the obvious DIP violation, there are other problems with `IOptions<T>` that make it awful. For instance, `IOptions<T>` causes configuration files to be read lazily, at the point you call `IOption<T>.Value` for the first time. This could cause the application to fail at runtime instead of during start-up in cases of misconfiguration. As a result of this you will have to test through the entire application to make sure everything works.
 
To make things worse, in instances where you forget to configure a particular section (by not calling `services.Configure<T>`) or you make a typo while retrieving the configuration section (by supplying the wrong name to `Configuration.GetSection(name)`), the configuration system will simply supply you with a default and empty object instead of throwing an exception! This may make sense in some cases but it can also lead to fragile applications.
 
As far as I see, there is no advantage in injecting an `IOption<T>` over injecting the configuration object directly (as you do in your last code example). During application start-up you want to verify whether the supplied configuration values are correct. In some cases it might be okay if the configuration section is completely missing (so you can supply the application with defaults for the developer), while in other cases it doesn’t make sense at all. For some configuration options any supplied value would be okay, while in other cases you expect values to be in a certain range, have a certain format, or simply be non-empty. You want to check this and you want the application to *fail fast* during start-up. Operations staff will thank you for that.
 
Since you want to verify the configuration at start-up, it makes no sense to delay reading it, and that makes injecting `IOption<T>` into your components plain wrong. Perhaps it’s still useful to use `IOptions<T>` when bootstrapping the application, but not as a dependency anywhere else.
 
Once you have a correctly read and verified configuration object, registration of the component that requires the configuration object is as simple as this:
 
``` c#
EventStoreConfiguration config = LoadEventSourceConfiguration();
container.RegisterSingleton<IConstructEventStoreConnections>(
    new EventStoreConnectionFactory(config));
```

**Comment by kichalla** [comment]
I came across this issue via a reference in a StackOverflow question...found it interesting...

Regarding
> For instance, IOptions<T> causes configuration files to be read lazily, at the point you call IOption<T>.Value for the first time. This could cause the application to fail at runtime instead of during start-up in cases of misconfiguration. As a result of this you will have to test through the entire application after each deployment to make sure everything works.

and 

> Since you want to verify the configuration at start-up, it makes no sense to delay reading it, and that makes injecting IOption<T> into your components plain wrong. Perhaps it’s still useful to use IOptions<T> when bootstrapping the application, but not as a dependency anywhere else.

As far as I know an options object is built upfront (like in Startup's ConfigureServices method) and the way this is built is left for the end user. For example, one could new up an options object instance themselves for use or for example they could use the `ConfigurationBinder` to bind the configuration information (for example, from config files) to POCO types. All this is done at the startup time, so I am curious about your statement. Could you please clarify?

**Comment by dotnetjunkie** [comment]
> As far as I know an options object is built upfront (like in Startup's ConfigureServices method)

As far as I could determine during testing with the latest DNX bits, the typed configuration objects are created when you call `IOptions<T>.Value`. If you add any predondition checks inside the object's properties, the exception will *not* be thrown at startup, but during the time `IOptions<T>.Value` is called. Perhaps the configuration *file* itself is read during startup, but this is irrelevant, because verification is only done during the call to `.Value`.

**Comment by kichalla** [comment]
Thanks for the clarification @dotnetjunkie...probably you should share your thoughts in the options repo? https://github.com/aspnet/Options

**Comment by dotnetjunkie** [comment]
Feel free to notify the ASP.NET team about this discussion, but to be honest, I don't think this is useful, because it will be impossible for them to address the main issue, which is IMO the violation of the Dependency Inversion Principle, unless of course they completely remove the `IOptions<T>` feature completely.

**Comment by danludwig** [comment]
I found another way to do this, avoiding the IOptions<T> bologna altogether. You can do something like this using the `ConfigurationBinder` extensions (in `Microsoft.Extensions.Configuiration.Binder` as of RC1):

    // build the IConfiguration instance as normal
    IConfigurationBuilder configBuilder = new ConfigurationBuilder()
      .SetBasePath(appEnv.ApplicationBasePath)
      .AddJsonFile("SomeCustomConfig.json);
    IConfiguration config = configBuilder.Build();

    // use the ConfigurationBinder extension method to get your object from a specific config section
    SomeCustomConfigPoco myCustomConfig = config.GetSection("Root:SectionName")
      .Get<SomeCustomConfigPoco>();

You can then register the `myCustomConfig` instance as a singleton and inject it by itself. Just make sure your project.json includes the `"Microsoft.Extensions.Configuration.Binder": "1.0.0-rc1-final"` under `"dependencies"`

**Comment by ajbeaven** [comment]
Something must have changed in the most recent version of `Microsoft.Extensions.Configuration.Binder` as `IConfigurationSection.Get()` no longer exists. You can can achieve the same thing like so:

```
// build the IConfiguration instance as normal
IConfigurationBuilder configBuilder = new ConfigurationBuilder()
    .SetBasePath(appEnv.ApplicationBasePath)
    .AddJsonFile("SomeCustomConfig.json");
IConfiguration config = configBuilder.Build();

// create and hydrate a custom configuration object from a specific config section
var myCustomConfig = new SomeCustomConfigPoco();
Configuration.GetSection("Root:SectionName").Bind(config);
```

**Comment by danludwig** [comment]
Good find @ajbeaven. It's not hard to roll your own `Get<T>` extension method using `Bind`

```
public static class MyConfigurationExtensions
{
  public static T Get<T>(this IConfiguration config)
    where T : new()
  {
    var settings = new T();
    config.Bind(settings );
    return settings ;
  }
}
```

**Comment by iAlexanderMoon** [comment]
I'm thankful I came across this thread and @ajbeaven comment... for others who find this you do want to bind to the custom poco though not config.

// create and hydrate a custom configuration object from a specific config section
var myCustomConfig = new SomeCustomConfigPoco();
Configuration.GetSection("Root:SectionName").Bind(myCustomConfig);

**Comment by johnfnz** [comment]
> As far as I see, there is no advantage in injecting an `IOption<T>` over injecting the configuration object directly (as you do in your last code example). During application start-up you want to verify whether the supplied configuration values are correct.

I disagree that you should be injecting your configuration directly, but I also don't think IOption<T> is the best solution. Not all configuration comes from files, it may come from Azure Key Vault for example. Creation of your object graph is not the time to be making HTTP requests, or ideally I would argue, to be reading the file system. For one thing I want to be able to create the object graph and test that I can resolve my top level classes without depending on persistence services. After you resolve the top class of your object graph from the container (and release your container) you then call an entry method on that class. That is when you say "Go", and is the right time to be finding out if you are able to read your config and get valid values, not during creation of the object graph, in the class constructors. This is still at startup for a console app, or when a request comes in for a web app. 

This makes Lazy<T> a good choice for representing the relationship between my class and the configuration my class needs "_at some point in the future_" (see [Implicit relationship types](https://autofaccn.readthedocs.io/en/latest/resolve/relationships.html)).

My exception handling, logging, and health checks are what make my operations staff happy. Having my code throw exceptions while the ASP.NET Core processing pipeline is still trying to create my controller isn't improving that situation. 

I would go on to argue that while I want a class to model config that comes from appSettings.json and a class to model config I get from Key Vault, following the Interface Segregation Principle I want a client-specific interface for my class to consume it's config from. Which means I'll need an adapter that implements IMyClassConfig (and potentially IMyOtherClassConfig etc) and depends on my various config implementations to provide just the config that each class requires without exposing them to values they don't need or the details of where it comes from. So I would sum up by saying that in many cases Lazy<IMyClassConfig> is what your class depends on, and so what it should declare in it's constructor.

**Comment by dotnetjunkie** [comment]
Hi @johnfnz,

There's a lot of truth in what you are saying. Let me summarize the points you make that I completely agree with:

* `IOptions<T>` is *not* the best solution
* "Creation of your object graph is not the time to be making HTTP requests, or [...] to be reading the file system." This is something I [expressed myself](https://blogs.cuttingedge.it/steven/p/runtime-data/) a few years ago.
* You want to be able to test whether or not object graphs can be constructed. This disallows calling I/O during object graph construction. This is why Simple Injector has documentation that describes how to [make your DI configuration testable](https://simpleinjector.org/howto#verify-configuration).
* Config value should not be read from inside constructors of resolved components. This is something that I expressed in [my book](https://manning.com/seemann2) (section 4.2.1). My coauthor, Mark Seemann, [blogged about this](https://blog.ploeh.dk/2011/03/03/InjectionConstructorsshouldbesimple/) as well back in 2011.
* Using `Lazy<T>` can be a great way to allow values to be lazy loaded.
* You should follow the Interface Segregation Principle for configuration values as well. This means that each client should have access to only the values it requires, not a complete set of configuration values.

There are, however, a few points I wish to comment on:

* Although object graph construction should be free of receiving runtime data and doing *any* I/O, instead of loading configuration data *after* the object graph has been configured and/or constructed, a generally more sensible time to do this is *before* you start configuration your object graphs. This allows you to read all configuration data (or at least, all configuration data that can be read *at that point in time*), and supply it (preferably as immutable data structures) to a method that registers or composes the object graph. By separating this I/O and container registration phase, you can easily supply that registration method with a fake block of configuration data inside your test. That configuration data doesn't have to (and IMO *shouldn't*) be read from disk during that test. That test should be able to be completely free of any I/O. Supplying the DI configuration with configuration data beforehand prevents [Temporal Coupling](https://blog.ploeh.dk/2011/05/24/DesignSmellTemporalCoupling/). This doesn't mean that you can't load this data *after* you built up your container, but in most cases doing it before is more reasonably. One reason to want to do it afterwards, is when you have to deal with asynchronous operations. It might be impossible to do async/await before configuring the container. I discussed a similar topic with Stephen Cleary [a year ago](https://stackoverflow.com/questions/45924027/avoiding-all-di-antipatterns-for-types-requiring-asynchronous-initialization).
* Although the use of `Lazy<T>` is a great way to prevent eager loading of stuff, injecting `Lazy<T>` as dependency leads to leaky abstractions. Leaky abstractions are Dependency Inversion Principle violations. Instead of letting application components depend on `Lazy<T>` dependencies, a better solution is to hide the use of `Lazy<T>` behind a proxy. This allows encapsulating `Lazy<T>` inside the [Composition Root](https://mng.bz/K1qZ). Section 8.4.2 of my book contains a detailed discussion on this.
* In general, I would prevent the use of interfaces as configuration objects (such as `IMyClassConfig`) and instead use simple concrete classes. This is typically a simpler solution. Exception to this rule is when configuration values can change during the application's lifetime. For that, you need some kind of abstraction. This is, for instance, why Microsoft defined an `IOptionsSnapshot<TOptions>` abstraction. I'm not saying, though, you should use *that* abstraction in particular, but in that particular case you need to find a way to postpone reloading until its value is requested.

I hope this helps.
