### ISSUE TITLE
Cannot add into Xamarin Android/iOS PCL project

### ISSUE THREAD

**Issue by cheansiong** [simpleinjector/SimpleInjector#144]
Hi,

I was trying to add the Nuget Package into my Xamarin Android project, however I encounter the following errors, which I think you could do something about because I have no issue when adding "Simple Injector" and "Simple Injector Lifetime Scoping". Would you confirm the error?

Thank you.

Could not install package 'SimpleInjector.Extensions.ExecutionContextScoping 3.1.0'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v5.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by dotnetjunkie** [comment]
That is correct. The `SimpleInjector.Extensions.ExecutionContextScoping` package is only available for .NET 4.5 and is not compatible with PCL. Internally the `ExecutionContextScopeLifestyle` depends on the [CallContext](https://msdn.microsoft.com/en-us/library/system.runtime.remoting.messaging.callcontext%28v=vs.110%29.aspx), but this class is only available in .NET 4.5 and not in Xamarin.

**Comment by cheansiong** [comment]
So, if that is the case, what options do I have?

**Comment by dotnetjunkie** [comment]
Since in a phone application there is typically only one thread of execution (which means that although operations might be asynchronous, they are sequential), you only need one `Scope` at the time. This means you can write a really simple `ApplicationWideScopedLifestyle ` like this:

``` c#
public class ApplicationWideScopedLifestyle : ScopedLifestyle
{
    private static Scope currentScope;
    public ApplicationWideScopedLifestyle() : base("Custom Scoped") { }
    public static Scope BeginScope() {
        return currentScope = new Scope();
    }
    protected internal override Func<Scope> CreateCurrentScopeProvider(Container container) {
        return () => currentScope;
    }
}
``` 

And you can start an 'application wide scope' as follows:

``` c#
var container = new Container();
container.Options.DefaultScopedLifestyle = new ApplicationWideScopedLifestyle();

// Register your scoped components
container.Register<IPlugin, PluginImpl>(Lifestyle.Scoped);

using (ApplicationWideScopedLifestyle.BeginScope())
{
    // Resolve root object here.
}
```

**Comment by cheansiong** [comment]
Sorry, I don't understand what you mean here... Is that what you really mean, one thread?
"Since in a phone application there is typically only one thread of execution (which means that although operations might be asynchronous, they are sequential), you only need one Scope at the time."

**Comment by cheansiong** [comment]
By the way, how I'm accessing could be simplify as...

Button1_Click(object sender, EventArgs e)
{
  using (ApplicationWideScopedLifestyle.BeginScope())
  {
       // await execute request 1 to server
       // save result to db
  }
}

Button2_Click(object sender, EventArgs e)
{
  using (ApplicationWideScopedLifestyle.BeginScope())
  {
       // await execute request 2 to server
       // save result to db
  }
}

Button3_Click(object sender, EventArgs e)
{
  using (ApplicationWideScopedLifestyle.BeginScope())
  {
       // cancel all requests
  }
}

And in this case, some of the classes are not thread safe, therefore, I would like to scope those objects from a controller layer down to model layer. 

So, is there any other better option available?

**Comment by dotnetjunkie** [comment]
I was talking explicitly about 'one thread of execution', instead of 'one thread', since asynchronous programming means that many threads can be involved (although in a phone app, everything is normally executed on the UI thread). What I mean by 'one thread of execution' is that you only have one operation at the time, compared to having multiple parallel processes running at the same time in the background. So as long as you don't allow the user to click another button, before the execution of the previous button finished, you are fine.

Do note though that calling `BeginScope()` only has affect on any resolve/getinstance that comes after it. So that means that any dependency that gets resolved before doesn't run within that scope (which is obvious, because it is resolved before you started the scope).

Also note that the code you are showing not only has a lot of repetitive code, but also causes your complete code base to depend on your DI library, which is typically not something you want (since the reason to use such library is to adhere to the Dependency Inversion Principle). So instead of doing that, a much better approach is to abstract this from your UI component.

A very pleasant and effective way of doing that is to make use of generic abstractions that define use cases such as mutations and reads (commands and queries). You can read more about such design in [this article](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=91) and [this article](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=91). After you applied these patterns, your UI component might look like this:

``` c#
private readonly ICommandHandler<Operation1> operation1Handler;
private readonly ICommandHandler<Operation2> operation2Handler;
private readonly ICommandHandler<Operation3> operation3Handler;

public MyWindow(
	ICommandHandler<Operation1> operation1Handler,
	ICommandHandler<Operation2> operation2Handler,
	ICommandHandler<Operation3> operation3Handler)
{
	this.operation1Handler = operation1Handler;
	this.operation2Handler = operation2Handler;
	this.operation3Handler = operation3Handler;
}

async Task Button1_Click(object sender, EventArgs e) {
	await this.operation1Handler.Handle(new Operation1 {
		SomeValue = this.TextBox1.Text,
	});
}

async Task Button2_Click(object sender, EventArgs e) {
	await this.operation2Handler.Handle(new Operation2 {
		Id = new Guid(this.IdContainer.Value),
		Description = this.DescriptionTextBox.Text,
	});
}

async Task Button3_Click(object sender, EventArgs e) {
	await this.operation3Handler.Handle(new Operation3 {
		Id = new Guid(this.IdContainer.Value),
		Name = this.NameTextBox.Text,
	});
}
```

Now the only thing your UI component has to know about is the `ICommandHandler<T>` abstraction. No use of your DI library is in sight.

Now you can create your command handlers in your application -or- [even better](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=95), just have a shared assembly with your command objects that you reuse on both the client and the server, and have your command handler implementations on the server. In that case you can simply post your commands as JSON data to the server and let the server execute them.

But either way, when you can now define a generic decorator for your command handlers that allows you to wrap a real operation in a scope. Such decorator can look like this:

``` c#
public interface ICommandHandler<T> {
    Task Handle(T command);
}

public class ScopeCommandHandlerDecorator<T> : ICommandHandler<T>
{
    private readonly Func<ICommandHandler<T>> decorateeProvider;
    public ScopeCommandHandlerDecorator(Func<ICommandHandler<T>> decorateeProvider) {
        this.container = container;
        this.decorateeProvider = decorateeProvider;
    }

    public async Task Handle(T command) {
        // This is the only place in the application where you will need to call BeginScope
        using (ApplicationWideScopedLifestyle.BeginScope())
        {
            ICommandHandler<T> handler = this.decorateeProvider.Invoke();
            await handler.Handle(command);
        }
    }
}
```

This generic handler can be wrapped around any command handler implementation. Without Simple Injector, it might look like this:

``` c#
ICommandHandler<Operation1> handler =
    new ScopeCommandHandlerDecorator<Operation1>(
        new Operation1Handler(new WcfLogger()));
```

With Simple Injector you would use the following registration:

``` c#
// Registers all command handler implementations in the given assembly.
container.Register(typeof(ICommandHandler<>), typeof(ICommandHandler<>).Assembly);

// Makes sure that all command handlers will be wrapped with the decorator.
container.RegisterDecorator(typeof(ICommandHandler<>),
    typeof(ScopeCommandHandlerDecorator<>));
```

This might be quite a lot to digest, but I can assure you, once you get the hang of these patterns, you will never want to go back!

**Comment by cheansiong** [comment]
Thank you very much for the detail explanation. Really need a some times to digest fully and I think the example I gave earlier are not very precise into the situation here.

Here is the full picture:
Consider that there is screen A where it display some of the User information (Eg: name) from the database. 
Thread 1
1. (READ) User information is read from database and display to user.
2. Some other data is read from database and process as well

From screen A, user are allowed to go to screen B, where screen B displays the detail User information and allows user to edit. 

In screen B, User information is read from the database:
Thread 2
1. (READ) Get the User information (and possibly other stuff) from the database
Thread 3 (Mostly same thread as 2, depends on TaskScheduler)
2. Execute a HTTP request to server to get latest data
3. (WRITE) When the HTTP request completed successfully, save to database
4. (READ) Get the data and trigger events/ return the data to screen.

When editing, the changes will be:
Thread 4
1. (WRITE) Save to database
Thread 5
2. (READ) Trigger some background process to synchronize to server asynchronously (User are allowed to exit the screen at anytime)

In the condition that user exit from screen B (anytime, probably using "back" button in android), screen A will be displayed, and the User information is read again from the database.

At anytime when it involved the I/O operation or client/server operation, it will definitely not on UI thread. 

In this case, the database used here is SQLite (https://www.sqlite.org/threadsafe.html) with MultiThread mode, therefore the connection object is not thread-safe. This is the place where I think need to be scoped, because I don't feel like to create too much connection object per object used.
Note: I need this feature (so that the reading operation started after were not blocked by previous heavy I/O read operation, if any) so that multiple-read-single-write could be achieved (probably I hope). 

Hopefully it clarify the scenario better and I gotta stopped here a while, see you tomorrow.

**Comment by dotnetjunkie** [comment]
The number of threads the application runs is irrelevant. The question here is: do you run operations in parallel or not?

**Comment by cheansiong** [comment]
Obviously Yes.
As you can see from this scenario below, user are allowed to exit the screen while some backend is perform some synchronization.
When editing, the changes will be:
Thread 4
1. (WRITE) Save to database
Thread 5
2. (READ) Trigger some background process to synchronize to server asynchronously (User are allowed to exit the screen at anytime)

**Comment by dotnetjunkie** [comment]
In your case, what might work best is a custom scoped lifestyle that has thread-affinity:

``` c#
public class ThreadScopedLifestyle : ScopedLifestyle {
    [ThreadStatic]
    public static Scope CurrentScope;
    public ThreadScopedLifestyle() : base("Custom Scoped") { }
    public static Scope BeginScope() => CurrentScope = new Scope();
    protected internal override Func<Scope> CreateCurrentScopeProvider(Container container) => 
        () => CurrentScope;
}
```

This custom scope can be used as follows:

``` c#
using (ThreadScopedLifestyle.BeginScope())
{
    // call GetInstance here before doing calling await.
}
```

Restriction of this is that a call to `GetInstance` must resolve the complete object graph imediately. You can't call `GetInstance` lazily during execution of your code, because since you're using async/await, you can be executing on a different thread and other operations that start a scope could have been executed in between on the same thread.

**Comment by cheansiong** [comment]
Sorry for late response.

I'm not quite sure on the reason of limitation you mentioned. But from the documentation.

```
var container = new Container();
// Set the scoped lifestyle one directly after creating the container
container.Options.DefaultScopedLifestyle = new WebApiRequestLifestyle();
```

Therefore, I was thinking that I could be using in this way below.
```
// using SimpleInjector.Extensions.ExecutionContextScoping;

using (container.BeginExecutionContextScope()) {
    var dbConn1= container.GetInstance<IDatabaseConnection>();
    await SomeAsyncOperation();
    var dbConn2= container.GetInstance<IDatabaseConnection>();
    await SomeOtherAsyncOperation();

    Assert.AreSame(dbConn1, dbConn2);
}
```

Is there any differences as far as you may know?

**Comment by dotnetjunkie** [comment]
Yes, your usage of the execution context scope is correct, exect for two things:

1. As explained, the execution context scope is not available in PCL, due to limitations in the .NET framework.

2. Even if it was available, with async in client applications can (unless you disable this) click multiple buttons directly after each other, which will cause operations to run seemingly concurrently , while everything is delegated back to the UI thread. Thise would cause both clicks to run in the same Call Context which also means working in the same scope. This can can problems when resolves take place after an `await` (as in your previous code sample) and this will cause problems when the first click finished while the second click is still running, because it will in that case dispose the second scope as well (because they would run in the same Call Context).

So even if Call Context was supported in PCL/WP8/Xamirin, we would still need to use a thread-specific scope for actions that are triggered from the UI and use a execution scope for background tasks that are asynchronous (or use thread-specific scope if those background tasks are synchronous).

**Comment by cheansiong** [comment]
By using a scoped limitation lifestyle, does it means that all objects that depends on the (in my case) ThreadScoped will need to be changed to ThreadScoped as well (Even though before this, they are all Singletone)

I received error when trying to change one of the object scoped become custom scope (Thread Scope). And it gives me the following error when Container.Verify() is called.
````
-[Lifestyle Mismatch] 
````

**Comment by dotnetjunkie** [comment]
Try to understand exactly what a [captive dependency](http://blog.ploeh.dk/2014/06/02/captive-dependency/) and [lifestyle mismatch](https://simpleinjector.readthedocs.org/en/latest/LifestyleMismatches.html) are, and why they are so dangerous.

> By using a scoped limitation lifestyle, does it means that all objects that depends on the (in my case) ThreadScoped will need to be changed to ThreadScoped as well

Components should have a lifestyle that is shorter or equal to their dependencies.

**Comment by cheansiong** [comment]
Eventually I choose to create a new database connection when needed (of course immediately dispose it when not in use) and do not create a single database connection based on thread scoped. So far do not feel (user perspective) any penalty in performance.

At one time, there might have about 5-6 open connection to the file, so far still works very well. :-)

**Comment by dotnetjunkie** [comment]
> I choose to create a new database connection when needed

This is the exact advice that Mocrosoft gives when it comes to database connections in .NET. Connections are pooled, which makes opening connections really fast. You should not see any significant performance difference when closing connections a.s.a.p.
