### ISSUE TITLE
Which known projects use Simple Injector?

### ISSUE THREAD

**Issue by JohanGl** [simpleinjector/SimpleInjector#148]
Hi,
Just to easier motivate my project to keep simple injector and to not replace it with another tool, do you know of any famous or large scale projects that uses it? Btw: I couldnt find any official email address on the site.

**Comment by janhartmann** [comment]
Just dropping by here, I have created a project called [ScaffoldR](https://github.com/hartmanns/ScaffoldR). Will be available on NuGet this week.

ScaffoldR is a SOLID platform for structuring or scaffolding .NET applications. ScaffoldR supports commands, queries, events, repositories and validation with intelligent dispatching via C# generic variance. ScaffoldR integrates heavily into Simple Injector.

@dotnetjunkie: If this is inappropriate, please delete this post.

**Comment by qujck** [comment]
@JohanGl are you implying that your project team are considering dropping Simple Injector for another container based on fame and fortune: is that even a thing in the world of *IoC Container*'s :-D?

It may be more fruitful to address any real concerns your team have with Simple Injector or perceive as *better* in another container, are you able to give more information?

**Comment by dotnetjunkie** [comment]
I agree with @qujck, you should select your tools based on your project's design and requirements. 

Simple Injector is an opinionated library with a very clear philosophy. We are passionate about applying the right patterns, principles and practices and Simple Injector has spawn from this. [Many](https://twitter.com/LuukSommersNL/status/588294060869312513) [developers](https://twitter.com/bitbonk/status/608039536715812865) praise Simple Injector for this, but you have to do your own research to see whether Simple Injector matches your requirements. 

As one of the maintainers, I speak with Simple Injector users regularly and I came across quite a few big applications. I know some teams choose Simple Injector because of its performance and scalability, while [others](https://github.com/simpleinjector/SimpleInjector/issues/91) resolve extremely big object graphs using Simple Injector. Whether or not these projects match your definition of ‘large scale’ is hard to say, but rest assure that Simple Injector is built for high load and high performance, and if you find a bug concerning load and performance, we push patch releases quite rapidly.

**Comment by JohanGl** [comment]
I completely agree with your reasoning and i personally prefer SI. I will mention your input when/if a time comes to discuss frameworks. Thanks!

**Comment by christophdebaene** [comment]
Since more than 2 years I introduced Simple Injector at a customer. Since then we have already more than 10 applications using Simple Injector and we are very happy about it.

I have chosen Simple Injector because of the great documentation, performance, intuitive API and forcing us to use SOLID principles.
