### ISSUE TITLE
Throwing an exception in run time with simple injector 3.1.0

### ISSUE THREAD

**Issue by adithyasai** [simpleinjector/SimpleInjector#150]
No registration for type IEnumerable<IExceptionLogger> could be found.

public IEnumerable<object> GetServices(Type serviceType)
Line 120:            {
Line 121:                return this.container.GetAllInstances(serviceType);
Line 122:            }

STACK TRACE- IMAGE

you can find the screen shoot of stack trace in below URL.

![simpleinjector_exception](https://cloud.githubusercontent.com/assets/15884712/11204764/19c0e134-8d28-11e5-959b-2d710493f9ab.png)

**Comment by dotnetjunkie** [comment]
You are using a custom `IDependencyResolver` for Web API. Please use the `SimpleInjectorWebApiDependencyResolver` from the SimpleInjector.IntegrationWebApi NuGet package and everything will work.

What you are experiencing is a breaking change that was introduced in v3. By default,  unregistered collections are not resolved as empty lists. The adapters for MVC and Web API have been updated for this, and that's why it's best to use the official integration libraries whenever possible.

**Comment by adithyasai** [comment]
thank you for the response.
I have already installed SimpleInjector.IntegrationWebApi and i am using mpleInjectorWebApiDependencyResolver. 
here are the packages that were installed
<package id="SimpleInjector" version="3.1.0" targetFramework="net45" />
  <package id="SimpleInjector.Extensions.ExecutionContextScoping" version="3.1.0" targetFramework="net45" />
  <package id="SimpleInjector.Integration.Web" version="3.1.0" targetFramework="net45" />
  <package id="SimpleInjector.Integration.Web.Mvc" version="3.1.0" targetFramework="net45" />
  <package id="SimpleInjector.Integration.WebApi" version="3.1.0" targetFramework="net45" />

But the problem is not yet resolved.

Herei is my file
[simleinjectorinitializer.txt](https://github.com/simpleinjector/SimpleInjector/files/36379/simleinjectorinitializer.txt)

**Comment by dotnetjunkie** [comment]
From the stack trace you provided I see you are using a custom implementation located in Megnet.App.My_App.

**Comment by adithyasai** [comment]
Thank you resolved my issue
