### ISSUE TITLE
Nested Views automatic wiring (WPF)

### ISSUE THREAD

**Issue by mschaefer88** [simpleinjector/SimpleInjector#151]
Hi!

I have a setup like:

`<MainWindow>
           <UserControl1/>
           <UserControl2/>
</MainWindow>`

Where MainWindow and UserControl1 have their ViewModel injected in their corresponding constructor. But everytime UserControl1 has its dependency in its constructor the container verifying fails. Am i doing something wrong, or is there another way to do it? I found nothing in the documentation regarding that problem.

Best regards

**Comment by dotnetjunkie** [comment]
Can you give more details about the problem? Please include the exception details (message, exception type, stack trace, and the same info for all the inner exceptions).

**Comment by mschaefer88** [comment]
So thats my detailed setup:

View:
`<Window>
    <DockPanel>
        
        <views:RibbonView DockPanel.Dock="Top"/>
        <views:EntityView Content="{Binding SelectedEntity}" Grid.Column="1"/>

    </DockPanel>
</Window>`

CodeBehinds:
`public MainWindow(MainWindowViewModel viewModel)
{
		InitializeComponent();
        DataContext = viewModel;
}

public RibbonView(RibbonViewModel viewModel)
{
        InitializeComponent();
        DataContext = viewModel;
}

public EntityView()
{
        InitializeComponent();
}`

ViewModels:
`public MainWindowViewModel(IEventAggregator aggregator)
{

}

public RibbonViewModel()
{

}`

SI-Bootstrap:
`private static Container Bootstrap()
{
	var container = new Container();
	
	container.Register<IEventAggregator, EventAggregator>(Lifestyle.Singleton);
	
	container.Register<MainWindow>();
	container.Register<RibbonViewModel>();
	
	container.Verify();
   
	return container;
}`

Error:
`Ein Ausnahmefehler des Typs "System.InvalidOperationException" ist in SimpleInjector.dll aufgetreten.

Zusätzliche Informationen: The configuration is invalid. Creating the instance for type MainWindow failed. Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.`

Unfortunately it's german, but it says NullReferenceException.

Pic of detailed exception attached.
![sierr](https://cloud.githubusercontent.com/assets/9464284/11369498/93b4c4a0-92bf-11e5-8b50-f8418750a9e2.jpg)

**Comment by dotnetjunkie** [comment]
Please post the complete stack trace.

**Comment by dotnetjunkie** [comment]
The exception is happening within the constructor of `MainWindow` and is thrown by the `System.DafaultBinder.BindToMethod`. The error is probably not related to Simple Injector, but you probably misconfigured a binding. So the verification mechanism of Simple Injector is really working great here, because now your application fails fast instead of finding out the problem later on.

**Comment by mschaefer88** [comment]
I commented all out and used a simple plain usercontrol with viewmodel (plain too) as dependency in ctor. But the error still persists. Here's the trace:

System.InvalidOperationException was unhandled
  HResult=-2146233079
  Message=The configuration is invalid. Creating the instance for type MainWindow failed. Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
  Source=SimpleInjector
  StackTrace:
       bei SimpleInjector.InstanceProducer.VerifyInstanceCreation()
       bei SimpleInjector.Container.VerifyInstanceCreation(InstanceProducer[] producersToVerify)
       bei SimpleInjector.Container.VerifyThatAllRootObjectsCanBeCreated()
       bei SimpleInjector.Container.VerifyInternal(Boolean suppressLifestyleMismatchVerification)
       bei SimpleInjector.Container.Verify()
       bei Client.View.Program.Bootstrap() in C:\Users\Bytep\Source\Workspaces\Project\Client\Client.View\Program.cs:Zeile 34.
       bei Client.View.Program.Main() in C:\Users\Bytep\Source\Workspaces\Project\Client\Client.View\Program.cs:Zeile 16.
       bei System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       bei System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       bei Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       bei System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       bei System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
       HResult=-2146233088
       Message=Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
       Source=SimpleInjector
       StackTrace:
            bei SimpleInjector.InstanceProducer.GetInstance()
            bei SimpleInjector.InstanceProducer.VerifyInstanceCreation()
       InnerException: 
            HResult=-2147467261
            Message=Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
            Source=mscorlib
            StackTrace:
                 bei System.DefaultBinder.BindToMethod(BindingFlags bindingAttr, MethodBase[] match, Object[]& args, ParameterModifier[] modifiers, CultureInfo cultureInfo, String[] names, Object& state)
                 bei MS.Internal.Xaml.Runtime.DynamicMethodRuntime.CreateInstanceWithCtor(Type type, Object[] args)
                 bei MS.Internal.Xaml.Runtime.DynamicMethodRuntime.CreateInstanceWithCtor(XamlType xamlType, Object[] args)
                 bei MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstance(XamlType xamlType, Object[] args)
                 bei MS.Internal.Xaml.Runtime.PartialTrustTolerantRuntime.CreateInstance(XamlType xamlType, Object[] args)
                 bei System.Xaml.XamlObjectWriter.Logic_CreateAndAssignToParentStart(ObjectWriterContext ctx)
                 bei System.Xaml.XamlObjectWriter.WriteEndObject()
                 bei System.Xaml.XamlWriter.WriteNode(XamlReader reader)
                 bei System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
                 bei System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
                 bei System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
                 bei System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
                 bei System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
                 bei Client.View.Views.MainWindow.InitializeComponent() in C:\Users\Bytep\Source\Workspaces\Project\Client\Client.View\Views\MainWindow.xaml:Zeile 1.
                 bei Client.View.Views.MainWindow..ctor(MainWindowViewModel viewModel) in C:\Users\Bytep\Source\Workspaces\Project\Client\Client.View\Views\MainWindow.xaml.cs:Zeile 13.
                 bei lambda_method(Closure )
                 bei SimpleInjector.InstanceProducer.BuildAndReplaceInstanceCreatorAndCreateFirstInstance()
                 bei SimpleInjector.InstanceProducer.GetInstance()
            InnerException:

**Comment by TheBigRic** [comment]
I'm surprised you even got this compiling. WPF does not allow a UserControl to have a non default constructor. So this code:
 
```
<Window>
    <DockPanel>

        <views:RibbonView DockPanel.Dock="Top"/>
        <views:EntityView Content="{Binding SelectedEntity}" Grid.Column="1"/>

    </DockPanel>
</Window>
```
where `RibbonView` is defined as:
``` c#
public RibbonView(RibbonViewModel viewModel)
{
        InitializeComponent();
        DataContext = viewModel;
}
```
should simply not compile at all. I guess you got this compiling by adding a second (and default) constructor to  the `RibbonView` usercontrol.

The trick here is to, just as you compose your application from classes, to compose your `MainView` from smaller views. But just as your composition root is responsible for composing the application, it should also be responsible for composing your views. Not doing so would still lead to tight coupling between your views. 

For the composition of your views WPF has the `ContentControl`. So instead of instantiating the `RibbonView` yourself in de xaml of `MainView` (because that is what you’re actually doing!) you should let Simple Injector create all the types your application needs  and set the `Content` property of the `ContentControl` to the Simple Injector created instance of the RibbonView. This should be as simple as:
```
<Window>
        <ContentControl Name="MyRibbonView" />
</Window>
```
And in the code behind:
``` c#
public partial class MainWindow : Window
{
    public MainWindow(RibbonView ribbonView)
    {
        InitializeComponent();
        this.MyRibbonView.Content = ribbonView;
    }
}
```

An even nicer approach would be to bind the `RibbonView` to the `Content` property of the `ContentControl` because this way there is a minimal coupling between your code behind and your actual view (the xaml). This makes it possible to drop the code behind completely in the future and bind you xaml directly to the viewmodel by using some MVVM toolkit. This would look like:

```
<Window>
    <ContentControl Content="{Binding RibbonView, 
                       RelativeSource={RelativeSource Mode=FindAncestor, AncestorType=Window}}" />
</Window>
```

and in code behind:
``` c#
public partial class MainWindow : Window
{
    public MainWindow(RibbonView ribbonView)
    {
        InitializeComponent();

        this.RibbonView = ribbonView;
    }

    public RibbonView RibbonView { get; private set; }
}
```

Now for the configuration of the container: Best practice is register all types needed for composing the application. Not doing so could make the container blind, while `Verify()` is there to help you spot configuration mistakes.
 
Looking at the classes you mentioned the configuration should look like:
``` c#
private static Container Bootstrap()
{
    var container = new Container();

    container.Register<IEventAggregator, EventAggregator>(Lifestyle.Singleton);

    container.Register<MainWindow>();
    container.Register<MainWindowViewModel>();
    container.Register<RibbonView>();
    container.Register<RibbonViewModel>();
    container.Register<EntityView>();

    container.Verify();

    return container;
}
```

As you can see this 'bootstrapping' class, a.k.a. the [`Composition Root`](http://blog.ploeh.dk/2011/07/28/CompositionRoot/) will start to grow rapidly.Therefore it is advisable to design your application around some smart chosen and simple generic abstractions as you can read [here](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=91). Although at first this blog does not seem to fit this answer, these patterns are also applicable for defining your viewmodels as I once wrote in a S.O. answer [here](http://stackoverflow.com/a/28310234/3294832) and [here](http://stackoverflow.com/a/28465845/3294832).

Registering all your edit view models for example will become a one liner in this case:
``` c#
container.Register(typeof(IEntityEditorViewModel<>), new [] {Assembly.GetExecutingAssembly()});
```

**Comment by dotnetjunkie** [comment]
I totally support Ric's answer. I've got nothing to add.

**Comment by mschaefer88** [comment]
great thanks!
