### ISSUE TITLE
Relocate Packaging Interface

### ISSUE THREAD

**Issue by Mystagogue** [simpleinjector/SimpleInjector#154]
I'm using SimpleInjector in a PCL for Xamarin, but the SimpleInjector.Packaging is not able to install:

>install-package : Could not install package 'SimpleInjector.Packaging 3.1.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile78', but the package does not contain any assembly references or content files that are compatible with that framework.

I'm not surprised, but I feel there is a white-elephant here.  In my opinion, the IPackage _interface_ should be defined in the SimpleInjector library instead of the SimpleInjector.Packaging library.  This would be analogous to the IObservable interface which is defined in the mscorlib, while everything that implements IObservable is found in separate NuGet packages.

If this adjustment were made, I could re-define a tiny amount of what is found in SimpleInjector.Packaging within my PCL and yet still benefit from the "official" packaging interface.

**Comment by dotnetjunkie** [comment]
The omission of a PCL version of the Packaging library can be considered an oversight on our side. As a matter of fact, the only version that needs to exist is a PCL version. 

The reason the `IPackage` interface is not part of the core library, is because hardly anyone ever needs such modularity. The package interface gives a false sense of flexibility, since the same can often be achieved in a more practical and safe way as explained [here](https://stackoverflow.com/questions/8983843/how-can-i-emulate-modules-installers-registries-with-simple-injector) for instance (i.e. using static method calls).

The only scenario that such `IPackage` interface becomes useful is when you have a true plug-in architecture, where assemblies are unknown at compile time and picked up dynamically when placed in the /bin folder. That is a scenario that very little people actually need. But even if you need true plug-in behaviour, defining your own abstraction has usually more benefits than using the library's interface, since you can change the your own abstraction to your particular needs, while the Simple Injector’s `IPackage` abstraction is fixed.

Because of its limited usefulness, we decided to keep Packaging separate from the core library; we like to push developers into a different direction, before considering using the Packaging project.

Also note that Packaging is nothing more than a simple interface and an [extension class](https://github.com/simpleinjector/SimpleInjector/blob/master/SimpleInjector.Packaging/PackageExtensions.cs). The following code example recreates all the Package's functionality:

``` c#
public interface IPackage
{
    void RegisterServices(Container container);
}

public static class PackageExtensions
{
    public static void RegisterPackages(this Container container,
        IEnumerable<Assembly> assemblies)  {
        var packages =
            from assembly in assemblies
            from type in assembly.GetExportedTypes()
            where typeof(IPackage).IsAssignableFrom(type)
            where !type.IsAbstract
            where !type.IsGenericTypeDefinition
            select (IPackage)Activator.CreateInstance(type);

        foreach (var package in packages) {
            package.RegisterServices(container);
        }
    }
}
```

Although you are actually the first person who ever raised an issue about the absence of the PCL version, I think it is good to change that project into a PCL version. We will however not merge the Packaging project into the core library because of the above reasons.

**Comment by qujck** [comment]
It's worth noting the `IPackage` abstraction promotes vendor lock in [which goes against one of the design principles](https://simpleinjector.readthedocs.org/en/latest/principles.html#vendor-lock-in) behind SI.
