### ISSUE TITLE
Cannot access a disposed object. ExecutionContextScope

### ISSUE THREAD

**Issue by oruchreis** [simpleinjector/SimpleInjector#157]
Hi,
I'm getting this error:

> Cannot access a disposed object.\r\nObject name: 'SimpleInjector.Extensions.ExecutionContextScoping.ExecutionContextScope'"

Because I can't check the current execution scope for disposing in lifestyleSelector. I've fixed the issue with reflection to access to state property of the scope
```csharp
public static readonly ScopedLifestyle HybridScopedLifestyle = Lifestyle.CreateHybrid(
    lifestyleSelector: () =>
    {
        var scopeAsync = Container.GetCurrentExecutionContextScope();
        return scopeAsync != null 
            && scopeAsync.GetPropertyValue("state", Flags.InstancePrivate).ToString() == "Alive";
    },
    trueLifestyle: new ExecutionContextScopeLifestyle(),
    falseLifestyle: new LifetimeScopeLifestyle());
```
Could you add `IsDisposed` property to the `Scope` class?

**Comment by dotnetjunkie** [comment]
Which version of Simple Injector are you using? The `GetCurrentExecutionContextScope` should normally not return disposed `Scope` instances at all. It should return `null`.

**Comment by oruchreis** [comment]
3.1.1 for SimpleInjector and ExecutionContext Scope and Lifetime Scope.
This error occured in a long running thread that is outside of the web request scope. I've wrapped owin web request with Execution Context scope as suggested in Documentation. So I've wrapped with lifetimescope this long thread. But ExecutionContextScope is preemptive than lifetime scope for the project. So I've created hybrid scope to check if executionscope is disposed or not. By the way, I've examined the source code of Scope.cs and I've seen the syncRoot private locker object. I've wrapped above code with a lock with this object. Everything is working fine now, but using reflection is not a final solution, it is only a workaround.

**Comment by dotnetjunkie** [comment]
The reason that `GetCurrentExecutionContextScope` returns disposed `Scope` instances, is because somewhere in the application, you dispose execution context scopes after the `CallContext`, in which the scope runs, has ended. When `Scope.Dispose` is called when the `CallContext` has ended, the scope is disposed, but because there is no relationship anymore with an active `CallContext`, the `Scope` instance can't be popped from the stack, which can cause a disposed scope to be returned by `GetCurrentExecutionContextScope` later on.

Can you show how you are starting and disposing execution context scopes in your application?

**Comment by oruchreis** [comment]
Thanks for this information. I've looked the code again witih this perpective, I think I've found the problem. I don't know if the following code is the problem, could you confirm?
```csharp
static AStaticClass()
        {
            Task.Factory.StartNew(async () =>
                {
                    while (true)
                    {
                        try
                        {
                            using (Container.BeginLifetimeScope())
                            {
                                  .........
                                  .........
                                  await Task.Delay(1000)
                            }
```
I've moved await Task.Delay to outside of lifetime scope. I've called this static constructor in the start of the web application in an execution context scope:
```csharp
//Owin startup function
public static void Initialize(IAppBuilder appBuilder)
{
  using(Container.BeginExecutionContextScope())
  {
    .........
    .........
    AStaticClass.Foo();
  }
}
```
This Intialize function called once when the web application is started. So after initialization, `ExecutionContextScope` will be disposed. But the async Task in AStaticClass will still be running which is in LifetimeScope. Anyway, Does the `ExecutionContextScope` in the initialization method suppose to be disposed after initialization? And liftimestyleSelector should choose the `LifetimeScope`, because the `ExecutionContextScope` is disposed.

**Comment by dotnetjunkie** [comment]
The `LifetimeScopeLifestyle` scope has a thread affinity. This means you should never ever use the `LifetimeScopeLifestyle` across threads, and asynchronous calls don't work as well. So you should never do an await inside a `using` code block for a lifetime scope. I would have expected the `LifetimeScope.Dispose` method to throw an exception btw, but perhaps here by accident, the same thread will keep handling the operation after the await.

> Does the ExecutionContextScope in the initialization method suppose to be disposed after initialization?


I don't know whether there actually is a proper CallContext when this `Initialize` method runs. It could be there isn't any, and that might be why a disposed `ExecutionContextScope` is dangling around. Since however this `Initialize` method isn't async, you can use `LifetimeScope` as well, which will work for sure.

Do note however, that I think that both the `ExecutionScopeLifestyle` and `LifetimeScope` lifestyle implementations should be improved to ensure never to return disposed Scopes. I just realized that this same problem exists in Web API as well, since Web API will call `IDependencyScope.Dispose` after the CallContext (that captured the request) finished. I'll add a separate work item for this.

**Comment by oruchreis** [comment]
I've removed `await Task.Delay` from the `LifetimeScope`, but this didn't fix the problem. The `ExecutionContextScope` is still not null, but Disposed as state in the lifestyleSelector. I wonder if this is happening because I started `ExecutionContextScope` before registering types and verifying the container? I'm logging after verifying Container, and Logging use `ExecutionContextScope`, so I wrapped `Initialize` method which registers and calls `Verify`, with `ExecutionContextScope`.

**Comment by dotnetjunkie** [comment]
You can try this:

``` c#
//Owin startup function
public static void Initialize(IAppBuilder appBuilder)
{
  using(Container.BeginExecutionContextScope())
  {
      CallContext.LogicalSetData("foobar", "hello");
    .........
    .........
    AStaticClass.Foo();

      string foobar = (string)CallContext.LogicalGetData("foobar");
  }
}
```

If the value of `foobar` is `null` after assignment, that means that call context does not work during OWIN startup, and the `ExecutionContextScopeLifestyle` should not be used.

**Comment by oruchreis** [comment]
I've tried the above test, and foobar isn't null after getting the data. I have tried a background thread instead of async Task, but it didn't solve the problem, too. I didn't fixed the issue but I reduced using reflection by checking `LifetimeScope` instead of `ExectuionContextScope` in the lifestyleSelector. But this changed all project's design decision to accept that the `LifetimeScope` is superior than `ExecutionContextScope`. By doing this, I'm using reflection after checking `LiftetimeScope` is null or not.

**Comment by dotnetjunkie** [comment]
I just pushed v3.1.2 to [NuGet](https://www.nuget.org/packages/SimpleInjector/) and [Github](https://github.com/simpleinjector/SimpleInjector/releases/tag/v3.1.2). That patch release fixes the problem where disposed scopes are returned from `GetCurrentXXXScope()` methods. I hope this helps.
