### ISSUE TITLE
How to use SimpleInjector for ViewComponents in asp.net MVC 6

### ISSUE THREAD

**Issue by Asshiah** [simpleinjector/SimpleInjector#158]
Hello,

I am presently using your DI framework for an asp.net MVC 6 project without a problem.

But recently, I wanted to use the new ViewComponent possibility of the framework.

The thing is I can't find a way to handle Di in ViewComponent using SimpleInjector.
I can't find any activator like for controllers.

Do you have an idea as how this could be done?

Best regards

**Comment by dotnetjunkie** [comment]
Can you supply us with more details about what it is you are trying to achieve?

**Comment by Asshiah** [comment]
I am trying to define a ViewComponent (the new way to define a reusable part of a view) that uses business services that I registered in the SimpleInjector container:

```csharp
public class DashboardCounterViewComponent : ViewComponent
{
	private readonly IBasicCrudService basicCrudService;
	private readonly ISecurityService securityService;
	public DashboardCounterViewComponent(IBasicCrudService crudService, ISecurityService securityService)
	{
		this.basicCrudService = crudService;
		this.securityService = securityService;
	}


	[AllowAnonymous]
	public IViewComponentResult Invoke()
	{            
		var currentIdStr = HttpContext.User.Claims.Where(c => c.Type == "CurrentId").Select(c => c.Value).SingleOrDefault();
		var currentId = Convert.ToInt32(currentIdStr);
		var userPermissions = securityService.GetUserPermissionsByName(User?.Identity?.Name).Select(p => p.Id).ToList();
		var userTenants = securityService.GetUserTenantsByName(User?.Identity?.Name).Select(t => t.Id).ToList();
		var notificationCount = basicCrudService.Get<Notification>(n => n.TargetedUser_Id == currentId && n.Status == Data.Enumerations.NotificationStatus.Unread).Count();
		var taskCount = basicCrudService.Get<CPASTask>(n => (n.Tenant_Id == null || userTenants.Contains(n.Tenant_Id.Value)) && userPermissions.Contains(n.Permission.Id) && n.Status == Data.Enumerations.TaskStatus.Todo).Count();
		ViewBag.NotificationCount = notificationCount;
		ViewBag.TaskCount = taskCount;
		return View();
	}
}
```

I can then display this ViewComponent inside a razor cshtml view like this:

```csharp
@Component.Invoke("DashboardCounter")
```

The thing is that the mvc 6 framework is trying to provide the requested services to the viewcomponent by using the native DI container.

At the moment, I was able to specify the framework to use SimpleInjector's DI container for DI in controllers by using a sample of code you provided (with the controlleractivator):

```csharp
internal sealed class SimpleInjectorControllerActivator : IControllerActivator
{
	private readonly Container container;
	public SimpleInjectorControllerActivator(Container container)
	{
		this.container = container;
	}

	public object Create(ActionContext context, Type controllerType)
	{
		return container.GetInstance(controllerType);
	}
}
```

```csharp
services.AddInstance<IControllerActivator>(new SimpleInjectorControllerActivator(container));
```

I could not find a way to do the same for ViewComponents. I did not foudn any activator classes in the framework.

So I was wondering if you already encountered this problem or if you have an idea as how to do this.

**Comment by dotnetjunkie** [comment]
I'm sorry, but you're out of luck on this one, because an abstraction is missing in ASP.NET 5 that allows intercepting the creation of View Components. Since there isn't an interception point for view components, you're left with intercepting on the `IServiceProvider` level, but as far as I can see, this is not possible.

I reported [this issue](https://github.com/aspnet/Mvc/issues/3752) with Microsoft in the hope that they will address this before RTM. In the meantime, the only work arounds I see are:

 1. Don't use View Components. (Perhaps you can still use controllers like we could in MVC 5).
 2. Make View Components [humble objects](http://xunitpatterns.com/Humble%20Object.html) and use the Service Locator pattern inside View Components.

I know, this really sucks and is really - really ugly. I hope MS will fix this a.s.a.p., because I think this is a real severe design flaw. But please expect more of those awkward design flaws.

**Comment by Asshiah** [comment]
Okay thank you for your answer.

As I could not find any abstraction for intercepting DI for ViewComponents like the ControllerActivator, I thought I was missing something really obvious.

Too bad.

Let's hope MS fixes this.

Thank you again.

**Comment by dotnetjunkie** [comment]
Related to commit c395e86e7aafc22bf819b04c72f83f649241a61b.

**Comment by dotnetjunkie** [comment]
We found a way to override the framework's default behavior. What we did was absolutely ugly, because ASP.NET 5 misses the proper abstractions to do so. But nevertheless, we just pushed [beta2](https://www.nuget.org/packages/SimpleInjector.Integration.AspNet) of the ASP.NET 5 integration package. This beta now contains a `SimpleInjectorViewComponentInvokerFactory` class. This class allows intercepting the creation of ViewComponents. Just replace the built-in with this this one as follows:

``` c#
services.AddInstance<IViewComponentInvokerFactory>(
    new SimpleInjectorViewComponentInvokerFactory(container));
```

This would be all you have to do to let Simple Injector resolve view components. Please let us know if this works for you.

**Comment by Asshiah** [comment]
Thank you very much!

I just tried it and unfortunately, there seems to be a problem with the way the ViewComponents are instantiated.

In my ViewComponent, I was using the ```HttpContext``` Property to assess the current user's claims.

It seems that this property is not populated properly now, so I end-up with a ```NullReferenceException```

```csharp
using Microsoft.AspNet.Authorization;
using Microsoft.AspNet.Mvc;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json;
using CPAS.Web.ViewModels;

namespace CPAS.Web.ViewComponents
{
    public class MenuViewComponent : ViewComponent
    {
        public MenuViewComponent()
        {
        }

        [AllowAnonymous]
        public IViewComponentResult Invoke()
        {
            List<AllowedTenant> allowedTenants = new List<AllowedTenant>();
            var claim = HttpContext.User.Claims.Where(c => c.Type == "AllowedTenants").Select(c => c.Value).SingleOrDefault();
            if (claim != null)
                allowedTenants = JsonConvert.DeserializeObject<List<AllowedTenant>>(claim);
            return View(new MenuViewModel { AllowedTenants = allowedTenants });
        }
    }
}
```

**Comment by dotnetjunkie** [comment]
Ahh... okay... now I understand what the `IViewComponentActivator` abstraction is for :-/

**Comment by dotnetjunkie** [comment]
I pushed a [beta3](https://www.nuget.org/packages/SimpleInjector.Integration.AspNet) package to NuGet. Would you like to try it again?

**Comment by Asshiah** [comment]
OK, this is working great!

Thank you very much for your time!^^

**Comment by dotnetjunkie** [comment]
Cool! Great that this is working out.

![a-team](http://blogs.northampton.ac.uk/history/files/2014/03/a-team-t-shirt-hannibal-a-plan-comes-together.jpg)

**Comment by dotnetjunkie** [comment]
@Asshiah, if you install beta4, you can also batch-register your view components as follows:

``` c#
container.RegisterAspNetViewComponents(app);
```

**Comment by Asshiah** [comment]
Thank you ;-D
