### ISSUE TITLE
Add .NET Native support.

### ISSUE THREAD

**Issue by coonmoo** [simpleinjector/SimpleInjector#162]
We are currently porting our app to Windows Universal Platform.

We'd like to continue using Simple Injector but have some problems when enabling the .NET Native Toolchain in Release mode.

> C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x86\ilc\IlcInternals.targets(1408,5): warning : Assembly 'SimpleInjector' requests the address of the virtual method 'Type.IsAssignableFrom(Type)' which is not available in the targeted .NET platform. Please ask the author of 'SimpleInjector' to provide an implementation that can be used in the currently targeted .NET platform.

> C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x86\ilc\IlcInternals.targets(791,7): error : MCG0024: MCG0024:UnresolvableTypeReference Unresolvable type reference 'System.Reflection.Emit.Label' in 'Assembly(Name=mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)' found. Check the references in your build system. A reference is either missing or an assembly is missing an expected type.

Is there any chance you could add .NET Native support to Simple Injector?

**Comment by dotnetjunkie** [comment]
At this time, we have no plans to invest into a .NET Native compatible version of Simple Injector.

Dependency Injection libraries depend heavily on both the ability to reflect over types and assemblies. On top of that Simple Injector depends heavily on the ability to generate code at runtime by building up expression trees. Both are scenarios that aren't well supported with .NET native. This is quite obvious when you think about it, .NET Native is a pre-compiler instead of a just-in-time compiler, like .NET is. That would make it a huge time investment.

My advice is to refrain from using a DI container in your native app and instead hand-wire your object graphs in the start-up path of the application. This is a practice called [Pure DI](http://blog.ploeh.dk/2014/06/10/pure-di/). The use of Pure DI allows the application to be designed around the use of dependency injection, while having the structure of object graphs pre-compiled up-front. Pure DI seems a very good fit for mobile applications that usually have quite simple object graphs and can't afford the overhead and additional start-up costs that JIT-compiling DI containers bring.

**Comment by MattWhilden** [comment]
Hello! I'm a developer on the .NET Native runtime and compiler team. If/when you decide to tackle this workitem we're happy to assist with any .NET Native related issues you have. The big one would be the use of Reflection.Emit which is unsupported at this time. However, using the System.LinqExpression namespace is support via an interpreter. So perhaps it's not as bleak as it seems!

Anyhow, feel free to tag me or send mail to dotnetnative@microsoft.com. Happy to work with you so that our mutual customers can be successful.

**Comment by dotnetjunkie** [comment]
Hi @MattWhilden,

That is awesome. Can you supply us with more information about how to use this interpreter?

**Comment by MattWhilden** [comment]
You should get this behavior "for free" when using .NET Native. It does have the side effect of your calls to Compile not actually doing anything. While the interpreter loop is slower for heavy throughput scenarios, the speed of startup is often enough for this model to be MORE performant. It will depend the specifics of what you're doing though.

**Comment by dotnetjunkie** [comment]
Hi @MattWhilden, 

But if it is supported, what is the reason the OP is getting this weird exception?

**Comment by MattWhilden** [comment]
The error above is about Reflection Emit which is unsupported. System.Linq.Expression trees are supported. The warning about Type.IsAssignableFrom is because this library isn't built targeting the .NET Core APIs. The framework folks have done a bit of shuffling. I presume that API was moved to TypeInfo.

**Comment by dotnetjunkie** [comment]
@coonmoo, can you try Simple injector again with the latest version? We now have support for .NET Core nd according to @MattWhilder, that should solve the problem.

**Comment by zedr0n** [comment]
Hm, I'm currently using SimpleInjector in a UWP application and I didn't have issues so I guess .net native is working fine as UWP only compiles to .NET Native as far as I understand

**Comment by MattWhilden** [comment]
If you're in the DEBUG configuration you're most likely running without .NET Native. If you've pushed something through the store then it's definitely running as .NET Native and would be great news.

**Comment by zedr0n** [comment]
Yes, I just double checked and for some reason .NET Native Toolchain was disable for Release. When trying with .NET Native some registrations are not supported, getting an exception "PlatformNotSupported_NoTypeHandleForOpenTypes" 

`
            container.Register(typeof(IScopeFactory<,>), typeof(ScopeFactory<,>), Lifestyle.Singleton);
`
So it seems like for the moment the open generic types auto-resolution doesn't seem to be supported

**Comment by MattWhilden** [comment]
If you stop on first chance exceptions are there any new ones with .NET Native enabled? In particular you may see things like MissingMetadataException.

**Comment by dotnetjunkie** [comment]
It kind of makes sense that .NET native foes not support open generic types, because this would mean new types need to be created at runtime and they need to be JITted.

But this is of course a  serious downside which basically means you will have to register all closed versions up-front. Not nice from a maintainability perspective, but still doable, since you can verify the container with a simple test.

**Comment by zedr0n** [comment]
It's a bit painful as even if I remove the open interfaces to stay just with concrete types I still need to register explicitly to apply the lifestyle. But this can probably be worked around.

Getting some more exceptions going forward, multidimensional arrays are not supported. Also a MissingTemplateException, seems like it's going to take some time.

**Comment by MattWhilden** [comment]
We've added some more build time static analysis stuff to VS that is useful when first migrating projects. If can be enabled thus: project properties > build > Enable static analysis for .NET Native. 

I'm a bit surprised you ran into the Multidimensional array exception. Currently, .NET Native supports arrays up to dimension 4. For .NET Native we did some analysis that showed that 5+ dimension arrays were exceedingly rare (only 9 apps in the entire Windows catalog had higher dimensional arrays). If it's a real blocking issues, we'd love to know more about your scenario and if various workarounds are too cumbersome, ex: use an array of arrays instead.

As for the MissingTemplateException, we have some work that will be shipped as part of VS Update 2 RTM that should completely eliminate this class of issue. It's actually pretty rare for our analysis to fail here but it's quite annoying when it does! I suspect it will be shipped sometime in late March or early April. For now you're stuck using Runtime Directives to give us hints. More info here: http://rdxml.net

**Comment by zedr0n** [comment]
This multidimensional issue was just a really hacky workaround for creating new types in CoreCLR. I fully expect this not to work

    typeof(DynamicType).MakeArrayType(dim[hash])

where hash is a hash of an attribute string. This allows me to define new dynamic types at runtime

    typeof(Element<>).MakeGenericType(typeof(DynamicType).MakeArrayType(dim[hash]))

giving something like Element<DynamicType[]>. The maximum number of dimensions is the maximum number of types I can create this way. This seems to work in CoreCLR but I understand why it would be an issue in Native

**Comment by MattWhilden** [comment]
Thanks for the info.
