### ISSUE TITLE
Log function calls

### ISSUE THREAD

**Issue by taxinvoice** [simpleinjector/SimpleInjector#164]
I am very new to IOC programming, but was told years ago that using IOC framework i could easily record every function that was called and all its parameters.  Can anyone help me provide this ability?

I usually  put a Trace("Start:FunctionA") at the beginning of all my functions, but is there a better way?

**Comment by dotnetjunkie** [comment]
An IOC framework by itself would not be able to 'record every function that was called'. An IOC container is just a tool that makes it easier to construct object graphs of application components.

What you seem to want is to use interception. Interception is the ability to decorate services with a dynamically generated classes that allow adding custom logic (the so called interceptor) to the code of the service. This requires an interception library. There is one library that has built-in support for interception, and that's Microsoft Unity. Other IOC libraries integrate with Castle Dynamic Proxy, which is the de facto standard OSS interception library.

Simple Injector lacks any official interception support or integration package for Castle Dynamic Proxy, but [documentation explains how to use interception with Simple Injector](https://simpleinjector.readthedocs.org/en/latest/advanced.html#interception) and [Stackoverflow q/a](https://stackoverflow.com/questions/24513530/using-simple-injector-with-castle-proxy-interceptor) explains how to integrate with Castle.

> I usually put a Trace("Start:FunctionA") at the beginning of all my functions, but is there a better way? 

Having to write code that is not part of the problem domain (such as logging, security, etc) in every function is an absolute horrifying approach. This makes application an absolute maintenance nightmare for you and any future developer. Interception gives you a much better method, because it allows your application code to stay clean of any such cross-cutting concern.

Still however, you will see that Simple Injector doesn't support interception at all. That's because we feel that although interception might be a step into the right direction when it comes to application maintainability, it is still a matter of treating the symptoms. Interception is used in places where the application design is suboptimal; the SOLID principles are violated.

> but is there a better way? 

With Simple Injector, we promote designs that are founded on the SOLID principles and allow cross-cutting concerns to be applied effectively using [decoration](https://en.wikipedia.org/wiki/Decorator_pattern) instead of interception. Articles like [this one](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=91) and [this one](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=92) describe a design that applies the SOLID principles and leads to code that can be enriched with cross-cutting concerns without the need to use tools such as interception libraries of code-weaving tools.

Whether such design is suited for you is hard to say. It might be a bridge too far for you and your team, considering the fact that you're very few to IOC programming, and probably the related patterns, principles and practices. What I can advise however is to read those articles and if you feel that this is not suited for you and your team yet, try out interception first. Interception will not solve the problems you have in your design, but at least your code will become cleaner and more maintainable than it is today.

Good luck.
