### ISSUE TITLE
Expand existing RegisterAll dynamically

### ISSUE THREAD

**Issue by Sebazzz** [simpleinjector/SimpleInjector#17]
I am currently building a component that needs to use a collection of `IThing`, this is an abstract example of course. Using SimpleInjector it is possible to register multiple services using `RegisterAll`. This works of course great... unless you want to dynamically register more services, for example using `SimpleInjector.Packaging`.

Is there a built in way to do this using SimpleInjector? If not, how would I do this, and are there better ways? I noticed that it is sometimes possible to abuse the decorator pattern for this.

**Comment by dotnetjunkie** [comment]
The normal (an adviced way) to register collections of things is by calling `RegisterAll`. This means that during the call all types must be available. Usually this is not an issue, because you can reflect over the loaded assemblies dynamically as follows (snippet taken from [the documentation](https://simpleinjector.readthedocs.org/en/latest/advanced.html#registering-plugins-dynamically)):

``` c#
string pluginDirectory =
    Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Plugins");

var pluginAssemblies =
    from file in new DirectoryInfo(pluginDirectory).GetFiles()
    where file.Extension.ToLower() == ".dll"
    select Assembly.LoadFile(file.FullName);

var thingTypes =
    from assembly in pluginAssemblies
    from type in assembly.GetExportedTypes()
    where typeof(IThing).IsAssignableFrom(type)
    where !type.IsAbstract
    where !type.IsGenericTypeDefinition
    select type;

container.RegisterAll<IThing>(thingTypes);
```
If however it is impossible, or undesired, to register all types in one call to `RegisterAll`, the registration can be split up in multiple calls to `AppendToCollection`. `AppendToCollection` is an extension method that lives in the `SimpleInjector.Advanced` namespace. Here's an example:

``` c#
// using SimpleInjector.Advanced;
container.AppendToCollection(typeof(IThing), typeof(ThingImpl1));
container.AppendToCollection(typeof(IThing), typeof(ThingImpl2));
container.AppendToCollection(typeof(IThing), typeof(ThingImpl3));
```

The `AppendToCollection` extension method is a bit hidden, because it is primarily meant for integration scenarios (integration with libraries and frameworks that use the [Conforming Container pattern](http://blog.ploeh.dk/2014/05/19/conforming-container/)) and require registration of collections in multiple calls. By putting this method in a different namespace, we try to prevent it from cluttering the main API and prevent the method from being used in case `RegisterAll` would do just fine.

**Comment by Sebazzz** [comment]
Right, good to know. I understand from your post it is usually better to have a factory instead. I assume that factory would then call into the container directly?

**Comment by dotnetjunkie** [comment]
My previous comment does not advice the use of factories nor does it argue against this. But if you describe what you are trying to achieve, I can tell you whether the use of a factory is the right approach or not.
