### ISSUE TITLE
Registering DelegatingHandler using RegisterCollection causes DiagnosticType.DisposableTransientComponent

### ISSUE THREAD

**Issue by abatishchev** [simpleinjector/SimpleInjector#183]
I register all Web Api pipeline related components within the container:
```csharp
container.RegisterCollection<DelegatingHandler>(
    new[]
    {
        typeof(CertificateValidationHandler),
    });
````
and the wire them up with the pipeline itself:
```csharp
foreach (var handler in container.GetAllInstances<DelegatingHandler>())
{
    handlers.Add(handler);
}
```
Since I don't explicitly specify lifestyle, this causes a warning accordingly:

>[Disposable Transient Component] CertificateValidationHandler is registered as transient, but implements IDisposable.
See the Error property for detailed information about the warnings. Please see https://simpleinjector.org/diagnostics how to fix problems and how to suppress individual warnings.

What would be the right way to solve this, other than suppress the warning.?

Maybe additional overload?
```csharp
void RegisterCollection<TService>(IEnumerable<Type> serviceTypes, Lifestyle lifestyle) where TService : class
```

**Comment by dotnetjunkie** [comment]
Register the handler as singleton, because this is what happens anyway when you add thrm to the list of hsndlers in Web API.

**Comment by abatishchev** [comment]
Yes, true. But how to register singletons using RegisterCollection()? Looks like there is no way. I use this method since down the road I don't need to get them by type. This isn't a problem for 1 but is for 10+. Also you need do not forget to do this, i.e. register each twice. If there would be the overload I propose, it would solve this problem.

**Comment by dotnetjunkie** [comment]
There are several ways to register a collection of singletons. For instance by registering the concrete type as singleton as well:

``` C#
c.RegisterSingleton<X>();
c.RegisterCollection<I>(new [] { typeof(X) }),
```

Amother option is to use the `RegisterCollection` overload that takes a list of `Registration` objects. You can supply it with an instance created with a `Lifestyle.Singleton.CreateRegistration` overload.

**Comment by abatishchev** [comment]
Thanks, that worked! But still wouldn't the overload benefit and simplify?

**Comment by dotnetjunkie** [comment]
We have considered the overload before, but this can lead to inconsistency. For instance, what would the expected lifestyle of X be here?

``` c#
c.Register<X>(Lifestyle.Transient);
c.RegisterCollection<I>(new [] { typeof(X) }, Lifestyle.Singleton);
```

That's why we decided not to include this overload. Insteadyou can use the two suggested methods -or- in case all your registrations are singleton by default, it might be easier to override the `LifestyleSelectionBehavior`.

**Comment by abatishchev** [comment]
I see. Yes, this makes sense. Thanks, as always!

**Comment by legion-gaming** [comment]
This is wrong. You do not register handlers as singletons, and here's why. Consider a handler called OAuthHandler. The constructor of that handler takes in IOptionsSnapshot<OAuthHandlerOptions>. This is a configurable and re-usable handler so that I can have multiple http clients that can configure their own OAuth options.
