### ISSUE TITLE
How to SuppressDiagnosticWarning on a disposable decorator

### ISSUE THREAD

**Issue by rowdy1** [simpleinjector/SimpleInjector#191]
I'm attempting to register and verify a decorated object, both the underlying implementation and decorator are disposable.  

After registering the implementation and decorator (both as transient) I have added a suppression statement as per below

`Registration interfaceRegistration = container.GetRegistration(typeof(IObject)).Registration;
interfaceRegistration.SuppressDiagnosticWarning(DiagnosticType.DisposableTransientComponent, "Disposal will be handled by creation factory");`

After applying the suppression the container verification is still failing on the decorated object (without the suppression statement it will fail on both implementations).  Are you able to confirm if there is a way to suppress this warning on the decorator?

**Comment by qujck** [comment]
Can I ask why they both implement `IDisposable`?

**Comment by rowdy1** [comment]
The object is to be placed in a pool, the job of the decorator is to release the object back to the pool unless the pool is disposed.

**Comment by qujck** [comment]
Okay,

I can't see how to supress the warning for the decorator so it may be a feature we need to add, we'll need to look into it. I know it's not ideal but you can use `container.Verify(VerificationOption.VerifyOnly);` to prevent the container throwing an exception.

**Comment by qujck** [comment]
I still can't understand why the decorator needs to implement `IDisposable`. Is it because `IObject` implements `IDisposable`? If so then I suggest you fix that - abstractions rarely need to force all implementations to be disposable.

**Comment by rowdy1** [comment]
Thank you for the prompt responses.

Really like the SimpleInjector is implemented, Good job guys...

**Comment by rowdy1** [comment]
Both implementations implement IDisposable independently.  The decorator won't actually dispose the object and forward to the underlying implementation unless the pool is disposed.

Allows the following code to be used against the pool.

`using (IObject objectInstance = pool.Acquire())
{

}`

when the object falls out of scope the decorator will intercept the Dispose call and return the object to the pool.  When the pool is disposed it will forward the dispose call to the underlying implementation, hence the underlying implementation will not need to know about the existence of the pool.

**Comment by dotnetjunkie** [comment]
Sorry for my late response. I find the use of decorators a strange design choice. At one hand, you use the container to create and control an object, but you wrap it with a decorator that seizes control by sending it to a pool.

The concept of object pooling is an old and proven concept, but you should be careful mixing this with a DI container. I think it's better to separate these responsibilities and perhaps a decorator is not the best choice.

Since the consumer seems to call Dispose on the decorator (instead the container), I think it's much better to make your design more explicit by using a factory class. The factory class can itself wrap the objects in a decorator that allows returning items to the pool.

Also be careful with pooling items that are built up by the container. Pooled items live for a very long time, which basically means it should only contain singleton dependencies (to prevent Lifestyle Mismatches). But if you implement your own pool, Simple Injector will be unable to detect any mismatch.

**Comment by dotnetjunkie** [comment]
The warning can be suppressed on decorators, but you'll have to make sure the container has built the object graph of that particular object. One way of doing that is by calling `Verify(VerificationOption.VerifyOnly)`. After that you can suppress the warning and diagnose by calling `Verify()`:

``` c#
container.Verify(VerificationOption.VerifyOnly);

var r = container.GetRegistration(typeof(IObject));
r.Registration.SuppressDiagnosticWarning(DiagnosticType.DisposableTransientComponent, "message");

container.Verify();
```

When Simple Injector hasn't built the graph, it doesn't yet know about the decorator, and `GetRegistration` will get the `InstanceProducer` of the real instance instead of the decorator. After calling `Verify(VerificationOption.VerifyOnly)`, this information is known and the `InstanceProducer` returned from `GetRegistration` will be that of the outer-most decorator. In case the disposable decorator isn't the outer-most, you'll have to go through the list of relationships, as follows:

``` c#
container.Verify(VerificationOption.VerifyOnly);

var r = container.GetRegistration(typeof(IObject)).GetProducers()
    .Single(p => p.ImplementationType == typeof(DisposableDecorator));
r.Registration.SuppressDiagnosticWarning(DiagnosticType.DisposableTransientComponent, "message");

container.Verify();
```

Here `GetProducers` is the following self-defined extension method:

``` c#
public static IEnumerable<InstanceProducer> GetProducers(this InstanceProducer producer) => 
    from relationship in producer.GetRelationships()
    from childProducer in GetProducers(relationship.Dependency).Concat(new[] { producer })
    select childProducer;
```
