### ISSUE TITLE
Hybrid scoped registration

### ISSUE THREAD

**Issue by zedr0n** [simpleinjector/SimpleInjector#192]
Is it possible to not only use a different lifestyle based on whether we are within executing scope
`            _hybridLifestyle = Lifestyle.CreateHybrid(
    lifestyleSelector: () => _container.GetCurrentExecutionContextScope() == null,
    trueLifestyle: Lifestyle.Transient,
    falseLifestyle: new ExecutionContextScopeLifestyle());
`

but also resolve a different implementation type? I was thinking something like this would work

`            _container.RegisterConditional<IElementProvider, WebElementProvider>(_hybridLifestyle, c => _container.GetCurrentExecutionContextScope() == null);
            _container.RegisterConditional<IElementProvider, ElementProvider>(_hybridLifestyle,
                c => _container.GetCurrentExecutionContextScope() != null);
`

but the predicate is not suitable for runtime checking. Overriding expressionBuilding has the same problem

**Comment by dotnetjunkie** [comment]
You can do it as follows:

``` c#
container.Register<ElementProvider>();
container.Register<WebElementProvider>(Lifestyle.Scoped);
container.Register<IElementProvider>(() =>
    container.GetCurrentExecutionContextScope() == null
        ? container.GetInstance<ElementProvider>()
        : container.GetInstance<WebElementProvider>());
```

But it's in general better to prevent dynamic build ups of your object graphs, because this makrs it much harder to verify the correctness of the graph. So instead use a proxy class that allows switching to the correct implementation at runtime:

``` C#
container.Register<ElementProvider>();
container.Register<WebElementProvider>(Lifestyle.Scoped);
container<IElementProvider, ProviderProxy>();
```

ProviderProxy is a class tjat gets ElementProvider and WebElementProvider (and the Container) injected onto its constructor, and everytime the IElementProvider method(s) is called, it will determine to which imementation the call should be forwarded. This makes the complete object graph known upfront, which allows complete analysis and diagnostic support.

**Comment by zedr0n** [comment]
Thanks, that makes a lot of sense
