### ISSUE TITLE
SimpleInjector and UWP

### ISSUE THREAD

**Issue by zedr0n** [simpleinjector/SimpleInjector#195]
I've been using Simple Injector in UWP apps and I've had to resort to a Service Locator pattern to create dependencies as UWP has its own internal implementations of navigation services (e.g. Frame.Navigate() ) which as far as I understands limits the ability of changing the constructor arbitrarily ( I think it will always use a no argument constructor ). I've tried to get inspired from WPF and ASP.NET integration guides but there doesn't seem to be a way in UWP to override the default page construction mechanisms. 

Am I missing something obvious here?

**Comment by TheBigRic** [comment]
I guess not. I never used UWP, but I made a POC project for this [issue](https://github.com/simpleinjector/SimpleInjector/issues/173#issuecomment-173953299) and as you can see I wrote there:

> And for some reason we (us developers) are back to square one because the page behind does not support constructor arguments

I did not spend too much time finding if there is something to do about it, but a quick google confirms `Frame.Navigate` expects a parameterless constructor. I can't believe MS did this, because we back to Asp.Net webforms of this is really the case, but as it stands I'm unsure how to bypass this.

Sorry, not being to help you any further. Please keep us posted how you proceed with this issue.

**Comment by dotnetjunkie** [comment]
@zedr0n, the OP of issue #173 states that he is able to do ctor injection with Autofac. You might want to investigate what Autofac is doing to make this work. You can probably apply a similar strategy with SI.

**Comment by TheBigRic** [comment]
@zedr0n, @dotnetjunkie 
The OP from #173 refers to Autofac when talking about using an IOC container in using the design time datacontext for his XAML views. 

He never replied to the issue with Frame.Navigate and supplying an instance instead of a type. So while this might work in Autofac, I doubt it actually does. 

However, if you would use the MVVM pattern and let your pages just be pages, you don't need parameters in the constructor of the page and use a ViewModel for all your logic. It nevertheless is still very strange of MS to force this in this way.

**Comment by dotnetjunkie** [comment]
Here's a related question on Stackoverflow: https://stackoverflow.com/q/35832160
