### ISSUE TITLE
Q: Understanding complex injection

### ISSUE THREAD

**Issue by CaninChristell** [simpleinjector/SimpleInjector#196]
I've been Googling around on this issue and haven't come across any clear explanation of how-to with complex conditional injection. One of the common concerns voiced is that one is not fulfilling the Liskov Substitution Principle, but I don't believe that's the case with this design.

(I have viewed the [documentation on the subject](https://simpleinjector.readthedocs.org/en/latest/advanced.html#context-based-injection), but either I'm not understanding it, or it's addressing a different concern)

Say that you have the interface `IDataReader<T>`, and the concrete implementations `CacheReader<T>`, `MongoReader<T>`, `SqlServerReader<T>`, and `OracleReader<T>`. All have a simple method that takes an ID (let's say always an int), and returns T. Several business logic classes depend on `IDataReader<T>`, and let's say that's fulfilled by `CacheReader<T>` (with the freedom to change this choice in the future). CacheReader itself also depends on another `IDataReader<T>`. This dependency might be on any of the three other implementations of IDataReader, which is defined using Simple Injector at compile type (not dynamically). 

How, then, would you specify: 

``` c#
new ConcreteA(
	new CacheReaderDecorator<T>(
		new MongoReader<T>()))

new ConcreteB(
	new CacheReaderDecorator<T>(
		new SqlServerReader<T>()))

new ConcreteC(
	new CacheReaderDecorator<T>(
		new OracleReader<T>()))

new ConcreteD(
	new CacheReaderDecorator<T>(
		new OracleReader<T>()))
```

Again, I don't think this is violating LSP as all of the `IDataReader<T>`s fulfill the programmatic requirements (return T given an ID of _) and externally viewed none of them behave differently; CahceReader could be removed and have Concrete[A,B,C] depend directly on a data storage implementation of `IDataReader<T>`, and Concrete[A,B,C] should not be able to tell the difference.

The only issue, then, is if the ultimate storage technology houses the desired information, which I don't think should be the concern of the code architecture or injection.

I apologize if this was wordy, I was just trying to provide clarity to my lack of understanding, and state what I've worked through/thought through.

**Comment by dadhi** [comment]
+1.

CacheReader seems like a good fit for Decorator.

What about the rest?

**Comment by dotnetjunkie** [comment]
Hi @CaninChristell,

@dadhi is right, your `CacheReader<T>` is a decorator. So for convenience, let's rename it to `CacheReaderDecorator`<T>.

So if I understand correctly, these are the object graphs you wish to build:

    new ConcreteA(
        new CacheReaderDecorator<T>(
            new MongoReader<T>()))

    new ConcreteB(
        new CacheReaderDecorator<T>(
            new SqlServerReader<T>()))

    new ConcreteC(
        new CacheReaderDecorator<T>(
            new OracleReader<T>()))

    new ConcreteD(
        new CacheReaderDecorator<T>(
            new OracleReader<T>()))

You can achieve this by using the following configuration;

    container.RegisterConditional(typeof(IDataReader<>), typeof(MongoReader<>),
        c => c.Consumer.ImpementationType == typeof(ConcreteA));
    container.RegisterConditional(typeof(IDataReader<>), typeof(SqlServerReader<>),
        c => c.Consumer.ImpementationType == typeof(ConcreteB));
    container.RegisterConditional(typeof(IDataReader<>), typeof(OrackeReader<>),
        c => !c.Handled);

    container.RegisterDecorator(typeof(IDataReader<>), typeof(CacheReaderDecorator<>));

> I don't think this is violating LSP as all of the IDataReader(T)s fulfill the programmatic requirements (return T given an ID of _) and externally viewed none of them behave differently; 

Whether or not the implementations use the same abstraction is irrelevant for adhering to the LSP.  Instead you should ask yourself what would happen to your application if you supply say for instance `ConcreteA` with an `OracleReader` instead of a `MongoReader`. Would that break `ConcreteA` at runtime or would it keep functioning correctly?

If `ConcreteA` would keep functioning correctly (e.g. no exception is thrown), you adhere to the LSP. But in case it would break `ConcreteA`, you are in fact violating the LSP,  since clearly the implementations of `IDataReader` behave in an incompatible way (since LSP states that implementations should be interchangeable). The contract of an interface consists not only of its method signature; it consists of its behavior as well; this behavior can be defined both implicitly or explicitly.

So the LSP states that when implementations behave differently in a way that affects their consumers, they deserve their own interface.

So in general, when it comes to databases, it is the data model that defines the interface. So in case all three databases have the exact data model (i.e. same set of entities), they can use the same contract. But when each database has a different data model (say Mongo conrains Products and ProductDetails, while SQL contains Orders and OrdeItems and Oracle contains Customers), in that case LSP states that the `IDataReader` should be split into multiple abstractions.

**Comment by CaninChristell** [comment]
Thank you for the reply, Steven! I think I follow the logic up until the
!c.Handled part. What is that accomplishing, and why?

As far as the LSP; as long as the various data storage technologies were
upholding the contract of storing (and returning) type T then nothing
should break, and thus Concrete[A,B,C,D] shouldn't care if they are being
fulfilled by whichever IDataReader; the code itself is LSP. It'd be up to
the programmer to ensure he was injecting dependencies properly based on
where the items actually were being stored, and adjusting the injection if
the storage choices changed. Since the chance of code breakage would be
strictly outside the actual code itself (including the data access), and
dependent on the storage itself (the data) fulfilling an imposed contract,
wouldn't this be a LSP sound design?

I feel as though it is LSP sound, as it accomplishes the code-side promises
and consistency that LSP is trying to enforce. And this solution allows,
say, Product and ProductDetails to move from Mongo to Oracle by only
changing the injection (and a new concrete that fulfills the interface) and
leaving absolutely all of the existing code untouched, thus abiding by the
Open Close Principle.

Is that all correct? I'm new to actually trying to implement SOLID (thus
why I'm trying to work through the logic of dependency injectors) so these
concepts are fairly new to me.

**Comment by dotnetjunkie** [comment]
> I follow the logic up until the
!c.Handled part. What is that accomplishing, and why?

Simple Injector handles `RegisterConditional` calls in order of registration and it will prevent accidental overlapping registeations. It will throw an exception if two predicates return true for the same service type. So what `!c.Handled` does is selecting that registration if no of the previous predicates return true. In other words, the `OracleReader` has now become the fallback implementation.

I used `.Handled` explicitly to show this part of the API to you, and because it was easier to write for me than checking both ConcreteC and ConcreteD in the predicate. Whether is is the best solution obviously depends on your application. In your case it might be better to not use `Handled`, and instead specify all types explicitly, to prevent the fallback to be selected by accident. You lose a bit of verifiability when you use `Handled`.

I'll comment on the LSP another time. My wife now wants me to visit some Cambodian temples with her (we're on holiday, wish me luck ;))

**Comment by dotnetjunkie** [comment]
> As far as the LSP; as long as the various data storage technologies were
upholding the contract of storing (and returning) type T then nothing
should break.

I would say this is correct. From perspective of the LSP, each closed implementation of the `IDataReader<T>` abstraction should be considered a different interface. This is obvious, because you can't replace an `SqlReader<Person>` with a `OracleReader<Order>`; that would simply not compile. Btw, from perspective of the CLR this is also the case. This means that each closed version should be checked against the LSP in isolation. And in that case, as long as your `SqlReader<User>` can be replaced with an `OracleReader<User>` without breaking a consumer, you're fine.

This is much different when you would have a non-generic `IDataReader` abstraction that allowed retrieving any entity, while you have one implementation managing one data model, while another implementation would manage a total different data model. Note that this is different than having simply a `SqlReader` that allows connecting to any model in a SQL database, and having an `OracleReader` that connects to any model in an Oracle db. In that case the implementations would still adhere to the LSP. When the implementations however would have code specific to their data model (that the other implementation lacks), it would make it impossible to swap implementations (ignoring the fact that of course the db should contain those tables, but that is out of scope what the LSP is concerned).
