### ISSUE TITLE
ASP.NET Web Forms and ResolveUnregisteredType event

### ISSUE THREAD

**Issue by s9ilent** [simpleinjector/SimpleInjector#199]
The current recommended solution approach for DI with ASP.NET Web Forms [Link](http://simpleinjector.readthedocs.org/en/latest/webformsintegration.html?highlight=asp) results in the ResolveUnregisteredType being raised. 

This issue appears to be caused due to the fact that the IHttpHander is not the Page type that is registered, but is a derived type of it (presumably created at runtime by ASP. Also this type is not in the reflected types enumeration yet, as the default behaviour of ASP is to compile the type when it is first requested)

Suggestions:
a) Update the documentation with a note about this

or

b) Consider creating an object that holds onto the registered types. 

This will also also allow a more explicit registration (rather than an implicit registration w/ attributes, as the linked implementation also has the side effect of attempting to resolve ALL aspx pages, even if they have no explicit code behind and do not need registration)

Example signature:
(I personally used a Concurrent dictionary, but there may be better ways to implement this directly in the IOC container it self?)

``` c#
class ExampleWebFormsHelper: IPropertySelectionBehavior
{
    public ExampleWebFormsHelper(Container container) { }
    public void RegisterPage(Type type) { }
    public bool SelectProperty(Type serviceType, PropertyInfo propertyInfo) { }
    public bool TryInitializeInstance(IHttpHandler httpHandler) { }
    public bool IsTypeHandled(Type type) { }
}
```

 
(If requested I can do a more complete write up in pull request)

**Comment by dotnetjunkie** [comment]
I think you misunderstood the reason for the registration of those Page classes.

You are right; ASP.NET generates classes on the fly the add markup to the defined Page class. In the end, those generated classes will be resolved from the container instead of the original. This means that the originally registered page classes are in fact never resolved from the container. 

But the sole reason for them to be registered is to be able to verify the complete object graph including those page classes. Object graph verification is important, because it is a fail-fast mechanism that can safe precious time during development. To be able to have a trustworthy verification, we need to resolve/verify all page classes, even if some (currently) have no dependencies (yet). Perhaps the description of the 'why' of this is missing from the documentation; it would be good to add it.

It is true that after that the registrations of those Page classes keep dangling around, consuming memory, without being used. The amount of memory however is quite low and should typically not cause any problems in a web application.

You can skip thebwhole registration of Page classes altogether and your application will keep working. However, you will lose the possibility to diagnose and verify the complete object graph.

Do you have a particular issue that causes problems to you?

**Comment by s9ilent** [comment]
You are correct I thought it was required as opposed to just used for verification. 

My issue is minor and only used in debug. 

I merely use the ResolveUnregisteredType for debugging/diagnosing broken dependencies hidden by the common service locator pattern (which is unfortunately required due to 3rd party library limitations requiring a parameterless constructor with out any effective DI entry point), which kept catching the aspx pages (which is enough to by pass by simply ignore Page types.

**Comment by dotnetjunkie** [comment]
Documentation updated.
