### ISSUE TITLE
How To: Decoration and Composition registrations 

### ISSUE THREAD

**Issue by ricardo100671** [simpleinjector/SimpleInjector#200]
Hi All 

I have the following

``` c#
abstract class Message {}

abstract class Handler<T>
    where T : Message
{
    public abstract void Handle(Message message);
}

abstract class ValidationDecorator<T> : Handler<T> 
    where T : Message
{
     Handler<T> _decoratee;
     public Validator(Handler<T> decoratee){
         _decoratee = decoratee;
      }
}

abstract class CompositeHandler<T> : Handler<T>
    where T : Message
{
    IEnumerable<IHandler<T>> _handlers;

    public Manager(IEnumerable<T> handlers) {
        _handlers = handlers
    }
}

class PlaceOrder :  Message {
    public string Country;
}

class PlaceOrderValidationDecorator : ValidationDecorator<PlaceOrder> {}

class PlaceOrderEuropeanHandler : Handler<PlaceOrder> {}

class PlaceOrderDefaultHandler : Handler<PlaceOrder> {}

class PlaceOrderCompositeHandler : CompositeHandler<PlaceOrder>{
    public PlaceOrderCompositeHandler(IEnumerable<Handler<PlaceOrder>> handlers)
        : base (handlers) {}
    
    public void Handle (PlaceOrder message){
        if(message.Country == "UK") 
            _handlers.OfTType<PlaceOrderEuropeHandler>.Single().Handle(message);
        else
            _handlers.OfTType<PlaceOrderDefaultHandler>.Single().Handle(message);            
    }
}

class ReduceInventory : Message {}

class ReduceInventoryValidationDecorator : ValidationDecorator<ReduceInventory> {}

class ReduceInventoryHandler : Handler<ReduceInventory> {}

class TakePayment : Message {}

class TakePaymentHandler : Handler<TakePayment> {}
```
Now I would like to be able to call something like container.GetAllInstances(typeof(Handler<>)) which should give me an collection containing the following instances
ReduceInventoryValidationDecorator
PlaceOrderCompositeHandler
TakePaymentHandler
where the decoration and composition chains are setup correctly. 

I have tried various registration strategies but cannot seem to get it to work. Or maybe I have the whole concept of how decoration and composition should work . 

Some advise would be much appreciated. 

Thank you

**Comment by TheBigRic** [comment]
When looking at your design you have created something that looks a lot the patterns described [here](https://cuttingedge.it/blogs/steven/pivot/entry.php?id=91) and [here](https://cuttingedge.it/blogs/steven/pivot/entry.php?id=92). But looking more closely, you made some, from my perspective, awkward design decisions which are causing the problems you're having right now.

First of all the use of all the abstracts seem odd to me. It would be best to define the same infrastructure based on interfaces instead of abstract classes. This would make you're `Handler`:
``` c#
interface class IHandler<T> :  where T : Message 
// unsure if the generic type constraint is really needed?
{
    void Handle(T message);
}

// Register all implementations of IHandler<T> is simple:
container.Register(typeof(IHandler<>), assemblies);
// where assemblies is an IEnumerable<Assembly> which you want scanned for
// implementations
```

Second thing I notice is that what you're calling a `CompositeHandler` is IMO a proxy which dispatches the call to the correct implementation. So instead of implementing the business logic in two handlers you would handle the logic in 2 services: `PlaceOrderForEuropeService` and `PlaceDefaultOrderService`.

This approach would remove the need for the `CompositeHandler` completely. The new implementation would look something like:
``` c#
class PlaceOrderHandler : IHandler<PlaceOrder>
{
    private readonly PlaceOrderForEuropeService placeOrderForEuropeService;
    private readonly PlaceDefaultOrderService placeDefaultOrderService;
     
    public PlaceOrderHandler (
         PlaceOrderForEuropeService placeOrderForEuropeService,
         PlaceDefaultOrderService placeDefaultOrderService)
    {
        this.placeOrderForEuropeService = placeOrderForEuropeService;
        this.placeDefaultOrderService = placeDefaultOrderService;
    }

    public void Handle (PlaceOrder message){
        if(message.Country == "UK") 
            this.placeOrderForEuropeService.Handle(message);
        else
            this.placeDefaultOrderService.Handle(message);            
    }
}
```

The real solution here is probably to use of [Holistic Abstractions](http://qujck.com/holistic-abstractions-take-2/). But more about that later on.

The third thing I see in your design is that you have a specific `ValidationDecorator` for each `Message` in your system. This would mean you need to call `RegisterDecorator` for each and every `ValidationDecorator` in your system. This is a violation of [OCP](https://IEnumerable<ValidationResult> Validate(T instance);en.wikipedia.org/wiki/Open/closed_principle). Often a sign that you're missing an abstraction. The original design will probably also grow into an extra abstract class `CompositeValidationDecorator<T>` when the number of things to validate will grow and you're trying to prevent from violating [SRP](https://en.wikipedia.org/wiki/Single_responsibility_principle).
 
What you're missing is an `IValidator<T>` abstraction, which will solve both problems. Consider the following:
``` c#
interface IValidator<T> where T: Message
{
    IEnumerable<ValidationResult> Validate(T message);
}

class ValidateOrder : IValidator<PlaceOrder>
{
    public IEnumerable<ValidationResult> Validate(PlaceOrder message)
    {
         // do validation here
    }
}

class ValidationDecorator<T> : IHandler<T>  where T : Message {
    private readonly IHandler<T> decoratee;
    private readonly IValidator<T> validator;

    public ValidationDecorator(IHandler<T> decoratee, IValidator<T> validator)  {
        this.decoratee = decoratee;
        this.validator = validator;
    }

    public void Handle(T message) {
        this.Validate(message);
        this.decoratee.Handle(message);
    }

    private void Validate(T message) {
       var errors = this.validator.Validate(message);

        if (errors.Any())  throw new ValidationException("Validation failed");
    }
}
```

You can create as many IValidator implementations as you need, keeping them SRP, when adding a `CompositeValidator<T>` implementation:
``` c#
public class CompositeValidator<T> : IValidator<T> where T: Message {
    private readonly IEnumerable<IValidator<T>> validators;

    public CompositeValidator(IEnumerable<IValidator<T>> validators) {
        this.validators = validators;
    }

    public IEnumerable<ValidationResult> Validate(T message) {
        return
            from validator in this.validators
            from result in validator.Validate(instance)
            select result;
    }
}

// register as follows:
container.RegisterDecorator(typeof(IHandler<>), typeof(ValidationDecorator<>));
container.RegisterCollection(typeof(IValidator<>), assemblies);
container.RegisterSingleton(typeof(IValidator<>), typeof(CompositeValidator<>));
```

**Holistic abstractions**
As the linked blogpost explains in detail a handler should never call another handler. One of the reasons why you shouldn't do this is because a soon as you'll use a decorator around `IHander` all 'sub'handlers will be decorated also. This would typically lead to problems when you'll add decorators which controls lifestyles and transactions. 
The other problem holistic abstraction can solve is the design problem I introduced myself in the `PlaceOrderHandler`. By injecting the two specific services, the problem could arise when you would add a `PlaceOrderForAsiaService`, `PlaceOrderForAmericaService`. The amount of dependencies will grow with each continent added. If you would however add an abstraction `ISubHandler<T>` you could inject again an `IEnumerable<ISubHandler<PlaceOrder>>`. The registration will look the same as for `IValidator<>`.


Last: Instead of the if statement:
``` c#
 if(message.Country == "UK") 
            _handlers.OfTType<PlaceOrderEuropeHandler>.Single().Handle(message);
```
you could define the `ISubHandler<T>` interface as:
``` c#
interface ISubHandler<T> where T : Message
{
   bool CanExecute(T message);
   void Handle(T message);
}
```

This gives you the possibility to change the implementation of the `PlaceOrderHandler` to:
``` c#
 public void Handle (PlaceOrder message) {
        foreach(var handler in this.handlers) {
            if (handler.CanExecute(message) handler.Handle(message);
        }
    }
```

**NOTE:**
You say you want to use container.GetAllInstances(). I'm unsure why you want this but be aware that the `GetAllInstances<TService>()` method calls `GetInstance<IEnumerable<TService>>()` under the covers. Which means that you'll have to register TService using `RegisterCollection()` which is typically not what you will do for something as `IHandler`. So please elaborate on this part

**Comment by TheBigRic** [comment]
@ricardo100671 Did my answer help you in any way?

**Comment by ricardo100671** [comment]
Hi Ric

Thanks so much for taking the time to provide such a detailed answer. In fact I am still chewing the fat to try to make sense of it all in the context of how I want to use it. Yes you are correct that I intent it for CQRS with ES and the idea was to get all handlers created; by their decorator chair and subscribe each on their handled message type queue. Problem came though when introducing two handlers that could handle the same message I.e. PlaceOrderXHandlers. While I could use the SubHandler idea. What if I needed a common bit of logic to decided which handler to choose, like A/B testing where I might generate a random number and if over 30 choose handler1 otherwise handler2.

I will give more details once I can get my head around some other aspects.

Thank you
