### ISSUE TITLE
How to batch register with RegisterWebApiRequest

### ISSUE THREAD

**Issue by cgreen69** [simpleinjector/SimpleInjector#201]
Hi everyone, 

I'm working on a project which has a long list of calls to RegisterWebApiRequest. I'd like to batch these up in a similar fashion to that I've seen for Register i.e. reflect against the assembly and iteration through the list e.g. 

``` c#
foreach (var reg in registrations) {
    container.Register(reg.Service, reg.Implementation, Lifestyle.Transient);
}
```

However the signature of RegisterWebApiRequest is insisting on declaring the generic type and I'm struggling to write the code.

**Comment by dotnetjunkie** [comment]
The `RegisterWebApiRequest` method is obsolete since v3.0. Although it can still be used, the advice is to use the new `DefaultScopedLifestyle` feature as explained [here](https://simpleinjector.readthedocs.org/en/latest/lifetimes.html#scoped).

This basically means you set the WebApiRequestLifestyle once like this:

``` c#
var container = new Container();
container.Options.DefaultScopedLifestyle = new WebApiRequestLifestyle();
```

And after that you make the web request registrations ad follows:

``` c#
container.Register(reg.Service, reg.Implementation, Lifestyle.Scoped);
```

**Comment by cgreen69** [comment]
Perfect, thank you so much
