### ISSUE TITLE
Allow Register(Type, IEnumerable<Assembly>) to register non-generic types

### ISSUE THREAD

**Issue by stoune** [simpleinjector/SimpleInjector#206]
This is kind of feature request to allow automatic registration for non-generic types using either overload 
`Register(Type openGenericServiceType, IEnumerable<Assembly> assemblies)`
or other.

What was motivation was to restrict such registration only for generic types? 
Currently I forced to register types using two steps like this:

``` c#
var storageServiceTypes = container.GetTypesToRegister(typeof(IStorageService),
    AppDomain.CurrentDomain.GetAssemblies());
container.Register(typeof(IStorageService), storageServiceTypes.First());
```

These types have exactly one implementation.
What technical difficlties limited `Register(Type openGenericServiceType, IEnumerable<Assembly> assemblies)` only to generic types?

**Comment by stoune** [comment]
Currently I resolved this issue by implementing own extension method:
```
using SimpleInjector;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;

namespace MyNameSpace.DI
{
    public static class ContainerExtensions
    {
        /// <summary>
        /// Registers the non generic type within the container.
        /// </summary>
        /// <param name="container">The container.</param>
        /// <param name="nonGenericServiceType">Type of the non generic service.</param>
        /// <param name="assemblies">The list of assemblies.</param>
        public static void RegisterNonGeneric(this Container container, Type nonGenericServiceType, IEnumerable<Assembly> assemblies)
        {
            var storageServiceTypes = container.GetTypesToRegister(nonGenericServiceType, assemblies);
            // It will throw excception if more than one implementation found
            container.Register(nonGenericServiceType, storageServiceTypes.Single());
        }
    }
}

```
But I'm curious why original Register automatic registration does not supports non-generic implementations. 
What difficulties I have not foreseen?

**Comment by qujck** [comment]
You have 2 options:

- one implementation of `IStorageService` use `Register` 
- many implementations of `IStorageService` use `RegisterCollection`

if it was possible to do this (which it is not)

```csharp
container.Register<IStorageService, StorageService1>();
container.Register<IStorageService, StorageService2>();
```

then what exactly would you expect `container.GetInstance<IStorageService>()` to return?

**Comment by stoune** [comment]
My constraint is to register type from the assembly which is not referenced and not known at the compile time, but I'm always sure that there is always only one implementation of the needed interface(because I'm the implementor of these modules).
Due to some architecture limitations I can't reference assemblies with the implementation, but the assemblies are loaded into my application domain by external loader. 
If it is possible to do automatic registration for generic open types I'm interested on the rationale why it was not implemented for non-generic types.  
Currently I overcome this issue with the extension method that I have shown.

**Comment by TheBigRic** [comment]
> but I'm always sure that there is always only one implementation of the needed interface(because I'm the implementor of these modules

I understand that you can be sure, but the thing is, we can't be sure this will always be the case. Changes are there won't be a single implementation, which will obviously result in an exception. 

It is implemented for generic types because it is common practice to have one single open generic servicetype with many closed generic implementations of this servicetype. 
Consider this interface

``` c#
public interface ICommandHandler<TCommand>
{
    void Handle(TCommand command);
}
```

Which could have these implementations (any many more):
``` c#
public class MoveCustomerCommandHandler : ICommandHandler<MoveCustomerCommand> { ... }
public class SendFlowersCommandHandler : ICommandHandler<SendFlowersCommand> { ... }
etc..
```

Batch registering these makes sense because there could be hundreds.

Non generic types however always have one single registration, except when you want to inject an IEnumerable<TService>. 

The use case you present is pretty rare. Most of the time the implementation is in a referenced library and you just call `container.Register<TService,TImplementation>()`, so it doesn't make sense to supply our users with such an overload.

**Comment by dotnetjunkie** [comment]
Your case is actually quite rare: it's quite unusual to have exactly one implementation in an assembly that can't be referenced from the [Compostion Root](http://blog.ploeh.dk/2011/07/28/CompositionRoot/) at compile-time. This is because in most cases, it [doesn't make sense](https//stackoverflow.com/questions/9501604/ioc-di-why-do-i-have-to-reference-all-layers-assemblies-in-entry-application) to not be able to have compile-time references to those assemblies from within your Composition Root.

In other words, your case is so specific, that we dind't feel the need to create special support for this. Especially since the solution is two lines of code.

I do think however that support can be added by removing the limitation from the current `Register(Type, Assemblies[])` method (although I'm not saying that we will). In case the `Register` method finds multiple implementations, a descriptive exception can be thrown, explaining the error and stating the names of the types that are found. We would only have decide what to do with the special '0' case, i.e. in case no implementation was found.

Again, I'm not sure we will add support in the near future, but I would like to keep this issue open for now.

**Comment by dotnetjunkie** [comment]
I decided not to add support for such feature in the future because of 3 reasons:

 1. This feature is a really uncommon scenario.
 2. It can  be added by a few lines of custom code as shown in [this comment](https://github.com/simpleinjector/SimpleInjector/issues/206#issuecomment-200955252).
 3. The behavior of the 0-case (where there is no implementation) might confuse users, no matter which solution we pick (options are: ignoring and throwing an exception).
