### ISSUE TITLE
Register singleton instances into collection

### ISSUE THREAD

**Issue by gregbty** [simpleinjector/SimpleInjector#208]
I am having the same outcome as https://github.com/simpleinjector/SimpleInjector/issues/79 but I am not sure if it is due to my lack of understanding of the registration of collections or if it is indeed a bug.

```csharp			
var container = new Container();
container.RegisterSingleton<IFoo, FooBar>();

container.RegisterCollection<IBar>(
  typeof (IBar).Assembly
  .GetTypes()
  .Where(t => typeof (IBar).IsAssignableFrom(t) && t.IsClass && !t.IsAbstract)
  .Select(t => Lifestyle.Singleton.CreateRegistration(t, container)));

container.Verify(); //Fails with TornLifestyle
```

**Comment by TheBigRic** [comment]
What the torn lifestyle means is that a (in this case) singleton component has multiple registrations, which would effectively lead to having not one but 2 singletons.

The following code illustrates this (notice that this code will throw a 'TornLifeStyleWarning' when calling 'Verify()'):
``` c#
public interface IFoo {}
public interface IBar {}
public class FooBar : IFoo, IBar {}

container.RegisterSingleton<IFoo, FooBar>();
container.RegisterSingleton<IBar, FooBar>();

var foorBar = container.GetInstance<IFoo>();
// this will result in another singleton instance!
var barFoo = container.GetInstance<IBar>();
```

As the [documentation describes](http://simpleinjector.readthedocs.org/en/latest/tornlifestyle.html) the way to resolve this, is instead of letting the container make a `Registration` by calling `container.Register<,>()` you should make the `Registration` object yourself and add this to the list of registrations in the container.

In your case this is somewhat harder to do, but not impossible:

``` c#
var container = new Container();
// NOTE: I use the convenient helper functions Simple Injector supplies to find the types needed
var barTypes = container.GetTypesToRegister(typeof(IBar), new[] { typeof(IBar).Assembly });

var barRegistrations = (
    from type in barTypes
    select Lifestyle.Singleton.CreateRegistration(type, container)
    ).ToArray(); // This call is needed to prevent double enumeration!!

container.RegisterCollection<IBar>(barRegistrations);

// Now find the registration for FooBar to register this also for the service IFoo
var fooBarRegistration = barRegistrations.Single(r => r.ImplementationType == typeof(FooBar));
container.AddRegistration(typeof(IFoo), fooBarRegistration);

container.Verify();
```

That should do it!

**Comment by gregbty** [comment]
I was able to create an extension method for what I needed based on what you mentioned above which resolved the issue. Thanks for the detailed explanation!
