### ISSUE TITLE
Add TypesToRegisterOptions overload to RegisterCollection(Type, params Assembly[])

### ISSUE THREAD

**Issue by alexfoxgill** [simpleinjector/SimpleInjector#214]
It would be handy to include generic types in [this RegisterCollection overload](https://github.com/simpleinjector/SimpleInjector/blob/ec8890ace798e83f43f1c4ca5171af41602e3114/src/SimpleInjector/Container.Registration.Batch.cs#L202).

For example, I have some hardcoded generic implementations here:

```CSharp
container.AppendToCollection(typeof(IAttendeeActionOutcome<>), typeof(ConsultantDeclineSendEmailToClientActionOutcome<>));
container.AppendToCollection(typeof(IAttendeeActionOutcome<>), typeof(BookingSendConfirmationEmailActionOutcome<>));
container.AppendToCollection(typeof(IAttendeeActionOutcome<>), typeof(DeallocateUnitsActionOutcome<>));
container.AppendToCollection(typeof(IAttendeeActionOutcome<>), typeof(AllocateUnitsActionOutcome<>));
container.RegisterCollection(typeof(IAttendeeActionOutcome<>), CoreAssembly);
```

I'd prefer a more maintainable solution, so I wrote some reflection code to do this instead:

```CSharp
var ts = typeof(IAttendeeActionOutcome<>).Assembly.GetExportedTypes()
    .Where(t => t.IsAssignableToGenericType(typeof(IAttendeeActionOutcome<>)) && !t.IsAbstract);

foreach (var t in ts)
    container.AppendToCollection(typeof(IAttendeeActionOutcome<>), t);
```

However, the ideal result would be an overload making use of `TypesToRegisterOptions`:

```CSharp
container.RegisterCollection(typeof(IAttendeeActionOutcome<>), 
    new TypesToRegisterOptions() { IncludeGenericTypeDefinitions = true }, 
    CoreAssembly);
```

**Comment by dotnetjunkie** [comment]
Your suggestion would be a shortcut for the following construct that you can already use:

``` c#
container.RegisterCollection(typeof(IAttendeeActionOutcome<>), 
    container.GetTypesToRegister(typeof(IAttendeeActionOutcome<>), CoreAssembly, 
        new TypesToRegisterOptions { IncludeGenericTypeDefinitions = true }));
```

If this is a construct you need more often, you can create an extension method for this as follows:

``` c#
public static void RegisterCollection(this Container container, Type serviceType,
    IEnumerable<Assembly> assemblies, TypesToRegisterOptions options) {
    container.RegisterCollection(serviceType,
        container.GetTypesToRegister(serviceType, assemblies, options));
}
```

There are two reasons for me to hesitate adding such overload to the core library. First of all, this is a feature that not many people need, while the work-around consists of one extra line of code. Second, if we would add this feature, it would require us to define a new parameter object type such as: `CollectionTypesToRegisterOptions`, because the `TypesToRegisterOptions.IncludeComposites` property makes little sense when registering collections; you typically want it to be false. Not adding that type would make the API less intuitive, while including that type would pollute the API as well.

**Comment by alexfoxgill** [comment]
Ok, that's fair enough!
