### ISSUE TITLE
How to unit test simple injector lifestyle scope

### ISSUE THREAD

**Issue by umarmohammed** [simpleinjector/SimpleInjector#223]
Hi, I'm currently using simple inject in a web api project. I see that the code included when installing the nuget package includes the following:

``` c#
container.Options.DefaultScopedLifestyle = new WebApiRequestLifestyle();
```

So that when I register a dbcontext like so:

``` c#
container.Register<ApplicationDbContext>(Lifestyle.Scoped);
```

it gets disposed when then http request ends.

I'm trying to write a unit test to confirm that the dispose method of a dbcontext is indeed called when the request ends however i'm a bit unsure how to go about doing so. The reason I want to do this is because I've had issues in the past with a different IoC container which wasn't always managing the lifecycle of dependencies correctly. I would appreciate any guidance on how I can go about doing this. Thanks.

**Comment by dotnetjunkie** [comment]
It's actually quite hard to verify this behavior, since this requires your unit/integration test to spin up a Web API service and trigger a call that ensure the creation of a `DbContext`. After that the test should probably communicate again with the service to check whether that `DbContext` is disposed.

Creating such test is cumbersome and probably fragile and IMO a complete waste of your time. It's not your job to test the correctness of Simple Injector; it is our job and we have a large set of unit tests to ensure it behaves as expected. It is usually advised against writing automated tests that verify the correctness of the frameworks and libraries your application uses. This would be a massive undertaking and one would hope that the library builders did their job by writing automated tests.

It is your job however to verify that your application in total behaves according to its specifications. You are already using automated testing for this, which is great. You can use integration or acceptance testing for this. Such test will test the application functionally and can cover calls into the used libraries as well. So instead of having a test that is concerned about the DbContext being disposed, try define tests that verify whether the application behaves functionally correctly, and performs within the defined boundaries. You can think of tests that verify if a certain load can be achieved. If not disposing a DbContext will cause performance or availability problems, such load test will catch this, and much more.

You can still of course check manually during debugging whether things get disposed to get a sense of whether the library does as it says it does, but that doesn't mean that this is something you need to automate. But I can guarantee you that the `WebApiRequestLifestyle` keeps its promise: it will dispose the scoped instances that it has created during a request.

**Comment by umarmohammed** [comment]
Thank you for the reply, some good pointers there on how best to proceed.
