### ISSUE TITLE
Simple Injector + Scoped + Multithread

### ISSUE THREAD

**Issue by bellinat** [simpleinjector/SimpleInjector#224]
Hello,

First, thank you for those who help me.

I have a app that already run succesful for ASP.NET Web and Api.

Now I have to use the existing architecture for Windows Service Application. So, I created new SimpleInjectorInitialize for this specified project (Windows Service) as Lifestyle Scoped.

But, when I execute the project, throw exception above:

Service Error: SimpleInjector.ActivationException: The IConfigurationAppService is registered as 'Lifetime Scope' lifestyle, but the instance is requested outside the context of a Lifetime Scope.

	at SimpleInjector.Scope.GetScopelessInstance[TService,TImplementation](ScopedRegistration`2 registration)
	at SimpleInjector.Scope.GetInstance[TService,TImplementation](ScopedRegistration`2 registration, Scope scope)
	at SimpleInjector.Advanced.Internal.LazyScopedRegistration`2.GetInstance(Scope scope)
	at lambda_method(Closure )
	at SimpleInjector.InstanceProducer.GetInstance()
	at SimpleInjector.Container.GetInstanceFromProducer(InstanceProducer instanceProducer, Type serviceType)
	at SimpleInjector.Container.GetInstanceForRootType[TService]()
	at SimpleInjector.Container.GetInstance[TService]()
	at UP.EmailService.Services.EmailProcessor.ServiceManagement.StartServiceManagement() na c:\ProjetosTFS2013\Serviço Email\ServicoEmail\app\UP.EmailService.Services.EmailPThe thread 0x3b5c has exited with code 259 (0x103).
	The program '[10448] UP.EmailService.Services.EmailProcessor.vshost.exe' has exited with code 0 (0x0).
	The program '[10448] UP.EmailService.Services.EmailProcessor.vshost.exe: Program Trace' has exited with code 0 (0x0).

If you have a suggestion to help me, thank you for your attention.

**Comment by dotnetjunkie** [comment]
When working with Web API, MVC or Web Forms, the Simple Injector integration packages will ensure that their corresponding scoped lifestyle is automatically started and stopped at the boundaries of a web request.

When working with a Windows Service however, there is no such thing as a web request and you will yourself have to define the boundaries of such 'request' by making sure your code executes withing an explicitly started scope.

The documentation [shows](https://simpleinjector.readthedocs.org/en/latest/lifetimes.html#per-lifetime-scope) how to start a LifetimeScope:

``` c#
using (container.BeginLifetimeScope()) {
    var myService = container.GetInstance<MyService>();
    myService.DoMyStuff();
}
```

**Comment by bellinat** [comment]
Thank you for your attention!!!

The principal problem (_Service Error: SimpleInjector.ActivationException: The IConfigurationAppService is registered as 'Lifetime Scope' lifestyle, but the instance is requested outside the context of a Lifetime Scope._) it's ok.

But now a new problem is trown and I'm study this:

_Service Error: System.InvalidOperationException: The operation cannot be completed because the DbContext has been disposed.
   em System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   em System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   em System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   em System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext()
   em System.Data.Entity.Infrastructure.DbQuery`1.System.Linq.IQueryable.get_Provider()
   em System.Linq.Queryable.Where[TSource](IQueryable`1 source, Expression`1 predicate)
   em UP.EmailService.Infrastructure.Data.Repository.EntityFramework.Common.Repository`2.Find(Expression`1 predicate, Boolean readonly) na c:\ProjetosTFS2013\Serviço Email\ServicoEmail\app\UP.EmailService.Infrastructure.Data.Repository\EntityFramework\Common\Repository.cs:linha 123
   em UP.EmailService.Infrastructure.Data.Repository.EntityFramework.ConfigurationRepository.GetAllRecordsThatHaveQueuedMessage(Boolean readonly) na c:\ProjetosTFS2013\Serviço Email\ServicoEmail\app\UP.EmailService.Infrastructure.Data.Repository\EntityFramework\ConfigurationRepository.cs:linha 14
   em UP.EmailService.Domain.Services.ConfigurationService.GetAllRecordsThatHaveQueuedMessage() na c:\ProjetosTFS2013\Serviço Email\ServicoEmail\app\UP.EmailService.Domain\Services\ConfigurationService.cs:linha 95
   em UP.EmailService.Application.ConfigurationAppService.GetAllRecordsThatHaveQueuedMessage() na c:\ProjetosTFS2013\Serviço Email\ServicoEmail\app\UP.EmailService.Application\ConfigurationAppService.cs:linha 121
   em UP.EmailService.Services.EmailProcessor.ServiceManagement.CheckForMessageDeliveryRun() na c:\ProjetosTFS2013\Serviço Email\ServicoEmail\app\UP.EmailService.Services.EmailProcessor\ServiceManagement.cs:linha 361
   em UP.EmailService.Services.EmailProcessor.ServiceManagement.StartServiceManagement() na c:\ProjetosTFS2013\Serviço Email\ServicoEmail\app\UP.EmailService.Services.EmailThe thread 0x29dc has exited with code 259 (0x103)._

**Comment by bellinat** [comment]
Also in time as to control connection to a control using Windows I as follows:

`public class ContextManager<TContext> : IContextManager<TContext>
        where TContext : IDbContext, new()
    {
        private readonly string _contextKey;

        public ContextManager()
        {
            _contextKey = "_contextKey." + typeof(TContext).Name + ((HttpContext.Current == null) ? "." + Thread.CurrentThread.Name : "");
        }

        public IDbContext GetContext()
        {
            if (HttpContext.Current != null)
            {
                if (HttpContext.Current.Items[_contextKey] == null)
                    HttpContext.Current.Items[_contextKey] = new TContext();
                return HttpContext.Current.Items[_contextKey] as IDbContext;
            }

            if (CacheWrapper.Get(_contextKey) == null)
                CacheWrapper.Insert(_contextKey, new TContext(), CacheItemPriority.Default,
                    CacheWrapper.NoAbsoluteExpiration, TimeSpan.FromMinutes(4));

            return CacheWrapper.Get(_contextKey) as IDbContext;
        }

        public void Finish()
        {
            if (HttpContext.Current != null)
            {
                if (HttpContext.Current.Items[_contextKey] == null) return;
                var dbContext = HttpContext.Current.Items[_contextKey] as IDbContext;
                if (dbContext != null)
                    dbContext.Dispose();
            }

            if (CacheWrapper.Get(_contextKey) == null) return;
            var context = CacheWrapper.Get(_contextKey) as IDbContext;
            if (context != null)
                context.Dispose();
        }
    }

public static class CacheWrapper
    {
        private static readonly MemoryCache MemoryCache = MemoryCache.Default;

        public static ObjectCache Cache
        {
            get { return MemoryCache; }
        }

        public static DateTimeOffset NoAbsoluteExpiration
        {
            get { return DateTimeOffset.MaxValue; }
        }

        public static TimeSpan NoSlidingExpiration
        {
            get { return TimeSpan.MaxValue; }
        }

        public static void Insert(
            String cacheKey,
            Object cacheValue,
            CacheItemPriority cacheItemPriority,
            DateTimeOffset absoluteExpiration,
            TimeSpan slidingExpiration)
        {
            if (cacheValue == null) return;
            Cache.Set(cacheKey, cacheValue, new CacheItemPolicy
            {
                Priority = cacheItemPriority,
                AbsoluteExpiration = absoluteExpiration,
                SlidingExpiration = slidingExpiration
            });
        }

        public static Object Get(String cacheKey)
        {
            return Cache[cacheKey];
        }

        public static void Remove(String cacheKey)
        {
            if (Cache.Contains(cacheKey))
                Cache.Remove(cacheKey);
        }
    }`

**Comment by bellinat** [comment]
``

**Comment by dotnetjunkie** [comment]
The problem obviously is that somewhere you let the `DbContext` be disposed, while using it later on. Why this happens however, isn't completely clear to me. But instead of implementing your own caching, you should move that responsibility to Simple Injector, since that's what a `Scope` is all about. This also simplifies your implementation and removes the dependency on `HttpContext` that you now have in your Windows Service.

For instance, you can reduce the `ContextManager<T>` implementation to the following:

``` c#
public class ContextManager<TContext> : IContextManager<TContext> where TContext : IDbContext
{
	private readonly Func<TContext> _contextProvider;

	public ContextManager(Func<TContext> contextProvider)
	{
		_contextProvider = contextProvider;
	}

	public IDbContext GetContext()
	{
		return _contextProvider();
	}

	public void Finish()
	{
		// Do not!! dispose the DbContext here. That's Simple Injector'sbyte
		// responsibility. In fact, you should remove the Finish method completely.
	}
}
```

``` c#
var container = new Container();
container.Options.DefaultScopedLifestyle = new LifetimeScopeLifestyle();

var dbContextProvider = Lifestyle.Scoped.CreateRegistration<MyAppDbContext>(
	() => new MyAppDbContext("constr"), container);

container.RegisterSingleton<IContextManager<TContext>>(
	new ContextManager<MyAppDbContext>(dbContextProvider.GetInstance));

using (container.BeginLifetimeScope()) {
    var myService = container.GetInstance<MyService>();
    myService.DoMyStuff();
}
```

Here we register the `ContextManager<MyAppDbContext>` as a singleton, and it is created with a delegate that calls into the `GetInstance()` method of the `Registration` object for the `MyAppDbContext`. This will ensure that when `IContextManager.GetContext()` gets called for the first time within an active lifetime scope, a new `MyAppDbContext` is created. Every next call to `GetContext()` the same `MyAppDbContext` is created. When the `using` block ends, the C# compiler ensures that `Scope.Dispose()` is called and this will ensure that the created `MyAppDbContext` gets disposed as well.

I hope this helps.

**Comment by bellinat** [comment]
Hello,

First of all, thank you.

I need keep the code of ContextManager with the control of HttpContext because this is used for other projects such as Web and Api Projects and these already run success in production and not use using blocks.

Also important to say that I constructed the solution based in DDD, so basic I have the abose structure for any CRUD action:

**Presentation > Web**
`_consumerAppService.Create(consumer);`

**Application > ConsumerAppService**
`BeginTransaction();
_service.Register(obj);
Commit();`

**Service Domain > ConsumerService**
`_repository.Add(entity)`

I did the implementation of IDisposabled in my repository, so this explain the the 'why or where I use disposed'.

`public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        protected virtual void Dispose(bool disposing)
        {
            if (!disposing) return;

            if (Context == null) return;
            Context.Dispose();
        }`

When was necessary to created a Windows Service Project so I created the new control of Context with Wrapper that I showed previous.

Now, with the Windows Service Project when I use using blocks, as you say I can't used implementation of IDisposable, because move that responsibility to Simple Injector, however as I have implemented control for Web and API and can not take, that's why I kept the way you can see.

I hope is clear to you.

**Comment by dotnetjunkie** [comment]
> I need keep the code of ContextManager with the control of HttpContext because this is used for other projects such as Web and Api Projects

The beauty of scopes in Simple Injector is that you can simply select the appropriate scoped lifestyle for your project type, and the rest of the code can be reused. In an ASP.NET or Web API web application, the Scope will be automatically managed for you in the background. You don't have to use any `using` blocks; the scoped components will be disposed when the web request ends.

This means that you select the appropriate `Container.Options.DefaultScopedLifestyle` for the project type, and register the `DbContext` as `Lifestyle.Scoped`. For your Windows service you will have to wrap the `GetInstance` call into a `using` block, but the rest of your application code will stay the same. This considerably simplifies your application code.

> Application > ConsumerAppService
> BeginTransaction(); _service.Register(obj); Commit();

Your transaction handling is a cross-cutting concern and you are probably duplicating this logic throughout your business layer. In the future, you might want to consider refactoring to message based pattern like the [command/handler pattern](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=91), because those patterns simplifies the addition of cross-cutting concerns such as transaction handling, logging, profiling, audit trailing, authorization and caching. You will be able to plugin cross-cutting concerns without having to change any of your existing code.

> I did the implementation of IDisposabled in my repository,

A class should only dispose instances that it has the ownership over. In the case of your repository, an existing DbContext is injected into it by someone else. This means this 'someone else' is responsible over creating it; not the repository. It's can't be any other way else, because your repository has no way of knowing whether the DbContext is reused or not. And in your case, the DbContext is actually reused. This means that almost none of your application components should actually implement IDisposable, since those few classes that really require disposal for themselves, are managed in your Composition Root (in your case most likely by Simple Injector). This makes your application code considerably simpler.

**Comment by bellinat** [comment]
Wow... it's great and thank you.

At this point I can't change much, even a small change. Therefore, in a next project I believe in studying more about what spoke and apply as far as possible.
