### ISSUE TITLE
Container Verify() is executing func delegates

### ISSUE THREAD

**Issue by DaEkstrim** [simpleinjector/SimpleInjector#227]
We have a particular scenario where an implementation of a service is being provided through a static method which is discovered through reflection (using method decorator attribute) and registered with the container. However when we call the container Verify(), the container is executing the the delegate. Is there a way where we can exclude such registrations from verification or a way to having the Verify() skip over registration with delegates.
Simple Inject Version: 3.1.3.0
Framework: 4.5.1

**Comment by dotnetjunkie** [comment]
Yes, there are ways to do this. Can you provide me with a bit more context for your problem? Can you show some code that demonstrates this? How do your registrations look like?

**Comment by DaEkstrim** [comment]
Absolutely.

So I have this method which I have decorated with the IoCFactoryFor(Type type) attribute

```
[IoCFactoryFor(typeof(IPaymentMethodProvider))]
public static IPaymentMethodProvider Create()
{
    return GetInstance();
}
```

I then fetch all these static methods through a LINQ expression which groups factories of a particular service together:

```
var injectableFactoriesGroups =
                assemblyList.SelectMany(a => a.GetTypes().SelectMany(t => t.GetMethods())
                            .Where(m => Attribute.IsDefined(m, typeof(IoCFactoryForAttribute))))
                            .Select(m => new
                            {
                                service = m.GetCustomAttribute<IoCFactoryForAttribute>().ServiceType,
                                factory = m
                            })
                            .GroupBy(m => m.service,
                                     m => m.factory,
                                     (service, factories) => new { service = service, factories = factories.ToList() })
                            .ToList();
```

I then iterate through each group, and create a collection of registrations for each service and register the collection into the container

```
foreach (var factoryGroup in injectableFactoriesGroups)
{
    var registrations = factoryGroup.factories.Select(f =>
            Lifestyle.Transient.CreateRegistration(factoryGroup.service, () => IoCFactoryInvoker.InvokeMethod(f), NormalContainer));
     NormalContainer.RegisterCollection(factoryGroup.service, registrations);
}
```

The IoCFactoryInvoker simply invokes the methodInfo passed (since this is a static method it roughly translates to m.Invoke(null, null)).

Lastly, I call the Verify method of the container, at which point the static method above is executed causing logic which is not yet ready for execution (due to database connections initialization happening after the IoC is initialized)
`NormalContainer.Verify();`


My request is that the Verify skips over and does not verify these delegate registrations.

**Comment by dotnetjunkie** [comment]
> due to database connections initialization

This basically means that you can't [compose object graphs with confidence](http://blog.ploeh.dk/2011/03/04/Composeobjectgraphswithconfidence/) which is really something you should strive for. This is something you might want to look at in the future.

Simple Injector does not contain a feature to explicitly state that Verify() should ignore some registration. The reason it doesn't exist is because it is quite difficult to skip a registration, since Simple Injector tests its configuration by creating instances for all registrations. If the registration is a dependency of another type, the whole graph should be created.

So the typical way to skip a registration is to ensure that the `InstanceProducer` for the registration is created after `Verify()` has been called. This is usually trivial to do, but in your case it's a bit more complex, since you register collections of types where the service types are unknown at compile time.

Here's how to do it:

``` c#
public static void RegisterFactoryCollection(Type serviceType, Container container, List<MethodInfo> methods)
{
	Expression<Action> x = () => RegisterFactoryCollection<object>(null, null);
	((MethodCallExpression)x.Body).Method.GetGenericMethodDefinition().MakeGenericMethod(serviceType)
		.Invoke(null, new object[] { container, methods });
}

public static void RegisterFactoryCollection<TService>(Container container, List<MethodInfo> methods) 
	where TService : class
{
	container.RegisterSingleton<IEnumerable<TService>>(
		methods
		.Select(f => new Lazy<InstanceProducer>(() => CreateFactoryProducer<TService>(container, f)))
		.ToArray()
		.Select(lazyProducer => lazyProducer.Value.GetInstance()));
}

static InstanceProducer<T> CreateFactoryProducer<T>(Container c, MethodInfo f) where T : class =>
	new InstanceProducer<T>(CreateFactoryRegistration<T>(c, f));

static Registration CreateFactoryRegistration<T>(Container c, MethodInfo f) where T : class =>
	Lifestyle.Transient.CreateRegistration(() => (T)IoCFactoryInvoker.InvokeMethod(f), c);
```

With this code, you can change your loop to:

``` c#
foreach (var factoryGroup in injectableFactoriesGroups)
{
	RegisterFactoryCollection(factoryGroup.service, NormalContainer, factoryGroup.factories);	
}
```

There is some nasty reflection going on here, but the idea is actually simple and it consists of two parts:

 - We use `Register<IEnumerable<T>>` instead of `RegisterCollection<T>` because this prevents Simple Injector from verifying the registered collection.
 - We create an array of `Lazy<InstanceProducer>` instances and wrap that in a `select` query. This ensures that the `InstanceProducer` instances are created when the enumerable is iterated for the first time, and they are created exactly once.

**Comment by DaEkstrim** [comment]
I agree with your object graph composition guarantee statement; this is a mature project and such changes will take a considerable amount of time to be implemented; these are however scheduled to be tackled later on this year.

As for your solution: it works. The only change I made is specify the generic parameter for the `Lazy<InstanceProducer>`:
`
.Select(f => new Lazy<InstanceProducer**<TService>**>(() => CreateFactoryProducer<TService>(container, f)))
`

Thanks for the help and keep up the good work!

**Comment by dotnetjunkie** [comment]
I'm sorry, I should have tested that code. I'm glad you got it working.
