### ISSUE TITLE
How to analyze initialization performance problems

### ISSUE THREAD

**Issue by andreagiraldin** [simpleinjector/SimpleInjector#238]
I have a strange behavior with Container initialization.
The first call to **GetInstance<TService>()** took approximately 20 seconds to execute.
The biggest problem is that this behavior occurs only in some PCs where I run my program both in DEBUG and RELEASE mode. In other PCs everything seems ok.

I use nuget package of SimpleInjector in my project.
I try many versions of library but all have the same problem.
I try also to use SimpleInjector source code but I stop my investigation in method **CreateInstanceWithNullCheck** of **SingletonLifestyleRegistrationBase** class where the Expression is built and compiled.
The execution of compiled expression requires 20 seconds and I'm not able to debug it.

Maybe the resolution of dependencies runs in a recursive call.
What else can I do to restrict the problem?

Thanks in advance!

**Comment by dotnetjunkie** [comment]
There could be many reasons why this could happen. Two things that come to mind is that some of your classes have complex or heavy initialization, or you are (accidentally) creating `InstanceProducer` instances during verification. 

A way to measure the time it takes to build an object graph is by measure a call to `InstanceProducer.BuildExpression()` using `Stopwatch`. This isn't 100% accurate and not a 100% solution, but it might give you a clue. Example:

``` c#
var watch = new Stopwatch();

foreach (var reg in container.GetCurrentRegistrations()) {
    watch.Restart();

    reg.BuildExpression();

    long ms = watch.ElapsedMilliseconds;

    if (ms > 3) Console.WriteLine("{0} ms. {1}", ms, reg.Registration.ImplementationType);
}
```

Do note that [injection constructors should be fast and simple](http://blog.ploeh.dk/2011/03/03/InjectionConstructorsshouldbesimple/). So you shouldn't do any have initialization, such as do blocking calls, query the database, or even anything that can fail (such as accessing the file system). You want to be able to [build object graphs with confidence](http://blog.ploeh.dk/2011/03/04/Composeobjectgraphswithconfidence/).

Another possibility is that somewhere in the background you are creating new `InstanceProducer` instances during the verification process. `InstanceProducer`s that are created during this process are verified as last step, but if this again triggers verification, this can cause a severe delay. Eventually Simple Injector breaks out, but this can cause a delay. Since however you are experiencing this on some PCs, this won't be a very likely cause.

**Comment by andreagiraldin** [comment]
After some days the problem is gone without code changes.
I suppose it was caused by my company antivirus (Trend Micro OfficeScan).
Perhaps when the expressions are compiled the antivirus detect it and it do something that slows the execution.

**Comment by dotnetjunkie** [comment]
Anti Virus tools are regularly causing problems during the development process and when they do, the problem is often difficult to pinpoint.
