### ISSUE TITLE
No registration for type IEnumerable<___View> could be found.

### ISSUE THREAD

**Issue by acedened** [simpleinjector/SimpleInjector#251]
I'm moving from Ninject to Simple Injector in my UWP project that uses Caliburn Micro. And I have encountered a problem with `Container.GetAllInstances(Type)` method.
Here is the code of the App class
```
sealed partial class App {
        
    private Container container;

    public App() {
        InitializeComponent();
        this.container = new Container();
        // Register services
    }

    protected override void OnLaunched(LaunchActivatedEventArgs args) {
        DisplayRootViewFor<IShell>();
    }
      
    protected override object GetInstance(Type service, string key) {
        return this.container.GetInstance(service);
    }

    protected override IEnumerable<object> GetAllInstances(Type service) {
        return this.container.GetAllInstances(service);
    }

    protected override void BuildUp(object instance) {
        var registration = this.container.GetRegistration(instance.GetType(), true);
        registration.Registration.InitializeInstance(instance);
    }
 }
```

When Caliburn tries to create a view, it calls `GetAllInstances` method, and Simple Injector fails to resolve `IEnumerable<SomeView>`.

I also tried the following code, but it fails with System.EntryPointNotFoundException
```
protected override IEnumerable<object> GetAllInstances(Type service)
{
    IServiceProvider provider = this.container;
    Type collectionType = typeof(IEnumerable<>).MakeGenericType(service);
    var services = (IEnumerable<object>)provider.GetService(collectionType);
    return services ?? Enumerable.Empty<object>();
}
```

How to fix that?

**Comment by dotnetjunkie** [comment]
Can you post the stack trace for that exception?

**Comment by acedened** [comment]
@dotnetjunkie Yes, here it is
``` 
   at SimpleInjector.Container.ThrowMissingInstanceProducerException(Type serviceType)
   at SimpleInjector.Container.GetInstanceForRootType(Type serviceType)
   at SimpleInjector.Container.GetInstance(Type serviceType)
   at SimpleInjector.Container.GetAllInstances(Type serviceType)
   at App.GetAllInstances(Type service)
   at Caliburn.Micro.ViewLocator.<>c.<.cctor>b__10_0(Type viewType)
   at Caliburn.Micro.CaliburnApplication.DisplayRootViewFor(Type viewModelType)
   at App.OnLaunched(LaunchActivatedEventArgs args)
```

**Comment by dotnetjunkie** [comment]
I'm sorry, can you post all relevant details. Exception message, type and stack trace of the exception and all its inner exceptions?

**Comment by acedened** [comment]
@dotnetjunkie
Message: No registration for type IEnumerable<ShellView> could be found.
Type: SimpleInjector.ActivationException
Stack trace:
```
   at SimpleInjector.Container.ThrowMissingInstanceProducerException(Type serviceType)
   at SimpleInjector.Container.GetInstanceForRootType(Type serviceType)
   at SimpleInjector.Container.GetInstance(Type serviceType)
   at SimpleInjector.Container.GetAllInstances(Type serviceType)
   at TheChan.App.GetAllInstances(Type service)
   at Caliburn.Micro.ViewLocator.<>c.<.cctor>b__10_0(Type viewType)
   at Caliburn.Micro.CaliburnApplication.DisplayRootViewFor(Type viewModelType)
   at TheChan.App.OnLaunched(LaunchActivatedEventArgs args)
```

There is no inner exception. Requested service is ShellView

**Comment by TheBigRic** [comment]
The exception and stacktrace are from the first attempt:

``` c#
protected override IEnumerable<object> GetAllInstances(Type service) {
        return this.container.GetAllInstances(service);
    }
```

> I also tried the following code, but it fails with System.EntryPointNotFoundException
protected override IEnumerable<object> GetAllInstances(Type service)
{
    IServiceProvider provider = this.container;
    Type collectionType = typeof(IEnumerable<>).MakeGenericType(service);
    var services = (IEnumerable<object>)provider.GetService(collectionType);
    return services ?? Enumerable.Empty<object>();
}

This is indeed the correct fix, for 'normal' .Net. But because UWP uses .Net Core. `.MakeGenericType()` isn't available I think in .Net Core. This is probably where EntryPointNotFoundException is coming from. I'm not sure how to resolve this. 

On the other hand, you probably never return an enumerable of views or viewmodels. You most likely always have precisely one. I can't think of a reason where caliburn would need to call back in the container to get collection of items.

So a workaround could be to always return 'Enumerable.Empty<object>()' until that point in time you find that there is actually something needed that is a collection.

**Comment by acedened** [comment]
@TheBigRic Caliburn can't create views without parameterless constructor if Enumerable.Empty is returned

**Comment by TheBigRic** [comment]
Sorry, I think you need to explain. In my experience Caliburn will always call `GetInstance` and `GetAllInstances`. So if there is one view, GetInstance will provide the view to Caliburn which would be build by Simple Injector. And since GetAllInstances will return `Empty`, Caliburn should be satisfied with the single instance.

Can you show a sample which proves this?

**Comment by acedened** [comment]
@TheBigRic Here is the sample project
[IssueProject.zip](https://github.com/simpleinjector/SimpleInjector/files/312802/IssueProject.zip)

**Comment by acedened** [comment]
@TheBigRic I also viewed the sources of Caliburn.Micro and found out that it calls GetAllInstances https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Caliburn.Micro.Platform/ViewLocator.cs#L263

**Comment by acedened** [comment]
Oh, looks like I found a solution:
```
protected override IEnumerable<object> GetAllInstances(Type service) {
    return new[] { GetInstance(service, null) };
}
```

**Comment by TheBigRic** [comment]
Sorry for my late response, had a deadline to catch the past few days.

> Oh, looks like I found a solution

That seems like a very nice workaround. 

I'm really surprised how C.M. has implemented this. A design flaw if you ask me. Why call `GetAllInstances` and then say `.FirstOrDefault()`? This is so very unintuitive that I always thought it worked like I explained in my last post in this thread. So a very good thing, you did look into this and created a pull request.

**Comment by laranjee** [comment]
I'm just guessing, but probably it was implemented that way because when you register the view in the container it will be one-to-one and calling GetAllInstances is always safe (empty collection in the worst case scenario). On the other hand, calling GetInstance have always thrown an exception if the service is not found, at least from what I can remember.
