### ISSUE TITLE
Allow decorators to be registered conditionally

### ISSUE THREAD

**Issue by Eldar1205** [simpleinjector/SimpleInjector#255]
I have a scenario where I have an object graph that should basically look like this:

``` c#
var singleton =
    new SingletonWorker(
        new DefaultMetricSubmitter()); // implements IMetricSubmitter

var scoped =
    new ScopedWorker(
        new EnrichMetricsDecorator( // implements IMetricSubmitter
            new DefaultMetricSubmitter())); // implements IMetricSubmitter
```

The graph contains two classes, let's call them `SingletonWorker` and `ScopedWorker`, registered with `Singleton` and `Scoped` lifestyles respectively. Both depend on `IMetricSubmitter` in their constructor. The workers submit metrics as part of their logic using the `IMetricSubmitter`. There's a singleton implementation for `IMetricSubmitter` called `DefaultMetricSubmitter`, which I like to decorate with `EnrichMetricsDecorator` for the purpose of `ScopedWorker` dependency, such that `SingletonWorker` will end up with `DefaultMetricSubmitter` and `ScopedWorker` will end up with `EnrichMetricsDecorator` decorating `DefaultMetricSubmitter`.

Is there a way to create such registrations using Simple Injector today?

To me it looks like combining the `RegisterConditional`, which has a predicate that knows about the consumer, with `RegisterDecorator` which is the way to register decorators, but I don't know of any way to combine the two. Ideally I'd like to register the decorator with a condition that is based on whether there's an active scope when it's requested as a dependency for a consuming constructor, and in that case create the decorator instance for that active scope. For the purpose of debate, the scope can be assumed to be `LifetimeScope`.

**Comment by dotnetjunkie** [comment]
What you want to do is not possible using the `RegisterDecorator` methods. Instead, you will have to revert to using the `RegisterConditional` methods. Considering your given object graph, these registrations should look something like this:

``` c#
container.Register<ScopedWorker>(Lifestyle.Scoped);
container.Register<SingletonWorker>(Lifestyle.Singleton);

container.RegisterConditional<IMetricSubmitter, EnrichMetricsDecorator>(
	Lifestyle.Scoped,
	c => c.Consumer.ImplementationType == typeof(ScopedWorker));

container.RegisterConditional<IMetricSubmitter, DefaultMetricSubmitter>(
	Lifestyle.Singleton,
	c => c.Consumer.ImplementationType != typeof(EnrichMetricsDecorator));
```
	
This practice is described [here][1] in the documentation.


  [1]: https://simpleinjector.readthedocs.io/en/latest/advanced.html#applying-decorators-conditionally-based-on-consumer

**Comment by Eldar1205** [comment]
1. Can you please explain why the second conditional has implementation type different than the decorator? The decorator should decorate the default submitter.

2. I suggest to add a RegisterConditionalDecorator overload, that receives a predicate context which combines the `DecoratorPredicateContext` with the `PredicateContext` used for conditional registrations. The reason is registering decorators like suggested above is inconsistent with standard decorator registration since the way it's written above the decorator is registered before the decoratee instead of after. Additionally it's not intuitive how to add another decorator `CachingDecorator` that should always decorate `DefaultMetricsSubmitter` and be injected to `SingletonWorker` while `EnrichMetricsDecorator` decorates the `CachingDecorator` and injected to `ScopedWorker`.

**Comment by dotnetjunkie** [comment]
Note that the second conditional registration did an `!=` (inequality) check, but this should have been `==` (equality). This is obvious. The `DefaultMetricSubmitter` should be injected into the `EnrichMetricsDecorator`, while the `EnrichMetricsDecorator` should be injected into either the `EnrichMetricsDecorator` or the `SingletonWorker`. I updated my answer accordingly.

About your second question, we considered adding such feature, but the feature is very complex to implement, and since the use case is 1. very uncommon and 2. possible to implement using `RegisterConditional` we decided not to implement this. I even think that there were problems when having the predicate walk both up and down the object graph to determine whether it should be applied, although I can't recall exactly what the problems were in doing that.

**Comment by dotnetjunkie** [comment]
I now remember why we decided not to implement this. Due to the way Simple Injector’s decorator sub system is designed, it is impossible to make decorators conditional based on the consuming types. The reason for this is that a decorator is applied (using the `ExpressionBuilt` event) to a specific `InstanceProducer`. This means that the actual type registration is altered by a decorator. Such `InstanceProducer` instance, however, is reused by all consumers to get the proper instance. Result of this is that a single `InstanceProducer` can never construct multiple object graphs.

This is a very different design to what you would normally see with other DI Containers, which will give a decorator its own unique registration. In general, the way Simple Injector does this is far more flexible and does make it possible to apply decorators conditional based on generic type constraints and other conditions.

To map this description to the example above, all registrations in Simple Injector get their own `InstanceProducer` instance (and in the case of generic types, every closed generic type gets its own `InstanceProducer`). Simple Injector will call `GetExpression()` on `SingletonWorker`'s `InstanceProducer` in order to build up the object graph for `SingletonWorker`. `SingletonWorker`’s `InstanceProducer`, however, will again call `GetExpression` on `DefaultMetricSubmitter`'s `InstanceProducer` as it contains a reference to all its depending `InstanceProducers`.

When `DefaultMetricSubmitter`'s `GetExpression` is called, however, will construct its expression tree and *cache that expression tree indefinitely*, in order to achieve good performance. The `EnrichMetricsDecorator`, however, will get applied to that expression tree before `DefaultMetricSubmitter` returns that tree. This means that a decorator can *never* be applied conditionally based on the consumer, as this means there would be a different tree per consumer, while there can only be one tree per `InstanceProducer` and all consumers reference the same `InstanceProducer`.

This is exactly what the solution using `RegisterConditional` works around, as each `RegisterConditional` registration gets its own `InstanceProducer` allowing the graphs to differ.

Although it would be technically possible to change this system, it would be a severe change, a major effort, and likely be breaking as well.

I, therefore, see now way to implement this feature inside `RegisterDecorator` and will thus close this issue.
