### ISSUE TITLE
SimpleInjector.Packaging doesn't work with UWP apps.

### ISSUE THREAD

**Issue by jonantoine** [simpleinjector/SimpleInjector#257]
Trying to Register Packages results in the following error.
Could not load file or assembly 
	'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. 
	The located assembly's manifest definition does not match the assembly reference

**Comment by dotnetjunkie** [comment]
This might be a bug in the NuGet package or an error in how we compile stuff.

Since the SimpleInjector.Packages assembly is nothing more than an interface and an extension method, the current work around is to just define those yourself. 

As a matter of fact, for most types of applications, it doesn't really makes much sense to use the packaging functionality. Packages are useful in case you have a highly dynamic pluggable application where your Composition Root doesn't have a compile-time dependency on the assemblies that contain part of the bootstrap code. In most applications however, the Composition Root depends [on every other assembly anyway](https://stackoverflow.com/questions/9501604/ioc-di-why-do-i-have-to-reference-all-layers-assemblies-in-entry-application), and this means that you can just as well make static method calls to the separate bootstrap methods/classes/packages that you defined.
