### ISSUE TITLE
Could not load ConditionalHashSet on Xamarin.Android

### ISSUE THREAD

**Issue by ghost** [simpleinjector/SimpleInjector#263]
I'm using 3.1.5. 
My steps: I create a new Android application and add SimpleInjector 3.1.5 via NuGet. 
Then I add `new Container();` in `OnCreate` in `MainActivity` and start the app. I get the following error:

> System.TypeLoadException: Could not load type 'ConditionalHashSet`1' from assembly '/storage/sdcard0/Android/data/AndroidTestApp8.AndroidTestApp8/files/.__override__/SimpleInjector.dll'.

Is there anything I miss? Do I need to add some special calls for Android? Same procedure works perfectly in UWP.

**Comment by dotnetjunkie** [comment]
Simple Injector's internal `ConditionalHashSet<T>` makes use of the `System.Runtime.CompilerServices.ConditionalWeakTable<TKey,  TValue>` class that is located in mscorlib. I bet that this `ConditionalWeakTable<TKey, TValue>` class is missing from Andoid and that this what's causing the failure to load `ConditionalHashSet<T>`.

It's unclear to me why this is missing, since Andoid should have the same API. Simple Injector depends on `ConditionalWeakTable<TKey, TValue>` internally to implement `ThreadLocal<T>
