### ISSUE TITLE
Crosswiring ASP.NET Identity Core

### ISSUE THREAD

**Issue by janhartmann** [simpleinjector/SimpleInjector#268]
I'm trying to get myself going with ASP.NET Identity Core + .NET DI + Simple Injector and I (unfortunately) have to cross wire a lot of .NET services since I wish to use Simple Injector as my application DI library. I've been following the various blog posts around the state of .NET DI and I hope everything will work out in the end.

I have a lot of services, which is wired like:

```cs
_container.RegisterCommands(typeof(MyHandlerAssembly).GetTypeInfo().Assembly);
_container.RegisterQueries(typeof(MyHandlerAssembly).GetTypeInfo().Assembly);

...			
		
// Cross wiring
_container.Register(app.ApplicationServices.GetService<UserManager<MyUser>>, Lifestyle.Singleton);
_container.Register(app.ApplicationServices.GetService<RoleManager<IdentityRole>>, Lifestyle.Singleton);
_container.Register(app.ApplicationServices.GetService<SignInManager<MyUser>>, Lifestyle.Singleton);
_container.Register(() => new MyDbContext(new DbContextOptionsBuilder().UseSqlServer(_configuration.GetConnectionString("Default")).Options), Lifestyle.Scoped);
          
_container.Verify();
```

Simple Injector throws me this when verifying:

> The configuration is invalid. Creating the instance for type `RoleManager<IdentityRole>` failed. The registered delegate for type `RoleManager<IdentityRole>` threw an exception. The registered delegate for type `RoleManager<IdentityRole>` returned null.

How can I register the  `RoleManager<IdentityRole>`like I do with the `UserManager<MyUser>`, which works fine?

Jan

**Comment by dotnetjunkie** [comment]
I don't think that those manager classes can be registered as singleton. They probably depend on a `DbContext` which means they should at most be Scoped. I'm not sure why `null` is returned, but I can imagine it having to do anything with their scoping. So prevent using `app.ApplicationServices` to retrieve those components, as [this blog post](https://simpleinjector.org/blog/2016/07/working-around-the-asp-net-core-di-abstraction/) advises. 

Instead use the `RequestServices` as follows:

``` c#
_container.Register(GetAspNetServiceProvider<UserManager<MyUser>>(app));
_container.Register(GetAspNetServiceProvider<RoleManager<IdentityRole>>(app));
_container.Register(GetAspNetServiceProvider<SignInManager<MyUser>>(app));

private static Func<T> GetAspNetServiceProvider<T>(IApplicationBuilder app) {
    var accessor = app.ApplicationServices.GetService<IHttpContextAccessor>();
    return () => accessor.HttpContext.RequestServices.GetRequiredService<T>();
}
```

> (unfortunately) have to cross wire a lot of .NET services

In general (as [this article](https://simpleinjector.org/blog/2016/07/working-around-the-asp-net-core-di-abstraction/) explains), you shouldn't have to cross wire anything at all. Your application code should only talk to application-specific abstractions. Adapter implementations for those abstractions are located in the composition root. So what services do you want to cross wire?

**Comment by janhartmann** [comment]
I agree that my application should only talk to my application specific abstractions. I just wanted to get going with my application, but should probably abstract the methods I use from the e.g the `RoleManager<T>`.

Using the `GetAspNetServiceProvider<T>` with your example gives:

> System.NullReferenceException: Object reference not set to an instance of an object.

On the `accessor.HttpContext`. I've added `services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();` as described in https://github.com/aspnet/Hosting/issues/793

**Comment by dotnetjunkie** [comment]
Weird that you're seeing it was not added by default. With my local test project, the `IHttpContextAccessor` was registered by ASP.NET. Perhaps I used some `UseXXX` methods that registered it OOTB.

So adding the `IHttpContextAccessor` solves the problem?

**Comment by janhartmann** [comment]
The issue is still herefixed - still returns null when accessing the `HttpContext` property. The `HttpContextAccessor` is set as the instance of `IHttpContextAccessor` when debugging.

**Comment by dotnetjunkie** [comment]
It probably returns null necayse you are calling Verify at startup.

**Comment by janhartmann** [comment]
Ah, yeah... You say something, hold on.

**Comment by dotnetjunkie** [comment]
Can you try this extension method?

``` c#
private Func<T> GetAspNetServiceProvider<T>(IApplicationBuilder app) {
    var appServices = app.ApplicationServices;
    var accessor = appServices.GetRequiredService<IHttpContextAccessor>();
    return () => {
        var services = accessor.HttpContext != null
            ? accessor.HttpContext.RequestServices
            : this.container.IsVerifying ? appServices : null;
        if (services == null) throw new InvalidOperationException("No HttpContext");
        return services.GetRequiredService<T>();
    };
}
```

**Comment by janhartmann** [comment]
Yes, first thing tomorrow morning. Had to leave the office early, sorry. :-)

**Comment by janhartmann** [comment]
Works like a charm - much more explicit.

Also a quick note, my `RoleManager<T>`  was registered as `RoleManager<IdentityRole>` but since I've changed the primary key on the `IdentityRole` to `Guid`, I had to register it with `RoleManager<IdentityRole<Guid>>`. 

Now I just need to solve some dependency issues with different scopes and possible abstract the methods I use from both the `UserManager` and `RoleManager`. 

Thanks a lot Steven!

**Comment by dotnetjunkie** [comment]
Hi Jan,

Great. Please keep me posted (privately or publically) on your progress. This whole integration is very new and we need the experience to improve the guidance and integration for developers.

Thanks

Steven

**Comment by janhartmann** [comment]
Thanks Steven, still hitting a few roadblocks.

I am trying to create some initial users and roles during startup (No EF seed yet).  But are getting `No HttpContext` from the method now. Not sure if this is too much extend for this issue here.

If you have the time, please take a look at this:

```cs
public interface IDatabaseInitializer
{
	int Order { get; }

	Task SeedAsync();
}

public class AddDefaultRolesDatabaseInititalizer : IDatabaseInitializer
{
	private readonly RoleManager<IdentityRole<Guid>> _roleManager;

	public AddDefaultRolesDatabaseInititalizer(RoleManager<IdentityRole<Guid>> roleManager)
	{
		_roleManager = roleManager;
	}

	public int Order { get; } = 1;

	public async Task SeedAsync()
	{
		if (_roleManager.Roles.Any()) return;

		var roles = new[]
		{
			"Role1",
			"Role2"
		};

		foreach (var role in roles)
		{
			var result = await _roleManager.CreateAsync(new IdentityRole<Guid>() { Name = role });
			if (!result.Succeeded)
			{
				throw new Exception("Errors creating roles.");
			}
		}
	}
}

public class AddDefaultUserDatabaseInititalizer : IDatabaseInitializer
{
	private readonly UserManager<ApplicationUser> _userManager;

	public AddDefaultUserDatabaseInititalizer(UserManager<ApplicationUser> userManager)
	{
		_userManager = userManager;
	}

	public int Order { get; } = 2;

	public async Task SeedAsync()
	{
		if (_userManager.Users.Any()) return;

		var result = await _userManager.CreateAsync(new ApplicationUser
		{
			UserName = "my@email.com",
			Email = "my@email.com",
			PhoneNumber = "004512345678",
			EmailConfirmed = true
		}, "Test1234@");

		if (!result.Succeeded)
		{
			throw new Exception("Errors creating users.");
		}

		var user = await _userManager.FindByEmailAsync("my@email.com");
		await _userManager.AddToRolesAsync(user, new[]
		{
			"Role1"
		});
	}
}

public class CompositeDatabaseInitializer : IDatabaseInitializer
{
	private readonly IEnumerable<IDatabaseInitializer> _databaseInitializers;

	public CompositeDatabaseInitializer(IEnumerable<IDatabaseInitializer> databaseInitializers)
	{
		_databaseInitializers = databaseInitializers;
	}

	public int Order { get; } = 0;

	public async Task SeedAsync()
	{
		foreach (var databaseInitializer in _databaseInitializers.OrderBy(initializer => initializer.Order))
		{
			await databaseInitializer.SeedAsync();
		}
	}
}

public static class CompositionRoot
{
	public static void RegisterDatabaseInitializers(this Container container, params Assembly[] assemblies)
	{
		container.RegisterCollection<IDatabaseInitializer>(assemblies);
		// I have to scope this since the UserManager and RoleManager is Scoped, not sure if I can
		// come around this.
		container.Register<IDatabaseInitializer, CompositeDatabaseInitializer>(Lifestyle.Scoped);
	}
}

// Startup.cs
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
	ConfigureAuth(app);
	InitializeContainer(app);

	app.UseStaticFiles();
	app.UseIdentity();
	app.UseMvcWithDefaultRoute();

	// Time to seed the database
	using (_container.BeginExecutionContextScope())
	{
		var databaseInitializer = _container.GetInstance<IDatabaseInitializer>(); // Composite
		databaseInitializer.SeedAsync();
	}
}

private void InitializeContainer(IApplicationBuilder app)
{
	app.UseSimpleInjectorAspNetRequestScoping(_container);

	/* Code removed for brevity*/
	_container.RegisterDatabaseInitializers(typeof(AuthDbContext).GetTypeInfo().Assembly);

	// Cross wiring
	_container.Register(GetAspNetServiceProvider<UserManager<ApplicationUser>>(app), Lifestyle.Scoped);
	_container.Register(GetAspNetServiceProvider<RoleManager<IdentityRole<Guid>>>(app), Lifestyle.Scoped);
	_container.Register(GetAspNetServiceProvider<SignInManager<ApplicationUser>>(app), Lifestyle.Scoped);
	_container.Register(() => new AuthDbContext(new DbContextOptionsBuilder().UseSqlServer(_configuration.GetConnectionString("Default")).Options), Lifestyle.Scoped);
   
	_container.Verify();
}

private Func<T> GetAspNetServiceProvider<T>(IApplicationBuilder app)
{
	var appServices = app.ApplicationServices;
	var accessor = appServices.GetRequiredService<IHttpContextAccessor>();

	return () => {
		var services = accessor.HttpContext != null
			? accessor.HttpContext.RequestServices
			: _container.IsVerifying ? appServices : null;

		if (services == null) throw new InvalidOperationException("No HttpContext");

		return services.GetRequiredService<T>();
	};
}
```

**Comment by dotnetjunkie** [comment]
The code you presented seems like code that is only used during initialization and it doesn't even require Simple Injector. I would remove Simple Injector from the equation and fall back on [Pure DI](http://blog.ploeh.dk/2014/06/10/pure-di/) for this scenario. I even believe this to be cleaner:

``` c#
var initializer = new CompositeDatabaseInitializer(
    new AddDefaultRolesDatabaseInititalizer(
        app.ApplicationServices.GetRequiredService<RoleManager<IdentityRole<Guid>>>()),
    new AddDefaultUserDatabaseInititalizer(
        app.ApplicationServices.GetRequiredService<UserManager<ApplicationUser>>()));

// Don't forget to call Wait, since everything is async.
initializer.SeedAsync().Wait();
```

Also note that you didn't call `Wait()` after the `SeedAsync()`, which might have caused the problems you are experiencing. Since your `Configure` method isn't async, the execution context scope block exists imediately, and the `SeedAsync` call effectively runs in the background.

But since this code runs at startup, running this code asynchronously has no benefits; it only complicates things. So my advice is to make this code synchronous.

**Comment by janhartmann** [comment]
Thanks Steven, I'll do that! Thanks for your time :-)

**Comment by janhartmann** [comment]
I've made everything sync now and changed it to Pure DI using simple constructor arguments:

```cs
var initializer = new CompositeDatabaseInitializer(new IDatabaseInitializer[]
{
	new AddDefaultRolesDatabaseInititalizer(app.ApplicationServices.GetRequiredService<RoleManager<IdentityRole<Guid>>>()),
	new AddDefaultUserDatabaseInititalizer(app.ApplicationServices.GetRequiredService<UserManager<AskCodyIdentityUser>>())
});

initializer.Seed();
```

But seems that accessing the `RoleManager` throws the exception on its `CreateAsync` method: 

```cs
// Now sync.
var result = _roleManager.CreateAsync(new IdentityRole<Guid> { Name = role }).Result;
```

> InnerException	{System.ObjectDisposedException: Cannot access a disposed object.
> Object name: 'RoleManager`1'.
>    at Microsoft.AspNetCore.Identity.RoleManager`1.ThrowIfDisposed()
>    at Microsoft.AspNetCore.Identity.RoleManager`1.<CreateAsync>d__30.MoveNext()}	System.Exception {System.ObjectDisposedException}

This is of course not an Simple Injector issue, so I'll bug the .NET Identity Core.

**Comment by marcwittke** [comment]
This is an old issue, I know, but I stumbled various times over it. My application needs to interact with identity (it's basically about human resources, that might have a user account on their own or not), and after struggling a long time with with various issues having identity in the framework container, I was trying to configure simple injector to provide all identity services. Call it crazy, but this is how it works:

This is the "ConfigureServices" part:
```csharp
// identity options are provided from outside, allowing configuration of the framework
container.RegisterSingleton<IOptions<IdentityOptions>>(new OptionsWrapper<IdentityOptions>(identityOptions));

// we rely on BCrypt instead of the default PBKDF2 hashing algorithm
container.Register<IPasswordHasher<MepUser>>(()=>new BCryptPasswordHasher(bcryptOptions));

// forwarding the framework logger to our own logging framework
container.Register<Microsoft.Extensions.Logging.ILoggerFactory, FrameworkToBackendFxLoggerFactory>();
container.Register(typeof(Microsoft.Extensions.Logging.ILogger<>), typeof(Microsoft.Extensions.Logging.Logger<>));

// identity store = a specific Entity Framework Core  DbContext, getting mapped into a specific db scheme
container.RegisterSingleton(identityDbContextOptions);
container.Register<MepIdentityDbContext>();

// UserStore<T> und RoleStore<T> both require a DbContext (no IdentityDbContext, neither a generic TDbContext)
// via constructor, but the container only knows about MepIdentityDbContext so we have to wire it manually
container.Register<IUserStore<MepUser>>(() => new UserStore<MepUser>(
                                                container.GetInstance<MepIdentityDbContext>(),
                                                container.GetInstance<IdentityErrorDescriber>()));
container.Register<IRoleStore<IdentityRole>>(() => new RoleStore<IdentityRole>(
                                                container.GetInstance<MepIdentityDbContext>(),
                                                container.GetInstance<IdentityErrorDescriber>()));

// framework internal services
container.Register<IdentityErrorDescriber>();
container.Register<ILookupNormalizer, UpperInvariantLookupNormalizer>();
container.Register<IPasswordValidator<MepUser>, PasswordValidator<MepUser>>();
container.Register<IUserValidator<MepUser>, UserValidator<MepUser>>();
container.Register<IUserClaimsPrincipalFactory<MepUser>, UserClaimsPrincipalFactory<MepUser>>();
container.Register<IRoleValidator<IdentityRole>, RoleValidator<IdentityRole>>();

// ASP.Net Core Identity violates a design decision of SimpleInjector: The API clearly differentiates the registration of collections
// https://simpleinjector.readthedocs.io/en/latest/decisions.html#the-api-clearly-differentiates-the-registration-of-collections
// By registering IEnumerables of those violating services with a simple wrapping single item array, Identity is happy
container.Register<IEnumerable<IUserValidator<MepUser>>>(() => new[] { container.GetInstance<IUserValidator<MepUser>>() });
container.Register<IEnumerable<IRoleValidator<IdentityRole>>>(() => new[] { container.GetInstance<IRoleValidator<IdentityRole>>() });
container.Register<IEnumerable<IPasswordValidator<MepUser>>>(() => new[] { container.GetInstance<IPasswordValidator<MepUser>>() });

// Role and UserManager reflect the API surface of the whole ASP.Net Core Identity framework
container.Register<RoleManager<IdentityRole>>();
// UserManagerShim is omitting (=nulling) the IServiceProvider parameter of UserManager<T>
container.Register<UserManager<MepUser>, UserManagerShim>();
```

and this needs to be done during "Configure", otherwise password reset and other two factor token stuff won't work (runtime error, although the container was verified)
```csharp
// if you eagerly instantiate a provider instance that is considered being a singleton and
// put it into the respective field in the TokenProviderDescriptor and list it in the option's
// provider map, ASP.Net Core Identity will use this one instead of asking the IServiceProvider 
// instance injected into UserManager<T> (that we do not do, because it is bad design. Instead, 
// we just stuff null in there)
identityOptions.Tokens.ProviderMap[TokenOptions.DefaultProvider] =
        new TokenProviderDescriptor(typeof(DataProtectorTokenProvider<MepUser>))
        {
            ProviderInstance = new DataProtectorTokenProvider<MepUser>(
                    dataProtectionProvider, 
                    new OptionsWrapper<DataProtectionTokenProviderOptions>(new DataProtectionTokenProviderOptions()))
        };

identityOptions.Tokens.ProviderMap[TokenOptions.DefaultEmailProvider] =
        new TokenProviderDescriptor(typeof(EmailTokenProvider<MepUser>)) {
                ProviderInstance = new EmailTokenProvider<MepUser>()
        };
```

Although there appears `AspNetCore` in the namespace definition, nothing is dependent on ASP.Net Core hosting, actually. The only dependency to the "outside world" are the options (POCOs) and an implementation of `IDataProtectionProvider`, that will use the `KeyRing` in ASP.Net scenarios, but can also be satisfied using the `EphemeralDataProtectionProvider` in tests.

Caveat: `SignInManager<T>` is not being injected. This class is a total mess, depending on the whole world, so I rewrote it basically matching my requirements. You also loose lots of the configuration flexibility regarding token providers. But however, in my case it's something you decide once at design time, so I am fine with it.

I expect @dotnetjunkie to say this is crazy (and I know that he's right 95%), but the alternative made me headaches all the time. So this was the less bad decision. Maybe this post helps someone to avoid the struggles I had.

**Comment by dotnetjunkie** [comment]
@marcwittke, yes, you are right. I will call this crazy and advise against this kind of madness. I'll comment within a few days (AFK ATM) with a more detailed response on what to do instead. Stay tuned.

**Comment by dotnetjunkie** [comment]
@marcwittke 

This set of registrations that you show effectively duplicate the list of registrations that Identity already made in ASP.NET Core's built-in configuration system. Duplicating these registrations is a bad idea because:

- It leads to lots of boilerplate code
- It leads to a maintenance nightmare, because you possibly have to update this configuration every time a new version of Identity is released.
- Because of the sometimes subtle differences in how Simple Injector works compared to ASP.NET Core's built-in configuration system, your Simple Injector registrations might be incorrect.
- It could cause a *Scoped* registration to exist multiple times within a single web request—a problem known as [Torn Lifestyles](https://simpleinjector.org/diatl).

Duplicating registrations is therefore _never_ the option. Instead, you should keep Identity's configuration completely _inside_ the built-in configuration system, and _cross-wire_ **only** the dependencies that your application needs.

Cross-wiring in this respect, is the act of telling Simple Injector to resolve a certain dependency from ASP.NET Core's configuration system.

When you tell Simple Injector to resolve a dependency from ASP.NET Core, you only need to add a registration to Simple Injector for an abstraction that is _directly_ used by your application code.

Cross-wiring is very different from what you are currently doing, because by duplicating the registrations in Simple Injector, you instruct Simple Injector to construct the complete graph of components required for Identity to work, including classes that are not required by your application. With cross-wiring, the ASP.NET Core configuration system is in control over the construction of Identity's components.

I have no idea what abstractions from Identity your application code requires, but it will typically just be a hand full—much less than what you are registering right now.

Although cross-wiring isn’t that complicated to do manually, Simple Injector helps you out with this process by providing you with a `CrossWire` extension method. This allows you to tell Simple Injector to resolve _only specific_ dependencies that your application code _really needs_ from ASP.NET Core:

``` c#
container.CrossWire<RoleManager<IdentityRole>>(app);
container.CrossWire<ILookupNormalizer>(app);
```

The previous configuration assumes that `RoleManager<IdentityRole>` and `ILookupNormalizer` are the _only_ two dependencies that are required to be injected into application components (like your controllers, command handlers, etc) that are composed by Simple Injector. Although your application might require different types, you only need to register what you _directly_ need—not indirectly.

This severely simplifies your registration and reduces maintenance to a minimum.

On top of this `CrossWire` extension method, Simple Injector [v4.1](https://github.com/simpleinjector/SimpleInjector/milestone/22) will simplify cross-wiring even further by the introduction of  the [AutoCrossWireAspNetComponents](https://github.com/simpleinjector/SimpleInjector/issues/442) extension method. This will remove the need to add any individual `CrossWire` methods and instead Simple Injector will use Unregistered Type Resolution to figure out whether or not a missing registration exists in ASP.NET Core, and it will do the cross-wiring on your behalf.

Here is an example of what your `Startup` class will look like with v4.1:

``` c#
public class Startup {
    private Container container = new Container();

    public Startup(IHostingEnvironment env) {
        // ASP.NET default stuff here
    }

    public void ConfigureServices(IServiceCollection services) {
        // ASP.NET default stuff here
        services.AddMvc();

        // Simple Injector stuff
        container.Options.DefaultScopedLifestyle = new AsyncScopedLifestyle();

        services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();

        services.AddSingleton<IControllerActivator>(
            new SimpleInjectorControllerActivator(container));
        services.AddSingleton<IViewComponentActivator>(
            new SimpleInjectorViewComponentActivator(container));

        services.EnableSimpleInjectorCrossWiring(container);
        services.UseSimpleInjectorAspNetRequestScoping(container);
    }

    // Configure is called after ConfigureServices is called.
    public void Configure(IApplicationBuilder app, IHostingEnvironment env,
        ILoggerFactory factory) {

        // Here use the new extension method! No need to call CrossWire<T> manually.
        container.AutoCrossWireAspNetComponents(app);
        
        // Add application presentation components:
        container.RegisterMvcControllers(app);
        container.RegisterMvcViewComponents(app);

        // Add application services. For instance:
        container.Register<IUserService, UserService>(Lifestyle.Scoped);

        // Also new in v4.1, the UseMiddleware<T>(Container) extension method.
        app.UseMiddleware<CustomMiddleware1>(container);
        app.UseMiddleware<CustomMiddleware2>(container);

        container.Verify();
    }
}
```

Simple Injector v4.1 is not RTM at the moment, but you can try this out using the alpha release that you can find on NuGet.

If you can’t wait for an RTM release of v4.1, the new `AutoCrossWireAspNetComponents` is almost identical to the `ConfigureAutoCrossWiring` extension method shown [here]( https://github.com/simpleinjector/SimpleInjector/issues/442#issuecomment-317423080).

**Comment by marcwittke** [comment]
Hey Steven (aka @dotnetjunkie ), I just remembered that I did never responded to your excellent guidance. Sorry for that 😞  In the end I followed your advice for cross wiring that is really very easy as of version 4.1 now, even respecting scoping twirks. Thanks for this amazing piece of software.*

Some side note: you got me a little bit wrong. While you are right that the code I showed was a duplication of the original registration logic for ASP.Net Core, it was not really _done_ twice. There was no `.UseIdentity()` anywhere. The build in container did not know anything about Identity.

> \* Did I ever notice somewhere how much untraceable errors I found in a productive application switching from Ninject to SimpleInjector and kicking off validation and diagnostics? It was like pumping out the fish pond and finding all the car wrecks 😲
