### ISSUE TITLE
How to conditionally register type into collection?

### ISSUE THREAD

**Issue by abatishchev** [simpleinjector/SimpleInjector#283]
Currently I register web api infrastructure modules as a collection of types:

```csharp
container.RegisterSingleton<CertificateValidationHandler>();
container.RegisterCollection<DelegatingHandler>(
	new[]
	{
		typeof(CertificateValidationHandler),
		typeof(CorrelationIdHandler)
	});
```

Now I'd like to conditionally add one more type:

```csharp
container.RegisterConditional<DelegatingHandler, SubscriptionKeyHandler>(Lifestyle.Singleton,
    c => container.GetInstance<IConfigurationSource>()
		.GetApplicationSetting("Environment") != null);
	
container.RegisterCollection<DelegatingHandler>(new[]
	{
		...
		typeof(SubscriptionKeyHandler)
	});
```

But this code doesn't work since single and collection registrations are independent.

I also cannot do something like this:

```csharp
var handlerTypes = new List<Type>();

if (container.GetInstance<IConfigurationSource>().GetApplicationSetting("Environment") != null))
    list.Add(typeof(SubscriptionKeyHandler)));

container.RegisterCollection<DelegatingHandler>(handlerTypes);
```

because this would lock down the container from further registrations.

Is there a way to achieve that?

**Comment by dotnetjunkie** [comment]
What you are trying to doesn't require conditional registrations at all. Conditional registrations are meant to be registered conditional based on the context (as in the rest of the object graph) they live in. In your case you handler its registration based on the application configuration. As far as I understand from your example, this configuration will not change as long as the application lives. In other words, the result of the predicate `GetApplicationSetting("Environment") != null)` will never change as long as the application is running. Changing it will require an application restart (since .NET will only read its configuration file once).

In such case it's much easier (and better) to move this check up and simply base the registrations on this check, as you are doing in your second example. [Obviously](https://simpleinjector.org/locked) making registrations after you resolve something is not allowed, but you should never have to do this. Reading the application's configuration should be done before you make the registration, so you should not have to pull the registrastion from the container (just like you would separate container registrations from using it, likewise should you separate reading the config and registering your container). You should be able to do something like this:

``` c#
var configuration = LoadConfigurationSource();

var container = new Container();

container.RegisterSingleton<IConfigurationSource>(configuration);

var handlerTypes = new List<Type>();

if (configuration.GetApplicationSetting("Environment") != null) 
    container.Register<SubscriptionKeyHandler>(Lifestyle.Singleton);
    list.Add(typeof(SubscriptionKeyHandler)));
}

container.RegisterCollection<DelegatingHandler>(handlerTypes);
```

Prefer refraining from registering this `IConfigurationSource` object *at all* in the container. You will be violating the Dependency Inversion Principle and Interface Segregation Principle in case application code depends on this abstraction. Instead, prefer injecting very specific configuration values into
constructors of types, or hide those configuration values behind very specific and narrow abstractions. For instance, instead of injecting an `connectionString` into 20 repositories, prefer injecting an `IConnectionFactory` of some sort, whose implementation depends on this `connectionString`.

**Comment by abatishchev** [comment]
Hi Steven, thanks for replying so promptly!
In general you're absolutely right and I wouldn't try to argue. But this case is slightly different: this is not standard statem.configuration-based configuration but Enterprise Grade Configuration Subsystem (TM) :)) which mimics the standard one but involves certificates, certificate stores, web services, caches, etc. thus requires a container to build its dependency graph. And here I reuse the main container. You're right there are some modules that accept IConfigurationSource in ctor but usually they're tiny decorators on top of real modules.
However, you provided a good food for thoughts. An option here would be using a separate/child container, which will only construct IConfigurstionSource and be disposed after that. Then I'll register it in the main/root one.

**Comment by dotnetjunkie** [comment]
Instead of using a separate container, I'd opt for moving to Pure DI for building your configuration object. In other words, new that object graph by hand. Chances are slim that this part of the application changes this rapidly that that not using a container would cause maintenance problems.

**Comment by abatishchev** [comment]
Yes, both (child container and container poor man's di) are good options and worked for me. Thanks for the pointer!

However, out of curiosity, is it possible to achieve what I've asked initially? Conditional registration into a collection.

**Comment by dotnetjunkie** [comment]
> out of curiosity, is it possible to achieve what I've asked initially?

There are possibly several ways to do this. What won't work however is to use `RegisterConditional`, since `RegisterCollection` will always register its elements unconditionally.

The first thing that comes to my mind is to use a decorator. For instance, you can wrap each `DelegatingHandler` with a decorator and let the decorator decide whether the logic of the decoratee should be executed or skipped.

If this doesn't work because you need the element to disapear from the collection completely, you can wrap the collection itself with a decorator. Take a look at this example for instance:


``` csharp
public class ConditionalDelegatingHandlerCollectionDecorator : IEnumerable<DelegatingHandler>
{
    private readonly IEnumerable<DelegatingHandler> decoratedCollection;

    public ConditionalDelegatingHandlerCollectionDecorator(
        IEnumerable<DelegatingHandler> decoratedCollection) {
        this.decoratedCollection = decoratedCollection;
    }

    IEnumerator IEnumerable.GetEnumerator() => this.GetEnumerator();

    public IEnumerator<DelegatingHandler> GetEnumerator() {
        return (
            from handler in this.decoratedCollection
            where handler != typeof(SubscriptionKeyHandler) // some runtime condition
            select handler)
            .GetEnumerator();
    }
}
```

You can register this decorator simply as follows:

``` c#
container.RegisterDecorator(
    typeof(IEnumerable<DelegatingHandler>), 
    typeof(ConditionalDelegatingHandlerCollectionDecorator),
    Lifestyle.Singleton);
```

This will work up to the point that you want to start to decorate individual handlers as well, because to be able to filter handlers based on their type, such instance can't be decorated (because we would lose that type information). To solve this, you can inject the required meta data (like an `Type[]`) in the decorator (conditionally) or register a delegate that will handle the filtering for you. For instance:

``` csharp

public delegate bool IndexBasedDelegatingHandlerFilter(int index);

public class ConditionalDelegatingHandlerCollectionDecorator : IEnumerable<DelegatingHandler>
{
    private readonly IndexBasedDelegatingHandlerFilter indexBasedFilter;
    private readonly IEnumerable<DelegatingHandler> decoratedCollection;

    public ConditionalDelegatingHandlerCollectionDecorator(
        IndexBasedDelegatingHandlerFilter indexBasedFilter,
        IEnumerable<DelegatingHandler> decoratedCollection)
    {
        this.indexBasedFilter = indexBasedFilter;
        this.decoratedCollection = decoratedCollection;
    }

    IEnumerator IEnumerable.GetEnumerator() => this.GetEnumerator();

    public IEnumerator<DelegatingHandler> GetEnumerator()
    {
        return this.decoratedCollection
            .Select((handler, index) => new { handler, index })
            .Where(pair => indexBasedFilter(pair.index))
            .Select(pair => pair.handler) 
            .GetEnumerator();
    }
}
```

Here we injected an `IndexBasedDelegatingHandlerFilter` will do the proper filtering based on the index of the handler in the collection. The delegate can find out what the exact type of the handler is, because collections have a guaranteed ordering. Here's how to register this:

``` csharp
var handlers = new[] { typeof(SubscriptionKeyHandler), ... };

container.RegisterCollection<DelegatingHandler>(handlers);

container.RegisterSingleton<IndexBasedDelegatingHandlerFilter>(
    index => handlers[index] != typeof(SubscriptionKeyHandler) // runtime condition here
);

container.RegisterDecorator(
    typeof(IEnumerable<DelegatingHandler>), 
    typeof(ConditionalDelegatingHandlerCollectionDecorator),
    Lifestyle.Singleton);
```

Do note however that filtering `DelegatingHandler`s from a collection based on runtime conditions probably makes little sense, since the list of `DelegatingHandler`s in Web API is AFAIK a fixed list of singletons. It will only be read once and the list is stored forever. If you wish to dynamically enable disable Web API `DelegingHandler`s, you are better of using a decorator around individual handlers instead.

ps. don't forget to register your handlers as singleton, because Web API will store them as singleton. Registering them as singleton allows Simple Injector to detect captive dependencies on them.
