### ISSUE TITLE
Stub DecoratorContext

### ISSUE THREAD

**Issue by bjorncoltof** [simpleinjector/SimpleInjector#287]
Hi I have the following decorator:

```c#
public class CheckFeatureToggleRequestDecorator<TRequest, TResponse>
        : IAsyncRequestHandler<TRequest, TResponse>
        where TRequest : IAsyncRequest<TResponse>
    {
        private readonly IAsyncRequestHandler<TRequest, TResponse> _handler;
        private readonly IMasterDbContext _context;
        private readonly ICurrentUser _user;
        private readonly DecoratorContext _decoratorContext;

        public CheckFeatureToggleRequestDecorator(
            IAsyncRequestHandler<TRequest, TResponse> handler,
            IMasterDbContext context,
            ICurrentUser user,
            DecoratorContext decoratorContext)
        {
            _handler = handler;
            _context = context;
            _user = user;
            _decoratorContext = decoratorContext;
        }

        public async Task<TResponse> Handle(TRequest message)
        {
            
            await FeatureToggleCheck.ThrowIfNotAllowed(_decoratorContext.ImplementationType, _context, _user.DomainId);

            return await _handler.Handle(message);
        }
    }
```

I would like to write a unit test for this decorator to check that it actually throws if a feature is not allowed. A bug in the previous code used the type of the _handler as a parameter to the feature toggle check, which ofc worked fine in test, but broke in the real software where the handler turned out to already be decorated. This now does what we want, but I don't know how to stub the decorator context.

I know I can pour the FeatureToggleCheck into it's own class/interface and then inject it into decorator and then verify that the ThrowIfNotAllowed is called with the proper type through an integration test, but I much prefer to keep this unit test.

Is there a better approach I can take?

**Comment by dotnetjunkie** [comment]
`DecoratorContext` has an internal constructor. This makes it easier for us to evolve Simple Injector without having to make breaking changes to the library. Downside of course is that it becomes impossible for you to create it manually, which is what you are trying to achieve.

> I would like to write a unit test for this decorator to check that it actually throws if a feature is not allowed.

So what exactly do you want to test? The decorator has 2 lines of code :-). In general I would have this kind of code being tested as part of the set of integration tests that my application contains, since the decorator is part of your composition root.  But if you can't resist, I see two solutions in your case. Either you add a second constructor, or you make the `DecoratorContext` optional.

Here's an example with a second constructor:

``` csharp
public class CheckFeatureToggleRequestDecorator<TRequest, TResponse>
    : IAsyncRequestHandler<TRequest, TResponse>
    where TRequest : IAsyncRequest<TResponse>
{
    private readonly IAsyncRequestHandler<TRequest, TResponse> _handler;
    private readonly IMasterDbContext _context;
    private readonly ICurrentUser _user;
    private readonly Type _implemenationType;

    public CheckFeatureToggleRequestDecorator(IAsyncRequestHandler<TRequest, TResponse> handler,
        IMasterDbContext context, ICurrentUser user, DecoratorContext decoratorContext)
        : this(handler, context, user, decoratorContext.ImplementationType) { }
    
    internal CheckFeatureToggleRequestDecorator(
        IAsyncRequestHandler<TRequest, TResponse> handler, IMasterDbContext context,
        ICurrentUser user, Type implemenationType) {
        _handler = handler;
        _context = context;
        _user = user;
        _implemenationType = implemenationType;
    }    

    public async Task<TResponse> Handle(TRequest message) {
        await FeatureToggleCheck.ThrowIfNotAllowed(_implemenationType, _context, _user.DomainId);
        return await _handler.Handle(message);
    }
}
```

I added a second constructor to the decorator and pass `decoratorContext.ImplementationType` with the other dependencies to this second constructor. This constructor needs to be either `internal` or `protected` in Simple Injector's default configuration. This way your unit test can call this new constructor and pass in the right implementation type. In case the constructor is `internal` you must mark your unit test assembly as `InternalsVisibleTo` so it can access the internals of your main project. If you make the constructor `protected`, you will have to derive from the decorator so you can override it.

Here's the option with the optional argument:

``` csharp
public class CheckFeatureToggleRequestDecorator<TRequest, TResponse>
    : IAsyncRequestHandler<TRequest, TResponse>
    where TRequest : IAsyncRequest<TResponse>
{
    private readonly IAsyncRequestHandler<TRequest, TResponse> _handler;
    private readonly IMasterDbContext _context;
    private readonly ICurrentUser _user;

    public CheckFeatureToggleRequestDecorator(
        IAsyncRequestHandler<TRequest, TResponse> handler,
        IMasterDbContext context,
        ICurrentUser user,
        DecoratorContext decoratorContext = null)
    {
        _handler = handler;
        _context = context;
        _user = user;
        ImplementationType = decoratorContext?.ImplementationType;
    }
    
    public Type ImplementationType { get; set; }

    public async Task<TResponse> Handle(TRequest message) {
        await FeatureToggleCheck.ThrowIfNotAllowed(ImplementationType, _context, _user.DomainId);
        return await _handler.Handle(message);
    }
}
``` 

Example:

``` csharp
var sut = new CheckFeatureToggleRequestDecorator<SomeRequest, SomeResponse>(
    new FakeRequestHandler<SomeRequest, SomeResponse>(),
    new FakeMasterDbContext(),
    new FakeUserContext());

sut.ImplementationType = typeof(MyHandler);

sut.Handle(new SomeRequest());
```

**Comment by bjorncoltof** [comment]
Thanks, we will be going with integration test route. We did end up hiding the check behind an interface as we could use that for imperative checks.
