### ISSUE TITLE
Fails to resolve randomly

### ISSUE THREAD

**Issue by devteamexpress** [simpleinjector/SimpleInjector#292]
We are using the WebAPI and have been in production more than a year. I would say about 3% of the time i get weird errors that one of the dependencies was null. The only possible explanation was that simple injector resolved it to null. Has anyone seen this behavior or maybe have some pointers for what I can look for in order to diagnose the problem.

**Comment by dotnetjunkie** [comment]
Simple Injector does not allow null to be injected into constructors. The expression trees it compiles do not allow nulls and even the return values from delegates you register are checked for null; clear exception messages are thrown when null values are detected.

Besides this, I haven't heard of anyone having something similar, so I find it very unlikely this to be caused by a bug in Simple Injector.

The usual way to investigate is to analyze the stack trace of the thrown exceptions. If you deploy the .pdb files to production,  you'll even get line numbers in the stack trace. This should typically give you a good indication where the problem is.
