### ISSUE TITLE
Factory method with parameter?

### ISSUE THREAD

**Issue by AnderssonPeter** [simpleinjector/SimpleInjector#294]
Is there any way to have a factory method with a parameter?
Lets say i have the following two classes

```
Organisation (OrganisationContext organisationContext, string name)
OrganisationContext (Func<OrganisationContext, Organisation, string> organisationFactory)
```

How would i register this in SimpleInjector so that i get a method injected into `OrganisationContext` that can be called with a `OrganisationContext` and string parameter to create a `Organisation` with the parameters passed to the function into the constructor?

Or is this simply not possible, if that is the case should i just add a initialize method and pass the parameters there?

Or am i missing something about how to use DI?

**Comment by dotnetjunkie** [comment]
Everything is possible :) However, I'm unsure what it is you are trying to achieve. Could you show what it is you are trying to do by giving an example of how you would create these objects by hand? So without any DI container.

**Comment by AnderssonPeter** [comment]
@dotnetjunkie thanks for your reply
i remade my example a bit to make it more logical (or i hope its more logical)

Without a DI container
```
public class Database
{
    public IEnumerable<string> GetMemberNames()
    {
        //Replace with database logic!
        return null;
    }

    public void DeleteMember(string name)
    {
        //Replace with database logic
    }
}

public class Organisation
{
    private Database database;
    public IEnumerable<Member> Members
    { get; }

    public Organisation(Database database)
    {
        this.database = database;
        var memberNames = database.GetMemberNames();
        this.Members = memberNames.Select(name => new Member(database, this, name));
    }
}

public class Member
{
    private Database database;

    public Organisation Organisation
    { get; }

    public string Name
    { get; }
    public Member(Database database, Organisation organisation, string name)
    {
        this.database = database;
        this.Organisation = organisation;
        this.Name = name;
    }

    public void Delete()
    {
        database.DeleteMember(Name);
    }
}
```

And with a DI Container
```
public class Database
{
    public IEnumerable<string> GetMemberNames()
    {
        //Replace with database logic!
        return null;
    }

    public void DeleteMember(string name)
    {
        //Replace with database logic
    }
}

public class Organisation
{
    private Database database;
    public IEnumerable<Member> Members
    { get; }

    public Organisation(Database database, Func<Organisation, string, Member> memberFactory)
    {
        this.database = database;
        var memberNames = database.GetMemberNames();
        this.Members = memberNames.Select(name => memberFactory(this, name));
    }
}

public class Member
{
    private Database database;

    public Organisation Organisation
    { get; }

    public string Name
    { get; }
    public Member(Database database, Organisation organisation, string name)
    {
        this.database = database;
        this.Organisation = organisation;
        this.Name = name;
    }

    public void Delete()
    {
        database.DeleteMember(Name);
    }
}
```

There should only be one(Singleton) `Database` instance active, but multiple(Transient) `Organisation` and `Member`.

i simplified a lot of the details but if i can get this to work i think i would be able to hammer out the rest of the details on my own.

**Comment by dotnetjunkie** [comment]
That was not exactly what I meant by "without any DI container." Whether or not you use a DI container or not, should not change the way you write your code. Your code looks different "without DI container", that should not be true. What I meant was, you are asking how to configure Simple Injector in such way that it will build the object graphs for you. But when practicing DI, a DI container is an optional tool. You can *always* build those object graphs yourself by newing those objects using the C# `new` statement inside your [Composition Root](http://blog.ploeh.dk/2011/07/28/CompositionRoot/). So my question was: if you weren't using a DI container, how would you new up those objects by hand (without making any changes to your classes).

I often ask this question and I ask this for two reasons. First of all, it helps me understand how the object graph should be structured. This allows me to understand which configuration to suggest. As a side effect, it helps the OP visualize what he needs his object graph to be. Developers often forget about visualizing the object graphs, which makes a DI container some magical tool. Visualizing the object graph in your head (or on a piece of code) helps to understand how things work and often give interesting insights on how to structure the application.

But anyway, I would like to suggest a different application design. Your `Organisation` and `Member` classes seem entities, who are typically short lived objects. The `Database` class on the other hand seems a service; services are typically longer lived. As a rule of thumb, services are built up by the container; these are the classes that you inject dependencies into through the constructor. Entities on the other hand should *not* be built up by the container; They should not have any dependencies injected into their constructor.

There's an ongoing discussion whether or not entities should even have dependencies at all; whether they should be [anemic](http://www.martinfowler.com/bliki/AnemicDomainModel.html) or not. But either way, in your case you inject dependencies into the constructor to let the constructor do all the hard work of loading the entity with its sub entities. Loading data from and saving data to the database should not be the responsibility of the entity, and in general, [constructors should be simple]( http://blog.ploeh.dk/2011/03/03/InjectionConstructorsshouldbesimple/). This logic should instead be part of your `Database` class. Btw, the general design pattern for this `Database` class of yours is called: Repository.

So no matter whether you want your domain entities to be rich or anemic, you should never have this creation and initialization logic inside your entities (both Eric Evens and Martin Fowler are pretty clear about this).

So I would like to propose a different application design. This design separates data from behaviour (where the entities consist of data and the services consist of behaviour). Accidentally, this design also solves your probems. Here’s what I propose:

``` c#
// Services: A repository for members and one for Organisations
public class MemberRepository : IMemberRepository
{
    public IEnumerable<string> GetMemberNames() { ... }

    public void DeleteMember(string name) { ... }
}

public class OrganisationRepository : IOrganisationRepository
{
    private IMemberRepository memberRepository;

    public OrganisationRepository(IMemberRepository memberRepository)
    {
        this.memberRepository = memberRepository;
    }

    // Builds up a completely initialized Organisation object.
    public Organisation GetOrganisation()
    {
        var memberNames = this.memberRepository.GetMemberNames();
        var organisation = new Organisation();
        organisation.Members = 
            memberNames.Select(name => new Member(organisation, name))
            .ToArray();
        return organisation;
    }
}

// Entities (don't require any dependencies in their constructor)
public class Organisation
{
    public IEnumerable<Member> Members { get; set; }
}

public class Member
{
    public Organisation Organisation { get; }
    public string Name { get; }

    public Member(Organisation organisation, string name)
    {
        this.Organisation = organisation;
        this.Name = name;
    }
}
```

I created an `OrganisationRepository` that depends on `IMemberRepository` (your old `Database` class). The `OrganisationRepository` builds up `Organisation` entities. This class now contains the initialization logic that before was in your `Organisation` class. Since `Organisation` and `Member` have a cyclic dependency, I made the `Organisation` class mutable. Instead of creating cyclic dependencies, you can also choose to remove the dependency from `Member` back to `Organisation`. This makes certain things (like building up this aggregate and serializing it) much easier. I leave this up to you.

I also removed the `Delete` method from `Member`. This method should not be here, because you would be implementing the [Active Record](http://www.mehdi-khalili.com/orm-anti-patterns-part-1-active-record/) pattern. Anyone who wishes to remove a `Member` should simply call `IMemberRepository.DeleteMember`.

Configurating Simple Injector now has become trivial:
``` c#
container.RegisterSingleton<IMemberRepository, MemberRepository>();
container.RegisterSingleton<IOrganisationRepository, OrganisationRepository>();
```
I hope this helps.

**Comment by AnderssonPeter** [comment]
Well ok then i understand what you mean.
Well then lets go with the example With DI.

```
Database database = new Database();
Organisation organisation = new Organisation(database, (o, name) => (new Member(database, o, name)));
foreach (Member member in organisation.Members)
{
    Console.WriteLine($"Member name: {member.Name}");
}
```
Is this possible with SimpleInjector?
But i guess i will have to think a bit more about simplifying the design with something like your example.

**Comment by dotnetjunkie** [comment]
You can do the registration as follows:

``` c#
var database = new Database();

container.RegisterSingleton(database);
container.Register<Organisation>(() => new Organisation(
    database, 
    (o, name) => new Member(database, o, name)));
```

But again, I would urge you to change your design. Prevent constructor injection into entities. Prevent doing any considerable logic into constructors. Apply the repository pattern instead of letting entities query the database them selves. Refrain from using the Active Record pattern. These tips will guide you to a cleaner, more maintainable design and simplify constructing your object graphs; whether you apply DI  by hand (a.k.a. Pure DI) or whether you use a container to do so.

**Comment by AnderssonPeter** [comment]
They where just examples and wont be my entities classes in production.
Again thanks a lot for your help!
