### ISSUE TITLE
Contextual registration for Serilog ILogger

### ISSUE THREAD

**Issue by luisbelloch** [simpleinjector/SimpleInjector#295]
Hi, I'm reading documentation related to [context based injection](https://simpleinjector.readthedocs.io/en/latest/advanced.html#context-based-injection) but I cannot find a way to control the instantiation of components depending on the class being injected.

The specific problem I have is that I've created a Serilog's `ILogger` and I would like to set the `SourceContext` [property](https://github.com/serilog/serilog/wiki/Writing-Log-Events#source-contexts) for some of the injected classes, using `logger.ForContext<SomeType>()`. Ideally, I'd like to have something like:

```
var logger = new LoggerConfiguration() ...
container.RegisterFactory<ILogger>(ctx => logger.ForContext(ctx.Consumer.Type))
```

This is supported by [Ninject](https://github.com/ninject/Ninject/wiki/Contextual-Binding) or [Autofac](http://docs.autofac.org/en/latest/faq/select-by-context.html). An specific example containing Serilog/Autofac integration can be found [here](https://github.com/nblumhardt/autofac-serilog-integration/blob/fb73f5bfae863bbbe1716645db7b4fbd998257d3/src/AutofacSerilogIntegration/ContextualLoggingModule.cs#L39).

Are there any plans to support this?

**Comment by dotnetjunkie** [comment]
As you already read in the documentation, the primary way to do these types of registrations in Simple Injector is using the `RegisterConditional` method overoads. The `RegisterConditional` method overloads allow specifying either types conditionally, or contextually. What you want is to register the `ILogger` type unconditionally, but let the type vary based on its context. The `RegisterConditional` extension methods lack an overload that allows you to create a type using a predicate; this is by design. The use of a delegate disallows Simple Injector to do diagnostics and verification; it blinds Simple Injector. Registration of delegates are also often abused to do runtime conditions inside the delegate, which is something we wanted to discourage, since it is bad practice.

The way to typically solve this, is shown in [the section](https://simpleinjector.readthedocs.io/en/latest/advanced.html#context-based-injection) you already referred to. Simple Injector pushes you into supplying types so complete analysis of the object graph can be done for you. This means you should create a generic type that implements the `ILogger` interface.

This however presents us with a problem with Serilog. Its `ILogger` abstraction contains 79 members and creating an implementation for this is very cumbersome and error prone. From a more general point of view, the `ILogger` abstraction is a blaitant violation of the Interface Segration Principle, that guides us into creating narrow and focussed interfaces. `ILogger` neither is narrow, nor focussed. Serilog could have made things much easier for us if it would supply us with a default implementation of `ILogger` that we could override to create a generic implementation for. log4net actually does this with its `LogImpl` class.

I reported [this issue](https://github.com/serilog/serilog/issues/861) at the Serilog forum and asked Nicholas Blumhardt whether I should send a pull request for such a feature. Up until this point in time however, there is no solution and I would not advise you to create your own implementation, because it requires you to write hundreds of lines of code. Yuck!

However, if we take a step back and look at this from perspective of the SOLID principles, we see that it should not really matter that our logging tool violates the SOLID principles. The Dependency Inversion Principle forbids us to let the core layer of our application depend directly on external tools. Instead, the application should be responsible for defining its own abstractions; even logging abstractions.

Take a look at [this Stackoverflow answer](https://stackoverflow.com/a/5646876/264697) that goes into more detail about this.

So instead of registering the abstraction of the external logging library in the container, you should define your own logging abstraction (that that adheres to Interface Segregation Principle) and create an adapter that implements this abstraction and adapts to your external library.

This basically means creating a class as follows:

``` c#

public class SerilogLogAdapter<T> : ILog
{
    private static readonly ILogger logger = Serilog.Log.Logger.ForContext<T>();

    public void Log(LogEntry entry)
    {
        if (entry.Severity == LoggingEventType.Debug)
            logger.Debug(entry.Exception, entry.Message);
        if (entry.Severity == LoggingEventType.Information)
            logger.Information(entry.Exception, entry.Message);
        else if (entry.Severity == LoggingEventType.Warning)
            logger.Warning(entry.Message, entry.Exception);
        else if (entry.Severity == LoggingEventType.Error)
            logger.Error(entry.Message, entry.Exception);
        else
            logger.Fatal(entry.Message, entry.Exception);
    }
}
```

And register it as follows:

``` c#
container.RegisterConditional(
    typeof(ILogger),
    c => typeof(SerilogLogAdapter<>).MakeGenericType(c.Consumer.ImplementationType),
    Lifestyle.Singleton,
    c => true);
```

Do note, that since Serilog is semantic, your application-specific `ILogger` API might need to look a bit different to allow property values to be passed in, as Serilog likes them. Changing the `LogEntry` and the extension methods to support this should be trivial.

**Comment by dotnetjunkie** [comment]
In case creating your own logging abstraction is not feasible at this point in time, Simple Injector's dependency injection behavior can be overridden to achieve the same using Serilog's `ILogger` interface.

The following custom `IDependencyInjectionBehavior` implementation allows intercepting the creation of the `ILogger` abstraction and ensures a contextual logger is created based on the type of the consumer:

``` c#
class SerilogContextualLoggerInjectionBehavior : IDependencyInjectionBehavior
{
    private readonly IDependencyInjectionBehavior original;
    private readonly Container container;

    public SerilogContextualLoggerInjectionBehavior(ContainerOptions options)
    {
        original = options.DependencyInjectionBehavior;
        container = options.Container;
    }

    public void Verify(InjectionConsumerInfo consumer) => original.Verify(consumer);

    public InstanceProducer GetInstanceProducer(InjectionConsumerInfo i, bool t) =>
        i.Target.TargetType == typeof(ILogger)
            ? GetLoggerInstanceProducer(i.ImplementationType)
            : original.GetInstanceProducer(i, t);

    private InstanceProducer<ILogger> GetLoggerInstanceProducer(Type type) =>
        Lifestyle.Singleton.CreateProducer(() => Log.ForContext(type), container);
}
```

The following code snippet shows how to hook this up:

``` c#
var container = new Container();

container.Options.DependencyInjectionBehavior =
    new SerilogContextualLoggerInjectionBehavior(container.Options);
```

That's all. It's just a matter of replacing the default `DependencyInjectionBehavior` with the custom `SerilogContextualLoggerInjectionBehavior`.

**Comment by evvo1961** [comment]
Thanks i follow this but still getting an error on container.Verify() that ILog is not registered.

Not really getting much else back in the way of meaningful error messages

**Comment by dotnetjunkie** [comment]
@evvo1961 which approach did you take? There are multiple approaches in this thread. Do note that there is no ILog in Serilog, so if you took the injection behavior-approach, it only hooks up an ILogger.

**Comment by evvo1961** [comment]
yes sorry ILog is our own interface that implements ILogger

and tried the previous approach, at first it threw an error as i didnt have it as the first registration so did it before all the other registrations but it hasnt seemed to register

**Comment by dotnetjunkie** [comment]
Can you post a minimal reproducible example?

**Comment by wnssi** [comment]
Hi. I am trying to use the Simpleinjector interception method mentioned above in order to have contextual creation of the Serilog logger object to use Log.ForContext in the implementations transparently. The problem I currently experience when the Lifestyle of the service registrations is NOT singleton, then the interception didn't work -> Which means the logger configuration which have been defined during service registration isn't applied. Instead a new logger instance (without configuration) is created.

Currently I have no clue how to make it work for non-singleton lifestyle instances. Does anyone have an idea what could be wrong?

Here is part of my code:

**Interceptor class**

```
public class SerilogContextualLoggerInjectionBehavior : IDependencyInjectionBehavior
{
    private readonly IDependencyInjectionBehavior original;
    private readonly Container container;

    public SerilogContextualLoggerInjectionBehavior(ContainerOptions options)
    {
        original = options.DependencyInjectionBehavior;
        container = options.Container;
    }

    public void Verify(InjectionConsumerInfo consumer) => original.Verify(consumer);

    public InstanceProducer GetInstanceProducer(InjectionConsumerInfo i, bool t) =>
        i.Target.TargetType == typeof(ILogger)
            ? GetLoggerInstanceProducer(i.ImplementationType)
            : original.GetInstanceProducer(i, t);

    private InstanceProducer<ILogger> GetLoggerInstanceProducer(Type type) =>
        Lifestyle.Singleton.CreateProducer(() => Log.ForContext(type), container);       
}
```

**Registration**

```
var container = new Container();
container.Options.DefaultScopedLifestyle = new AsyncScopedLifestyle();
container.Options.DependencyInjectionBehavior = new SerilogContextualLoggerInjectionBehavior(container.Options);
var activator = new SimpleInjectorHubActivator(container);    

// Register logger
string basedir = AppDomain.CurrentDomain.BaseDirectory;
container.RegisterSingleton<ILogger>(() => new LoggerConfiguration()
                .Enrich.WithExceptionDetails()
                .Enrich.FromLogContext()
                .Destructure.JsonNetTypes()
                .ReadFrom.AppSettings()
                .CreateLogger());

container.Register<IServiceA, ServiceAImplementation>(Lifestyle.Singleton); // Work!
//container.Register<IServiceA, ServiceAImplementation>(Lifestyle.Scoped); // DIDN'T WORK!
```

**Comment by dotnetjunkie** [comment]
Hi @wnssi,

I'm not that familiar with Serilog, but it seems that you build up a Serilog configuration, while not using that same configuration to build the logger in your `SerilogContextualLoggerInjectionBehavior` class. Might this be the source of your problem?

In that case, you should pass in the `LoggerConfiguration` into your `SerilogContextualLoggerInjectionBehavior`. This allows you to call `CreateLogger().ForContext(type)`, which will likely solve your problem. Example:

``` c#

public class SerilogContextualLoggerInjectionBehavior : IDependencyInjectionBehavior
{
    private readonly LoggerConfiguration serilogConfig;
    private readonly IDependencyInjectionBehavior original;
    private readonly Container container;

    public SerilogContextualLoggerInjectionBehavior(
        LoggerConfiguration serilogConfig, ContainerOptions options)
    {
        original = options.DependencyInjectionBehavior;
        container = options.Container;
        this.serilogConfig = serilogConfig;
    }

    public void Verify(InjectionConsumerInfo consumer) => original.Verify(consumer);

    public InstanceProducer GetInstanceProducer(InjectionConsumerInfo i, bool t) =>
        i.Target.TargetType == typeof(ILogger)
            ? GetLoggerInstanceProducer(i.ImplementationType)
            : original.GetInstanceProducer(i, t);

    private InstanceProducer<ILogger> GetLoggerInstanceProducer(Type type) =>
        Lifestyle.Singleton.CreateProducer(
            () => serilogConfig.CreateLogger().ForContext(type),
            container);
}
```

And your bootstrapping will be:

``` c#
LoggerConfiguration serilogConfig = new LoggerConfiguration()
    .Enrich.WithExceptionDetails()
    .Enrich.FromLogContext()
    .Destructure.JsonNetTypes()
    .ReadFrom.AppSettings();

var container = new Container();
container.Options.DefaultScopedLifestyle = new AsyncScopedLifestyle();
container.Options.DependencyInjectionBehavior = 
    new SerilogContextualLoggerInjectionBehavior(serilogConfig, container.Options);
var activator = new SimpleInjectorHubActivator(container);

container.Register<IServiceA, ServiceAImplementation>(Lifestyle.Scoped);
```

If that doesn't work, please reduce your problem to a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve). If you get any exceptions, please post their details as well.

**Comment by wnssi** [comment]
Hi @dotnetjunkie 

Thanks for your response! I had almost the same idea to create the Serilog configuration inside the interceptor class - with the difference that the LoggerConfiguration creation also inside the interceptor. Indeed, not a good design.

I think I misunderstand the behavior of CreateProducer. I though that the second parameter (container) is used to retrieve the current registration of ILogger and then being intercepted with Log.ForContext(type). It seems it is not the case. 

I solved the issue in the way that I am going to get the instance of the current registered ILogger and then intercepting it with the ForContext call:

```
public class SerilogContextualLoggerInjectionBehavior : IDependencyInjectionBehavior
{
    private readonly IDependencyInjectionBehavior original;
    private readonly Container container;

    public SerilogContextualLoggerInjectionBehavior(ContainerOptions options)
    {
        original = options.DependencyInjectionBehavior;
        container = options.Container;
    }

    public void Verify(InjectionConsumerInfo consumer) => original.Verify(consumer);

    public InstanceProducer GetInstanceProducer(InjectionConsumerInfo i, bool t) =>
        i.Target.TargetType == typeof(ILogger)
            ? GetLoggerInstanceProducer(i.ImplementationType)
            : original.GetInstanceProducer(i, t);

    private InstanceProducer<ILogger> GetLoggerInstanceProducer(Type type) =>
        Lifestyle.Singleton.CreateProducer(() => container.GetInstance<ILogger>().ForContext(type), container);
        
}
```

In this way everything works as expected without touching the other parts of my code.

Thanks for your help!

**Comment by demonguru18** [comment]
This should work with unity container
`container.RegisterFactory<ILogger>((ctr, type, name) =>
            {
                ILogger log = new LoggerConfiguration()
                             .MinimumLevel.Debug()
                             .Enrich.FromLogContext()
                             .WriteTo.File(Path.Combine(AppDomain.CurrentDomain.BaseDirectory + $"{Path.DirectorySeparatorChar}Logs{Path.DirectorySeparatorChar}", $"error_{DateTime.Now:yyyyMMdd}.txt"),
                                  outputTemplate: "{" +
                                                  "Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} " +
                                                  "[{Level}] " +
                                                  "{SourceContext}" +
                                                  "{MemberName} " +
                                                  "{Message}" +
                                                  "{NewLine}{Exception}")
                             .CreateLogger();
                return log;
            }, new ContainerControlledLifetimeManager());`

Controller

`public class TestController : ApiController
    {
        private readonly ILogger _logger;

        public TestController(ILogger logger)
        {
            _logger = logger.ForContext<TestController>();
        }


        [HttpGet]
        public IHttpActionResult GetResult()
        {
            _logger.Information("This is test");
            return Ok("Test Succeeded");

        }
    }`

**Comment by sguryev** [comment]
Hi @wnssi , @dotnetjunkie .
Thank you for the great samples.

I have a combination of the Serilog and default .NEt dependency injector in ASP.NET Core 3.1 application.
I'm trying to avoid injection `ILogger<T>` in each controller/service and would like to simplify it to `ILogger` with passing a context from hosted object. 

Do you think default IoC in ASP.NET Core has some way to implement it without any custom logging abstraction?

**Comment by dotnetjunkie** [comment]
> Do you think default IoC in ASP.NET Core has some way to implement it without any custom logging abstraction?

I'm sorry @sguryev, but the Simple Injector forum is not the right place to ask questions about ASP.NET Core's default IoC Container. You might try raising a question on Stack Overflow instead.

If you have any questions specifically about Simple Injector, please let me know.
