### ISSUE TITLE
IAuthorizationHandler asp.net core

### ISSUE THREAD

**Issue by kaagati** [simpleinjector/SimpleInjector#297]
I am trying to use custom policy handler in asp.net mvc core. 

``` cs
public class AbcPolicyRequirement : IAuthorizationRequirement { }

public class AbcPolicyHandler : AuthorizationHandler<SupplierPolicyRequirement>
{
    protected override Task HandleRequirementAsync(AuthorizationHandlerContext context,
        SupplierPolicyRequirement requirement)
    {
        context.Succeed(requirement);
        return Task.FromResult(0);
    }
}
```

It works when i try to register instance of `IAuthorizationHandler`

``` cs
public void ConfigureServices(IServiceCollection services)
{
    //works when adding this to service collection
    services.AddSingleton<IAuthorizationHandler, SupplierPolicyHandler>();
    services.AddSingleton<IControllerActivator>(
        new SimpleInjectorControllerActivator(container));
    services.AddSingleton<IViewComponentActivator>(
        new SimpleInjectorViewComponentActivator(container));
    services.RegisterPipelineServices(this.Configuration, 
        typeof(IServicePipeline).GetTypeInfo().Assembly);
}
```

**but** if the same thing is registered in SimpleInjector Container, it does not work,

``` cs
public class AuthorizationHandlerModule : IModule
{
    public void RegisterServices(Container container)
    {
        container.RegisterSingleton<IAuthorizationHandler,AbcPolicyHandler>();

        // container.RegisterCollection<IAuthorizationHandler>(
        //    new Assembly[] { this.GetType().GetTypeInfo().Assembly });
    }
}
```

The problem I think is the ServiceCollection is not aware of what is registered in the container. 

When I follow the doc I can see only Controller and View component activation logic is integrated like so. Nothing is specified for AuthorizationHandler. 

``` cs
public void Configure(IApplicationBuilder app, IHostingEnvironment env, 
    ILoggerFactory loggerFactory)
{
    app.UseSimpleInjectorAspNetRequestScoping(container);
    container.Options.DefaultScopedLifestyle = new AspNetRequestLifestyle();
    container.RegisterMvcControllers(app);
    container.RegisterMvcViewComponents(app);
    CompositionRoot.Init(container, app);
    container.Verify();
}
```

**Comment by dotnetjunkie** [comment]
You probably want to inject some dependencies into your `AbcPolicyHandler`, because it needs to run some business logic. Since `IAuthorizationHandler` is an abstraction that is handled by the framework, you need to create an adapter that can forward the call to components that are registered in Simple Injector. You can do this with the following code:

``` c#
public sealed class SimpleInjectorAuthorizationHandler : IAuthorizationHandler
{
    private readonly Container container;
    public SimpleInjectorAuthorizationHandler(Container container) { this.container = container; }

    public Task HandleAsync(AuthorizationHandlerContext context) =>
        foreach (var handler in this.container.GetAllInstances<IAuthorizationHandler>())
            await handler.HandleAsync(context);
}
```

You can register this adapter as follows:

``` c#
services.AddSingleton<IAuthorizationHandler>(new SimpleInjectorAuthorizationHandler(container));
```

By doing so, you allow `IAuthorizationHandler` implementations to be registered in Simple Injector as follows:

``` c#
container.RegisterCollection<IAuthorizationHandler>(new Type[] { /* list of handlers */ });
```

This however will cause your application code to take a dependency on the `IAuthorizationHandler` interface, which is a specific to the AspNetCore presentation framework. This is a problem since we typically don't want any business logic to take a dependency on code from our presentation framework. If you are concerned about this SOLID violation, please read on.

The adapter approach would have made it trivial to remove this unwanted dependency, except for the existence of the `IAuthorizationRequirement` [marker interface](https://github.com/aspnet/Security/blob/34ee0212d0c6de76a40609b70df77545dbdde3bf/src/Microsoft.AspNetCore.Authorization/IAuthorizationRequirement.cs). This interface is a design flaw and shouldn't have existed. It forces simple DTOs to require a dependency on a framework. I created [an issue](https://github.com/aspnet/Security/issues/977) for this on the aspnet/security forum, but don't expect it to be fixed soon (or ever).

So to work around this, we can create a wrapper DTO for our custom authorization requirements (let's call them policies), as follows:

``` c#
// IAuthorizationRequirement wrapper class fro BL policy DTOs.
public sealed class PolicyAuthorizationRequirement : IAuthorizationRequirement
{
    public readonly object Policy;
    public PolicyAuthorizationRequirement(object policy) {
		if (policy == null) throw new ArgumentNullException(nameof(policy));
        this.Policy = policy;
    }
}
```

This allows us to define our requirement DTOs without the need to know about ASP.NET Core:

``` c#
// DTO in business layer. Note that it lacks the IAuthorizationRequirement
public sealed class MinimumAgePolicy
{
    public readonly int MinimumAge;

    public MinimumAgePolicy(int age) { MinimumAge = age; }
}
```

Now we can make the policy registration as follows:

``` c#
public void ConfigureServices(IServiceCollection services)
{
    services.AddMvc();

    services.AddAuthorization(options =>
    {
        options.AddPolicy("Over21", policy => policy.Requirements.Add(
            new PolicyAuthorizationRequirement(new MinimumAgePolicy(21))));
    });
}
```

With this in place we have our application-specific policy interfaces that are possibly designed much different than the ASP.NET counter parts. For instance:

``` c#
public interface ISecurityValidator<TPolicy>
{
    void Validate(TPolicy policy);
}
```

With this in place we can create an adapter that adapters to our `ISecurityValidator<TPolicy>` abstraction:

``` c#
public sealed class AuthorizationHandlerToSecurityValidatorAdapter : IAuthorizationHandler
{
    private readonly Container container;
    public AuthorizationHandlerToSecurityValidatorAdapter(Container container) {
        this.container = container; 
    }

    public Task HandleAsync(AuthorizationHandlerContext context)
    {
        try
        {
            foreach (var req in context.Requirements.OfType<PolicyAuthorizationRequirement>())
            {
                object policy = req.Policy;
                Type validatorType = typeof(ISecurityValidator<>).MakeGenericType(policy.GetType());
                foreach (dynamic validator in this.container.GetAllInstances(validatorType))
                    validator.Validate(dynamic)policy);

                context.Succeed(req);
            }            
        }
        catch (SecurityException ex)
        {
            context.Fail(ex.Message);
        }
		
        return Task.FromResult(0);
    }
}
```

This adapter maps any defined policies using the `PolicyAuthorizationRequirement` to the business layer-specific `ISecurityValidator<T>` abstraction.

Depending on your application and its needs, you might even take it one step further. Perhaps your application can work without controllers altogether (as described in [this article about WCF](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=95)). This especially works well for SPAs where there is no MVC on the server side (thus no view generated on the server); only a Web API. In that case you only need [command](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=91) and [query](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=92) objects, and when you do this, you can mark your command and query DTOs with attributes that define roles, permissions, policies or authorization requirements. [This discussion](https://simpleinjector.codeplex.com/discussions/566865) shows several approaches you can take to implement these kinds of requirements.

Good luck.

**Comment by chispaK** [comment]
Good day Steven:

I am a bit late to the game here but please can you explain a bit more about the usage of the AuthorizationHandlerToSecurityValidatorAdapter.

Would this handler be the single entry point for all PolicyAuthorizationRequirement to be handled?  

As for registration would be registering

`services.AddSingleton<IAuthorizationHandler>(new AuthorizationHandlerToSecurityValidatorAdapter(container));`

`container.RegisterCollection(ISecurityValidator<>, new Assembly[] { this.GetType().GetTypeInfo().Assembly });`

**Comment by dotnetjunkie** [comment]
> Would this handler be the single entry point for all PolicyAuthorizationRequirement to be handled?

Correct.

> As for registration would be registering

Your registration seems correct.

**Comment by chispaK** [comment]
Thanks a lot for the update. It works as expected as well.
