### ISSUE TITLE
Simple Injector throwing an error when I try to unit test a bootstrap that calls RegisterPackages

### ISSUE THREAD

**Issue by cjhoward92** [simpleinjector/SimpleInjector#300]
Hello all,

I am using .NET 4.5 in Visual Studio 2015 and I am getting an odd error. I have one IPackage out there that I use for dynamic registration at runtime, so naturally in my bootstrap routine I have the container.RegisterPackages(); routine. When unit tesiting with xUnit 2.1 I get a weird error.

```
Could not load file or assembly 'Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

Like I said, I simply call:

`container.RegisterPackages();`

My unit test looks like so

```csharp
[Fact]
public void Verify()
{
    var container = Program.Bootstrap();
    container.Verify();
    Assert.True(true);
}
```

Simple Injector Version 3.2.2
xUnit Version 2.1.0.3179

If there is anything else I can provide for you, let me know. I just found this odd. 

A workaround is to specify the assemblies in the RegisterPackages routine, so that is what I am doing. 

This is only an issue with Unit Tests, it works fine from Debug or Release mode in a normal execution environment.

**Comment by dotnetjunkie** [comment]
This typically happens when a loaded assembly in your appdomain refers to an assembly that is not present. In this case Microsoft.VisualStudio.TestPlatform.ObjectModel is not present. There's not much you can do about this, but specifying the assemblies explicitly, which in general is a good idea to do, since using AppDomain.CurrentDomain.GetAssemblies (what the default RegisterPackages overload calls under the covers) is very undeterministic.

**Comment by cjhoward92** [comment]
Thanks, that makes sense.
