### ISSUE TITLE
Async/Await-safe per request lifestyle in .Net Core

### ISSUE THREAD

**Issue by corey-waymark** [simpleinjector/SimpleInjector#311]
Apologies if you have already answered this question (or it is a bad one), after reading the docs and trying the lifestyles I couldn't get anything working right.

I'm trying to set up SI in an existing .net core application, which heavily uses async/await, and has many services which need to be created per request. Using AspNetRequestLifestyle I get exceptions due to services being disposed (deep in an async workflow). I know I can use BeginExecutingContextScope(), but every method used by my controllers is asynchronous, so I would have to wrap every controller.

Is there an easy way to have the best of both worlds, with new services created per request, but maintained through an async/await workflow? I found a HttpModule example, but that isn't applicable in core.

If there is an obvious solution (given how common I imagine this issue should be) could the docs surrounding .Net Core integration be updated?

**Comment by dotnetjunkie** [comment]
If you followed the [integration guide](https://simpleinjector.readthedocs.io/en/latest/aspnetintegration.html), every request is wrapped with an execution context scope. Both `AspNetRequestLifestyle` and `ExecutionContextScope` are designed to work in asynchronous situations, so if you are seeing your objects being prematurely disposed, it is very likely that you are **not running code asynchronous, but in parallel**. In other words, you are not using `await` on your asynchronous methods (or you have `void` methods that spin up new `Task`s); doing so will cause code to run in parallel, which is typically not what you want, since this means that your objects (like `DbContext`) must be safe to be accessed concurrently (they need to be thread-safe).

In case you deliberately start background operations that might finish after the web request is finished (which can happen when you don't synchronize them at the end of the request), you need to explicitly wrap that background operation within its own `ExecutionContextScope`. If this causes calls to `container.BeginExecutionContextScope` to be sprinkled out over your code base, you are doing something wrong. Your design should allow you to define a single place (preferably a decorator) where you define such scope for background operations.

**Comment by corey-waymark** [comment]
Is the line in question <code>app.UseSimpleInjectorAspNetRequestScoping(container);</code>? I've got that, so it must be some issue with my code. 

Thanks for the quick reply - could I request a comment on the integration guide for that line? It's not mentioned on that guide or in the lifetimes section, and so was unclear (at least to me) that this is automatically done.

**Comment by dotnetjunkie** [comment]
> Is the line in question app.UseSimpleInjectorAspNetRequestScoping(container);?

Yes, this line ensures requests are wrapped in a scope.

> could I request a comment on the integration guide for that line?

I'm not sure whether that would help. I would say the method name `UseSimpleInjectorAspNetRequestScoping` is as clear as it gets; not sure what a comment would add. And besides, if you remove this line, Simple Injector will throw a very clear exception message once you resolve an object graph consisting of a scoped component. But if you have any suggestions for what text to add to the documentation, please do.
