### ISSUE TITLE
Add .snk file to repository

### ISSUE THREAD

**Issue by dotnetjunkie** [simpleinjector/SimpleInjector#315]
The Simple Injector repository does not include the strong name key, which is used to build Simple Injector. The .snk file is omitted to prevent developers from creating a signed version of Simple Injector. Although it is still possible for them to create an alternative version of the code base (with some custom patches for instance), it disallows them to use their custom version in combination with other NuGet packages that refer to the (correctly) signed version of Simple Injector.

We should commit the simpleinjector.snk file.

**Comment by TheBigRic** [comment]
You would have had a perfectly fine reason why you didn't commit this file. I myself never used signing because I found this process to be quite a big PITA the last time I tried... Which was maybe in VS2008 :-)...

Problem ofcourse is, without this file, a developer is searching for 30 minutes to find out what is going wrong. In the end is deleting all references to this file the only workable solution to get everything building. And that is rather strange for an open source project IMO. 

So is the argumentation to omit the file still correct and if so, is there maybe a simple solution to sign the assembly after build time? In this case the core test project doesn't need to be signed and the `InternalsVisibleTo` attribute can be simplified.

Or maybe their can be a project.debug.json which doesn't reference the .snk file, whereas the .release version does?

**Comment by dotnetjunkie** [comment]
In the past we were told that signing is important for security, but this argument seems not really strong. Many open-source projects don't even publish a signed version of their assemblies at all. Not having a signed version however has its own set of problems.

Publishing the snk has a few disadvantages:

 - In case an attacker would get access to the Simple Injector NuGet account (or the API key), the release of an infected version of Simple Injector would be more successful when it was signed with the same key.
 - It would make us loose the authority of being the only one who can release and publish new versions of Simple Injector.
 - Once published, a snk file can never be 'unpublished', just as dick pics will never go offline again.

Perhaps there are more disadvantages that I'm not aware of right now.

**Comment by TheBigRic** [comment]
> It would make us loose the authority of being the only one who can release and publish new versions of Simple Injector.

This is only the case if someone would gain control over the NuGet account and/or GitHub account, isn't it? These are the only reliable places where someone would download a version if he/she is smart enough. Publishing the package somewhere else is not a realistic scenario. Someone who want's to use Simple Injector as some sort of infections would want to publish in one of the official places because otherwise he will not reach a broad enough audience for doing his dirty things. 

Some reading online tells me NuGet doesn't even check the signing of the assembly when it updates the package.  Which effectively means that without the private key someone with the NuGet account details can publish a version of Simple Injector, not being signed at all. This will only break usercode who strongly sign their own assemblies which consume Simple Injector. Weakly signed packages (like mine and probably most non framework developers) don't even care. They will just update the package and build.

A quote from [MSDN](https://msdn.microsoft.com/en-us/library/wd40t7ad(v=vs.110).aspx):
> If you are an open-source developer and you want the identity benefits of a strong-named assembly, consider checking in the private key associated with an assembly into your source control system.
 
The only thing that still stands is that a user will be able to check if the assembly was published by the Simple Injector team. As it stands, this seems to be the only reason for strong signing NuGet packages. So you still can decide to make the .snk not a part of the repository but give/send it to users who signed the 'Contributor License Agreement'.

**Comment by dotnetjunkie** [comment]
Okay, let's postpone the decision to publish the .snk files. Instead let's try to fix the building problem that appeared after I added the .NET Core projects. In the Core projects, the project.json contains a hard reference to the .snk file and internal visibility is enabled by specifying the public key. In the existing projects, reference to the .snk file is done using an attribute, and the signing was done using a compiler directive, which allowed anyone to compile the code base when they didn't use the `PUBLISH` compiler directive. Unfortunately, this code based attribute has been deprecated, but we might be able to find a different way to achieve the same.

**Comment by TheBigRic** [comment]
Instead of signing the library through settings in VS, csproj, etc., we could remove that altogether and sign the application only in the [build script](https://github.com/simpleinjector/SimpleInjector/blob/master/src/build.bat). I make a big assumption here that you use this script only for building a new release...?

From the [command line reference of msbuild](https://msdn.microsoft.com/en-us/library/ms164311.aspx) I see that you can use `/property:Name=value` which sounds to me you can place here any property you normally would have in your csproj PropertyGroup's. And although project.json don't use property groups anymore I think msbuild will still allow you to do this?

**Comment by dotnetjunkie** [comment]
In the past I actually did the signing in the build script, but I moved away from this, because of... problems. I'm not sure anymore what problems I had, but because of these problems I moved to using attributes in the code base with compiler directives. This worked out great, until ofcourse the addition of the new Core projects.

**Comment by borrrden** [comment]
I'm mulling over this myself and just think that I should put this out there:

Nobody uses (or should use) strong name for security purposes, and to expect such a thing is foolish.  The only reason they exist is to give an assembly a more specific name than just "name of assembly".  That's why half the development world publishes their private keys and the other half just doesn't even bother signing.  It's become basically a dinosaur in this day and age.  It's only relevant to full .NET framework combined with stuff like GAC and trusted app domains.  

The official recommendation from [.NET documentation](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming#create-strong-named-net-libraries) is to 

✔️ CONSIDER strong naming your library's assemblies.

✔️ CONSIDER adding the strong naming key to your source control system.
