### ISSUE TITLE
Identity framework causing trouble for non-conformers

### ISSUE THREAD

**Issue by dotnetjunkie** [simpleinjector/SimpleInjector#328]
This is a question to @ciel, who stated:

> For me, the biggest problem with both Ninject, Castle, and SimpleInjector kept boiling down to the Identity framework. I know there are other concerns, but I was able to get most of them to do something right beyond the Identity framework. But getting that wired just didn't work. By the time I got the information to do cross wiring, it seemed pointless.

@ciel, I would like to hear from you what troubles you ran into. This information is very valuable. This allows us to simplify the integration of tools like Simple Injector, Ninject and Castle into the new ASP.NET Core chain. It might also help us communicate with framework and library builders (like the designers of Identity framework) how they can improve their tool to make it easier for anyone to use their tool.

**Comment by ciel** [comment]
The Identity Framework just has a lot going on under the hood that is frustrating to work with. For example, in my `IUserStore<T>` implementation, I inject `IAsyncDocumentSession` from `RavenDB` so it can obviously get the users and such.

Well, with SimpleInjector, this was a headache and a half. The explanations for cross-wiring really only work if you use the default implementations, as just cross-wiring `IUserStore<T>` wasn't enough. Now, I had to make sure that the database injection was __also__ handled by Microsoft's built in DI framework.

With __only__ that one constructor parameter being injected, I eventually had to cross-wire 17 different components just to make sure that part worked. By the time I was finished, it became a moot point to even use SimpleInjector because the built in DI was already forcing me to implement it there. Over 90% of SimpleInjector was having to use cross-wiring.

Again, that was with __1__ constructor parameter in __1__ place. I just gave up when it also started wanting more and more of these "silent" dependencies buried in the Identity framework. It was taking too much time, and the gain simply wasn't worth it. I think I spent a good 14 hours trying to get everything to work and never did.

**Comment by dotnetjunkie** [comment]
This is very interesting finding. Can you show some code with what you ended up doing. This allows me to get a better view of the problem at hand.

**Comment by ciel** [comment]
I never did it get to work. I simply abandoned SimpleInjector for the time being. The only one I've gotten to work so far is StructureMap, and I'm not really thrilled with it. 

It could also be argued that it's partially my fault for putting a dependency into the `IUserStore<T>` implementation. But, I don't use entity framework - I don't pass a `DbContext` around. I'm pretty accustomed to everything not working for me, since I use such a non-standard database system. But it was still really disheartening.

The main reason I needed SimpleInjector was to deal with resolving dependencies for `Hangfire`, because the objects it deserializes don't have any concept of the `HttpContext`, and therefore the dependencies need to be resolved through an adapter - and the samples on their own website don't work.

For me, it always keeps coming back to the Identity system. I can get everything else to work, but that damn Identity framework wiring just keeps throwing new wrenches. 

Off the top of my head, the dependencies I had to cross-wire...
`ILookupNormalizer`, `IPasswordHasher`, `IPasswordHasher<T>` (yes, both). `IPasswordValidator`, `IPasswordValidator<T>`, `IUserStore<T>`, `IRoleStore<T>`, `UserManager<T>`, `SignInManager<T>`, `IUserLoginStore<T>`, `IUserPasswordStore<T>`, `IUserRoleStore<T>`, `IUserSecurityStampStore<T>`, `IUserClaimStore<T>`, `IUserLockoutStore<T>`, `IUserTwoFactorStore<T>`, `IUserEmailStore<T>`, `IdentityOptions`, `IOptions<IdentityOptions>` (both, again), and there were about 12 others I can't quite recall.

Obviously it's doable. It's just a lot of plumbing.

**Comment by ciel** [comment]
I will add, I had to implement all of those interfaces, even though the only ones I used were `IUserStore<T>` and `IRoleStore<T>`.

**Comment by ciel** [comment]
The problem at hand is that too much is abstracted away and hidden under the rug, with the Identity system. I'm sure people using MS-SQL, Entity Framework, and default schemas appreciate it, but it's been very troublesome for us.

**Comment by ciel** [comment]
I'm about to board a plane. But later, I'll look and see if I saved any of it so I can show you. I'd still prefer to switch over to SimpleInjector.

**Comment by TheBigRic** [comment]
@ciel, @dotnetjunkie  
I don't have any experience with Identity for .Net Core, but I do have quite some experience with Identity for MVC 5. If you ever used this, with your own DI container, you quickly understand why this is such a problem. 

Identity is IMO a PITA if you want to do anything out of the default implementations given in the Identity NuGet package AND without the use of the crappy template you get 'for free'. It only just works in MVC 5 because their is a shitload of code in the template, but if you try to make the controllers etc. clearly organized or try to replace the DB for example things start to become pretty nasty very soon. 

Just because .Net Core now offers a built-in DI pipeline it seems like Identity is pretty easy to setup. But ofcourse under the covers Identity is the same bigass to setup as before. IUserStore<T> is one big SOLID (especially S, L and I) violation and replacing this thing is a project in its own. The Liskov violation is pretty nasty because the default UserManager<T> implementation expects IUserStore also implements: 
IUserLoginStore<TUser, TKey>,
IUserClaimStore<TUser, TKey>,
IUserRoleStore<TUser, TKey>,
IUserPasswordStore<TUser, TKey>,
IUserSecurityStampStore<TUser, TKey>,
IQueryableUserStore<TUser, TKey>,
IUserEmailStore<TUser, TKey>,
IUserPhoneNumberStore<TUser, TKey>,
IUserTwoFactorStore<TUser, TKey>,
IUserLockoutStore<TUser, TKey>

Implementing all these interfaces, just because you do not want to use EF directly, or whatever smallest change you want (different table name, different column name, different constraints), is real nasty because you have to implement 49! public methods/properties. And because UserManager has some expectations on the results, implementing these methods can't be done without looking at the source of UserManager<T>.

So with or without DI, built .Net Core DI, Identity will bite you anyway!

So, a while ago I took a complete different angle on this subject:
Why do we want to use Identity in the first place? Just because we want to do authentication, which is in basis nothing more than generating a secure cookie based on a matching password between the login attempt and the database. The whole build-in user management is something that is very simple to implement yourself and in my case, this was something that was already done (using truly SOLID patterns!).

So the only part you really need is `IAuthenticationManager`. I don't do third party logins, so maybe you need something more in that case, but this will at most be some small parts.

I will, depending on available time, approval of my manager and some other things, post my general code to get things working.

Notice that Identity has in total over 2000 lines of code and my total implementation (including user management)  consists of 350 lines of code...

**Comment by ciel** [comment]
I didn't find implementing the interfaces hard, just tedious.

**Comment by TheBigRic** [comment]
I think hard is besides the point. No it is not hard, it is even rather boring work. But a lot of work.

The point is, there are a lot of design flaws in Asp.Net identity. Especially when it comes to applying DI. The reason DI is so hard, with or without .Net core, is because of this design flaws.

That's why I took the direct solution to create an implementation myself.

**Comment by dotnetjunkie** [comment]
I think we all agree on this that the design of Identity Framework is the source of the problems here. Identity Framework has got a terrible track record with design, so I’m not surprised that this is still a problem with the Core version.

When you need that many cross-wired dependencies however, this is a red flag for me. Hooking in your application container should usually be doable without this amount of plumbing; even with Identify Framework. With the amount of plumbing you are having, you are basically rewiring Identity Framework's complete configuration to your application container.

I constantly see developers take the wrong route on this, and as I see it, this is caused by Microsoft who is blurring our view by solely showing examples using the Conforming Container model. This makes it really hard to look at this problem from a different angle, which is required when you plugging in an application-specific container.

I can't really see where you 'went wrong', but here are some tips that might help:

 - You can cross-wire in two directions. You can also replace a registration of the built-in container and redirect it to Simple Injector and let your application container build things up.
 - You can create an adapter implementation for a given framework interface that you register inside your application container and forwards the calls to the built-in container. This does require the library/framework to have specified narrow (role) interfaces. If you have to implement a dozen of members, the library/framework is designed poorly and this will cause you grief.

**Comment by ciel** [comment]
Okay, I am back home, and have had the last week to think about this subject in detail. 

I'll start by saying **I am not very experienced with dependency injection**. I've been programming for 20 years, but I'm still a rookie by **many** standards. A lot of the talk in the other threads about dependency injection goes **way** over my head.

So, to preface, this is my perspective **as an average user/programmer trying to get it to _work_**.

The problem keeps coming back to **Identity**, and it isn't necessarily a problem with how Identity is implemented, it is a problem with how many _hidden_ dependencies exist for it. I think this is ultimately where the issue lies - from what I have dug up, and researched (which is admittedly not as much as I'd have liked), it seems the overall answer to this problem has been **cross-wiring**.

From observation, the problem with cross-wiring is usually rooted in implementation and scope. For example, **everything** vs .NET's own `AddScoped`. I haven't seen a lot that suggests the .NET `AddScoped<T,R>` is **bad**, but rather that the incompatibilities with everything else make it caddywhompus to work with.

This seems to have led to the problem of the **[Conforming Container anti-pattern](http://blog.ploeh.dk/2014/05/19/conforming-container/)**, which seems to be Microsoft's "answer" to the problem. I've read the blog post in question, and I honestly can't pretend to fully grasp it, but from what I can gather, conforming container isn't generally accepted as the right way to go.

So, I think I'm caught up. Please let me know if I'm missing anything. I'm trying very hard to comprehend what all is happening in this playing field, it's all very new to me.

I think the biggest problem is that the Microsoft approach just hides too much for convenience, and it's just a huge trial/error process of getting things wired up, and it takes a long time.

**Comment by dotnetjunkie** [comment]
Hi @ciel, I would really like to get my hands on your configuration to see what it is you tried (and failed) to accomplish. What Identity services do you actually need in your application? How did you wire things up? How does your application interact with Identity?

I can understand if you won't be able to publically publish such thing, but feel free to send me a mail (steven -> cutting edge dot it) with details. Perhaps you're able to send a stripped down project of some kind that shows your configuration without disclosing any company sensitive code.

From this private discussion we can extract a solution that we might be able to make public.
