### ISSUE TITLE
Questions about open generic registration

### ISSUE THREAD

**Issue by maca88** [simpleinjector/SimpleInjector#329]
Hi,

I've recently ported the IoC library in a framework that I'm using for my work projects to Simple Injector. 
Previously I was using Ninject, but as it is not developed anymore I decided that is time to switch it.

The framework that I ported supports multiple databases by using NHibernate, each database is registered by using a keyed registration (except the default one).
Implementing a keyed registration in Simple Injector is quite easy and it works well for simple registrations. 
So the following example works like a charm:

``` c#
public class HomeController {
    public HomeController(ISession defaultSession, [Database("bar")]ISession barSession) {
    }
}
```

The problem arise when I want to register a keyed conditional open generic registration like this one:

``` c#
container.RegisterConditional(typeof(IRepository<>), typeof(Repository<>), 
    Lifestyle.Scoped, 
    o => !o.Handled);
```

where Repository is:

``` c#
public class Repository<TEntity> : IRepository<TEntity> {
    public Repository(ISession session) {
        Session = sesion;
    }
    
    protected ISession Session { get; }
    ...
}
```

Extending Simple Injector to support a keyed open generic registration would involve the use of reflection or coping a bunch of internal classed from the source like IRegistrationEntry, please correct me if I'm wrong.
Instead of implementing my own generic keyed registration for the `Repository<>`, I wrapped the default one and replaced the Session property after the creation.
[The approach that I took](https://github.com/maca88/PowerArhitecture/blob/master/Source/PowerArhitecture.DataAccess/Package.cs#L202) has a drawback that all repositories must be registered as transient, as it uses the same registration for keyed and non keyed registrations.

Here is an example of injecting two repositories for a model that exists in both databases:

``` c#
public class HomeController {
    public HomeController(
        IRepository<SharedModel> defaultRepository, 
        [Database("bar")]IRepository<SharedModel> barRepository) {
    }
}
```

I'm wondering if there is a better alternative to have the repositories registered with a scoped lifestyle?

I also have have a problem that would be reflected to the Repository<> if it would be scoped.
Here is a failing test that I'm unable to resolve:

``` c#
[Test]
public void GenericValidatorMustBeSingleton() {
    var validator = Container.GetInstance<IValidator<Model>>();
    var validator2 = Container.GetInstance<Validator<Model>>();
     
    Assert.AreEqual(validator, validator2);
}
```

where the registration is:

``` c#
container.RegisterConditional(typeof(IValidator<>), typeof(Validator<>), 
    Lifestyle.Singleton, 
    o => !o.Handled);
```

The test will fail as only `IValidator<Model>` is injected as a singleton. I've tried the approach that works for non generic registrations:

``` c#
var registration = Lifestyle.Singleton.CreateRegistration(typeof(Validator<>), container);
container.RegisterConditional(typeof(IValidator<>), registration, o => !o.Handled);
container.RegisterConditional(typeof(Validator<>), registration, o => !o.Handled);
```

but does not work for open generic.

One possible solution would be to make the `Validator<>` internal so that the developed could not inject it, but is not possible with this case as the validator can be extended by the developer to create a custom one.
The perfect solution to me would be an api to prevent the developer from injecting a `Validator<>`, for example:

``` c#
var registration = Lifestyle.Singleton.CreateRegistration(typeof(Validator<>), container);
registration.PreventConcreteTypeInjection(
    "Injection of Validator<> is not allowed, use IValidator<> instead.");
container.RegisterConditional(typeof(IValidator<>), registration, o => !o.Handled);
```

Is there maybe a different solution that I missed out?

**Comment by dotnetjunkie** [comment]
So, if I understand you correctly, you wish to mark the `IRepository<T>` constructor arguments with a `DatabaseAttribute`, and inject the `ISession` dependency conditionally into the `Repository<T>`, based on the value of the decorated `DatabaseAttribute`.

I imagine this looking something like this:

``` c#
new HomeController(
    defaultRepository: new Repository<SharedModel>(
        new DefaultSession()),
    barRepository: new Repository<SharedModel>(
        new BarSession());
```

Furthermore, you want to register these repositories as scoped, while you now only can register them as transient.

You effectively worked around a limitation in Simple Injector. While doing conditional registrations, Simple Injector only allows making decisions based on the direct consumer (parent) of the registration. You wish to look ahead one level up: you wish to make the `ISession` conditional based on information presented in the consumer of the `IRepository<T>`.

We had many internal discussions about this and decided not to allow to do walk the consumer stack, because this could easily lead to bugs that are very hard to find by the user and impossible for Simple Injector to detect.

One of the reasons why making decisions based on the consumer’s consumer is a bad idea, because this breaks down quickly in case lifestyles are not transient. And you already noticed this. So to answer your question: no, it is technically impossible to make your repository registration scoped, while preserving the conditional wishes of the dependency. To make it a bit more concrete, let’s take a look at the following example:

``` c#
public HomeController(Service1 s1, Service2 s2)
public Service1([Database(“foo”)] IRepository<X> r)
public Service2([Database(“bar”)] IRepository<X> r)
```
If we were to resolve the `HomeController` where we stated that the `IRepository<X>` should be resolved as `Scoped`, this would force Simple Injector to inject the same instance in both `Service1` and `Service2`. Because they both reference the same instance, it would be impossible to give each service its own conditional `ISession`.

Ninject actually allows walking the consumer stack all the way up to the root object being resolved. But as said before, this breaks down immediately when non-transient lifestyles are used. So this isn’t a Simple Injector problem, you see the same with Ninject as well. I’ve seen quite a lot developers who were completely confused and lost because of this.

So long story short, you effectively worked around a deliberate limitation of Simple Injector that exists to protect you as a user.

In general, I found out that most of the time when users (and I had this myself on my own applications as well) wanted this behaviour, something was wrong with the design. I find it hard to check whether this is the case in your case, because of the lack of context, but the thing that I wondered after reading the first paragraph of your question was: “Isn’t this design violating the Liskov Substitution Principle?”.

The Liskov Substitution Principle (LSP) tells us that any subtype of a given abstraction, should be interchangeable for one another, without causing the consumer of that abstraction to break. The abstractions we should consider in this question are of course `ISession` and `IRepository<T>`.

You would typically break the LSP when you reuse the same `ISession` abstraction to communicate with different database schemas. You can typically switch database instances without trouble, as long as they contain the same schema. Once you have a different schema (different table structures) the consumers typically expect a particular schema. For instance, a `ShipOrderHandler` expects the database that contains the `Orders` table. Letting it talk to the `CRM` database will obviously not work.

The LSP dictates that in case you can’t swap out implementations without breaking the consumer, the implementations do not belong to the same abstraction.

Again, I’m not sure whether this hold in your case, but if this is the case, you might need an `IBarRepository<T>`. Having such extra abstraction does solve the problem elegantly, because this makes the DI configuration a no-brainer (while you currently have a lot of trouble getting it right). It also prevents the use of attributes; attributes are completely untyped. It also makes it easier for the reader of the code; he immediately knows what the abstraction does.

**Comment by maca88** [comment]
Steven, firstly I would like to thank you for the deep explanation, very appreciated.

The main idea was to have a simple system to interact with multiple databases where each database has its own `ISessionFactory` so the `ISession` is not reused for different databases. A `ISession` is reused only within the same scope for repositories that represents the database where `ISession` belongs. For example lets take a look on a concrete example:

We have two databases "foo" and "bar" where both contains the same informations but the database schema is different, so our job is to create a service that will synchronize "bar" database with "foo"
```
public class SyncService {
	public SyncService(IRepository<FooModel> fooRepo, IRepository<BarModel> barRepo) {
		foreach(var fooModel in fooRepo.GetAll()) {
			barRepo.Save(new BarModel {
				Name = fooModel.Model,
				...
			});
		}
	}
}
```
In the above example each repository will have its own `ISession` that belongs to a different `ISessionFactory`. The implementation type for both `IRepository<>` is the `Repository<>` described in the first post.
In this example there is no need to have the Database attribute as we know by the mappings on which ISessionFactory the model belongs. In the first post the attribute was needed because the database schema was the same. 

Your proposal of having a `IBarRepository<>` is a great alternative than having an attribute when dealing with multiple databases with the same schema, as I agree with you that having an attribute for a parameter is nasty. I'll add it on my todo list, thanks! 

To keep it short, my point was to have a plug & play system that will work with many scenarios as possbile, so that the end developed does not need to care if the `ISession` in that repository is the correct or not, that should be automatically handled. The first question that I asked was just for curiosity to know if there are some better alternatives and I got the answer, thanks again.

What about the second question, how can I achieve that `IValidator<Model>` will be equal to `Validator<Model>` when injecting them both?

**Comment by dotnetjunkie** [comment]
> We have two databases "foo" and "bar" where both contains the same informations but the database schema is different

This is a great example of where you are violating the Liskov Substitution Principle. Swapping the injected dependencies will break your application, since they both use a different schema. Reusing the same abstraction makes it very easy to break the application, while you could have leaned on the compiler.

> A ISession is reused only within the same scope

The LSP isn't about reusing instances, it's about reusing one abstraction in incompatible contexts which I believe is the case here.

> Your proposal of having a IBarRepository<> is a great alternative than having an attribute when dealing with multiple databases with the same schema

The LSP argues the opposite. When both databases contain the same schema, the consumer will typically not break when you swap implementations, and this means that (according to the LSP) it's okay to have one abstraction. So I would advise to have an `IBarRepository<T>` in your case, since you have two separate schemas. Another option is to have different entities. This would lead to a consumer having an `IRepository<FooSharedModel>` and an `IRepository<BarSharedModel>`. This would comply with the LSP, since both are different interfaces.

> What about the second question, how can I achieve that IValidator<Model> will be equal to Validator<Model> when injecting them both?

I didn't fully get this question and what it is you are trying to achieve. Would you mind moving this question to a new issue and adding some more context and details? For instance, why do you wish to inject both an `IValidator<T>` and `Validator<T>`.

**Comment by maca88** [comment]
Oh, now I understand what you ment by violating the LSP, what a dummy I am. I was going in the wrong direction, thanks for pointing that out.
So one of the possible solutions to not violating the LSP when dealing with multiple databases with different schemas would be:

```
public class Repository<TSession, TEntity> : IRepository<TEntity> where TSession : ISession { 
    public Repository(TSession session) {
        Session = sesion;
    }
    
    protected TSession Session { get; }
    ...
}
public class DefaultRepository<TEntity> : Repository<ISession, TEntity> {
    public DefaultRepository(ISession session) : base(session)
}
    
public interface IBarSession : ISession {}
    
public interface IBarRepository<TEntity> : IRepository<TEntity> {}

public class BarRepository<TEntity> : Repository<IBarSession, TEntity>, IBarRepository<TEntity> {
    public BarRepository(IBarSession session) : base(session)
}

```
With the above structure each database would have its own abstraction, that would also simplify the DI configuration as there is no need to have a keyed registration anymore.
Also, to not break the LSP, the members of the `Repository<TSession, TEntity>` shouldn't be virtual in order to prevent subtypes to alter their meaning.

One problem that I see here is creating a `IBarSession` as the ISession is created internally by NHibernate so one solution to have it, is to create a decorator:
```
public class BarSession : IBarSession {
    public BarSession(ISession session) { 
        _session = session;
    }
    public void Save(object obj) { _session.Save(obj); }
    ...
}
```
But having a decorator for it, would require a lot of code as the ISession has a [lot of members](https://github.com/nhibernate/nhibernate-core/blob/master/src/NHibernate/ISession.cs).
Is there a better approach that I can take, as having ISession for both abstractions would break the LSP, if I understood it correctly?

**Comment by dotnetjunkie** [comment]
I don't think you should have an `IBarSession` per see. As I see it, the `ISession` is an implementation detail to your repository; the rest of the application shouldn't know about it (since `ISession` is not an application-specified abstraction). As long as you have an `IBarRepository<T>` to be used by the application.

> But having a decorator for it, would require a lot of code as the ISession has a lot of members.

That's because `ISession` is one blatant violation of the Interface Segregation Principle. The Dependency Inversion Principle states that interfaces should be owned by the application layer. Since `ISession` is not owned by the application layer, the DIP advises us to hide this interface as much as possible from the application. And the ISP violation makes this even clearer; the interface is really hard to intercept, decorate and mock. It's ugly.

So I don't think that decoration is the way to go here. Instead you might be able to let the repository create an `ISession` internally. Or when it must be injected, applying condition registrations should now be much easier since your conditional registration for `ISession` can now determine based on its parent which database-specific session should be created.

**Comment by maca88** [comment]
Everything clear, with your suggestion I can have also the repositories scoped and the DI configuration simplified. 
Again, thank you very much for your detailed explanations, I learned a lot from them!

**Comment by dotnetjunkie** [comment]
You're more than welcome. Happy I could be of any assistance.
