### ISSUE TITLE
ExecutionContextScopeLifestyle & WebApiRequestLifestyle & OWIN

### ISSUE THREAD

**Issue by stevengopmo** [simpleinjector/SimpleInjector#330]
The documentation (http://simpleinjector.readthedocs.io/en/latest/owinintegration.html) says to use the following when integrating with OWIN

`container.Options.DefaultScopedLifestyle = new ExecutionContextScopeLifestyle();`

but WebApi doc says

`container.Options.DefaultScopedLifestyle = new WebApiRequestLifestyle();`

I realize WebApiRequestLifestyle inherits from ExecutionContextScopeLifestyle but does it add additional info that would cause a conflict if I try and integrate with OWIN and WebApi?

**Comment by dotnetjunkie** [comment]
The two lifestyles are identical and are interchangable. `WebApiRequestLifestyle` is just a more user-friendly name, but since not all OWIN applications use Web API, `WebApiRequestLifestyle` is not always applicable (since it forces a dependency on the Web API integration package which again depends on several Web API packages).

**Comment by stevengopmo** [comment]
@dotnetjunkie thank you!

**Comment by dotnetjunkie** [comment]
The WebApiRequestLifestyle will be deprecated in v4.

**Comment by dotnetjunkie** [comment]
The WebApiRequestLifestyle will be deprecated in v4, so that will remove the ambiguity completely.

**Comment by stevengopmo** [comment]
Is that because Core?

**Comment by dotnetjunkie** [comment]
@stevengopmo, 

Main reason for the existence of the `WebApiRequestLifestyle` is because the name `ExecutionContextScopeLifestyle` was a bit confusing (technically correct, but confusing). In .NET 4.0 however, we are [moving](https://github.com/simpleinjector/SimpleInjector/issues/299) the `ExecutionContextScopeLifestyle` from its own package into the core library and with that we are renaming the lifestyle to `AsyncScopedLifestyle`. This name is much more obvious, and this removes the need to have a specific lifestyle named after the technology.

So this has nothing to do with .NET Core. It's just something we should have done a long time ago.
