### ISSUE TITLE
Register/RegisterCollection does not register complex generics for assemblies

### ISSUE THREAD

**Issue by vitidev** [simpleinjector/SimpleInjector#336]
version 3.3.1. `RegisterManyForOpenGeneric` is deprecated with message:

> 'SimpleInjector.Extensions.OpenGenericBatchRegistrationExtensions.RegisterManyForOpenGeneric(SimpleInjector.Container, System.Type, params System.Reflection.Assembly[])' is obsolete: 'This extension method has been removed. Please use Container.Register(Type, IEnumerable) instead.

Ok. Try "register" method. See comments

``` c#
public interface ICommandHandler<TCommand> { }
public class FirstCommand<TData> { }
public class SecondCommand<TData> { }
public class FirstCommandHandler<TData> : ICommandHandler<FirstCommand<TData>> { }
public class SecondCommandHandler<TData> : ICommandHandler<SecondCommand<TData>> { }
public class Person { }

class Program
{
    static void Main(string[] args)
    {
        Container container = new Container();
        //not work and not fail
        //container.RegisterCollection(typeof(ICommandHandler<>),
        //    AppDomain.CurrentDomain.GetAssemblies());
        //not work  and not fail     
        //container.Register(typeof(ICommandHandler<>), AppDomain.CurrentDomain.GetAssemblies()); 
        
        //but this work
        container.Register(typeof(ICommandHandler<>), typeof(FirstCommandHandler<>));
        container.Register(typeof(ICommandHandler<>), typeof(SecondCommandHandler<>));
        container.Verify();
        
        var t1 = container.GetInstance<ICommandHandler<FirstCommand<Person>>>();
        var t2 = container.GetInstance<ICommandHandler<SecondCommand<Person>>>();
    }
}
```

Also. if we have simple generics

```     
public class FirstCommand { }
public class FirstCommandHandler : ICommandHandler<FirstCommand> { }
```

then Register work, but not RegisterCollection (why??)

**Comment by dotnetjunkie** [comment]
The first thing you need to understand is when to use `Register` and when to use `RegisterCollection`:
 - You should use `Register` when you want to resolve or inject a single instance, i.e. an `ICommandHandler<T>`
 - You should use `RegisterCollection` when you want to resolve or inject a collection of instances, i.e. an `IEnumerable<ICommandHandler<T>>`.

So it is irrelevant how many implementations of `ICommandHandler<T>` your system has. The only thing that counts is whether there are multiple implementations of the same closed generic `ICommandHandler<T>` that you want to resolve at the same time.

In the case of having `ICommandHandler<T>` it is most likely that there is only one implementation, since command handlers map to use cases and you only execute one use case at the time. Hense, you should use `Register`, not `RegisterCollection`.

The second thing you need to understand is how the batch-registration overloads of `Register` and `RegisterCollection` behave when it comes to open-generic types. **Both methods *exclude* open-generic types by default**. This means that `container.Register(typeof(ICommandHandler<>), AppDomain.CurrentDomain.GetAssemblies())` will **not** register the open-generic types. Reason for this is that open-generic types often need special handling and including them by default in the batch-registration process often leads to problems.

Including them can be done as follows:

``` c#

var typesToRegister = container.GetTypesToRegister(typeof(ICommandHandler<>),
    AppDomain.CurrentDomain.GetAssemblies(), 
    new TypesToRegisterOptions { IncludeGenericTypeDefinitions = true });

container.Register(typeof(ICommandHandler<>), typesToRegister);
```

For more information, please see the [documentation](https://simpleinjector.readthedocs.io/en/latest/advanced.html#mixing-collections-of-open-generic-and-non-generic-components).
