### ISSUE TITLE
SimpleInjector, WebForm, Entity Framework Core issue?

### ISSUE THREAD

**Issue by Eneuman** [simpleinjector/SimpleInjector#338]
Hi!

I have a new clean project running .Net 4.5.1 Web Forms.
To this project I added Entity Framework Core 1.0.1 and SimpleInjector.Integration.Web 3.3.1

I followed the web forms integration exacly (http://simpleinjector.readthedocs.io/en/latest/webformsintegration.html).

When It runs the following code it gives me a "File not Found" error on the the line "assembly.**GetExportedTypes**()"

```
     var pageTypes =
          from assembly in BuildManager.GetReferencedAssemblies().Cast<Assembly>()
          where !assembly.IsDynamic
          where !assembly.GlobalAssemblyCache
          from type in assembly.GetExportedTypes()
          where type.IsSubclassOf(typeof(Page))
          where !type.IsAbstract && !type.IsGenericType
          select type;
```

The error says:
Could not load file or assembly Microsoft.Extensions.Logging.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 or one of its dependencies. The file was not found.

Is there a missing dependency in the package or are EFCore interfering with Simple Injector in some way ?

**Comment by dotnetjunkie** [comment]
This issue doesn't seem related to Simple Injector, because:
- Simple Injector does not depend on Microsoft.Extensions.Logging.Abstractions
- You copied the code from the documentation; it is not part of Simple Injector.

It might be a problem in one of the Microsoft NuGet packages; i.e. one of its assemblies references Microsoft.Extensions.Logging.Abstractions while not specifying it in its NuGet package.

Try adding Microsoft.Extensions.Logging.Abstractions manually to the list of dependencies of your project.
