### ISSUE TITLE
Registration of a service after resolution

### ISSUE THREAD

**Issue by prasannavl** [simpleinjector/SimpleInjector#34]
Hi, 

I understand that SimpleInjector's container is locked, and doesn't let you register services after the first resolution, by design. But there are many cases where one would like to resolve certain services during the startup-phase, in between registrations. I've also seen tid-bits of these discussions in many places, but unfortunately, I was unable to get a clean solution for the same so far. The documentation also seems to touch on this a bit, but just barely.

I was wondering if you could please give a quick scrip on what's the intended best way to accomplish this:

```c# 

public BootstrapperClass1 {
  public void Register(Container c)
  {
      c.Register<IService1, Service1>();
  }
}

public BootstrapperClass2 {
  public void Register(Container c)
  {
     // This is just to substantiate the notion 
     // that the service has to be resolved here, and more registration
     // to proceed after that. 
     if (c.GetInstance<IService1>().Version == 1)
     {
           c.Register<IService2, Service2v1>();
      }
      else {
        c.Register<IService2, Service2v2>();
      }
  }
}

```

One obvious way that I see is to use the UnresolvedType event. But the obvious problem is that, this ends up complicating the whole registration logic for anything beyond that. And you have to end up doing almost the entire rest of the registration logic as a part of that event, which seems highly unnatural. 

A whole bunch of my projects use multi-stage bootstrappers like these, where a later bootstrapper will need to examine registered services so far before they make their registrations and this seems make it quite difficult to migrate to SI. 

The only way I seem to be able to workaround this is by creating a whole bunch of different containers, and composing the registrations of the containers to a new one. This is bugging me since it isn't the cleanest approach, and also becomes very expensive on the startup path, as the startup stages increase.

**Comment by dotnetjunkie** [comment]
Unfortunately, the given example is too generic to allow any specific feedback to be given. What does `IService1` and `Service1` represent, and why does it have a `Version` property, and how is this version property determined? Please be as specific as possible about your use case and design.

**Comment by prasannavl** [comment]
I had actually intended it to be generic. Version property was just a hypothetical generic representation of the notion that a previously registered service during the startup phase has to be resolved, and based on a few conditions, further services be registered. 

One simple real example in one of my project involves an IFlashlightDriver which resolves to different services based on a IDriverInfo service, which ends up being registered by a different Plugin in the previous stages of the bootstrapper. And the flashlight is registered by another disconnected stage in the bootstrapper.

**Comment by dotnetjunkie** [comment]
There are a few options here. I'll give the two that came to mind first.

First, really try to separate the registration phase from the resolve phase. In my experience this is always possible and preferable. It does make your code much cleaner and understandable, and makes it less prone to weird bugs. In your case for instance, it seems weird to have the main application use some `IDriverInfo` service that is registered by some other plugin. Since this `IDriverInfo` contains configuration data, it should be available before the container is registered. If this class contains not only configuration data but also behavior, the class should be split in two; it has two responsibilities. If this data must come from a plugin, it's much cleaner to use a different communication mechanism to get this configuration data from the plugin. Don't abuse the container for this. The container is not a dictionary of configuration values to pass around. As a matter of fact, you should not have any abstractions such as `IApplicationConfiguration` that just contains properties with configuration values for other parts of the application to use. This violates SOLID and leads to ugly code (I speak from experience here, I used such abstraction for a long time). Instead, load configuration values before configuring the container and inject a specific configuration value into a service that needs it. For instance, don't inject an `IApplicationConfiguration` into a `UnitOfWork` class, but let that `UnitOfWork` take a `string connectionString` argument in its constructor. If you find yourself having to inject the same configuration value into multiple components, you are missing an abstraction to hide that configuration value behind. For the connection string for instance, this could be an `IConnectionFactory` which exposes an `SqlConnection CreateAndOpenConnection()` method. This hides the configuration value from the application and the only component that needs to be injected with this connection string is the `SqlConnectionFactory` component.

Another option is to use a proxy class to allow postponing the decision which component to use. This is especially useful when the types can/should change at runtime, but it can also used for configuration values, in case the refactoring that I described above is too much work. Here's what the proxy might look in your case:

``` c#
public class RuntimeSelectableFlashlightDriverProxy :  IFlashlightDriver {
    private readonly Func<IFlashlightDriver> selector;	
    public RuntimeSelectableFlashlightDriverProxy(Func<IFlashlightDriver> selector) {
        this.selector = selector;
    }

    void IFlashlightDriver.Flash() {
        this.selector.Invoke().Flash();
    }
}
```

This class can be registered as follows:

```
container.RegisterSingle<IFlashlightDriver>(
	new RuntimeSelectableFlashlightDriverProxy(() =>
		container.GetInstance<IDriverInfo>().Version == 1
			? container.GetInstance<FlashlightDriverV1>()
			: container.GetInstance<FlashlightDriverV2>()));
```

**Comment by prasannavl** [comment]
Thank you for the advice. I think I'll take the second approach, since fortunately, all the services that are in question in my scenario already are served via proxy since they are runtime swappable services. Your advise solves my current requirement. I appreciate your time for the detailed reply. 

It however does concern me a little, that SI doesn't have a builder like mechanism, that I currently use to solve multi-staged bootstrapping like these, which is provided by DI containers like Autofac, Grace, or the alternate route taken my LightInject and such where you're free to register anytime directly with the container itself. With SI, it seems difficult to compose services from various parts of the application, unless its all done in one sweep. Perhaps, you're right that I'm abusing the container by trying to make the container serve nearly everything. But basically this is the process 

** ApplicationCore: **
=> PreInitialize();
=> RegisterServices(Container c);
=> Initialize();

** PlugIn1: **
=> PreInitialize();
=> RegisterServices(Container c);
=> Initialize()  // Can use the registered services to perform initialization
                      //, or any other service of ApplicationCore, or previous plugins.

** PlugIn2: **
-- Same as above. 

And so on.

I take it, this not a pattern that is friendly to SI, if I use one container which handles all of these.

**Comment by dotnetjunkie** [comment]
I'm not sure that SI is unfriendly to this. It might be annoying that Simple Injector forces you to change your design, but this limitation is there for a reason. The [risks](https://simpleinjector.readthedocs.org/en/latest/decisions.html#container-is-locked) of doing registrations like this however are [very real](https://unity.codeplex.com/discussions/611770), so for me that was reason enough to not allow this. Don't forget that Autofac's `ContainerBuilder` is exactly meant to do what Simple Injector forces you: to separate the registration phase from the resolve phase.

What you can do is split your initialization phase in two steps, where you first iterate over all plugins and do some sort of pre-initialization and build up the configuration values, and after that iterate again where all plugins can register (but not resolve).

I do agree though that the documentation is a bit limited in this case, and doesn’t really describe how to make this work in Simple Injector. Main reason for this is that it’s impossible to come up with a general scenario that works for everybody. The solution is highly dependent on the exact use case. This is where the community comes in to help you and supply feedback to the design at hand.

But if you feel really strongly about being able to do this, and you feel that Simple Injector is limiting you in this, and you are willing to take the risk of making accidental misconfigurations, do switch to a different library. Simple Injector isn't this Swiss army knife that works in all scenarios. I feel strongly about protecting our users to doing what I see as the wrong thing, but if you don't share this opinion or vision, there are other libraries that might better suit your needs. I'll won’t be offended if you switch.

**Comment by prasannavl** [comment]
Fair enough. Thanks for your time and help with this. I see if I can make it work by shuffling the design a bit, or go probably go back to Autofac as a last resort.

**Comment by gravypower** [comment]
Hey @dotnetjunkie,

I am reopening this thread as I think a use case I want to achieve is along the same lines as described above.  Basically I am creating a framework that loads modules, these modules are then responsible for registering any dependencies and decorators. 

This is an OWIN application so the modules can define middleware that I register with SI.  Once I have completed building the Composition Root I then ask SI for all middleware with Container.GetAllInstances. 

Everything is fine and working well however I have started to play around with Nancy and want to use SI and have it handle dependencies there also. I have been basing  my code in an example you provided on [this issue](https://github.com/NancyFx/Nancy/issues/1227).  The issue is that I am using the container before ApplicationStartup is called and there for the container is locked.  

I want to keep the ability to decorate middleware so the only solution I can think of is a second container, on for middleware and one for the application.  Any advice on this would be much appreciated,

My code can be found [here ](https://github.com/FurnaceCMS/Furnace.Play)if you need to look at what I am actually doing.  This is just a playground so any feedback in general will be most welcome. 

Aaron

**Comment by dotnetjunkie** [comment]
Hi @gravypower,

Since this thread is quite old, it would be good to start a new thread. If you create a new issue with your question, we can take it from there. And please add some code to illustrate your issue, so it would be easier to understand your issue, reproduce it and give any feedback.

Cheers

**Comment by gravypower** [comment]
@dotnetjunkie thanks.

I have created  a new issue [here](https://github.com/simpleinjector/SimpleInjector/issues/279) if anyone comes accross this thread at a later time.
