### ISSUE TITLE
How to get the current scope's type

### ISSUE THREAD

**Issue by oruchreis** [simpleinjector/SimpleInjector#340]
If `Container.GetCurrentLifetimeScope()` is obsolete, how can we determine the scope type? I give high priority to lifetime scope over execution context scope like that:
```c#
public static readonly ScopedLifestyle HybridScopedLifestyle = Lifestyle.CreateHybrid(
            lifestyleSelector: () => Container.GetCurrentLifetimeScope() != null,
            trueLifestyle: new LifetimeScopeLifestyle(),
            falseLifestyle: new ExecutionContextScopeLifestyle());
```
If I use `Lifestyle.Scoped.GetCurrentScope(Ioc.Container)`, it gives me a base `Scope` class which I can't choose the scope over another scope.

**Comment by dotnetjunkie** [comment]
> If Container.GetCurrentLifetimeScope() is obsolete, how can we determine the scope type?

The obsolete message [states](https://github.com/simpleinjector/SimpleInjector/blob/v3.3.x/src/SimpleInjector.Extensions.LifetimeScoping/SimpleInjectorLifetimeScopeExtensions.cs#L301):

> GetCurrentLifetimeScope has been deprecated and will be removed in a future release. Please use Lifestyle.Scoped.GetCurrentScope(Container) instead.

Calling `Lifestyle.Scoped.GetCurrentScope(Container)` is typically the answer, because it redirects to `Container.Options.DefaultScopedLifestyle` which will normally be set with your scoped lifestyle such as `LifetimeScopeLifestyle`.

In your case however, you need to call `GetCurrentScope(Container)` on your scoped lifestyle directly instead of through `Lifestyle.Scoped`. In other words:

``` c#
var lifetimeScopeLifestyle = new LifetimeScopeLifestyle();
Lifestyle.CreateHybrid(
    lifestyleSelector: () => lifetimeScopeLifestyle.GetCurrentScope(container) != null,
    trueLifestyle: lifetimeScopeLifestyle,
    falseLifestyle: new ExecutionContextScopeLifestyle());
```

**Comment by dotnetjunkie** [comment]
To make things easer, Simple Injector v4 contains a new `CreateHybrid` overload that removes the need to supply a `lifestyleSelector`. Instead you can use the following code:

``` c#
var lifetimeScopeLifestyle = new LifetimeScopeLifestyle();
Lifestyle.CreateHybrid(
    defaultLifestyle: new ThreadScopedLifestyle(),
    fallbackLifestyle: new AsyncScopedLifestyle());
```
Note that `ThreadScopedLifestyle` replaces the `LifetimeScopeLifestyle` in v4 and `AsyncScopedLifestyle`  replaces `ExecutionContextScopeLifestyle`.
