### ISSUE TITLE
Should I explicitly dispose an IDbConnection?

### ISSUE THREAD

**Issue by janhartmann** [simpleinjector/SimpleInjector#344]
I was wondering if I should explicity dispose the `IDbConnection` in this scenario:

```cs
public interface IDbConnectionProvider
{
        IDbConnection Connect();
}
```

```cs
internal sealed class LegacyDatabaseProvider : IDbConnectionProvider, IDisposable
{
        private readonly IDbConnection _mySqlConnection;

        public LegacyDatabaseProvider(IDbConnection mySqlConnection)
        {
                _mySqlConnection = mySqlConnection;
        }

        public IDbConnection Connect()
        {
                _mySqlConnection.Open();
                return _mySqlConnection;
        }

        public void Dispose()
        {
                _mySqlConnection.Dispose();
        }
}
```

The SI registration is as follows: 

```cs
container.Register<IDbConnectionProvider>(
    () => new LegacyDatabaseProvider(new MySqlConnection("connectionString")));
container.Register(() => container.GetInstance<IDbConnectionProvider>().Connect(), 
    Lifestyle.Scoped);
```

This `IDbConnectionProvider` is injected into handlers and is used with dapper to query the database. It works just fine, my only concern is if I should explicity dispose the connection using an `IDisposable`  implementation or is this done by SI?

**Comment by dotnetjunkie** [comment]
A component should typically [only dispose what it creates](https://stackoverflow.com/a/30287923/264697) (and thus owns) itself. It should not take ownership over dependencies that are injected, and it should therefore not dispose those dependencies. Doing so complicates the application and can lead hidden coupling and might a change to one part of the application cause to break a seemingly unrelated other part, when that parts uses a dependency that got accidentally disposed earlier. 

Your `LegacyDatabaseProvider` seems to violate this rule, so I would say that it should either create the `MySqlConnection` itself, or it should not implement dispose.

Furthermore, it seems that you sometimes inject the `IDbConnectionProvider`, while other times you are injecting the `IDbConnection` directly. Injecting `IDbConnection` directly seems a bad idea, because it’s runtime data (https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=99) and in this case its creation is fragile (since a call to `.Open()` is something that can potentially fail), while the creation of components should be fast and reliable. I think you should refrain from injecting `IDbConnection` directly and use IDbConnectionProvider solely.

Your configuration seems is broken when it comes to the disposal of the `IDbConnection`. Although Simple Injector will take care of the disposal of your scoped `IDbConnection` registration, it will only do so in case that `IDbConnection` has been resolved during the current scope. In other words, in case you resolve an object graph during that request that contains (among other things) your `LegacyDatabaseProvider` -but not an IDbConnection as a dependency itself- it means that the created `MySqlConnection` won't get disposed when the `LegacyDatabaseProvider` in case it does not implement `IDisposable`, since without the `IDbConnection` being resolved through its registration, Simple Injector has no way of knowing that this instance actually exists and should be disposed. Although `LegacyDatabaseProvider` currently does implement `IDisposable`, Simple Injector will not call its `Dispose` method since you registered it as `Transient`. Simple Injector should have warned you about this though, when you called `Container.Verify()`.

I assume here that there is just one connection string for the complete application (opposed to having a connection string per request or per user, which might change things slightly). With that assumption I propose the following design:

``` c#
public interface IDbConnectionProvider
{
    IDbConnection Connection { get; }
}

internal sealed class LegacyDatabaseProvider : IDbConnectionProvider
{
    private readonly Func<IDbConnection> _connectionProvider;

    public LegacyDatabaseProvider(Func<IDbConnection> connectionProvider) {
        _connectionProvider = connectionProvider;
    }

    public IDbConnection Connection => _connectionProvider();
}
```

What happens here is that the `LegacyDatabaseProvider` itself isn't responsible anymore for disposing the `IDbConnection` and it therefore doesn't need to implement dispose anymore. Furthermore, it doesn't get an `IDbConnection` injected anymore but a provider delegate. This moves the responsibility of creating and disposing the connection up to the one who is creating the `LegacyDatabaseProvider` (which obviously is the composition root). Since you want to reuse the same connection throughout the same request, I changed the `Connect()` method to a `Connection` property. Having a `Connect()` method implies the creation of a new dbconnection and might cause the consumer to believe it need to dispose that instance, which obviously isn't the case, since you want it to be reused.

We can wire the previous code using the following registration:

```
string connectionString = ...;

var conProducer = Lifestyle.Scoped.CreateProducer<IDbConnection>(() => {
        var con = new MySqlConnection(connectionString);
        con.Open();
        return con;
    }, container);
    
container.RegisterSingleton<IDbConnectionProvider>(
    new LegacyDatabaseProvider(conProducer.GetInstance));
```

NOTE: I think it is best to not register `ConnectionStringSettings` into the container; no component should depend on `ConnectionStringSettings` directly; instead it should only depend on the configuration value that it actually requires.

Here we create an `InstanceProducer` for our `IDbConnection`. This `InstanceProducer` instance however, is not added to the container and this prevents the `IDbConnection` from being injected anywhere. Instead we use the `InstanceProducer` as our `Func<IDbConnection>` connection provider dependency.

Also note that since our delegate is a singleton, so can our `LegacyDatabaseProvider` be. When the `Func<IDbConnection>` is called, it will callback into Simple Injector and will hit its cache in case the instance already exists.

Since the `MySqlConnection` now will only get created when it actually is used by the application, it won't be created needlessly, while Simple Injector will guarantee its disposal when the request/scope ends.

The downside of this approach however is that when we call `container.Verify()`, Simple Injector will verify our `InstanceProducer<IDbConnection>` as well, which will cause a database connection to be opened. This could cause a delay or even verification to fail (which is very likely to happen if we call `Verify` as part of a unit test). The current version of Simple Injector does not allow certain registrations to be skipped during verification.

In case this becomes a problem we can move the creation of our `InstanceProducer<IDbConnection>` into a `Lazy<InstanceProducer<IDbConnection>>`, so we can ensure that our `InstanceProducer` instance is only created *after* the object graph is verified. Our `LegacyDatabaseProvider` would in that case be as follows:

``` c#
var lazyConProducer = new Lazy<InstanceProducer<IDbConnection>>(() =>
    Lifestyle.Scoped.CreateProducer<IDbConnection>(() => {
        var con = new MySqlConnection(connectionString);
        con.Open();
        return con;
    }, container);

container.RegisterSingleton<IDbConnectionProvider>(
    new LegacyDatabaseProvider(() => lazyConProducer.Value.GetInstance()));
```

Being able to suppress verification on an `InstanceProducer` would have made this somewhat easier, but such feature might on the other hand open up a can of worms, and that's why there is currently no support for such feature in Simple Injector.

The only problem left from a design perspective is that the `IDbConnection` abstraction implements `IDisposable` which can cause consumers to call `Dispose` on it, while they actually shouldn't. You typically want to prevent abstractions from implementing `IDisposable`, since it is a violation of the Dependency Inversion Principle (as explained [here](https://stackoverflow.com/a/30287923/264697)), and probably a violation of the Interface Segregation Principle as well. There is a limit however to which extend we should prevent SOLID violations and I'm not sure that it is feasible for you to abstract that `IDbConnection` away.
    
I hope I've shown that your current solution might be fragile and that the design can be simplified, while we make use of Simple Injector to guarantee deterministic disposal of our connections.

I hope this helps.

**Comment by janhartmann** [comment]
Thank you for this in-depth response to my question. 

Going to read though it a few times more and then implement the solution. :-)

**Comment by RobsonKarls** [comment]
Singleton for DBConnection is a good idea?

**Comment by dotnetjunkie** [comment]
@RobsonKarls 

That depends on your application, but you have to understand that `IDbConnection` implementations are _not_ thread-safe, while `Singleton` instances are reused by the complete application. So in case your application is multi-threaded, or lives for longer period of time (longer than a short console application that runs one action), it is probably a bad idea to register your `IDbConnection` as `Singleton`.
