### ISSUE TITLE
Can't install on portable-net452+win81 (System.Collections conflict)

### ISSUE THREAD

**Issue by UnderHeavyDevelopment** [simpleinjector/SimpleInjector#360]
Project type: Class Library
Simple Injector v3.3.2

Project targets:
- .NET Framework 4.6
- Windows 10

project.json content
```json
{
  "supports": {
    "net46.app": {},
    "uwp.10.0.app": {}
  },
  "dependencies": {
    "Microsoft.NETCore": "5.0.0",
    "Microsoft.NETCore.Portable.Compatibility": "1.0.0"
  },
  "frameworks": {
    "dotnet": {
      "imports": "portable-net452+win81"
    }
  }
}
```

Simple Injector installation fails with:
```
...
Installing runtime.win.System.Console 4.0.0.
Install-Package : Version conflict detected for System.Collections. 
 DemoApp (>= 1.0.0) -> SimpleInjector (>= 3.3.2) -> NETStandard.Library (>= 1.6.0) ->
 System.Collections (>= 4.0.11) 
 DemoApp (>= 1.0.0) -> Microsoft.NETCore.Portable.Compatibility (>= 1.0.0) -> Microso
ft.NETCore.Runtime (>= 1.0.0) -> Microsoft.NETCore.Runtime.CoreCLR-x86 (>= 1.0.0) -> System.Collections (=
 4.0.10).
At line:1 char:1
+ Install-Package SimpleInjector
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.Ins 
   tallPackageCommand
```

**Comment by dotnetjunkie** [comment]
The problem lies in the [Microsoft.NETCore.Runtime.CoreCLR-x86 v1.0.0](https://www.nuget.org/packages/Microsoft.NETCore.Runtime.CoreCLR-x86/1.0.0) package that the `Microsoft.NETCore.Portable.Compatibility` v1.0.0 package depends on. If you take a look at the dependencies that `Microsoft.NETCore.Runtime.CoreCLR-x86` requires, you'll see:

> System.Collections (= 4.0.10).

Do note the `=` sign here, instead of the usual `>=`. This means that `Microsoft.NETCore.Portable.Compatibility` requires the exact version of `4.0.10` and it doesn't support *any other version*.

This is a problem, since Simple Injector depends on `NETStandard.Library 1.6.0` which depends on:

> System.Collections (>= 4.0.11)

On other words, NETStandard.Labirary 1.6.0 requires at least 4.0.11 (but also excepts greater versions).

This obviously causes a conflict, and this is IMO a bug in the  `Microsoft.NETCore.Runtime.CoreCLR-x86` package.

I'm unsure how to solve this.

**Comment by dotnetjunkie** [comment]
Perhaps [this Stackoverflow q/a](https://stackoverflow.com/questions/36002554/a-ton-of-conflicts-on-simple-uwp-project) solves your problem.

**Comment by UnderHeavyDevelopment** [comment]
Now I see, that's the same issue I've reported while ago in MvvmCross (https://github.com/MvvmCross/MvvmCross/issues/1391). In that case, problematic package dependency was removed in MvvmCross. In mentioned thread, @ericstj from .NET team took voice: https://github.com/MvvmCross/MvvmCross/issues/1391#issuecomment-231404829

**Comment by UnderHeavyDevelopment** [comment]
> Perhaps this Stackoverflow q/a solves your problem.
@dotnetjunkie It does not. Latest release of Microsoft.NETCore is 5.0.0, Microsoft.NETCore.Portability.Compatibility is 1.0.1 (is not compatible with NETCore 5.0.0, so I can use only 1.0.0). So after reinstallation, I have the same packages versions as previously.

**Comment by dotnetjunkie** [comment]
It's unclear to me how you can solve this problem and whether or not there is something we can do with Simple Injector.

**Comment by UnderHeavyDevelopment** [comment]
I think I have the solution. I've checked https://docs.microsoft.com/en-us/dotnet/articles/core/tutorials/libraries#how-to-target-the-net-standard and for my needs, ``.NETStandard 1.4`` is ok. I can install Simple Injector on this target (so just need to retarget from standard PCL to .NETStandard).

Then I can reference such library in UWP app and WPF app targeting .NET 4.6. Solution then compiles and runs. I will update if any news.

(more info in https://github.com/autofac/Autofac/issues/818)
