### ISSUE TITLE
Root composition?

### ISSUE THREAD

**Issue by arcria** [simpleinjector/SimpleInjector#361]
My question involves root composition and in my demo (see pic below).  Is this the best practice for using simple injector?  In this example all projects (dll) are referenced in our sample console app.  This allows everything to get registered but what if I don't want to expose the data access layer (repositories).  The second issue is what if the common, dal and service layers are used across multiple applications (in this case console, SPA and iOS)?  Do we have to provide this root composition for each application?

![image](https://cloud.githubusercontent.com/assets/7604438/21462372/7f90c7ac-c929-11e6-8c13-8d7761e1b66e.png)

**Comment by dotnetjunkie** [comment]
> This allows everything to get registered but what if I don't want to expose the data access layer (repositories).

Your composition root (your main) is the point in the application where everything starts. This point will have to depend on every other assembly in the system. There is no reason to prevent this. Please take a look at [this Stackoverflow question](https://stackoverflow.com/questions/9501604/ioc-di-why-do-i-have-to-reference-all-layers-assemblies-in-entry-application) and read both the answers from Mark Seemann and myself about this subject.

> what if the common, dal and service layers are used across multiple applications (in this case console, SPA and iOS)? Do we have to provide this root composition for each application?

Yes, each end application contains its own Composition Root. Each application that is part of your system typically has a unique set of features, with usually little overlap. They might reuse some code, but typically not duplicate exact set of features. That's why Mark Seemann states that [Composition Root reuse](http://blog.ploeh.dk/2015/01/06/composition-root-reuse/) should be rare:

> Different applications have differing Composition Roots. Even if they start with substantial amounts of duplicated Composition Root code, in my experience, the 'common' code tends to diverge the more the applications are allowed to evolve. That duplication may be accidental, and attempting to eliminate it may increase coupling. It's better to understand why you want to avoid duplication in the first place.

In case both the SPA and iOS versions are duplicates of each other, you might be missing a shared web service (which is an end application with its own Composition Root) that both the SPA and iOS call. It seems to me that both the SPA project and iOS are completely different set of projects, so there shouldn't be much overlap in registrations.

**Comment by arcria** [comment]
Thanks for the information.  I just wanted to make sure I was following the correct way it is intended on being setup. And you are absolutely correct regarding the SPA and iOS.  There is another project being added that is a WebApi project that will call all the services from the Services project.  Then each of the SPA and iOS can use the WebApi.
