### ISSUE TITLE
@inject razor views

### ISSUE THREAD

**Issue by mathysd** [simpleinjector/SimpleInjector#362]
Good job on the migration to .net core!
Will there be support for @inject inside razors views? Or did I miss something?

[As explained here](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/dependency-injection)

**Comment by dotnetjunkie** [comment]
I have to l9ok into that, but my gut feeling is that this is a feature that shouldn't exist at all. Views should not have dependencies. Views should be dumb and all reqyired data should be supplied to the view by the controller.

**Comment by dotnetjunkie** [comment]
After some investigation, I have to come to the conclusion that ASP.NET Core MVC currently lacks the proper hook that allows intercepting injection of Razor View Properties (i.e. services that are injected using `@inject`). 

You can see that the way to resolve properties is hard-wired into the `RazorPageActivator` at line [204](https://github.com/aspnet/Mvc/blob/760c8f38678118734399c58c2dac981ea6e47046/src/Microsoft.AspNetCore.Mvc.Razor/RazorPageActivator.cs#L204). At that line, `GetRequiredService` is called directly on the `HttpContext.RequestServices` object, which always points to the built-in container.

The only way to intercept this is by replacing the default `RazorPageActivator` with a custom implementation, because the `RazorPageActivator` doesn't have any virtual methods that allow us to override, nor does it depend on a dependency (e.g. an imaginary `IRazorPagePropertyActivator`) that we can override.

This design flow means that the only way to add this behavior is to copy all the code from the original `RazorPageActivator` (and the internal `PropertyActivator<TContext>` and `PropertyHelper` as well) into your custom implementation of `IRazorPageActivator`. This allows you to make a few changes that would allow you to intercept the creation of properties to your own container.

This solution however isn't really feasible, because it causes a severe 'synchronization burden' on you, because you will have to keep these three files in sync with any possible changes and bug fixes that Microsoft will do on these three classes itself.

This does mean that [the statements](https://simpleinjector.org/blog/2016/07/working-around-the-asp-net-core-di-abstraction/) I made months ago about MVC having all the required interception points in place, where unfortunately false. This is an omission in the design of MVC.

But as I said previously, IMO from a design perspective, views should not have any dependencies; not even for "localization or data required only for populating view elements". This is better done at the controller level (or perhaps at a level between the controller and the view, by using decoration or interception to enrich this data). This keeps the views truly dumb.

**Comment by mathysd** [comment]
Thanks for looking into this and I agree with you that views should be kept simple. I have a shared layout that displays some information about the current user and I don't want every controller to get this information and "push" it to the layout. But for now I think I can solve it with a view component that does support constructor injection.

As a last resort I could cross-wire the asp.mvc container to make use of the simple injector container to resolve dependencies for the views. Something like:

services.AddScoped<ISomething>(provider => container.GetInstance<ISomething>());
Pragmatic aproach but it feels a bit hacky :)

**Comment by dotnetjunkie** [comment]
That isn't that hacky at all, I must say. What you are doing is called "cross-wiring" and is almost always required when to run an application-specific container besides the built-in framework container. You sometimes have to cross-wire registrations from one side to the other.

**Comment by dotnetjunkie** [comment]
ASP.NET Core 5.0 will allow the creation of Razor Components to be intercepted. [Here's](https://github.com/simpleinjector/SimpleInjector/issues/860#issuecomment-721743740) how to integrate it with Simple Injector.

**Comment by irmtim** [comment]
> ASP.NET Core 5.0 will allow the creation of Razor Components to be intercepted. [Here's](https://github.com/simpleinjector/SimpleInjector/issues/860#issuecomment-721743740) how to integrate it with Simple Injector.

So and there's still no way to add support of @inject in razor views?

**Comment by dotnetjunkie** [comment]
@irmtim ,

See https://simpleinjector.readthedocs.io/en/latest/advanced.html#enabling-property-injection

**Comment by dotnetjunkie** [comment]
@irmtim, I finally had some time to deep deeper into this, and unfortunately due to current limitations of Blazor (.NET 5.0) it is practically impossible to use the `@inject` attribute. But there is a workaround. You can read about what the issue is, what workaround there is, which issue I reported with Microsoft, and join the discussion [here](https://github.com/simpleinjector/SimpleInjector/issues/676#issuecomment-752924999).

**Comment by dotnetjunkie** [comment]
There is [Blazor Server App integration guide](https://simpleinjector.org/blazor) in the [Simple Injector documentation](https://simpleinjector.org/wiki).
