### ISSUE TITLE
RegisterCollection, open generics and lifetime question

### ISSUE THREAD

**Issue by smolyakoff** [simpleinjector/SimpleInjector#370]
I'm trying to find a way to register a collection of singletons. I have the following class which registers a bunch of request handling pipeline steps. I expect those steps to be resolved as singletons. However, they are resolved as transient and `eq === false` in the example. Can you point me to the correct way of doing singleton registration for items passed to `RegisterCollection`?

```csharp
public static class ContainerExtensions
    {
        public static void RegisterClientMediator(this Container container)
        {
            if (container == null)
            {
                throw new ArgumentNullException(nameof(container));
            }
            var assembly = typeof(LoginHandler).Assembly;
            var assemblies = new List<Assembly> {assembly};
            container.Register(typeof(IAsyncRequestHandler<,>), assemblies, Lifestyle.Singleton);
            var types = container.GetTypesToRegister(typeof(IPipelineBehavior<,>), assemblies, new TypesToRegisterOptions
            {
                IncludeGenericTypeDefinitions = true
            });
            foreach (var type in types)
            {
                container.RegisterSingleton(typeof(IPipelineBehavior<,>), type);
            }
            container.RegisterCollection(typeof(IPipelineBehavior<,>), new List<Type>
            {
                typeof(DiagnosticsBehaviour<,>),
                typeof(ErrorLoggingBehaviour<,>),
                typeof(AuthenticationBehaviour<,>)           
            });
            container.Register(() =>
            {
                var configuration = new MapperConfiguration(cfg => cfg.AddProfiles(assemblies));
                return configuration.CreateMapper();
            }, Lifestyle.Singleton);
            container.Register<SingleInstanceFactory>(() => container.GetInstance, Lifestyle.Singleton);
            container.Register<MultiInstanceFactory>(() => container.GetAllInstances, Lifestyle.Singleton);
            container.Register<IMediator, Mediator>(Lifestyle.Singleton);
            var a = container.GetAllInstances(
                typeof(IPipelineBehavior<CommandEnvelope<LoginCommand, LoginCommandResponse>, LoginCommandResponse>)).ToList();
            var b = container.GetAllInstances(
                typeof(IPipelineBehavior<CommandEnvelope<LoginCommand, LoginCommandResponse>, LoginCommandResponse>)).ToList();
            var eq = a[0] == b[0];
        }
    }
```

**Comment by dotnetjunkie** [comment]
You should replace this line:

``` c#
container.RegisterSingleton(typeof(IPipelineBehavior<,>), type);
```

with the following:

``` c#
container.RegisterSingleton(type, type);
```

`RegisterCollection` will always try to find an existing registration for the supplied types and it reused that registration (including its lifestyle). The documentation [shows](https://simpleinjector.readthedocs.io/en/latest/using.html#collections) the following example for this:

``` c#
container.Register<MailLogger>(Lifestyle.Singleton);
container.Register<ILogger, FileLogger>();

container.RegisterCollection<ILogger>(new[] {
    typeof(MailLogger),
    typeof(SqlLogger),
    typeof(ILogger)
});
```

Here a collection of three `ILogger` types is registered as a collection, where the `MailLogger` will become a Singleton, because there exists a non-collection registration for that type.

The error you made however is that you registered those types by their abstraction, while the `RegisterCollection` will try to locate them by the concrete type. This is obvious when you think about it, since in your case there could already be three different registrations of the same closed-generic `IPipelineBehavior<,>`; for `DiagnosticsBehaviour<,>`, `ErrorLoggingBehaviour<,>` and `AuthenticationBehaviour<,>`. That's why `RegisterCollection` only checks for the actual type, not for the abstraction.

I find your configuration a bit suspicious though, are you sure you only want to register those three behaviors as part of the collection, and not all the other types that are returned from `GetTypesToRegister`?

**Comment by smolyakoff** [comment]
It works, thanks. Was a bit silly about it indeed :) There are only 3 types and I need to make sure they are resolved in a specific order.
