### ISSUE TITLE
[Question] Dependency injection in parameterless constructor of implementation of third-party component

### ISSUE THREAD

**Issue by deastr** [simpleinjector/SimpleInjector#382]
We have a token handler implementing Windows Identity Foundation. We had to use service locator in one of its methods because we couldn't find any other way to inject a service because you can't change the constructor signature. I'd like to ask any guidance on this to get rid of the ServiceLocator.

Implementation:

``` c#
public class TokenServiceConfiguration : SecurityTokenServiceConfiguration
{
	public TokenServiceConfiguration(ICertificateLoader certificateLoader) : base()
	{
		//certificateLoader injects just fine
	}
}
```

CustomUserNameSecurityTokenHandler:

``` c#
public class CustomUserNameSecurityTokenHandler : UserNameSecurityTokenHandler
{
	public CustomUserNameSecurityTokenHandler() : base()
	{
	}

	public override ReadOnlyCollection<ClaimsIdentity> ValidateToken(SecurityToken token)
	{
		UserNameSecurityToken usernameToken = token as UserNameSecurityToken;
		SignInStatus signInStatus = 
			ServiceLocator.Current.GetInstance<ISignInManager>().SignIn(
				new UsernamePasswordData(token.UserName, token.Password, true));
		..
	}
```

web.config:

``` xml
<system.identityModel>
    <identityConfiguration>
      <securityTokenHandlers>
        <remove type="System.IdentityModel.Tokens.WindowsUserNameSecurityTokenHandler, 
			System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
        <add type="Identity.Authentication.Core.TokenServices.CustomUserNameSecurityTokenHandler,
			Identity.Authentication.Core" />
      </securityTokenHandlers>
    </identityConfiguration>
  </system.identityModel>
```

If I try to change `CustomUserNameSecurityTokenHandler` constructor to inject `ISignInManager` like this:

``` c#
public class CustomUserNameSecurityTokenHandler : UserNameSecurityTokenHandler
{
	public CustomUserNameSecurityTokenHandler(ISignInManager signInManager) : base()
	{
	}
```

We get this error:

```
System.Configuration.ConfigurationErrorsException occurred
  HResult=0x80131902
  Message=ID1024: The configuration property value is not valid.
Property name: 'type'
Error: 'Constructor on type 'Identity.Authentication.Core.TokenServices.CustomUserNameSecurityTokenHandler' not found.'
  Source=System.IdentityModel
  StackTrace:
   at System.IdentityModel.Configuration.TypeResolveHelper.Resolve[T](ConfigurationElementInterceptor customTypeElement, Type customType)
   at 
...
Inner Exception 1:
MissingMethodException: Constructor on type 'Identity.Authentication.Core.TokenServices.CustomUserNameSecurityTokenHandler' not found.
```

in `base()` call in this line:

``` c#
public TokenServiceConfiguration(ICertificateLoader certificateLoader) : base()
```

I'd appreciate any input if we can manage this without ServiceLocator..

**Comment by dotnetjunkie** [comment]
> I'd appreciate any input if we can manage this without ServiceLocator.

I can make this really short: you can't. You are hitting a limitation in how Windows Identity Foundation works, which uses the ASP.NET Provider 'pattern, which [is an anti-pattern](http://blog.ploeh.dk/2011/04/27/Providerisnotapattern/) since it applies the Constrained Construction anti-pattern.

The solution in working with these kinds of frameworks is to change the `CustomUserNameSecurityTokenHandler` into a [Humble Object](http://xunitpatterns.com/Humble%20Object.html) by extracting all relevant code out of that class into its own service. This leaves nothing in the Humble Object but a call to the DI container to resolve that new service.

As I see it, this is exactly the pattern you applied, so your solution is correct.

Do note that this method might not be a Service Locator at all, since whether or not it is a Service Locator depends on [the role, not on the mechanics](http://blog.ploeh.dk/2011/08/25/ServiceLocatorrolesvs.mechanics/). As long as this Humble Object is part of the [Composition Root](http://blog.ploeh.dk/2011/07/28/CompositionRoot/), you are not applying the Service Locator anti-pattern. In that case it is even valid to call into your DI Container directly, without depending on the MVC `ServiceLocator.Current`.

**Comment by deastr** [comment]
Thank you for the info dotnetjunkie, appreciate it.
