### ISSUE TITLE
Trouble installing package SimpleInjector.Integration.AspNetCore.Mvc 3.3.0

### ISSUE THREAD

**Issue by BennieCopeland** [simpleinjector/SimpleInjector#388]
Visual Studio 2017 Professional with Nuget 4.0.0. When I try to install into a .Net 4.6.2 console project, I receive the following error:

```
Attempting to gather dependency information for package 'SimpleInjector.Integration.AspNetCore.Mvc.3.3.0' with respect to project 'MyProject', targeting '.NETFramework,Version=v4.6.2'
Gathering dependency information took 26.77 sec
Attempting to resolve dependencies for package 'SimpleInjector.Integration.AspNetCore.Mvc.3.3.0' with DependencyBehavior 'Lowest'
install-package : Unable to find a version of 'NuSpec.ReferenceGenerator' that is compatible with 'SimpleInjector.Integration.AspNetCore 3.3.0 constraint: NuSpec.ReferenceGenerator (>= 2.0.0-beta-bld14)', 'SimpleInjector.Integration.AspNetCore.Mvc 3.3.0 
constraint: NuSpec.ReferenceGenerator (>= 2.0.0-beta-bld14)'.
At line:1 char:1
+ install-package SimpleInjector.Integration.AspNetCore.Mvc
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:28.0164634
```

**Comment by dotnetjunkie** [comment]
Try again with [SimpleInjector.Integration.AspNetCore.Mvc v3.3.2](https://www.nuget.org/packages/SimpleInjector.Integration.AspNetCore.Mvc/3.3.2).

**Comment by BennieCopeland** [comment]
After looking at Nuget, I realized that ```NuSpec.ReferenceGenerator``` is an actual package instead of something built into Nuget like I originally thought. I suspect that it was unable to find this dependency for install because of it being a pre-release. Maybe something to ask the Nuget maintainers about. After I manually installed the ReferenceGenerator package using ```install-package NuSpec.ReferenceGenerator -IncludePrerelease -Version 2.0.0-beta-bld14```, I was able to install the SimpleInjector package with no further issues.

**Comment by dotnetjunkie** [comment]
The ReferenceGenerator is a NuGet package that you only need to to simplify building NuGet packages for a Visual Studio project and we use it for this purpose as well in Simple Injector. While building a NuGet package, the reference to the ReferenceGenerator itself isn't removed, which is odd, because the package at runtime never uses the ReferenceGenerator. Although I noticed this reference before in the past, I never thought it could cause any troubles. Well, was I wrong, or what?

What I did now is publish an updated version of both SimpleInjector.Integration.AspNetCore and SimpleInjector.Integration.AspNetCore.Mvc where I manually removed the references to the ReferenceGenerator. This should solve the problem (for now), while in the meantime I try to find a more durable solution, so that I don't have to manually remove the reference (since this is something I will obviously forget in the future).

**Comment by BennieCopeland** [comment]
Since it is only a build dependency, and you are still using project.json, you can change the dependency to look like this:

```
"dependencies": {
    "Microsoft.AspNetCore.Mvc.Core": "1.0.0",
    "Microsoft.AspNetCore.Mvc.ViewFeatures": "1.0.0",
    "Microsoft.AspNetCore.Mvc.Razor": "1.0.0",
    "NuSpec.ReferenceGenerator": {
        "version": "2.0.0-beta-bld14",
        "type": "build"
     },
    "SimpleInjector.Integration.AspNetCore": { "target": "project" }
  },
```

**Comment by dotnetjunkie** [comment]
Ah, that's interesting. Never new that option existed. Thanks. I'll add this right away.
