### ISSUE TITLE
How to resolve dependencies in the WebApiConfig.Register function

### ISSUE THREAD

**Issue by seancostigan** [simpleinjector/SimpleInjector#392]
I have a Web API application that uses Simple Injector based on the guidance shown in the docs (https://simpleinjector.readthedocs.io/en/latest/webapiintegration.html)

This is working great for my Web API controllers, but I have dependency in the WebApiConfig.Register() and I'm not sure how to resolve it.  There doesn't seem to be a clear way to inject the dependency.  I also found this section of the docs that discusses Web API filter attributes and having to revert to the Service Locator pattern (https://simpleinjector.readthedocs.io/en/latest/webapiintegration.html#injecting-dependencies-into-web-api-filter-attributes).  However, I have tried using this approach in WebApiConfig.Register, but the dependency is never disposed so this does not appear to be correct (I have a nested dependency on my DB Context so I want to make sure it gets cleaned up properly via dispose). 

I could manually resolve the dependency here, but it seems like there should be a way to do this via Simple Injector and I would like to follow best practices.

My code looks something like this:

```cs
public void Register(HttpConfiguration config)
{
    var appSettings = GlobalConfiguration.Configuration.DependencyResolver
        .GetService(typeof(IAppSettings)) as IAppSettings;
    var allowedOrigins = appSettings.GetAllowedOrigins();
    
    var cors = new EnableCorsAttribute(allowedOrigins, "*", "*");
    cors.SupportsCredentials = true;
    config.EnableCors(cors);
                
    // Web API routes
    config.MapHttpAttributeRoutes();

    config.Routes.MapHttpRoute(
        name: "DefaultApi",
        routeTemplate: "api/{controller}/{id}",
        defaults: new { id = RouteParameter.Optional }
    );                
}
```

**Comment by dotnetjunkie** [comment]
I assume it is the ` IAppSettings` that you try to prevent resolving. IMO you should even prevent this class from being registered completely. I assume that `IAppSettings` contains all application configurations. Although it is fine to have such type of object in your Composition Root, having application code depend on it leads to an [Interface Segregation Principle](https://en.wikipedia.org/wiki/Interface_segregation_principle) violation which can lead to sweeping changes to code and unit tests. I used this design myself in the past, until I found out that such design is troublesome.

Instead, rather inject just the values into a consumer that it requires. This will often just be a single value (such as a configuration string) or a group of 2 or 3 values (for instance for configuring mail send functionality). Doing this makes it really clear what configuration values a class needs. Makes it much easier to test such class, since it is clear what values it requires.

When a consumer requires multiple values, it might be good to extract those to a Value Object containing just these values. I found it really practical to compose my AppSettings class out of these smaller Value Objects.

This still leaves you with the need to configure CORS. This however can be simply done by passing on the configuration object (that you read during an earlier stage) onto the `Register` method:

``` c#
public void Register(HttpConfiguration config, AppSettings settings) { ... }
```

Notice how I removed the `IAppSettings` interface: there is typically little use for an interface, when the implementation is a data-centric object. Interfaces are for hiding behavior, but:

 1. Your settings objects will typically have no behavior, since you should load configuration values at startup, not while the application is running. Loading them at startup allows your application to fail-fast.
 2. Only the Composition Root should use this big settings objects in its fullness; individual components should only use little parts of it. This means there is only 1 implementation of your `AppSettings` class and the Composition Root already takes a dependency on it. Extracting an abstraction out of it would make little sense.

**Comment by seancostigan** [comment]
Thank you for your quick response.  Passing in the AppSettings as a param does make sense, but I have a few questions.

1. In Application_Start in Global.asax, the call to WebApiConfig.Register is made like this: 

```cs
GlobalConfiguration.Configure(WebApiConfig.Register);
```
How do I call Register() if I make the change you suggested above (non-static method and add AppSettings parameter)?
2. Related to your point #2, how do I build the AppSettings object in the composition root? This object has nested dependencies will I just need to build those nested dependencies manually and pass them to the constructor (basically handle this outside the scope of Simple Injector)? 
3. This is more of a point of clarification for me, but when using the Service Locator pattern (as recommended for Filter Attributes), the dependencies are disposed properly, but in the WebApiConfig they were not. Do you know the reason for this? When applying the Service Locator pattern, how does it determine when to perform cleanup?

**Comment by dotnetjunkie** [comment]
> How do I call Register() if I make the change you suggested above

``` c#
AppSettings settings = LoadAppSettings();
GlobalConfiguration.Configure(config => WebApiConfig.Register(config, settings));
``` 

> how do I build the AppSettings object in the composition root? This object has nested dependencies

Can you show how this class looks like? What dependencies does it have. How does it use them?

**Comment by seancostigan** [comment]
AppSettings has a dependency on a business object, which has a dependency on a dataObject, which has a dependency on the DB Context.  All dependencies are handled via constructor injection.

**Comment by dotnetjunkie** [comment]
Let me take a step back. The solution to take depends on what kind of data you have. I typically differentiate between:

 - Configuration data: data that gets determined once during application startup and never changes after that.
 - Runtime data: data that gets generated during the request and is typically request specific.

But there obviously is a third kind of data, which is kind of in the middle: Configuration data that might change on each request. If we look however what solution we require for this third type, we see that the solution is the same as is with the runtime data.

So the question really is, do you load this configuration data once (in your case from the database) and keep that data around for as long as the application lives, or is that data change during the lifetime of your application. The former fits into the _Configuration_ category, while the latter fits into the _Runtime data_ category (even though it might be configuration data as well).

The advice goes as follows:

 - **In case of *Configuration data***: You load the configuration values before configuring your DI Container. This way the configuration values can be used to wire up the components that require these configuration values, while keeping the configuration [verifiable](https://simpleinjector.readthedocs.io/en/latest/howto.html#verify-the-container-s-configuration). In your case this means that you will have to create those few components that are required for loading this configuration values by hand, before wiring the container. Typically you will only need one or two components to get the configuration values from the database, so this is no big deal.
 - **In case of *Runtime Data***: You define abstractions that allow you to load these configuration values. The abstraction allows you to lazy-load the configuration values _after_ your components have been wired-up in the container and even after the container has been verified. An abstraction is typically required, because you would like to apply things like caching to such abstraction, to allow the values to change at most once per request, or once per session. This does mean that the abstraction is queried for those configuration values _after_ the object graph has been constructed, since [injection constructors should be simple, fast and reliable](http://blog.ploeh.dk/2011/03/03/InjectionConstructorsshouldbesimple/). Neither do you want to inject runtime data directly into your injection constructors: that's [an anti-pattern](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=99).

So those are your two options.
