### ISSUE TITLE
SimpleInjector.Packaging RegisterPackages - use params for assemblies parameter?

### ISSUE THREAD

**Issue by tiesont** [simpleinjector/SimpleInjector#397]
I noticed when updating my `container.RegisterPackages()` call that the `assemblies` parameter requires an "actual" collection, rather than allowing either a single item or a collection. The same parameter in, say, `container.RegisterMvcControllers` in the SimpleInjector.Integration.Web.Mvc assembly accepts a params. Could the packages extension be updated to work the same way?

If I'm not being clear, here's what I mean:

`public static void RegisterMvcControllers(this Container container, params Assembly[] assemblies)`

vs

`public static void RegisterPackages(this Container container, IEnumerable<Assembly> assemblies)`

Notice that RegisterPackages does not have the `params` modifier. I could do a simple pull request, and I don't see where the logic in the method needs to change at all, so should be non-breaking?

This is what I would change the method to:

`public static void RegisterPackages(this Container container, params Assembly[] assemblies)`

**Comment by dotnetjunkie** [comment]
Main reason we didn't add this overload, is that it conflicts with the already existing (but deprecated) `RegisterPackages()` method. As long as this method exists, the `params` overload can't be added.

`RegisterPackages()` is deprecated because it uses `AppDomain.GetAssemblies()` internally, but this method is very unreliable, because it only retrieves the already loaded assemblies. But having a `params` overload allows developers to call `RegisterPackages` without parameters, but this will currently fallback to the deprecated `RegisterPackages()` overload. This will be very confusing.

So a new overload can only be added, once the default overload has been removed. This will be in v5.

In the mean time, just pass in an array with one or two values.

**Comment by tiesont** [comment]
That's actually what I'm already doing. Thanks for the explanation. Assume it's okay to close this?

**Comment by dotnetjunkie** [comment]
I'll close it for now. I will create a new work item when we're starting work for v5.
