### ISSUE TITLE
Idiomatic Simple Injector way of providing a container adapter for Rebus

### ISSUE THREAD

**Issue by mookid8000** [simpleinjector/SimpleInjector#404]
In [Rebus](https://github.com/rebus-org/Rebus) I have made a "container adapter" for Simple Injector.

A "container adapter" in Rebus lingo is a thing that helps you

* look up message handler instances
* hold the bus singleton instance, disposing it when the container is disposed
* set up injection of `IBus` (which naturally has a singleton lifestyle) and `IMessageContext` (which must be resolved by a factory method because it is "ambient" and is retrieved from the logical call context)

When looking up message handlers, the situation is this: An incoming message `TMessage` must be handled and there can be any number of handlers. Moreover, handlers must be resolved "polymorphically", so that e.g. the message type

    class SomeMessage : IAccountMessage { ... }

results in a pipeline of handlers implementing `IHandleMessages<SomeMessage>`, `IHandleMessages<IAccountMessage>`, and `IHandleMessages<object>`

Some containers do polymorphic resolve by default because of the contravariant declaration of the message handler interface as `IHandleMessage<in TMessage>`. Other containers need explicit calls to resolve each compatible handler implementation closed with superclasses and implemented interfaces.

I thought I had these things nailed in [Rebus.SimpleInjector](https://github.com/rebus-org/Rebus.SimpleInjector), but because of [this question](http://stackoverflow.com/questions/43385332/rebus-multiple-queues-based-on-content) I am getting an impression that Simple Injector users somehow expect it to behave differently regarding how handlers are registered and resolved.

Therefore my questions are: _When I want to implement [this interface](https://github.com/rebus-org/Rebus/blob/master/Rebus/Activation/IHandlerActivator.cs) by resolving all compatible message handler implementations with Simple Injector, a) what would be The Cool Simple Injector way of registering message handlers, and b) what would be The Awesome Simple Injector way of resolving them?_

I appreciate any hints that can lead me towards a great implementation of Rebus' `SimpleInjectorContainerAdapter` 😎

**Comment by dotnetjunkie** [comment]
> b) what would be The Awesome SimpleInjector way of resolving them?

Simple Injector OOTB supports resolving collections of variant interfaces. So the following should do the trick:

``` C#
_container.GetAllInstances<IHandleMessages<TMessage>>()
```

> a) what would be The Cool SimpleInjector way of registering message handlers

Your current implementation doesn't seem to register handlers, but perhaps that's explicit and something that you would like to defer to the user (which might actually be a good thing to do). Nonetheless, since you are calling `GetAllInstances` you should use `RegisterCollection` to register the handlers. You can do this by passing in either a list of assemblies or a list of types. With the list of assemblies, Simple Injector will find the correct types for you. Simple Injector will automatically filter out: composites, decorators and generic type definitions.

Example:

``` c#
container.RegisterCollection(typeof(IHandleMessages<>), listOfAssemblies);
```

**Comment by dotnetjunkie** [comment]
I  see this in your code:

``` c#
container.Options.ResolveUnregisteredCollections = true;
```

You should not call this on behalf of the user, because:

1. it is a global setting that affects other collection registrations as well
2. it is not required

This should not be required, because when the user calls `container.RegisterCollection(typeof(IHandleMessages<>), ...)` the collection is registered and that will allow the user to resolve empty collections for messages with no handler.

**Comment by dotnetjunkie** [comment]
Furthermore, disposing of handlers should not be required, because:

1. Simple Injector will dispose resolved handlers when they have a lifestyle other than `Transient`.
2. In case there is a transient handler that implements `IDisposable`, Simple Injector will throw an exception whenever the user calls `Verify()`, because of [this Diagnostic Warning](https://simpleinjector.readthedocs.io/en/latest/disposabletransientcomponent.html).

That means that you can remove the call to `transactionContext.OnDisposed` from the `SimpleInjectorContainerAdapter`.

**Comment by dotnetjunkie** [comment]
As it seems, the Simple Injector integration could be minimized to the following Composition Root:

``` c#
var container = new Container();

container.RegisterCollection(typeof(IHandleMessages<>), listOfAssemblies);
container.RegisterSingleton(bus);
```

With the following `IHandlerActivator`:

``` c#
public class SimpleInjectorHandlerActivator : IHandlerActivator
{
	readonly Container _container;
	public SimpleInjectorContainerAdapter(Container container) { _container = container; }

	public async Task<IEnumerable<IHandleMessages<TMessage>>> GetHandlers<TMessage>(
		TMessage message, ITransactionContext transactionContext) =>
		 Task.FromResult(_container.GetAllInstances<IHandleMessages<TMessage>>());
}
```

We can add some optional features to the Composition Root when required, for instance:


``` c#
container.RegisterSingleton(bus.Advanced.SyncBus);
```

When the user requires to access the `MessageContext`, it's best not to inject it directly, because it is runtime data, while [injecting runtime data into application components is an anti-pattern](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=99). Instead, the user can define the following abstraction:

``` c#
public interface IMessageContextProvider
{
	IMessageContext Current { get; }
}
```

Where he defines the following implementation as part of his Composition Root:

``` c#
public class MessageContextProvider : IMessageContextProvider
{
	public IMessageContext Current => MessageContext.Current;
}
```

With the following registration:

``` c#
container.RegisterSingleton<IMessageContextProvider>(new MessageContextProvider());
```

I would say this is the most idiomatic integration of Rebus with Simple Injector, although I do understand that this practice (especially not injecting `IMessageContext` directly) might depart from the common use of Rebus (as shown in its documentation).

**Comment by mookid8000** [comment]
Thank you very much for your thorough answer 😄 

I will definitely fix the `ResolveUnregisteredCollections` thing..... I don't remember clearly why I added it though.... seems like a pretty random thing to do, so I might have had a good reason why I felt it was necessary..... I'll be back 😄

**Comment by dotnetjunkie** [comment]
Does Rebus allow first level and second level retry on message handlers? And if so, how does Rebus identify individual message handlers (since they are returned as a list)? If Rebus does this by calling `.GetType()`, does that mean that message handlers can't be wrapped with decorators?

I browsed through the docs to find out how to replace the default `IHandlerActivator`, but couldn't find it. Can you point me to this place in the documentation that shows this?

**Comment by mookid8000** [comment]
> Does Rebus allow first level and second level retry on message handlers? And if so, how does Rebus identify individual message handlers (since they are returned as a list)? If Rebus does this by calling .GetType(), does that mean that message handlers can't be wrapped with decorators?

When a message is dispatched to one or more message handlers, they are invoked in succession, and if that fails the message will be completely rolled back into the input queue. When the message is received again, the entire handler pipeline will be invoked once more.

This means that Rebus does not need to track message handlers individually – in fact it doesn't even care what they are, so you can decorate them as much as you like 😃 

> I browsed through the docs to find out how to replace the default `IHandlerActivator`, but couldn't find it. Can you point me to this place in the documentation that shows this?

[This page](https://github.com/rebus-org/Rebus/wiki/Container-adapters) hints at it, although it is not explicitly documented – the way you do it is simply to pass your implementation of `IHandlerActivator` to the `With` method like so:

    Configure.With(yourHandlerActivator)
        .(...)
        .Start();

**Comment by dotnetjunkie** [comment]
I'm making this issue into a reference page for Rebus until either this all is integrated into a Rebus integration library, or added to the integration guide of the Simple Injector documentation.

Here's some useful information about working with Scoped registrations as part of message handler components:

- [DbContext creation into message handler](https://stackoverflow.com/questions/43518345/dbcontext-creation-into-message-handler)
