### ISSUE TITLE
An alternative for IOptions<T>

### ISSUE THREAD

**Issue by guy-lud** [simpleinjector/SimpleInjector#406]
Hello Guys,

I really love the work you guys are doing, especially with your logic behind every architectural design.
Your API are great and as developer that truly believes in SOLID  your constraints are wonderful.

Anyway after a brief into, I've recently read your posts about IOptions and why you guys think it's not such a good idea to use them. (I totally agree).

So I've developed a small framework to replace IOptions and i wanted to get you opinion on it.

Could you please take a look?

[SimpleConfig](https://github.com/existall/SimpleConfig)

Many thanks in advance

Guy

**Comment by dotnetjunkie** [comment]
Hi Guy,

I haven't looked at the code, just read de `readme.MD`. 

As I understand, your library is able to dynamically generate implementations of interfaces that define configuration objects. This removes the DIP violation because it prevent coupling to a framework abstraction.

I'm afraid however not all your assumptions are correct. For instance, you say:

> All of the good IOC containers out there will tell you that injecting a string into a service is a bad idea. The best of them won't let you do it.

There is nothing inherently wrong with letting classes depend on configuration values like strings. Making a registration for `string` however is a bad idea, because `string` is an ambiguous type; we might have dozens of different values we'd like to inject. Still, we can register `EmailSender` as follows and this is completely fine:

``` c#
container.RegisterSingleton<IMailSender>(new EmailSender(emailServiceUrl));
```

Another thing you are stating is:

> In order to inject IOption<SomeClass> SomeClass have to be a concrete class and not an interface.

There is nothing wrong with dependencies on concrete classes, as long as these classes are mere data containers (DTOs, messages, entities, View Models, etc). Hiding data objects behind abstractions is typically not very useful, because abstractions allow hiding behavior. This allows us to replace, mock, intercept or decorate that _behavior_. When it's just data, there is not much to replace, intercept or decorate.

For that reason, it's just fine to let your class depend on `EmailProviderConfiguratation`. 

> this is not scale-able in any way and the last thing we want to do is to manually configure each configuration class.

This is debatable. Although I can imagine that this might hold true in really big applications, I haven't seen this happening in the applications I helped develop in the last few years. There is typically a finite set of configuration values, grouped in perhaps a dozen configuration objects. Since these configuration objects (such as `EmailProviderConfiguratation`) are quite stable, there is little maintenance to them.

So instead of letting application code depend on abstractions when it comes to configuration values, I rather inject a concrete configuration class. I make sure this class is immutable. This prevents the value from ever being changed, and ensures that the Composition Root must completely initialize it; no values can be forgotten. This allows the application to _fail-fast_ when values are missing.

Doing so simplifies testing, because test code is otherwise forced to create an implementation of that configuration interface itself.

This doesn't mean though that what you are doing is bad. It's already a great improvement over `IOption<T>`. Hell yeah! `IOption<T>` just doesn't make sense, at all!

I hope it makes sense?

**Comment by guy-lud** [comment]
@dotnetjunkie  thank you very much for your reply, 

Yet i disagree with some of your intakes like strings as parameters and concrete classes  i highly value your opinion (I am a bit more strict developer, since new developers tend to do stupid things.)

if you can spread the word about SimpleConfig (guess how i got the idea for the name) it would be great.

and again, thank you very much
