### ISSUE TITLE
Scoped (AsyncScopedLifestyle) and Singleton

### ISSUE THREAD

**Issue by elusivecube** [simpleinjector/SimpleInjector#419]
Hello,
I'm trying to understand how the async scoped lifestyle works when registering IDisposable instances with a lifestyle of scoped, specifically for ASP.NET Web Api. I am injecting via constructor in the controller and setting the instance to a private variable. My methods are also marked as async, and these instances are called within these types of methods. Does this instance have the Dispose method called automatically after the method and controller have been called or does it need wrapped around  a using statement with `AsyncScopedLifestyle.BeginScope(container)` in order to be disposed? How does simple injector handle object disposition that are marked as scoped?

Also, when registering an object with a life style of Singleton, does simple injector implement some kind of object locking for singleton instances?

Thanks!

**Comment by dotnetjunkie** [comment]
> does it need wrapped around a using statement with AsyncScopedLifestyle.BeginScope(container) in order to be disposed?

Here's a simple example of using the `AsyncScopedLifestyle` from the [Simple Injector documentation](https://simpleinjector.readthedocs.io/en/latest/lifetimes.html#asyncscoped):

``` c#
var container = new Container();
container.Options.DefaultScopedLifestyle = new AsyncScopedLifestyle();
container.Register<IUnitOfWork, NorthwindContext>(Lifestyle.Scoped);

using (AsyncScopedLifestyle.BeginScope(container)) {
    var uow1 = container.GetInstance<IUnitOfWork>();
    await SomeAsyncOperation();
    var uow2 = container.GetInstance<IUnitOfWork>();
    await SomeOtherAsyncOperation();

    Assert.AreSame(uow1, uow2);
}
```

In other words, to be able to resolve instances that are registered using the `AsyncScopedLifestyle`, a call to `GetInstance` must be wrapped in a `using (BeginScope(container))` call.

Whenever you try to resolve a scoped instance (or build an object graph that contains a scoped instance) while not inside an active scope, Simple Injector will throw an exception, as explained [here](https://simpleinjector.readthedocs.io/en/latest/decisions.html#dont-allow-resolving-outside-an-active-scope) in the documentation.

What this means is, that, in case you _don't_ get an exception, there _is_ an active scope.

So typically, while using `AsyncScopedLifestyle`, you will have to wrap an operation in a scope. When using the [Simple Injector integration package for Web API](https://www.nuget.org/packages/SimpleInjector.Integration.WebApi/) however (and specifically the [SimpleInjectorWebApiDependencyResolver](https://simpleinjector.org/ReferenceLibrary/?topic=html/T_SimpleInjector_Integration_WebApi_SimpleInjectorWebApiDependencyResolver.htm), it will ensure that a complete web request is wrapped in a scope of the `AsyncScopedLifestyle`.

This is the reason that you are not getting an exception, since it 'just works'.

So long story short, you need to wrap a scope around an operation for everything to even work. It's not so much that disposing won't work, but Simple Injector will blow up in your face when there is no scope (because every other behavior would be a design flaw). 

> Does this instance have the Dispose method called automatically after the method and controller have been called. How does simple injector handle object disposition that are marked as scoped?

Simple Injector will cache scoped objects inside a `Scope` instance and those cached instances will get disposed once `Scope.Dispose()` is called. If you wrap your `Scope` in a using block, this obviously means that the `Scope` instance gets disposed when the using block ends. In case of Web API, since the Simple Injector integration will wrap a request in a scope, it will ensure that dispose is called when the request ends. This might not directly be after the controller has been called, but it will be one of the last things that typically happens during a request.

There are many interesting details to how Simple Injector disposed instances, for instance:

 - Simple Injector ensures that objects are disposed in opposite order of creation. This ensures that objects can use disposable dependencies in their own `Dispose` method, without having to fear that such dependency is already disposed itself.
 - Simple Injector guarantees that all `Dispose` methods of all disposable objects will be called, even if the `Dispose` method of an instance throws an exception.

> when registering an object with a life style of Singleton, does simple injector implement some kind of object locking for singleton instances?

Absolutely. Simple Injector guarantees that under any condition, there will be _at most_ one instance of a type that is registered as *Singleton*. Even in case of multi-threaded applications. Simple Injector uses locks internally to make sure there are not accidentally two instances created. After such instance is created and cached however, locks aren't required anymore. This holds for every part of Simple Injector. Simple Injector is 'lock free' in the happy path, while during initialization, it depends on locks to keep the container thread-safe.

**Comment by elusivecube** [comment]
Thank you for the clarification!
