### ISSUE TITLE
Simple Injector - support all features from ASP.NET Core MVC

### ISSUE THREAD

**Issue by guy-lud** [simpleinjector/SimpleInjector#427]
Hell @dotnetjunkie,

I really love Simple Injector and the Philosophy round it.

I cloned your repository in order to develop full integration with MVC core (include View inject), yes i know that you your grasp on the matter is different. yet i believe that the Ioc sould not limit the freedom of a developer to chose his ways.

So to make a long story short i have two questions ?

1. Is this  kind of endeavor will be something you will be able to approve ?
2. why is the solution is still using xproj ? is there a reason behind it ?

thanks 

Guy.Lud

**Comment by dotnetjunkie** [comment]
> Is this kind of endeavor will be something you will be able to approve ?

Can you elaborate what you exactly mean? If you are asking whether there will be a [Conforming Container](http://blog.ploeh.dk/2014/05/19/conforming-container/) adapter for ASP.NET Core, the answer is simply: no, there won't be, because it is _impossible_ to do so. For a detailed description, read [this](https://simpleinjector.org/blog/2016/06/whats-wrong-with-the-asp-net-core-di-abstraction/). So it's not so much that Simple Injector "limits your freedom", it is actually ASP.NET Core with its Conforming Container abstraction that decided to do so.

So please don't blame us; me and others have made endless efforts in improving this situation (just read [this](https://github.com/aspnet/DependencyInjection/issues/433) and [this](https://github.com/aspnet/DependencyInjection/pull/416) and [this](https://github.com/aspnet/Mvc/issues/5403) for starters), but up untill now, Microsoft seems unwilling to do anything that improves the situation.

> why is the solution is still using xproj ? is there a reason behind it ?

The source code still uses xproj because I haven't migrated the project to Visual Studio 2017. xproj is a 2015 thingy. This has proven to be much more work than just letting VS 2017 do the conversion on your behalf, so that's still something that's on the todo list.

**Comment by guy-lud** [comment]
@dotnetjunkie , I am sorry. I did not meant in my comments that i blame you in any way.
I agree with you that MS did some really tidily coupling between it's DI and the ASP.NET frameworks.

I think that the pure API Simple provide is the better way to use frameworks.

anyway i successfully created a bridge between MS-DI and Simple so each of them will deal with it's own responsibility in the matter.

i wanted to if this is something you would like to incorporate within SimpleInjector Core.MVC 
or not. (im other words will you accept PR to such thing) ?

**Comment by dotnetjunkie** [comment]
> I did not meant in my comments that i blame you in any way.

I understand, just wanted to be sure we (and anyone else reading this) is on the same page.

> i wanted to if this is something you would like to incorporate within SimpleInjector Core.MVC
or not.

Can you elaborate on what it is you are missing from the integration that Simple Injector provides? How do you like to bridge between SI and Core DI?

**Comment by guy-lud** [comment]
Mostly i want to support View directive inject, Why you ask ?
well as like you i don't want any logic in my view BUT i need to support some infrastructure in my views. for example i don't like viewData so i use LayoutContext with is resolved currently  via a well hidden ServiceLocator pattern. I use server side bundling and minification and compilation of js rather than npm.
So i rather use inject on one View instead of override RazorPage<T>. and many more. (We totalty changed MVC and Razor to support what we found out a better way). So with Inject it will be cleaner and nicer and closer to Good rather than Bad

**Comment by guy-lud** [comment]
Regarding the bridge, what I've done is to make a hybrid ServiceResolver and Hybrid ServiceScopeProvider to support such a way that everything asp.net needs he gets from MS-DI and everything the App needs it gets from SimpleInjector.

**Comment by dotnetjunkie** [comment]
I'm not sure this is something I would like to add to integration package, but I am interested in seeing your code. Do you mind making a pull request so I can take a look at this?

**Comment by guy-lud** [comment]
@dotnetjunkie, well i am working with vs 2017 and csproj :), so with your permission i will upload a sample app  with my code to github thus you can review the code. No real magic there.

**Comment by dotnetjunkie** [comment]
Permission granted :)

**Comment by guy-lud** [comment]
@dotnetjunkie You can view the code in this [repo]( https://github.com/existall/SimpleInjectorSampleApp), 

please view it as a POC code not prodcution wise :)

**Comment by dotnetjunkie** [comment]
Hi guy, sorry for my late response. I'm on holiday right now but will take a look at this once I get back.

**Comment by guy-lud** [comment]
No worries, have fun

**Comment by dotnetjunkie** [comment]
It took some time before I understood what your POC is trying to do. But now I understand that what you created is _not_ a Conforming Container adapter, but merely a _Service Locator_. Your Service Locator will first query the ASP.NET Core container and when it returns `null` it will fall back to Simple Injector.

This approach is a great way to circumvent the use of a Conforming Container (since the Conforming Container will never work with Simple Injector due to incompatibilities) where callers are unaware of the existence of those two Composition Engines.

However, making this bridging Service Locator globally available can lead to serious problems, for instance when it is requested to build up object graphs that should be built by Simple Injector. Since the Core configuration system will in that case not be able to build the object graph, it depends on its state whether it returns `null` or throws an exception. For instance, ASP.NET Core MVC Controllers are automatically registered by MVC in the Core configuration system, while they are application components and therefore should be composed by Simple Injector. This will lead to having controllers registered in Core, while their dependencies are not (since both controllers and their dependencies are registered in Simple Injector). When a controller is resolved through this new bridging Service Locator, an exception will be thrown. This might hold for other common components as well.

So my advice would be to -whenever possible- only use such bridge locally -not globally, meaning that you should apply it in such way that it is only used when with the `@Inject`. Whether this is possible or not is unclear to me.

You might understand that I'm very hesitant to add such construct to the integration library. Instead I rather wait for other questions to come in to get a better view on the problem and look whether there is a better solution to this problem.

**Comment by dotnetjunkie** [comment]
Hi @guy-lud,

Could you take a look at [the following extension method](https://github.com/simpleinjector/SimpleInjector/issues/442#issuecomment-317423080). It allows registrations to be automatically cross-wired in case the registration is missing from Simple Injector, but does exist in the Core container. I think it is similar to your idea, but now goes the other way, and there should be less problems involved with this.

Your can report your findings on issue https://github.com/simpleinjector/SimpleInjector/issues/442.

**Comment by guy-lud** [comment]
Hey @dotnetjunkie,
Sorry for not getting back at your last comment for some reason i missed it.
I'll take a look at the last remark and the extension method ASAP.

**Comment by guy-lud** [comment]
Hi @dotnetjunkie 

I've changed the code at the simpleApp to support more situations as a bridge between SimpleInjector and MS DI. I know it's still a global ServiceLocator yet until MS will use Composition Root and non-Conforming Container but at least the inject works.

WDTY ?

**Comment by dotnetjunkie** [comment]
I have no idea what WDTY means.

**Comment by dotnetjunkie** [comment]
btw, can you describe the changes you made to the extension method and what the function is of those changes? What is the improvement and why is this important? What did you find out?

**Comment by guy-lud** [comment]
> I have no idea what WDTY means.

Sorry it has a typo it should be WDYT -> What Do You Think.

**Comment by guy-lud** [comment]
1. Extension Method -> I am using the created MS `ServiceProvider` from `ServiceCollection` to get the `IHttpContextAccesssor`, thus we'll be able to get `HttpContex.RequestServices.GetService` which is the `CompositeServiceProvider` with the child `MS ScopeServiceProvider`. this way we are sure that services requested from MS container are scoped.

2. By using your extensions method the `ControllerActivator`, `ViewComponent` etc. will get services from MS container (CrossWire) - although if we'll use the CompositeServiceProvider inside the `SimpleInjectorControllerActivator` i don't think we'll need the crossWire (yes i know ServiceLocator).

3. Now the inject directive will use the scoped CompositeServiceProvider in the RazorPageActivator thus allowing us to use it.

**Comment by dotnetjunkie** [comment]
Simple Injector v4.1 has been released. The ASP.NET Core Integration package v4.1 contains a new `AutoCrossWireAspNetComponents` method that simplifies cross-wiring framework components. For examples, please see [the docs](https://simpleinjector.readthedocs.io/en/latest/aspnetintegration.html).
