### ISSUE TITLE
Reloading IOptions<T> ASP.NET Core configuration values without application restart

### ISSUE THREAD

**Issue by HassanHashemi** [simpleinjector/SimpleInjector#429]
the [docs](http://simpleinjector.readthedocs.io/en/latest/aspnetintegration.html#working-with-ioption-t) is just providing a work around to access the configuration, this method dose not support binding to the configuration file.

am i missing some thing here?

**Comment by dotnetjunkie** [comment]
As I see it, the docs don't provide a "workaround", they provide the solution, which is not to inject `IOptions<T>` in your constructors and it states that you should read the configuration file at startup, never lazily.

What is the problem you are trying to solve here? Can you elaborate on this? What does it mean to be "binding to the configuration file"?

**Comment by HassanHashemi** [comment]
Yes, how can i bind to Configuration file.

**Comment by dotnetjunkie** [comment]
> when the app is deployed the change should dynamically be reflected into the application.

What does this mean? You want to be able to change the config file and restart the application?

**Comment by HassanHashemi** [comment]
No, consider a situation where i store conncetion string in config file, later i might change config file and expect the value of config to be changed in the program. (Typical web.config style)
Right now the solution in docs reads the value just once in the startup and thats all.

**Comment by dotnetjunkie** [comment]
What requires you to be able to change such value while the application is running? This is usually quite tricky, because it can lead to race conditions.

But either way, nothing is stopping you to wrap an IOptions in an adapter class that you inject into your application classes. You can even directly load an IOptions at startup and register it using RegisterSingleton into the container.

**Comment by HassanHashemi** [comment]
Registering it as a Singleton dose not solve the problem that we are reading the config file once at startup. race condition will not happen in most cases because the config file will be updated so rarely.

**Comment by dotnetjunkie** [comment]
> Registering it as a Singleton dose not solve the problem that we are reading the config file once at startup.

That's true, because an IOptions will never change after it is loaded. You will need to use [IOptionsSnapshot](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration#ioptionssnapshot) for this with reload enabled(as explained in the ASP.NET docs). You will have to register this IOptionsSnapshot with a scoped lifestyle, by cross-wiring it from the built-in configuration system. For instance:

``` C#
container.Register<IOptionsSnapshot<ConfigValues>>(
    () => app.GetRequestService<IOptionsSnapshot<ConfigValues>>(),
    Lifetime.Scoped);
```

> race condition will not happen in most cases because the config file will be updated so rarely.

Race conditions per definition only happen rarely, so unless you can stop the value from changing during a single request, or can block all requests during the time of the config update, the race condition is guaranteed to happen, since race conditions work like Murphys Law. Registering the snapshot as scoped however will effectively prevent race conditions from happening, since each request will only get one snapshot.

**Comment by HassanHashemi** [comment]
Corss-wiring solved problem of resolving the instance, but binding dose not work yet.
here is what i have done:
```
ConfigureServices Method:
services.Configure<UploadDirectorySettings>
                (Configuration.GetSection("UploadDirectorySettings"));
```
and for the SimpleInjector i have:
````
 source.Register(() =>
                app.ApplicationServices.GetService<IOptionsSnapshot<UploadDirectorySettings>>(),
                    Lifestyle.Singleton);
```
thanks Steven for the great support.

**Comment by dotnetjunkie** [comment]
`ApplicationServices` will not work, since that leads to singletons. I consider this to be a big design flaw in .NET Core, since it should have thrown an exception when a scoped or transient service is resolved from the root container.

Please use the example I provided you with. `GetRequestService` is a Simple Injector-provided extension method that allows resolving scoped instances from the built-in configuration system.

**Comment by HassanHashemi** [comment]
this code:
`
     source.Register(() =>
                app.GetRequestService<IOptionsSnapshot<UploadDirectorySettings>>(),
                    Lifestyle.Transient);
`

will result into this exception:
`
System.InvalidOperationException: 'Unable to request service 'IOptionsSnapshot<UploadDirectorySettings> from ASP.NET Core request services.Please make sure this method is called within the context of an active HTTP request.'
`

**Comment by dotnetjunkie** [comment]
Please post the full stack trace
