### ISSUE TITLE
Question about registering multiple decorators generically but with specific implementations

### ISSUE THREAD

**Issue by MetalKid** [simpleinjector/SimpleInjector#432]
Hey guys.  I found your RegisterDecorator method and loved the possibilities this presents!  However, I ran into a small snag that I'd like to know how to handle "correctly".  I technically have an answer that works, but wanted to make sure I'm not abusing anything.

Ultimately, I'm trying to follow the Command pattern with ICommand and `ICommandHandler<TCommand>` (Along with the Query version).  The first thing I tested was just adding a generic `CommandHandlerException<T>` to catch any exceptions that come out of a command and handle them appropriately.  This worked great!  However, the next step is where I got into a little trouble.  I wanted to be able to add a `CommandHandlerValidation<>` decorator that would validate specific Command implementations.  Thus, I added a `ICommandHandlerValidation<T> : ICommandHandler<T>` and created specific implementations for each CommandHandler that actually needed validation (not all need it).  

My problem was that I don't want to have to manually register every single validation handler when I knew each were going to be specific to its command and I needed to make sure I had a specific order.  Steven over on StackOverflow showed this style (and it works great):

``` c#
container.Register(typeof(IValidator<>), assemblies);

var t1 = container.GetTypesToRegister(typeof(IValidator<>), assemblies);
var t2 = container.GetTypesToRegister(typeof(IValidator<>), assemblies,
    new TypesToRegisterOptions { IncludeDecorators = true });

foreach (Type t in t2.Except(t1)) {
    container.RegisterDecorator(typeof(IValidator<>), t);
}
```
Obviously, I have to do an extra step here to ensure I'm only registering `ICommandHandlerValidation<>` types, but this does actually work.  I just wanted to make sure that this is an alright thing to do.  Thanks!

**Comment by dotnetjunkie** [comment]
Decorators are typically used best for implementing cross-cutting code; not for business logic itself. In your case you are putting the validation logic (which is business logic) for a specific command into a decorator, which leads to the complication you are having.

Instead, validation is a concept that deserves an abstraction of its own. So you should create an `IValidator<T>` interface that functions as definition for code that validates a certain command or query. That will simplify those classes as well, since validation code now doesn't need to be concerned about wrapping and calling a decoratee.

To allow those validator classes to be invoked, you can create a single generic `ValidatorCommandHandlerDecorator<T>` that depends on an `IEnumerable<IValidator<T>>`. This way you have a single decorator that applies validation.

Now you can batch-register the `IValidator<T>` implementations using `RegisterCollection(typeof(IValidator<>), assemblies)`.

It prevents having to batch-register decorators, simplifies the validation code and promotes validation to a clear application artifact.

**Comment by MetalKid** [comment]
Ah, wonderful!  Doing it this way, the ValidatorDecorator would still be in the correct chain (I wanted to have that called at a specific place in the chain), but then I could have any number of Validation classes for a specific command (though, hopefully we'd only need/have one).  Thanks a lot!
