### ISSUE TITLE
RegisterConditional based on generic type constraint does not always detect overlap

### ISSUE THREAD

**Issue by TheBigRic** [simpleinjector/SimpleInjector#438]
The following test succeeds whereas I expected this test would fail with an exception telling me that there are overlapping registrations. Is overlapping not checked when the first predicate returns true?

``` c#
[TestMethod]
public void ConfigureContainer_Resolve_CheckResolvedType()
{
    // Arrange
    var container = new Container();

    container.RegisterConditional(typeof(IGeneric<>), typeof(GenericMarker1<>), 
                  Lifestyle.Transient, 
                  c => !c.Handled);
    container.RegisterConditional(typeof(IGeneric<>), typeof(GenericMarker2<>), 
                  Lifestyle.Transient, 
                  c => !c.Handled);

    container.Verify();

    // Act
    var instance = container.GetInstance<IGeneric<MarkerDouble>>();

    // Assert
    Assert.IsInstanceOfType(instance, typeof(GenericMarker2<MarkerDouble>));
}

internal interface IGeneric<T> { }

internal interface IMarker1 { }
internal interface IMarker2 { }

internal class GenericMarker1<T> : IGeneric<T> where T : IMarker1 { }
internal class GenericMarker2<T> : IGeneric<T> where T : IMarker2 { }

internal class MarkerDouble : IMarker1, IMarker2 { }
```

Because I'm totally depending on the awesomeness Simple Injector does with generic type constraints this was a use case I overlooked. I think I understand why overlapping is not detected. 

So the solution is to extend my predicate with some checks whether or not both marker interfaces are implemented?

**Comment by dotnetjunkie** [comment]
When the predicate of the first registration runs, `c.Handled` is `false`. Because of the `!` sign, the predicate returns `true` indicating that this registration should indeed be used.

So far so good, but now Simple Injector will run the predicate of the second registration as well, to test whether there is an overlap. Since the first registration is already selected, and thus handled, the `c.Handled`  property is `true`. Because of the negation, the the second predicate returns `false` indicating that this second registration should be skipped.

Because the second predicate returns `false`, there is no overlap and that's why the first registration is selected without Simple Injector throwing an exception.

Would you let both predicates return `true`, an exception would indeed occur:

> Multiple applicable registrations found for IGeneric&lt;MarkerDouble&gt;. The applicable registrations are (1) the conditional open generic registration for IGeneric&lt;T&gt; using GenericMarker1&lt;T&gt; and (2) the conditional open generic registration for IGeneric&lt;T&gt; using GenericMarker2&lt;T&gt;. If your goal is to make one registration a fallback in case another registration is not applicable, make the fallback registration last using RegisterConditional and make sure the supplied predicate returns false in case the Handled property is true.

**Comment by TheBigRic** [comment]
Ehh that's pretty stupid of me. Never thought about it being the same context... They should simply  remove ctrl-c, ctrl-v from functioning...

Thanx
