### ISSUE TITLE
How to use CrossWire to register ASP.NET Core MVC Identity

### ISSUE THREAD

**Issue by Dunnymeister** [simpleinjector/SimpleInjector#440]
Continuing a discussion here based on https://stackoverflow.com/questions/45162931/how-to-resolve-a-dependency-based-on-attributes-on-a-controller-in-asp-net-core/45165014

Following the documentation at https://simpleinjector.org/aspnetcore#working-with-asp-net-core-identity will get a working ASP.NET Core MVC Identity setup if you're using the default implementations. In my case, I have custom implementations of UserManager, IUserStore, IRoleStore and IPasswordHasher. Because the example did not contain any cases where a class had to be registered with SI _and_ cross-wired, this was more confusing than I feel it should have been.

For example, `container.CrossWire<ILoggerFactory>(app);` does not explicitly show a container.Register() call that registers an ILoggerFactory, so I wasn't sure how it was obtaining one. This lead to some confusion about how I was supposed to be cross wiring my own classes.

It was simple to work out in hindsight, but entirely avoidable if there was an example which showed something being registered *and* cross wired.

**Comment by dotnetjunkie** [comment]
Thank you for taking the time to formulate and post this.

You can find the implementation of `CrossWire` [here](https://github.com/simpleinjector/SimpleInjector/blob/master/src/SimpleInjector.Integration.AspNetCore/SimpleInjectorAspNetIntegrationExtensions.cs#L181) in the repository. What cross-wire does is the following:

- [Determine the lifestyle](https://github.com/simpleinjector/SimpleInjector/blob/master/src/SimpleInjector.Integration.AspNetCore/SimpleInjectorAspNetIntegrationExtensions.cs#L280) in which the cross-wired service is made in the Core configuration system.
-Make a registration based on the lifestyle, where a delegate is registered that forwards the call to the Core configuration system. In case the instance is `Scoped` or `Transient`, that instance is resolved from an active ASP.NET Scope, otherwise the instance is resolved from the `ApplicationServices`, which is a set of singletons.
- In case the registration is transient and the cross-wired service type implements `IDisposable`, the `DisposableTransientComponent` diagnostic warning is [suppressed](https://github.com/simpleinjector/SimpleInjector/blob/master/src/SimpleInjector.Integration.AspNetCore/SimpleInjectorAspNetIntegrationExtensions.cs#L225) on the registration, since ASP.NET will ensure that the instance is disposed. Not suppressing this would lead to false positives in Simple Injector's diagnostic system.

We deliberately left this information about what is happening under the covers out of the documentation, but in case it raises more questions, we might need to reconsider this strategy and add this information to the documentation.

>  my case, I have custom implementations of UserManager, IUserStore, IRoleStore and IPasswordHasher. Because the example did not contain any cases where a class had to be registered with SI and cross-wired, this was more confusing than I feel it should have been.

In case the abstractions are framework abstractions (as in: part of Identity Framework), you should typically register them in the Core configuration system. Since the Core configuration system will be in control over the construction of Identity components, you will have to add these interfaces to the Core configuration system, not to Simple Injector.

In case the abstraction are 'user defined', which means you created them yourself (or the Visual Studio template generated them for you), you will have to register them in Simple Injector.

Things however get a bit more complicated when used-defined implementations of framework abstractions again require dependencies that are part of the application. In that case you might need to cross-wire the other way around, i.e. register the type in Simple Injector and cross-wire it into the Core configuration system. For instance:

``` c#
container.Register<CustomIdentityUser>()
services.AddTransient<IdentityUser>(c => container.GetInstance<CustomIdentityUser>());
```

If you have any suggestions on how we could improve our docs, please let me know.

**Comment by tim-elvidge** [comment]
Ran into a simliar issue when I was creating creating a custom IUserClaimsPrincipalFactory<ApplicationUser> and it was confusing sorting out exactly how to go about this. Got it working in the end but it was awkward.

**Comment by dotnetjunkie** [comment]
With the introduction to the ASP.NET Core Integration package for Simple Injector v4.1, we introduced a new `AutoCrossWireAspNetComponents` extension method (see [docs](https://simpleinjector.readthedocs.io/en/latest/aspnetintegration.html)) that simplifies cross-wiring. When you call `AutoCrossWireAspNetComponents` inside the `Startup` class, you won't have to cross-wire any Identity Framework components manually. Instead, Simple Injector will request them from the ASP.NET configuration system for you.

The [Idenity Framework integration page](https://simpleinjector.readthedocs.io/en/latest/aspnetintegration.html#working-with-asp-net-core-identity) has been updated to reflect this.

To use this new feature, please upgrade Simple Injector and the integration packages to version 4.1.
