### ISSUE TITLE
Nested containers

### ISSUE THREAD

**Issue by paulomorgado** [simpleinjector/SimpleInjector#444]
I need to have nested containers where I can register dependencies but can inherit dependencies (not just the registrations but also already constructed types) from a parent container.

Basically, what I need is to intersect the dependency resolution on failure and see if it can be resolved by the parent container, if one exists.

**Comment by dotnetjunkie** [comment]
Can you go describe your particular case in more detail?

**Comment by paulomorgado** [comment]
Imagine a VisualStudio-like application with lots of areas. Each area belongs to a container (UI) that can belong to another.

Some UI containers will inject services to override the global services. UI elements will rely on services registered on the container (DI) they belong to.

Depending on the context, the Account service might be the employee, the customer, the employee on behalf of the customer, etc.

**Comment by dotnetjunkie** [comment]
Nested containers is a feature that is not supported by Simple Injector, because and it basically boils down to [this design decision](https://simpleinjector.readthedocs.io/en/latest/decisions.html#container-is-locked). Simple Injector does not allows making or changing registrations on a later point in time, because that can easily lead to hard to trace bugs.

This doesn't mean however that doing context based registrations is impossible, but you might need to take a different approach. For instance, when the injected service is depending on its surrounding object graph, you can use [context based injection](https://simpleinjector.readthedocs.io/en/latest/advanced.html#context-based-injection).

In case the used services need to depend on runtime data (e.g. based on the request that is executing), the typical solution is to write a proxy implementation that can forward the call based on this runtime information and forward it to one of the real implementations that implement the same interface as the proxy.

If you provide more detailed information on where you need this context based injection and how the code and interfaces look like, I can provide you with a more detailed answer of how to solve your problem.

**Comment by paulomorgado** [comment]
I'm aware of the design decisions and their reasoning and I'm not disputing them.

I'm already using conditional registrations. They can be quite complexo to setup but allow easy to develop and test components. But that's not exactly what I'm looking for here.

What I'm looking for is a [ServiceContainer](https://docs.microsoft.com/dotnet/api/system.componentmodel.design.servicecontainer)-like implementation using **SimpleInjector** features.

Back to the VisualStudio example, image a language service. All editors share common services but each editor window has its own language service.

I could just copy all registrations from the parent container to the child container, but I don't want the registrations only. I want that all already constructed instances required by the child be the same as the ones on the parent and, if resolving an instance on the child requires it to be created on the parent, that it be created on the parent and still allow conditional registrations on the parent.

**Comment by dotnetjunkie** [comment]
> I want that all already constructed instances required by the child be the same as the ones on the parent and, if resolving an instance on the child requires it to be created on the parent, that it be created on the parent and still allow conditional registrations on the parent.

You lost me. Can you show this with a simple example where you build your object graphs by hand?

**Comment by paulomorgado** [comment]
I cannot show a simple example of a very complex system.

Building objects is part of what my system does.

Using `ServiceContainer`, what I'm doing now, at every level, is creating a container with the parent level container as a parent container and adding all the services unique to that level and all the services that must override parent services. But `ServiceContainer` does not build the service instances itself like `SimpleInjector` does.

`Unity` has this feature: [Using Container Hierarchies](https://msdn.microsoft.com/library/ff650130)

**Comment by dotnetjunkie** [comment]
> I cannot show a simple example of a very complex system

I would love to help, but to be able to, you should be able to help me understand what you are trying to achieve. The best solution is highly dependent on the structure and design of the application.

You can't do a simple one-to-one mapping from Unity to Simple Injector, since both libraries are designed quite differently. That doesn't mean what you need is not possible to do with Simple Injector. To my knowledge, it has never been the case that things can't be done with Simple Injector.

If it is not possible for you to provide an example, it is best to stick to using a container that does support Child Containers ootb.

Good luck.

**Comment by vladimir-kovalyuk** [comment]
@dotnetjunkie it seems to be useful for implementing Onion Architecture http://blog.thedigitalgroup.com/chetanv/2015/07/06/understanding-onion-architecture/
If all components belonging to a layer are registered in the container corresponding to this layer, and containers are nested like onion, it would allow to ensure inner layer's components does not make dependencies on outer layer's components.
As depicted in the article a lot of containers support this ootb or via extensions. I would prefer this as an extension.

**Comment by dotnetjunkie** [comment]
I'm not sure whether I understand correctly, but am I correct that you:

- wish to register your components _outside_ the [Composition Root](http://blog.ploeh.dk/2011/07/28/CompositionRoot/)
- Have an isolated container instance per layer in the application that holds the registrations for that particular layer

If my understanding is correct, could you provide me with links to how other containers support that what you wish to do?

Note that it is not custom nor advisable to have an isolated container per layer. This holds for all DI Containers. You typically create 1 container per Composition Root, not per layer.

Also note that the general consensus is that all application components should be registered in the entry point of the application (the Composition Root), not in a specific layer itself, since that causes an unwanted dependency on the DI Container, and can limit flexibility.

Also note that Simple Injector uses Scoping to achieve similar behavior as where some other containers (like StructureMap) use Nested Containers for.

**Comment by vladimir-kovalyuk** [comment]
The answers are:
- no
- yes
I'm pretty new to SimpleInjector - working on POC of switching from Autofac to SimpleInjector.
The goal is to make DI container to forbid or warn in case of design issues.
The sub-goal is to ensure inner layer's components do not make dependencies on outer layer's components. I didn't consider scopes as a solution - scopes are about lifetime, layers are about logical taxonomy of the application. Components from different layers can be activated along the course of handling web request (just one web request scope). How can I make sure that say a repository does not depend on some service?

**Comment by dotnetjunkie** [comment]
> The sub-goal is to ensure inner layer's components do not make dependencies on outer layer's components.

That's something that the Union architecture itself already provides for, since it places interfaces in a different assembly, which makes it impossible for components to depend on concrete components of a different layer.

To prevent letting to get this discussion to become too theoretical, would you mind sharing some code that expresses what you are doing at the moment, and which to do with Simple Injector as well?

**Comment by vladimir-kovalyuk** [comment]
I'm thinking about nesting containers with help of ResolveUnregisteredType event. This sample promises to be short :)

**Comment by RobertChrist** [comment]
Sure, I can explain a pretty simple use case.

My application has two major components, a message bus, and a command executor.

The message bus is responsible for pulling and pushing queue items.  The command executor is responsible for determining the business logic needed to determine when to push various queue items, depending on which command it is passed in (ie, that object was pulled form the message bus), then running that logic.

Both the message bus and the command executor use the same data access layer, and they will frequently query the same end points and database tables using the same DAL objects, albeit for different purposes.  The Message bus, for example may want to know how many "devices" are in the devices table, while the command executor may want to look up additional information about a specific device.  But both would use our generic Devices Data Access repository.

Some of our data access objects require significant spin up, and as such, we attempt to do so once at the beginning of the application.  This is for a variety of reasons, sometimes com objects, sometimes just the overhead of opening database connections.

As a result, we want both the command executor and the message bus to share low level DAL objects, ie, we want to register them once at the beginning of the application, and pass that container to both projects.  The message bus can then use this first container to resolve the objects it needs to, to pull its messaging service objects.

But the Command Executor does not know what objects it will need until it receives its first queue object from the messaging bus.  The Command Executor could have its own container, and spin up from scratch, but we want to reuse the same initial registrations as the message bus to avoid spin up time.  Some of the commands the executor will execute will only take a second or two, so spending spin up time on re-registering DAL components for each command is non-ignorable.

So I would desire a way, that each time the command executor is given a command from the messaging bus, it could clone the container from the message bus, and then append new object registrations as needed.  ie) nested registrations

**Comment by dotnetjunkie** [comment]
Hi @RobertChrist,

To my knowledge, the use of nested containers is not common use with pub/sub and I never had to use it in any of the pub/sub applications I used or built. What you might be confused with, is that _some_ containers use nested containers to allow registrations to be scoped. Unity is an example of this where nested containers are _the_ way to apply scoping. Containers like Autofac and Simple Injector, for instance, don't require the use of nested containers to do scoping.

Most of what you say sounds very reasonable, i.e.:

- Both the message bus and the command executor is part of the application's entry point and they therefore need to resolve object graphs based on the messages/commands they are receiving.
- To do this, you don't want to construct a complete new container instance, because there is a considerate amount of overhead in creating new container instances (btw, this holds for nested containers as well)

You can however all do this by simply resolving from the application's single container instance, while wrapping the resolve and execution in a scope.

> and then append new object registrations as needed. ie) nested registrations

Can you explain (and preferably show some examples) of the nested registrations you need?

**Comment by paulomorgado** [comment]
This all boils down to a scope. The difference is that some dependencies are only known at the beginning (just before) of the scope.

For my usage it doesn't even have to be the parent container managing the child containers. I could live with a child container having a parent and resolving from there what it can't resolve by itself.

**Comment by dotnetjunkie** [comment]
There are a few very simple "workarounds" that allow simulating child registrations, such as using stateful proxy implementations, pulling instances from the scope, or sometimes a small design change can fix the problem as well.

**Comment by dotnetjunkie** [comment]
Hi Robert,

Please share some code. Without actual code that demonstrates the problem, this discussion keeps being theoretical, which leads to nothing. With actual concrete code, I can show alternatives. With those alternatives, you can decide whether that would work, or using a different library would better suite your needs.

**Comment by RobertChrist** [comment]
Hi @dotnetjunkie, what exactly do you want me to post as example?  Is there something specific you would like to see in code?  I obviously can't post the entire applications, or even their entire DI roots.  We're talking about applications that are 100s of thousands of lines of code.  Was something unclear in my descriptions above?

**Comment by dotnetjunkie** [comment]
Hi @RobertChrist, I'm obviously not interested in seeing your complete code base, or even _any_ business logic. Such logic is typically not very interesting in a DI-related discussion.

What's interesting though, is _some_ code from your Composition Root that demonstrates how you are wiring things up related to this particular discussion. So I would expect some code that demonstrates how you are currently making registrations to your child container. To get a good picture of what’s happing and why, it is good:

- to see the code for (or parts of) the interfaces of those components that are explicitly registered in the child container
- a description of what their intended use in the application is
- _why_ those components require being registered explicitly in the child-container instead of using normal scoped registrations. It would help to show _some_ code that demonstrates this point.
- It might be helpful to visualize (part of) an object graph that contains such child-container registration.

Most can be pseudo code; it doesn't have to be copy-pasted from the actual application, since that might cause legal issues depending on what you copy and for which organization your work. However, real class names typically does help a lot, and should typically cause no legal issues.

**Comment by paulomorgado** [comment]
One of the use cases I have is:

``` C#
using (var servicesContainer = CreateServicesContainer())
{
    BuiltStuf1 builtStuf1;
    BuiltStuf2 builtStuf2;
    using (var buildersContainer = CreateBuildresContainer(servicesContainer))
    {
        builtStuf1 buildersContainer.GetInstance<StufBuilder1>().Build();
        builtStuf2 buildersContainer.GetInstance<StufBuilder2>().Build();
    }

    servicesContainer.GetInstance<DoSomethingWithStuff>().Run(builtStuf1);
}
```

The builders are transient and might or might not need services.

Any builder might need nested builders.
`Run` might need to build something.

**Comment by dotnetjunkie** [comment]
@paulomorgado Unfortunately, your example doesn't show much. What is happening inside the `CreateBuildresContainer`? As it seems now, since you are only just resolving from the `buildersContainer`, there is no reason to simply implement this using scoping.

**Comment by dotnetjunkie** [comment]
> Simple Injector allows multiple scopes but only one scope definition. I want multiple transient scope definitions. I know when the scope is relevant and out of the scope its definition is irrelevant and not necessary to keep it around.

I'm not sure I completely understand what you mean by this. What is a "scope definition"? What is a "transient scope definition" and what does it mean to have "multiple transient scope definitions"?

> And Simple Injector does not allow nested scopes either. Does it?

It absolutely does. Here's an example from [the documentation](https://simpleinjector.readthedocs.io/en/latest/lifetimes.html#asyncscoped):

``` c#
using (AsyncScopedLifestyle.BeginScope(container)) {
    var outer1 = container.GetInstance<IUnitOfWork>();
    await SomeAsyncOperation();
    var outer2 = container.GetInstance<IUnitOfWork>();

    Assert.AreSame(outer1, outer2);

    using (AsyncScopedLifestyle.BeginScope(container)) {
        var inner1 = container.GetInstance<IUnitOfWork>();

        await SomeOtherAsyncOperation();

        var inner2 = container.GetInstance<IUnitOfWork>();

        Assert.AreSame(inner1, inner2);

        Assert.AreNotSame(outer1, inner1);
    }
}
```

**Comment by paulomorgado** [comment]
The "scope definition" is the registrations for the scope. Transient means that I need the definition when and where I need it and nowhere else and never again.

Regarding nested scopes:

```C#
using (AsyncScopedLifestyle.BeginScope(container)) {
    var outer1 = container.GetInstance<IUnitOfWork>();
    await SomeAsyncOperation();
    var outer2 = container.GetInstance<IUnitOfWork>();

    Assert.AreSame(outer1, outer2);

    using (AsyncScopedLifestyle.BeginScope(container)) {
        var inner1 = container.GetInstance<IUnitOfWork>();

        await SomeOtherAsyncOperation();

        var inner2 = container.GetInstance<IUnitOfWork>();

        Assert.AreSame(inner1, inner2);

        Assert.AreNotSame(outer1, inner1);

        Assert.AreSame(outer1.GetType(), inner1.GetType()); // can the implementations vary depending on being an inner or outer scope?
    }
}
```

**Comment by dotnetjunkie** [comment]
> can the implementations vary depending on being an inner or outer scope?

Scopes in Simple Injector are _ambient_. This means that you never resolve from a _scope_ directly, you resolve from the _container_—the container knows in which logical context you are running and which scope to resolve from.

Can you show a concrete example of where and why you resolve from multiple scopes within the same logical context?

**Comment by paulomorgado** [comment]
What do you intend by logical context?

**Comment by dotnetjunkie** [comment]
> What do you intend by logical context?

The logical context is the context some code runs in. In ASP.NET for instance, code typically runs inside a request and using HttpContext.Current allows returning the correct request information.

Logical Context in the 'context' (no pun intended) of this discussion simply means _the active scope_. Starting a Scope means something to yoyr application. You wish to have a certain level of isolation for a certain operation. This typically is something like a web request or even within a single web request you can have as many as smaller bubbles of isolation as you like (i.e. nested scopes).

https://github.com/simpleinjector/SimpleInjector/issues/444#comment-374878616

**Comment by paulomorgado** [comment]
But those bubbles are all the same color. I cannot have bubbles in the color I choose when I choose.

**Comment by dotnetjunkie** [comment]
Let me repeat my previous question: Can you show a concrete example of where and why you resolve from multiple scopes within the same logical context?

**Comment by paulomorgado** [comment]
No. Because I have multiple logical contexts.

**Comment by dotnetjunkie** [comment]
Hi guys, 

I'm afraid that this discussion is leading to nothing. Without _concrete examples_ there is nothing I can do for any of you. To prevent any further "me too" response, as of now, I am locking this discussion.

If you are in the situation that you think you require a feature similar to child containers, please start a new question here on Github, and provide _meaningful and concrete code samples_ that demonstrates your exact scenario.

I really like to help any of you out, but without seeing any concrete examples, I am unable to do so. If you don't want my help, please use a different DI Container that satisfies your needs.
