### ISSUE TITLE
Batch / Automatic registration by using decorators

### ISSUE THREAD

**Issue by tonivix** [simpleinjector/SimpleInjector#448]
Please evaluate my proposal of extension for Batch / Automatic registration by using decorators:

https://github.com/tonivix/simpleinjector.extensions

**Comment by dotnetjunkie** [comment]
Your proposal violates the [don't force vendor lock-in principle](https://simpleinjector.readthedocs.io/en/latest/principles.html#don-t-force-vendor-lock-in) of Simple Injector, because it depends on using a framework defined attribute. On top of that, one of Simple Injector's design decisions was to [limit batch-registration](https://simpleinjector.readthedocs.io/en/latest/decisions.html#limited-batch-registration). For those reasons, I wouldn't want such API as part of Simple Injector. You are of course free to create your own extension package, as long as you conform to the [legal stuff](https://simpleinjector.readthedocs.io/en/latest/legal.html) (basically, don't use the logo, and we ask to prevent using the "SimpleInjector.*" prefix for your packages).

Besides all this, personally, I don't like the use of attributes for this - at all. I favor the use of generic abstractions, since this has many benefits, among which the easy you can register them in Simple Injector (and for them being SOLID).

But even if you don't use generic methods, it's much more practical to use [Convention over configuration](https://nl.wikipedia.org/wiki/Convention_over_configuration), which means you just look at names and their interfaces. In that you don't need to use such attribute at all, and you prevent your code base from being polluted by such attribute.

**Comment by tonivix** [comment]
Very proud to use SimpleInjector knowing that it has collaborators like you Mr. Steven.
I understood the concepts better after your explanation and decided to go with the 'Convention over Configuration' approach. 
Thank you very much.

**Comment by dotnetjunkie** [comment]
Your very welcome. :)
