### ISSUE TITLE
.Net Core console application documentation

### ISSUE THREAD

**Issue by darrenlewis1985** [simpleinjector/SimpleInjector#452]
Is it possible to get some example documentation put together for how to use Simple Injector with .Net Core console applications? All of the documentation I have found is geared towards ASP.Net Core and not console applications.

Specifically, I'm looking for the replacement for:

`loggerFactory.AddConsole(Configuration.GetSection("Logging"));`

in Simple Injector instead of the .Net Core build in DI. I've been trying to figure this out but I'm only getting so far. I can't seem to get it working picking up the config from the appsettings.json file. 

```
var loggerFactory = new LoggerFactory()
                .AddConsole(configuration.GetSection("Logging"));

container.Register<ILoggerFactory>(() => loggerFactory, Lifestyle.Singleton);
container.Register(typeof(ILogger<>), typeof(Logger<>), Lifestyle.Singleton);
```

Any suggestions?

**Comment by dotnetjunkie** [comment]
Did you read this?

https://simpleinjector.readthedocs.io/en/latest/consoleintegration.html

**Comment by darrenlewis1985** [comment]
Yup. I guess it would be nice to include examples of how to replicate the common things that are done using IServiceCollection e.g. Configuration, Logging etc.

As far as I'm aware, you can't pass IServiceCollection to the container like you can with AutoFac.

**Comment by dotnetjunkie** [comment]
> I guess it would be nice to include examples of how to replicate the common things that are done using IServiceCollection e.g. Configuration, Logging etc.

Well, I would say that in a .NET Core console application, you wouldn't have to use `IServiceCollection` that much at all. In most cases I would even say you don't use it at all. You just use Simple Injector. 

The use of `IServiceCollection` is only required if you are depending on any third-party libraries who integrate extensively with `IServiceCollection` by having an `AddXXX` extension method that registers a great deal of classes in the core container. In that case it would get cumbersome and error prone to duplicate those registrations in Simple Injector (e.g. Identity Framework). 

For most libraries that you'd use in a Console application however, there would be a limited amount of registration.

What logging is concerned, you can do this:

``` c#
var loggerFactory = new LoggerFactory()
    .AddConsole(configuration.GetSection("Logging"));

container.RegisterSingleton<ILoggerFactory>(loggerFactory);
container.Register(typeof(ILogger<>), typeof(LoggerProxy<>), Lifestyle.Singleton);
```

Where `LoggerProxy<T>` is defined as follows:

``` c#
public sealed class LoggerProxy<T> : ILogger<T>
{
    private readonly ILogger<T> logger;
    public LoggerProxy(ILoggerFactory factory) => logger = factory.CreateLogger<T>();
    public IDisposable BeginScope<TState>(TState state) => logger.BeginScope(state);
    public bool IsEnabled(LogLevel logLevel) => logger.IsEnabled(logLevel);
    public void Log<TState>(LogLevel l, EventId id, TState s, Exception e, Func<TState, Exception, string> f) => logger.Log(l, id, s, e, f);
}
```

The `LoggerProxy<T>` wraps the call to `ILoggerFactory.CreateLogger<T>` in a helper class, since you can't map a generic abstraction (i.e. `ILogger<T>`) to a method.

**Comment by dotnetjunkie** [comment]
But to be honest, I would replace the registration of `typeof(ILogger<>)` with (as shown [here](https://simpleinjector.readthedocs.io/en/latest/advanced.html#context-based-injection)) the following:

``` c#
container.RegisterConditional(
    typeof(ILogger),
    c => typeof(LoggerProxy<>).MakeGenericType(c.Consumer.ImplementationType),
    Lifestyle.Singleton,
    c => true);
```

This allows any consumer to simply depend on `ILogger` instead of `ILogger<T>`. This reduces code duplication, simplifies testing and makes it impossible to accidentally specify the wrong `T`, since this should always be equal to the type it is injected into.

Try doing that with the build-in container ;-)

**Comment by darrenlewis1985** [comment]
Thanks for the info.

You're right in that I don't want to have any references to `IServiceCollection`. I've not got any at the moment. Trying to find anything about console apps for .Net Core is hard enough, nevermind combining that with using the built in Logging framework with a config without using the built in DI framework that comes with .Net Core. All of the examples I have found use both together and not a different DI framework.

Will any of what you've suggested fix the problem with the configuration working correctly or is it just a more elegant implementation than I originally had? Or will I have to dig into the Logging repo in GitHub to find out where the config stuff is read?

**Comment by dotnetjunkie** [comment]
> Will any of what you've suggested fix the problem with the configuration working correctly or is it just a more elegant implementation than I originally had? Or will I have to dig into the Logging repo in GitHub to find out where the config stuff is read?

I'm sorry, I seemed to miss your question in your last comment. Did you solve your original problem, which was if I'm not mistaking: "I can't seem to get it working picking up the config from the appsettings.json file."

I must admit that I'm not very familiar with the API of that new logging library. There should be enough examples online that show how to configure the logging library using a config file I guess.
