### ISSUE TITLE
Open Generic instanceCreator

### ISSUE THREAD

**Issue by harrisse** [simpleinjector/SimpleInjector#454]
Hi, I'm looking to effectively bind an open generic type to a generic method on an instance of another type. An example of this is resolving `DbSet<>` when using EF Core. I'd like to have a registration like `container.Register(typeof(DbSet<>), type => dbContext.Set(type));` I've been working around this by using `ResolveUnregisteredTypes` to determine if I'm trying to resolve a `DbSet`, grab the generic argument off the type, and pass it into `DbContext`, but I was wondering if there's an easier way, as it feels kind of messy, or if this is another use case that Simple Injector expressly doesn't allow.

Thanks!

**Comment by dotnetjunkie** [comment]
Simple Injector does not support the syntax you are looking for. `ResolveUnregisteredType` is actually the way to go.

Typically, the advised solution is to create a proxy implementation that could forward the calls to the real set, for instance:

``` c#
container.Register(typeof(DbSet<>), typeof(ProxyDbSet<>));
```

Where `ProxyDbSet<T>` would be something like this:

``` c#
public class ProxyDbSet<T> : DbSet<T>
{
    private DbSet<T> wrapped;
    public ProxyDbSet(MyAppDbContext context) => this.wrapped = this.context.Set<T>();

    // Forward calls to the underlying DbSet
    public override void UpdateRange(params TEntity[] entities) => this.wrapped.UpdateRange(entities);
}
```

Although this might work, the `ProxyDbSet<T>` will have a lot of boilerplate code, because it has 19 members to override. 

The use of `ResolveUnregisteredType` is therefore the best approach.
