### ISSUE TITLE
Decorator vs .NET TypeFilter

### ISSUE THREAD

**Issue by ThisNoName** [simpleinjector/SimpleInjector#455]
Last time around, I used SimpleInjector with MediatR and was able to do conditional decorator with passive attribute, so only process marked with [Audit] [Transaction], etc., are actually wired up.  The only issue was that the entire MVC was left an empty shell, doing absolutely nothing.  

This time, I tried to simply the architecture and do away MVC Core 2 only.  But there seems no easy way to accomplish decorator, let alone conditional.  I saw their new Service/Type filter, seems every clean and with IoC.  But I remember there were several posts from Steve mentioning MVC attributes are cached and injected service turns into singleton.  

Is that the case with Type filter?  It implements IFilterFactory, but I honestly do not have the capacity to fully understand from reading source code.  Does that make any difference in experts' opinion?  

Thanks.

**Comment by dotnetjunkie** [comment]
>  The only issue was that the entire MVC was left an empty shell, doing absolutely nothing.

Is that an issue? I would say that's an absolute good thing.

**Comment by dotnetjunkie** [comment]
> Is that the case with Type filter?

I don't know whether or not type filters are being cached in .NET Core. 

>  The only issue was that the entire MVC was left an empty shell, doing absolutely nothing.

Is that an issue? I would say that's an absolute good thing. The less you have to deal with an application framework, the better, especially when it gives you very clean and pure code.

> But there seems no easy way to accomplish decorator, let alone conditional.

Why is not possible to apply decorators anymore? If you are defining your own abstractions , it should be trivial to decorarate your own abstractions with Simple Injector.

Can you express more clearly what the problem is with using Simple Injector?

**Comment by ThisNoName** [comment]
Thanks for the quick response.  

Right now, every single controller in my other app has literally one line to send request, seems like quite a waste.  If only I know how to auto wire those requests into Rest calls!    Yes, I know it's clean and pure and I have been using similar command/query type of architecture for many years.  But .NET MVC has been getting better, so I thought I might be able to cut some corners and get rid of a layer or two.  It's not like my application will ever move away from the underlying framework.  

By hard to decorate, I mean apply decorator to MVC controller, and only when there's a passive attribute on them.  I saw your [articles ](https://stackoverflow.com/questions/32118849/how-to-decorate-an-asp-net-mvc-controller-with-simple-injector) , but not quite sure if that's the preferred approach, how it performs and how it compares to other options like filter, middleware, etc.

Sorry if these questions sounds naive.  I'm just a regular programmer doing 9-5 jobs ^_^

**Comment by dotnetjunkie** [comment]
> Right now, every single controller in my other app has literally one line to send request, seems like quite a waste. 

That indeed seems like quite a waste. You should try to go [Controllerless](https://github.com/dotnetjunkie/controllerless/) as expressed in this [reference architecture application](https://github.com/dotnetjunkie/solidservices).

>  It's not like my application will ever move away from the underlying framework.

That's not the point. The point is to build highly maintainable software. The less cruft and cleaner your design, the more productive you'll be, the lower the Total Cost of Ownership will be.

> By hard to decorate, I mean apply decorator to MVC controller

MVC was the only framework that actually allowed this. Both ASP.NET Web API and the new and shiny ASP.NET Core make it **impossible** to decorate controllers. Both frameworks _require_ the returned `Controller` to be the actual type they request, since they will do reflection on that type to get its methods.

But if you have a SOLID architecture with command/query, you should mostly decorate on the level of your command and query handlers.

**Comment by ThisNoName** [comment]
Wow!  That sounds like exactly I have been looking for, hope I can read up enough to get it going!!  Thank you so much!!!

**Comment by dotnetjunkie** [comment]
There is only one little catch.

Although that reference architecture application contains examples of both WCF and ASP.NET Web API, I haven't had the time to research how to achieve the same with ASP.NET Core. The reference application therefore lacks an example of ASP.NET Core.

**Comment by ThisNoName** [comment]
Duh!  Premature celebration.  I thought it's a .NET-less solution ^_^  

Definitely something looking forward to.  I'll check back if I ever figured it out ... ...
