### ISSUE TITLE
Create factory for multiple open-generic implementations 

### ISSUE THREAD

**Issue by tzographos** [simpleinjector/SimpleInjector#460]
Here's my problem: 
-  I have an exporter interface `INetworkExporter<T>` and two concrete implementations:  `CsvNetworkExporter<T>` and `JsonNetworkExporter<T>`.
- If I had only one concrete instance, the registration could simply be:
`Container.Register(typeof(INetworkExporter<>), typeof(JsonNetworkExporter<>), Lifestyle.Transient);`
- I decided to create a factory where I could store the producers in a local dictionary and call their instances by key. 

Here's what I did:

IServiceFactory:
```C#
public interface IServiceFactory<in TKey>
{
    object Create(TKey key);
}
 ```

ServiceFactory:

```C#
public class ServiceFactory<TKey> : IServiceFactory<TKey>
{
    private readonly Container _container;
    private readonly IDictionary<TKey, InstanceProducer> _instanceProducers = 
        new Dictionary<TKey, InstanceProducer>();

    //constructor
    public ServiceFactory(Container container)
    {
        _container = container ?? throw new ArgumentNullException(nameof(container));
    }

    public void Register(TKey key, Type serviceType, Type implementationType, 
        Lifestyle lifestyle = null)
    {
        var producer = (lifestyle ?? _container.Options.DefaultLifestyle)
            **.CreateProducer(serviceType, implementationType, _container)**;           
        _instanceProducers.Add(key, producer);
    }       

    public object Create(TKey key)
    {
        if (_instanceProducers.ContainsKey(key))
        {
            return _instanceProducers[key].GetInstance();
        }
        else
        {
            KeyNotFoundException knfEx = new KeyNotFoundException(
                "There is no producer registered with specified key.");
            knfEx.TryAddData("ProducerKey", key);
            throw knfEx;
        }
    }
}  
```

And here's how I bootstrap it
```C#
var exporterFactory = new ServiceFactory<NetworkExporterType>(Container);
exporterFactory.Register(NetworkExporterType.Json, 
	typeof(INetworkExporter<>), typeof(JsonNetworkExporter<>), Lifestyle.Transient);
exporterFactory.Register(NetworkExporterType.Csv, 
	typeof(INetworkExporter<>), typeof(CsvNetworkExporter<>), Lifestyle.Transient);

Container.RegisterSingleton<IServiceFactory<NetworkExporterType>>(exporterFactory);
```

My problem is that the method denoted with bold in the above code throws an exception 
`"The supplied type JsonNetworkExporter<TNodeValue> is an open generic type. This type cannot be used for registration using this method.\r\nParameter name: implementationType"`

My question is:  why?   Why does the Producer care if I create it by specifying both service and implementation (open-generic) types to it?

Thanks :)

**Comment by dotnetjunkie** [comment]
> Why does the Producer care if I create it by specifying both service and implementation (open-generic) types to it?

An `InstanceProducer` is factory that builds one specific type. Each resolved type gets its own entry in the internal Dictionary and each type gets its own `InstanceProducer`. Even though you might have only one registration for an open-generic type, at runtime, each resolved closed-generic type will get its own `InstanceProducer`. Although a design where `InstanceProducer` would be able to construct any closed-version of a given open-generic type is imaginable, this is not the way this is designed in Simple Injector.

The design of Simple Injector aside, be careful with interfaces like `IServiceFactory`. First of all, when applying DI, factories are most of the time redundant; they can even be [considered a code smell](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=100). On top of that, your `IServiceFactory` feels much like a [Service Locator](http://blog.ploeh.dk/2010/02/03/ServiceLocatorisanAnti-Pattern/), i.e. a service that:

> supplies application components outside the *Composition Root* with access to an unbound set of *Volatile Dependencies*. ([source](https://livebook.manning.com/#!/book/dependency-injection-in-dot-net-second-edition/chapter-5/section-5-2))

Especially the `object` return type is really weird, because such returned object will be useless unless it is casted to something specific. This is error prone.

Instead of using a factory, you are probably much better of using a [Context Based registration](https://simpleinjector.readthedocs.io/en/latest/advanced.html#context-based-injection). Using `RegisterConditional`, Simple Injector allows you to base the implementation on the used parent. For instance:

``` c#
container.RegisterConditional(
	typeof(INetworkExporter<>), 
	typeof(JsonNetworkExporter<>), 
	Lifestyle.Transient,
	c => * condition here *);

container.RegisterConditional(
	typeof(INetworkExporter<>), 
	typeof(CsvNetworkExporter<>), 
	Lifestyle.Transient,
	c => * condition here *);	
```

You will have to state the condition under which the particular registration must be injected. I'm unsure what the condition should be in your case, but here are a few possibilities:

 * Based on the implementation type of the consumer
 * Based on the argument name of the constructor of the consumer that is used to inject the dependency in.
 * Based on an attribute placed on the consumer
 * Based on an attribute placed on the constructor argument or property
 * Based on the range of constructor arguments of the consumer
 * Based on (part of) the namespace in which the consumer type lives.
 * Based on whether a previous registration already was selected to be used (thus: this registration will become a fallback).

Contextual registration typically prevents the complexity of your application components to be increased using factory abstractions, by moving this logic into the Compostion Root.

**Comment by tzographos** [comment]
> An InstanceProducer is factory that builds one specific type. Each resolved type gets its own entry in the internal Dictionary and each type gets its own InstanceProducer. Even though you might have only one registration for an open-generic type, at runtime, each resolved closed-generic type will get its own InstanceProducer. Although a design where InstanceProducer would be able to construct any closed-version of a given open-generic type is imaginable, this is not the way this is designed in Simple Injector.

Well, I wish this was supported. 
The "internal" InstanceProducer dictionary would be: 
`INetworkExporter<Apple> --> JsonNetworkExporter<Apple>`
`INetworkExporter<Orange> --> CsvNetworkExporter<Orange>`

When I issue:
`container.CreateInstance<INetworkExporter<Apple>>()`  
there is sufficient information to determine which concrete implementation is needed.

Regarding the code-smell in the ServiceFactory, you are correct as long as it is used outside of the Composition Root, but as you can see in the code, it's type is registered (singleton).
```C#
Container.RegisterSingleton<IServiceFactory<NetworkExporterType>>(exporterFactory);
```

The bottom line is that I don't have enough "contextual information" to invoke an instance registerws with `container.RegisterConditional(...)` because I am at the "Main" method on a .Net Core 2.0 console app.

```C#
        [STAThread]
        static void Main(string[] args)
        {
            //start the bootstrapper
            Bootstrapper.Start();
            Container container = Bootstrapper.Container;

            //start the application
            RunApplication(container);
        }


        private static void RunApplication(Container container)
        {
            var exporterFactory = container.GetInstance<IServiceFactory<NetworkExporterType>>();
            INetworkExporter<Apple> exporter = (INetworkExporter<Apple>)exporterFactory.Create(NetworkExporterType.Json);
        }
```

**Comment by dotnetjunkie** [comment]
> The "internal" InstanceProducer dictionary would be:
> INetworkExporter<Apple> --> JsonNetworkExporter<Apple>
> INetworkExporter<Orange> --> CsvNetworkExporter<Orange>

Such mapping might translate to the following contextual registrations:

``` c#
var jsonExporterTypes = new[] { typeof(Appels), ... };

// Use JsonNetworkExporter for all types specified above
container.RegisterConditional(
    typeof(INetworkExporter<>), 
    typeof(JsonNetworkExporter<>), 
    c => jsonExporterTypes.Contains(c.ServiceType.GetGenericTypeArguments()[0]));

// Use CsvNetworkExporter for everything excluding the jsonExporterTypes
container.RegisterConditional(
    typeof(INetworkExporter<>), 
    typeof(CsvNetworkExporter<>), 
    c => !c.Handled);	
```

This allows you to inject `INetworkExporter<Apple>` and `INetworkExporter<Orange>` directly into the constructor of a consumer that needs them.
