### ISSUE TITLE
webapi resolver

### ISSUE THREAD

**Issue by evvo1961** [simpleinjector/SimpleInjector#476]
When resolving a container utilising the web api resolver - 

``` c#
GlobalConfiguration.Configuration.DependencyResolver =
    new SimpleInjectorWebApiDependencyResolver(container);
```

what is the syntax to return an instance? 
im using

``` C#
var jobService = DependencyResolver.Current.GetService<IJobService>();
```

but it is not retrieving anything as i believe this is related to the mvc resolver?

**Comment by dotnetjunkie** [comment]
I would advice to call the `SimpleInjector.Container` instance directly, instead of calling it through one of the `IDependencyResolver` interfaces (both MVC and Web API have their own interface with the same name). 

These interfaces are problematic because they specify in their contract that `GetService` should return `null` when an instance can't be resolved. So the `SimpleInjectorDependencyResolver` for MVC and the `SimpleInjectorWebApiDependencyResolver` are not allowed to throw an exception, which means you are losing valuable information.

Since calls to `DependencyResolver.GetService` should only take place _inside_ the Composition Root anyway, there is no harm in calling `SimpleInjector.Container.GetInstance` directly at that point.

When you do that, Simple Injector will throw an exception and tell you exactly what's wrong.

**Comment by evvo1961** [comment]
ok i dont get the GetInstance method from where i am accessing SimpleInjector.Container, these service instances are being set in both the global asax and other classes in the project... are you saying they need to be set in the SimpleInjectorConfig file at the place the container is created and resolved?

**Comment by dotnetjunkie** [comment]
You can store the `Container` instance in a static field and make it accessible to parts of the Composition Root that need to resolve services directly. Typically, the only objects that need to be resolved are controllers, which means you need custom `IDependencyResolver` (or alternatively `IControllerFactory` and `IControllerActivator`) implementations (as you have). Sometimes however, you need to resolve other services as well, for instance when you spin of a background thread. For this you need access to the `Container`.
