### ISSUE TITLE
Let the Container implement an IContainer interface

### ISSUE THREAD

**Issue by guy-lud** [simpleinjector/SimpleInjector#477]
Hello,
Would it be possible that the Container class will implement an interface IContainer? I would like to use a decorator pattern around it.

**Comment by dotnetjunkie** [comment]
How would such `IContainer` interface look like and how are you intended to use this? What would the function of the decorator be and who will consumer this `IContainer` interface?

**Comment by dotnetjunkie** [comment]
I would also like to refer to this Stackoverflow q/a: [Why doesn't Simple Injector have an IContainer abstraction like Unity?](https://stackoverflow.com/questions/16225737/why-doesnt-simple-injector-have-an-icontainer-abstraction-like-unity).

**Comment by guy-lud** [comment]
@dotnetjunkie , sorry for not getting back sooner it's been like crazy.

To make a long story short i wanted to be able to return a wrapper around the container to give him more abilities. 

Now the longer story, as you know i love using SimpleInjector in all my projects. over the years i've developed a personal usage that i liked.

So I've decided to build a [lib](https://github.com/existall/Shepherd) for it.
The lib should simply orchestrate and provide common registration for domain services, the usage of the container (in the future i plane to build for more Ioc's - i don't plan to build an abstraction around the Ioc but simply simplify).

I tough it would be nice to have an extension method `Container.AsShepherd()` and to wrap the current container with `Shepherd` 's abilities.

Without interface i can't use decoration but i can use DeepCloning, of course i still need to dispose the existing Container and so on. 

But for now this is only in experimental mode and Nice to Have.

Thanks anyway.

**Comment by dotnetjunkie** [comment]
Although it might be beneficial _for you_ to have an `IContainer` abstraction, as I explained [here](https://stackoverflow.com/a/16226207/264697), it is not beneficial for Simple Injector nor other users. An interface would even block further evolution, since even the addition of methods to an interface are breaking changes.

In case such interface is useful to you, my advice is to define such interface with companion implementation that wraps the `Container` yourself. Creating both the interface and the wrapper should be trivial for you.
