### ISSUE TITLE
 oAuth authorization filter 

### ISSUE THREAD

**Issue by nevillekelly** [simpleinjector/SimpleInjector#479]
Currently using an oAuth authorization filter where information is added to the claim. Also using the RequestMessageAccessor detailed in you docs however claim information is not available in that object. How would we retrieve the claim information for purpose of injecting the info?

**Comment by dotnetjunkie** [comment]
Can you provide more detailed information? Can you provide me with some code that reproduces the problem?

**Comment by nevillekelly** [comment]
Here is a snippet from the oAuth authorization attribute:
public class CustomOAuthProvider : OAuthAuthorizationServerProvider
    {
        string dbServer;
        string dbName;

        public override Task ValidateClientAuthentication(OAuthValidateClientAuthenticationContext context)
        {
            dbServer = context.Parameters.GetValues("dbserver")[0].ToString().ToLower();
            dbName = context.Parameters.GetValues("dbname")[0].ToString().ToLower();
            context.Validated();
            return Task.FromResult<object>(null);
        }

        public override async Task GrantResourceOwnerCredentials(OAuthGrantResourceOwnerCredentialsContext context)
        {
            //header info
            var allowedOrigin = "*";
            context.OwinContext.Response.Headers.Add("Access-Control-Allow-Origin", new[] { allowedOrigin });

            //build connection string to validate with, use provided server and dbname or default if none
            string connStr;
            if (dbServer == "" || dbName == "")
            {
                connStr = ConfigurationManager.ConnectionStrings["sqlclientdb"].ConnectionString;

                var dbServerStart = connStr.IndexOf("Server=") + 7;
                var dbServerLen = connStr.IndexOf(";", dbServerStart) - dbServerStart;
                var dbNameStart = connStr.IndexOf("Database=") + 9;
                var dbNameLen = connStr.IndexOf(";", dbNameStart) - dbNameStart;

                dbServer = connStr.Substring(dbServerStart, dbServerLen);
                dbName = connStr.Substring(dbNameStart, dbNameLen);
            }
            else
            {
                connStr = "server=" + dbServer + ";Trusted_Connection=yes;database=" + dbName + ";";
            }

            //authenticate the user against tblUsers
            var authUser = await AuthenticateUser(connStr, context.UserName, context.Password);

            if (authUser == null)
            {
                context.SetError("invalid_grant", "The user name or password is incorrect.");
                return;
            }

            if (authUser.ActiveFlag == 1)
            {
                context.SetError("invalid_grant", "The user is inactive.");
                return;
            }

            if (authUser.LockFlag == 1)
            {
                context.SetError("invalid_grant", "The user is locked.");
                return;
            }

            //have a user, now get their permissions
            IList<Claim> securityClaimCollection = new List<Claim>();
            if (authUser.UserName != null)
            {
                securityClaimCollection = await GetUserPermissions(connStr, authUser.UserID);
            }
            
            //create basic claims for jwt to include db conn info
            IList<Claim> claimsCollection = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, authUser.UserName),
                    new Claim("userID", authUser.UserID.ToString()),
                    new Claim("dbServer", dbServer),
                    new Claim("dbName", dbName)
                };

            ClaimsIdentity oAuthIdentity = new ClaimsIdentity("JWT");
            oAuthIdentity.AddClaims(claimsCollection);

            //add in any permission specific claimns
            if (securityClaimCollection.Count > 0) { oAuthIdentity.AddClaims(securityClaimCollection); };

            var ticket = new AuthenticationTicket(oAuthIdentity, null);
            context.Validated(ticket);
            
        }
}

**Comment by nevillekelly** [comment]
It is getting the information placed in the claim here:
            IList<Claim> claimsCollection = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, authUser.UserName),
                    new Claim("userID", authUser.UserID.ToString()),
                    new Claim("dbServer", dbServer),
                    new Claim("dbName", dbName)
                };
That I need access to. I understand it is a run-time value since it is input by the user but I was unsure if there was a way to access it in such a way that it could be injectable into another object.

**Comment by dotnetjunkie** [comment]
I'm still missing some context here. What framework does this run on? Is this ASP.NET Core? ASP.NET MVC? Or something else? How did you configure this?

Do note that I'm not familiar with oAuth, so I must be able to have an example that I can run as is to experience your problem. Could you provide me with a runnable example that demonstrates the problem?

**Comment by nevillekelly** [comment]
I am working to write a sample project. Will upload it to github and provide a link once completed.

**Comment by nevillekelly** [comment]
https://github.com/nevillekelly/Sample-Project

**Comment by nevillekelly** [comment]
To see the behavior:

1.  Login using any username and password, be sure the DB Server and DB Name are different values. 
2.  Place a break point in ConnectionStringGenerator.cs on line 18.
3. You will notice that the claim information is not in the RequestMessage but is available to the controller in the ActionContext and the values that you entered for DB Server and DB Name will display on the welcome page.

**Comment by dotnetjunkie** [comment]
That's very interesting. I have been able to reproduce this using your repository, but I have no idea what is going on.

There's a way to fix this though: prevent letting your [components depend on runtime data during construction](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=99).

In your case, the connection string is _runtime data_, since it is not a static or configuration constant. Construction of components should not depend on runtime data, as you are doing, because (as you already noticed) this leads to complication.

Instead, inject a service that allows retrieving the value at _runtime_ instead of at _time of composition_.

You can do that by replacing the following problematic registration:

```c#
container.Register(() => 
    container.GetInstance<Data.IDataAccessConfigurationFactory>()
    .GetConfiguration(container.GetInstance<IConnectionStringGenerator>()
    .GetConnectionString()));
```

This registration is problematic because of the following reasons:

- It calls back into the container using `GetInstance`, effectively blinding the container from doing any analysis on this part of the object graph. Simple Injector can only do analysis on information about the object graph that is available as metadata (typically constructor arguments).
- It calls methods on the object graph requesting runtime data required to construct other parts of the object graph.

There are several possible solutions that fix these two issues. One of them is to create a proxy implementation for `IDataAccessConfiguration` that allows forwarding the request to the real `IDataAccessConfiguration` implementation at runtime. Example:

``` c#
public class DataAccessConfigurationProxy : IDataAccessConfiguration
{
    private readonly Data.IDataAccessConfigurationFactory factory;
    private readonly IConnectionStringGenerator generator;

    public DataAccessConfigurationProxy(
        Data.IDataAccessConfigurationFactory factory, IConnectionStringGenerator generator)
    {
        this.factory = factory;
        this.generator = generator;
    }

    public string ConnectionString => GetRealInstance().ConnectionString;

    private IDataAccessConfiguration GetRealInstance() =>
        this.factory.GetConfiguration(this.generator.GetConnectionString());
}
```

Notice how this proxy:

- Accepts the two required dependencies as constructor arguments.
- The `GetRealInstance` contains the logic that previously was part of the lambda of the registration.

This proxy class can be registered as follows:

``` c#
container.Register<IDataAccessConfiguration, DataAccessConfigurationProxy>();
```

Do note that "not depending on runtime data during construction" also means that you should not request this runtime data _inside a constructor_, since this means the component still depends on runtime data _during construction_. This is also formalized by Mark Seemann in [this](http://blog.ploeh.dk/2011/03/03/InjectionConstructorsshouldbesimple/) blog post.

This means that your `SampleRepository` should be fixed as well.

**Comment by nevillekelly** [comment]
I've incorporated the suggested changes into the sample project but am still not able to get the data since it is only available in the ActionContext of the controller. How would you suggest I access that data?

**Comment by dotnetjunkie** [comment]
> but am still not able to get the data since it is only available in the ActionContext of the controller. 

That's probably because you [are still accessing that runtime data during object construction](https://github.com/nevillekelly/Sample-Project/blob/master/TestApp.Data/SampleRepository.cs#L13). As I said above:

> _This means that your SampleRepository should be fixed as well._

If it still not works after changing `SampleRepository`, please explain when the values are null.

**Comment by nevillekelly** [comment]
Changed the code and the problem is fixed. Thank you very much for all your assistance!

**Comment by dotnetjunkie** [comment]
You're welcome.
