### ISSUE TITLE
Getting DbContext from Scoped Lifestyle AND Transient Lifestyle

### ISSUE THREAD

**Issue by dmarlow** [simpleinjector/SimpleInjector#480]
I have my DbContext (technically it's a UnitOfWork holding the DbContext) that I get injected into my controllers using a Scoped Lifestyle. I, however, also want to get a completely new, transient instance of the UnitOfWork whether in or out of an HTTP request (the scope) that won't be disposed of automatically. The registration of the UnitOfWork is using a hybrid lifestyle.

I'm trying to use `_container.GetInstance<T>()` but if the request if after EndExecute, I get object disposed exceptions on my DbContext. What's the right way to do what I'm looking for? I understand it's not ideal, this is just to get us to a place where we can transition things correctly.

**Comment by dotnetjunkie** [comment]
Can you provide more information? Namely:

- An explanation of why you require a _transient instance in or out of an HTTP request (the scope) that won't be disposed of automatically_.
- Which application framework are you using. ASP.NET Core, Web Forms, MVC, Web API, other?
- A reproducible example of your issue.

**Comment by dmarlow** [comment]
* An explanation of why you require a transient instance in or out of an HTTP request (the scope) that won't be disposed of automatically.

We have a mix of usage today where our UnitOfWork is injected as well as manually controlled (by way of people doing this in various places:
`using (var uow = new UnitOfWork())`

I've recently re-worked the UnitOfWork to have its dependencies truly injected, so that meant people no longer can do what they did (`new UnitOfWork()`), but now they need to get an instance from the container. I abstract that by doing this `using (var uow = UnitOfWork.CreateNew())`. This is fine and all except that I could see scoped instances being returned by `CreateNew` (under the covers it just does this: `_container.GetInstance<IUnitOfWork>();`). I found some areas where getting a scoped instance is problematic and requires re-working our code (we have some translation stuff within a View that grabs some translations -- there's some caching involved, so it's not entirely all bad it seems -- but since this is after the EndExecute, the disposed DbContext error occurs here).

I've found a work around since creating this issue by introducing a `Lazy<UnitOfWork>` that I can get like so: `_container.GetInstance<Lazy<UnitOfWork>>();`. Is this the correct approach? This seems to work as the instances of the Lazy<UnitOfWork> are transient.

* Which application framework are you using. ASP.NET Core, Web Forms, MVC, Web API, other?

ASP.NET MVC 5 with Web API 2 on .NET 4.6.2.

* A reproducible example of your issue.

Please allow me a few days to get an example. There's quite a bit I'd have to clean up before sharing my company's source, so I'd have to create an example from scratch.

**Comment by dmarlow** [comment]
Should have also added that I'm SI 3.3.2

**Comment by dmarlow** [comment]
```   
   at System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   at System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   at System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext()
   at System.Data.Entity.Internal.Linq.InternalSet`1.Find(Object[] keyValues)
   at <REDACTED>.GenericRepository`1.Get(Object id) in <REDACTED>\Repository\GenericRepository.cs:line 99
   at <REDACTED>.FindSingleUserProfile(Guid id, Boolean detach) in <REDACTED>
   at <REDACTED>.BaseController.BeginExecuteCore(AsyncCallback callback, Object state) in <REDACTED>\Controllers\BaseController.cs:line 214
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.Controller.BeginExecute(RequestContext requestContext, AsyncCallback callback, Object state)
   at <REDACTED>.BaseController.BeginExecute(RequestContext requestContext, AsyncCallback callback, Object state) in <REDACTED>\Controllers\BaseController.cs:line 349
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__4(AsyncCallback asyncCallback, Object asyncState, ProcessRequestState innerState)
```
  
The code from the stacktrace above is getting the same scoped instance that's been disposed of here:
```
protected void Application_PostAuthenticateRequest(object sender, EventArgs e)
{
	using (var uow = UnitOfWork.StartNew())
	{
		//...
	}
}
```
So, I have two options. 
1) Fix all instances of these independent UnitOfWork usages. (this is the goal, but wanting a transient stop gap for the short term, this will allow us to get the proper foundation and start moving things in parallel).
2) Use a transient UnitOfWork so that `UnitOfWork.StartNew()` doesn't return the Scoped version.

**Comment by dotnetjunkie** [comment]
I think I see what is going on.

- Within the same request, you are calling `UnitOfWork.StartNew()` multiple times.
- `UnitOfWork.StartNew()` forwards the call to `_container.GetInstance<IUnitOfWork>();`.
- `IUnitOfWork` is registered in Simple Injector as `Lifestyle.Scoped`.
- You wrap a call to `UnitOfWork.StartNew()` in a `using` statement.
- The `using` statement ensures that the returned object is disposed.
- The second time you call `UnitOfWork.StartNew()` within the same request, Simple Injector will return you the same instance (since you told it to), but at that point in time, that instance has already been disposed by you and so the operation fails.

Solution:

Prefer removing that `StartNew()` method completely, and rely solely on Dependency Injection and let _only_ the DI Container manage the lifetime of the unit of work.

If that's not an option (yet), prevent always return a new `UnitOfWork` instance from within the `StartNew()` (which is basically what the method name says: to create a new instance) but prevent the disposal of a `UnitOfWork` to dispose the wrapped `DbContext`. You can let Simple Injector manage the lifetime of the `DbContext` as well.

**Comment by dmarlow** [comment]
Yep, that's exactly what's going on. Thank you for re-iterating it more concisely. I like your recommendation, it's not something I even considered. 
If I understand your recommendation correctly, I would register the DbContext and inject that to the UnitOfWork, like so: 
```
container.Register<DbContext>(hybridLifestyle);
container.Register<UnitOfWork>(hybridLifestyle);
---
public UnitOfWork(DbContext dbContext) { ... }
```
The DbContext would then be properly managed by SI and disposed of appropriately. The UnitOfWork can be created/disposed without affecting the DbContext.

I'll have to think about it more as the UnitOfWork is used elsewhere (in non-web applications) and need to think about its lifestyle there. If I do run into issues with that, is the Lazy<UnitOfWork> I alluded to a viable/appropriate work around?

Also, I should have mentioned this first. Thank you for all you do. You not only provide a great library, but also great support and documentation. Truly top notch!

**Comment by dotnetjunkie** [comment]
> the UnitOfWork is used elsewhere (in non-web applications) and need to think about its lifestyle there. If I do run into issues with that, is the Lazy I alluded to a viable/appropriate work around?

That should be a no-brainer. The lifestyle of your DbContext should almost certainly _always_ be scoped. Not a hybrid of Scope and Transient. Just scoped.

It typically makes no sense to have some instance like a `DbContext` Scoped in one place, but Transient in another. That could easily lead to nasty problems, because you might suddenly get multiple `DbContext` instances while executing a certain use case.

If you are running outside of the context of a web application, or even inside the context of a web application, but outside the context of a web request: wrap the operation in a scope. This ensures that even on a background thread the object graph can be resolved with your `DbContext`.

This is in fact what is happening for you under the covers with an ASP.NET web request: Simple Injector wraps the request in a scope for you.

The de facto scoped lifestyle is the `AsyncScopedLifestyle`. That is the default lifestyle for:

- ASP.NET Web API
- WCF (in the coming v4.1 release of Simple Injector)
- ASP.NET Core
- UWP

ASP.NET MVC is a bit the exception here with its own lifestyle (`WebRequestLifestyle`), but you could easily use `AsyncScopedLifestyle` and wrap the request in a piece of OWIN middleware that just starts calls `AsyncScopedLifestyle.BeginScope`, if you wish. This would prevent you from having to define a hybrid lifestyle of `WebRequestLifestyle` and `AsyncScopedLifestyle` in that particular setup.

**Comment by dmarlow** [comment]
Things are working a lot more smoothly now and I have a better understanding of the issues.
