### ISSUE TITLE
Add an event like BeforeVerifying?

### ISSUE THREAD

**Issue by maulwuff** [simpleinjector/SimpleInjector#483]
I have a hard time getting `.Verify()` to succeed in a way, so I don't have to duplicate any code.
As I target for WinForms, I currently have lots of `DisposableTransientComponent` warnings. 

Furthermore, I split the whole project into multiple layers/components (GUI, Service, Business, Data, Shared). Each of them has its own Bootstrapper part to register the things it serves. The Shared component is used on server and client, so it would duplicate the registrations and suppressions on each exe entry point. 

When it comes to verify, I'd like to `Verify()` each layer right away, as I don't know what is above the current layer.
Currently `.GetRegistration()` and `.Verify()` prevent any further registrations on upper layers with an Exception.
The idea was, to have an event like `BeforeVerifying`, where each Bootstrapper can place the necessary suppressions to the container.  
This would still prevent to call `.Verify()` in each Bootstrapper part, but I could 
live with that better, than having to copy/paste each suppression at the top
of the Bootstrapper line.

What do you think?

edit:
This description  regarding `.GetRegistration()`  may sound weird, but I got this from this call stack:

```
Additional information: The container can't be changed after the first call to GetInstance, GetAllInstances and Verify. ...
The following stack trace describes the location where the container was locked:
   at SimpleInjector.Container.LockContainer()
   at SimpleInjector.Container.GetRegistration(Type serviceType, Boolean throwOnFailure)
   at SimpleInjector.Container.GetRegistration(Type serviceType)
   at DataLayer.FinishBootstrap()
```
It also states the line, where the very first Suppression is added.

**Comment by dotnetjunkie** [comment]
Registration is something that should be solely done inside the application's [Composition Root](http://blog.ploeh.dk/2011/07/28/CompositionRoot/). The Composition Root is as close to the application's entry point as possible and it is not common (or advised) to let each layer have its own registrations, since the entry point depends on [all layers](https://stackoverflow.com/questions/9501604/ioc-di-why-do-i-have-to-reference-all-layers-assemblies-in-entry-application) anyway.

In case you have multiple applications that share a large set of registrations, it is okay to extract part of the Composition Root into a shared assembly that is reused by those applications. Composition Roots with lots of shared logic is quite rare, since each application would be very different in behavior and the use cases it handles. Cases where you might see lots of duplication is when you have both an WCF and Web API that expose the same features to clients.

Even though you might want to split up your Composition Roots in multiple parts, where each part configures a particular layer, I would not advise you in verifying each layer seperately. Not only would I advise against it, it is simply impossible because, as you already noticed, Verify locks the container.

But even if Simple Injector would support this, such features (of verifying half way) doesn't make much sense, since the most common case is to register application framework-specific implementations for abstractions that one of your core layers requires. For instance, while your business layer depends on an `IUserContext`, you will register an `AspNetUserContextAdapter` when building an ASP.NET web application. Without the existence of this registration, the set of registrations for the business layers simply is incomplete and would never verify.

Because of this, it typically makes little sense to verify in steps. Only after you added _all_ the registrations the final application requires, you can call verify to see if everything is working as a whole. You are only running one application and you want to verify the configuration for _that_ application.

**Comment by TheBigRic** [comment]
If suppression of the `DisposableTransientComponent` is your main goal or main issue this simple reusable extension method makes this tasks fairly easy.

Hope it helps:

``` c#
private static void RegisterWindowsForms(this Container container, IEnumerable<Assembly> assemblies)
{
    var formTypes =
        from assembly in assemblies
        from type in assembly.GetTypes()
        where type.IsSubclassOf(typeof(Form))
        where !type.IsAbstract
        select type;

    foreach (var type in formTypes)
    {
        var registration = Lifestyle.Transient.CreateRegistration(type, container);

        registration.SuppressDiagnosticWarning(DiagnosticType.DisposableTransientComponent,
            "Forms will be disposed by application code. Simple Injector won't be able to do this " +
            "because there is no way to use scoping here.");

        container.AddRegistration(type, registration);
    }
}
```

**Comment by maulwuff** [comment]
Hi, as I've written, verifying in steps is also something I would drop.
 But what about an event just before `Verify` is executed?
I'll give an example: In my ORM mapper I have some classes which need `IDisposable`, like `DataReader` and such. I don't want to put such suppressions in the exe project which is multiple layers up. It is complete in itself and just needs a container instance to work (+ runtime data). I can accept the hard dependency on Simple Injector, as it has way more value than what I get in value if I would drop the dependency ;-)

Another example might be a `FileWatcher` implementation, which I'd rather clean up deterministic.

For the whole project, I in deed need WCF, WebAPI, noService at all, and multiple Clients (WinForms, Web, App) - so I oriented myself at the gold worth example from SolidServices ;-) 

Of course I can realize a `BeforeVerify` manually, but I think it would be nice to just let classes subscribe to the event which need it to add their suppressions to the container.

@TheBigRic : this looks like a handy snippet ;-) I will modify it to pick up `Controls`, too.

**Comment by dotnetjunkie** [comment]
> But what about an event just before Verify is executed?

Adding some sort of `BeforeVerify` mechanism is not something I would like to pursuit with Simple Injector. Adding, documenting and maintaining such feature gives an overhead, it promotes more [stronger coupling to the container](https://simpleinjector.readthedocs.io/en/latest/principles.html#vendor-lock-in), and is something that is quite easy to achieve yourself without support of Simple Injector is you really need it.

> so I oriented myself at the gold worth example from SolidServices ;-)

Great to hear the SolidServices was valuable to you. TBH, that project has BL-specific registrations in the Business Layer [as well](https://github.com/dotnetjunkie/solidservices/blob/master/src/BusinessLayer/BusinessLayerBootstrapper.cs), but that actually is a practical shortcut, since both the WCF and Web API projects are functionally equivalent, and I wanted to keep things simple.

**Comment by maulwuff** [comment]
Ok, I'll add the pre-Verify things by hand. That's not a big issue.

I encountered one strange thing, though: A suppression added earlier, is not working anymore when `Verify` is called.
`registration.suppressions` is not null and filled with 1 item added earlier. 

this is what I added (twice):
 `registration.SuppressDiagnosticWarning(DiagnosticType.DisposableTransientComponent, ...`
 
and results in this content in `registration.suppressions`:
```
[0] AmbiguousLifestyles
[1] DisposableTransientComponent
```

this is a WcfServiceHost.exe

the same Code works nice when called from a WinForms.exe
content in `registration.suppressions` is then:
```
[0] DisposableTransientComponent
```

Why is the first `SuppressDiagnosticWarning` adding an `AmbiguousLifestyles` to the list instead of `DisposableTransientComponent`?

The full code is:
```
Registration registration = _container.GetRegistration(typeof(IDbDataReader)).Registration;
registration.SuppressDiagnosticWarning(DiagnosticType.DisposableTransientComponent, "IDbDataReader is disposed of in SqlToObjectProvider");
```

both times it is called in my new `BerofeVerify()` ;-)  One is located in the ORM dll, the other one right in the root of the service dll (not the exe-host project).

**Comment by dotnetjunkie** [comment]
> Why is the first SuppressDiagnosticWarning adding an AmbiguousLifestyles to the list instead of DisposableTransientComponent?

This is the code for the `SuppressDiagnosticWarning` method:

``` c#
public void SuppressDiagnosticWarning(DiagnosticType type, string justification)
{
    Requires.IsValidEnum(type, nameof(type));
    Requires.IsNotNullOrEmpty(justification, nameof(justification));

    if (this.suppressions == null)
    {
        this.suppressions = new HashSet<DiagnosticType>();
    }

    this.suppressions.Add(type);
}
```

The `type` is added to a `HashSet<T>` so there is not much what can go wrong here. Besides that, the core library itself never adds suppressions to that hashset. Only the integration libraries do, but they only ever add `DisposableTransientComponent` and only do so in a few very specific cases (when batch-registering controllers or WCF services for instance).

> Why is the first SuppressDiagnosticWarning adding an AmbiguousLifestyles to the list instead of DisposableTransientComponent?

I do strongly believe that your code is adding that suppression itself.

**Comment by maulwuff** [comment]
Have a look:
![si_ambiguouslivestyle](https://user-images.githubusercontent.com/4960210/32557175-b13aa330-c4a1-11e7-8e07-b3a4ad589061.png)

If I let execute `SuppressDiagnosticWarning` twice, it doesn't change the suppressions array.
Is there a decorator around it?

**Comment by dotnetjunkie** [comment]
Can you produce an example that can reproduce this problem? If there is a bug in Simple Injector, I need some code that can reproduce the problem.

By the way, it really sounds fishy to me that you are moving ownership of the `DbDataReader` from Simple Injector to the consumer of `DbDataReader`. This is typically not something you should do, because it complicates your code. In general, the part of the system that creates a disposable (Simple Injector in this case), should also be responsible of disposing it.

So questions:

- Why are you moving ownership of the `DbDataReader` resource to another component?
- Why aren't you either letting Simple Injector dispose it -or- let the consumer be in control over the creation of `DbDataReader` as well?
- If injection is a must, why is `DbDataReader` a transient? Disposable resources should typically be `Scoped`; that would remove the suppression problem completely, because Simple Injector will dispose `Scoped` resources.

**Comment by maulwuff** [comment]
It's fixed! I pulled SI from Github, had to replace all references to the dll in my SLNs, and the problem was gone. It turned out, that the ORM was still on SI 3.3.2 ... After updating it to 4.0.12 the problem was gone. Phew.

> Why are you moving ownership of the DbDataReader resource to another component?

Because the component (DbReadAccess) with a dependency on it knows how to deal with it. Another dependency brings in the real `System.Data.IDataReader`. The wiring is in DbReadAccess. 
It knows how to init it, when it is ready to use, when to cancel or finish it.

> Why aren't you either letting Simple Injector dispose it -or- let the consumer be in control over the creation of DbDataReader as well?

For SI to dispose it: as far as I understand, this would mean to use Scoped Lifestyle. Scopes and Lifestyle is something I always shied away from until now, because I see no benefit from it, yet ;)
Transient is nice and easy and also fitted best to the migration path from non-DI.

The consumer/DbReadAccess can't create the reader, as it may be decorated. 
As data readers need to be disposed, that's why it implements Disposable. 

If I change the registration to be `Lifestyle.Scoped`, it throws this at me:
> To be able to use the Lifestyle.Scoped property, please ensure that the container is configured with a default scoped lifestyle ...

The examples from  http://simpleinjector.readthedocs.io/en/latest/lifetimes.html#scoped don't make it clear to me, how they should be used. I really don't want to scope the whole application with ThreadScopedLifestyle or similar. This whole topic is much too abstract, so I stick with transient ;)

(Another example would be a custom implementation for using a MemoryStream or similar stream. Just because of this implementation, I don't want to change the whole application to be scoped. But as streams need to be disposed, I don't want to change the whole application)

The other thing is, that I see no real example on how to use the Scope. If this is how to use it:
```
using (ThreadScopedLifestyle.BeginScope(container)) 
```
then how should I pass the container down somewhere as deep as to the data reader level? This feels wrong to me. The other option I could think of, is to use it at the entry point where I call `container.GetInstance`. This would mean I have to scope all parts from this point, down to the data reader plus all of the accompanying parts - so that's nearly everything again....

**Comment by maulwuff** [comment]
It's fixed! I pulled SI from Github, had to replace all references to the dll in my SLNs, and the problem was gone. It turned out, that the ORM was still on SI 3.3.2 ... After updating it to 4.0.12 the problem was gone. Phew.

> Why are you moving ownership of the DbDataReader resource to another component?

Because the component (DbReadAccess) with a dependency on it knows how to deal with it. Another dependency brings in the real `System.Data.IDataReader`. The wiring is in DbReadAccess. 
It knows how to init it, when it is ready to use, when to cancel or finish it.

> Why aren't you either letting Simple Injector dispose it -or- let the consumer be in control over the creation of DbDataReader as well?

For SI to dispose it: as far as I understand, this would mean to use Scoped Lifestyle. Scopes and Lifestyle is something I always shied away from until now, because I see no benefit from it, yet ;)
Transient is nice and easy and also fitted best to the migration path from non-DI.

The consumer/DbReadAccess can't create the reader, as it may be decorated. 
As data readers need to be disposed, that's why it implements Disposable. 

If I change the registration to be `Lifestyle.Scoped`, it throws this at me:
> To be able to use the Lifestyle.Scoped property, please ensure that the container is configured with a default scoped lifestyle ...

The examples from  http://simpleinjector.readthedocs.io/en/latest/lifetimes.html#scoped don't make it clear to me, how they should be used. I really don't want to scope the whole application with ThreadScopedLifestyle or similar. This whole topic is much too abstract, so I stick with transient ;)

(Another example would be a custom implementation for using a MemoryStream or similar stream. Just because of this implementation, I don't want to change the whole application to be scoped. But as streams need to be disposed, I don't want to change the whole application)

The other thing is, that I see no real example on how to use the Scope. If this is how to use it:
```
using (ThreadScopedLifestyle.BeginScope(container)) 
```
then how should I pass the container down somewhere as deep as to the data reader level? This feels wrong to me. The other option I could think of, is to use it at the entry point where I call `container.GetInstance`. This would mean I have to scope all parts from this point, down to the data reader plus all of the accompanying parts - so that's nearly everything again....

**Comment by dotnetjunkie** [comment]
Scoping in generally pretty easy, it's just a matter of setting up a scoped lifestyle as follows:

``` c#
container.Options.DefaultScopedLifestyle = new AsyncScopedLifestyle();
```

After that you can register scoped lifestyles like this:

``` c#
container.Register<IDbReadAccess, DbReadAccess>(Lifestyle.Scoped);
```

And you wrap operations in a scope as follows:

``` c#
using (AsyncScopedLifestyle.BeginScope(container))
{
    container.GetInstance(...);
}
```


Typically what you would do is wrap a scope around a 'request' of some sort. In a web application this would be easy: you wrap a scope around a _web request_. But... with Desktop applications things typically get a bit more complicated, since the resolved root types (like Forms) can live for a long time.

So what you typically should do instead to determine what 'request' means in your application. This would typically be a push of a button. For instance a "Save" button. Once the user presses "Save" you can:

- begin a new scope and resolve the object graph within that scope, 
- operate on the resolved object, and 
- dispose the scope.

What you would like to prevent however is:

- Letting any other code except the Composition Root from having a dependency on the DI Container, which means you don't want to depen on `Container` nor `Scope`.
- You don't want to duplicate the creation of the scope, resolving the object graph, and disposing the scope all over the place.

Whether or not you would be able to achieve such a thing is highly depending on your application's architecture.

I know for instance, that @TheBigRic for instance, has got tons of experience with designing Windows Forms applications and he models his applications around the architecture as described [here](https://cuttingedge.it/blogs/steven/pivot/entry.php?id=91) and [here](https://cuttingedge.it/blogs/steven/pivot/entry.php?id=92). That is: he defines an `ICommandHandler<T>` for executing any state mutations and he defines an `IQueryHandler<TQuery, TResult>` for executing any read operation.

Such architecture might be a too big step for you to take in your existing application, but the advantage of it is, is that with two simple decorators is all you need to allow all command handlers and all query handlers be executed in their own isolated scope, without any code (except the Composition Root) from taking a dependency on the container.

But if you don't practice this kind of architecture, you can still achieve the same by using an Dynamic Proxy or Interception library (such as Castle.Core). Such library can generate decorator types for you on the fly that make use of interceptor classes that you define.

Again, Desktop applications are typically a bit more complex to work with, but if you are able to use scoping and make sure the managing of scopes is centralized in the Composition Root, it allows you to make your application code simpler and more maintainable. It prevents you from having to let consumers dispose of their dependencies, which is typically a bad practice, because the consumer typically has no idea whether or not it is safe to dispose its dependencies (they might be reused).

**Comment by maulwuff** [comment]
From my understanding, this is what we want to achieve:

```
class SomeForm : Form
{
    private void SelectButton_Click(object sender, EventArgs e)
    {
        using (AsyncScopedLifestyle.BeginScope(_container))
        {
            ...
```

And we want to keep the container in the CR:

> What you would like to prevent however is 
> - Letting any other code except the Composition Root from having a dependency on the DI Container ...

How should this be done? 
The form is the wrong location. Its controller is the wrong location. 
How should I run a using statement without having it under control (because
it should be in the CR)

I have done something similar for TransactionScopes, which acts like a factory, but the consumer with the `using(Transactionscope...)` block is still aware of the object ...

**Comment by dotnetjunkie** [comment]
> How should this be done?

Read [this article](https://cuttingedge.it/blogs/steven/pivot/entry.php?id=91) first, before continuing what I'll be describing in my next response.

**Comment by dotnetjunkie** [comment]
Done reading? Great! Here we go!

What you should do is implement business operations as implementation of `ICommandHandler<T>`. Let's say for instance that the user presses a "Cancel Order" button, that would respond to the following message:

``` c#
public class CancelOrder
{
    public Guid OrderId { get; set; }
}
```

The underlying business logic should be implemented using the `ICommandHandler<T>` interface, as follows:

``` c#
public class CancelOrderHandler : ICommandHandler<CancelOrder>
{
    public CancelOrderHandler( /* your dependencies here, as usual */) { ... }

    public void Handle(CancelOrder command)
    {
        // your regular business stuff here.
    }
}
```

Since you introduced the `ICommandHandler<T>` abstraction, we can now let our forms depend on this, for instance:

``` c#
class CancelOrderForm : Form
{
    private readonly ICommandHandler<CancelOrder> cancelOrderHandler;
    public CancelOrderForm(ICommandHandler<CancelOrder> cancelOrderHandler)
    {
        this.cancelOrderHandler = cancelOrderHandler;
    }

    private void CancelOrderButton_Click(object sender, EventArgs e)
    {
        this.cancelOrderHandler.Handle(new CancelOrder { OrderId = this.SelectedOrderId });
    }
}
```

But wait? Didn't I say you should wrap a button click in a new scope? Yes I did, but neither is the responsibility of the form or the handler. Instead we should define some piece of infrastructure that allows us to do this.

Since you defined a very generic `ICommandHandler<T>` abstraction that can be used for all business operations (mutations that is), we can define a Proxy on top of `ICommandHandler<T>` that not only postpones the creation of the real handler, but also wraps the operation in a new scope. This looks as follows:

``` c#
public class ScopedCommandHandlerProxy<T> : ICommandHandler<T>
{
    private readonly Container container;
    private readonly Func<ICommandHandler<T>> factory;

    public ScopedCommandHandlerProxy(Container container, Func<ICommandHandler<T>> factory)
    {
        this.container = container;
        this.factory = factory;
    }

    public void Handle(T command)
    {
        using (AsyncScopedLifestyle.BeginScope(this.container))
        {
                var handler = this.factory();
                handler.Handle(command);
        }
    }
}
```

This simple proxy class can be wrapped around every command handler implementation, and by doing so we will be able to create a new scope, and create a new handler, every time the Proxy's `Handle` method is executed, independently of the lifestyle of both the form and the proxy.

You can register this as follows:

``` c#
// Batch-register all command handler implementations (as transient)
container.Register(typeof(ICommandHandler<>),
    new[] { typeof(CancelOrderHandler).Assembly });

// Make sure the proxy is wrapped around each command handler implementation
container.RegisterDecorator(
    typeof(ICommandHandler<>),
    typeof(ScopedCommandHandlerProxy<>));
```

This is all. Now when `CancelOrderForm` is resolved, it gets the following object graph:

``` c#
new CancelOrderForm(
    new ScopedCommandHandlerProxy<CancelOrder>(
        container,
        () => new CancelOrderHandler(...)));
```

In other words, the `CancelOrderForm` now gets injected with the `ScopedCommandHandlerProxy` and it will only get injected with a factory that allows the creation of `CancelOrderHandler` when invoked.

Since `ScopedCommandHandlerProxy` wraps the call to the factory in a scope, it allows any `Scoped` registrations to exist exactly once inside that scope, and will get disposed at the end of the Proxy's `Handle` method.

Once you have such `ICommandHandler<T>` abstraction in place, it becomes trivial to add other Cross-Cutting Concerns, as explained in the blog post. You talked about `Transactionscope`, take a look at the `TransactionCommandHandlerDecorator<TCommand>` class in that article.

This is how I've been designing most of my systems for over the last 7 years, and this works very well fo everything but the smallest applications (it might be overkill for really small applications).

**Comment by TheBigRic** [comment]
I can only say Amen to this. 

All my applications (mostly windows forms and wpf) work like this nowadays and until now I didn't find anything that could not be done with this pattern or patterns. 

Please help yourself and try to understand this, it will make you produce far better software in a far quicker way. 

I also wrote a stackoverflow answer on lifetime scoping in windows forms. So if you haven't enough reading, take a look here: [Using Simple Injector with Unit Of Work & Repository Pattern in Windows Form ](https://stackoverflow.com/a/29808487/3294832)

**Comment by maulwuff** [comment]
Thanks a lot for the detailed examples. I've read article 91 multiple times already, but turning your head upside down after 7 years architecting in lego style, is not an easy task. It just hit me, as I red "decorator" the first time in your blog post ;-) I think I'll have to read it some more times in the future.  (I found, that thinking in decorators helps to keep a clean design. If you would not be able to decorate a class, something may be going wrong)

I'm now struggling with something like this:
```
container.RegisterConditional(typeof(IDbAdapter<>), typeof(MockDbAdapter<>), Lifestyle.Scoped, c => !c.Handled && UseMockDatabase);
container.RegisterConditional(typeof(IDbAdapter<>), typeof(SqlServerAdapter<>), Lifestyle.Scoped, c => !c.Handled);
```
Is  `c` meant to be evaluated dynamically? `UseMockDatabase` is a property which should influence wheter the  `MockDbAdapter` is used or not.  This way I want to switch between mockup and real database to fill the mockup data files ;)

**Comment by dotnetjunkie** [comment]
> Is `c` meant to be evaluated dynamically?

No. It is evaluated once per closed type that Simple Injector builds. After the type is built, this information is burned into the compiled object graph and the delegate is _never_ called again.

This means that you _can't_ use the delegate to influence the returned type _at runtime_.

This design is delibarate, since the structure of object graphs should not change based on runtime conditions.

Instead, if decisions should be made based on runtime conditions, create a proxy implementation for `IDbAdapter<T>` that wraps both a `MockDbAdapter<T>` and `SqlServerAdapter<T>`. It can decide at runtime which implementation to forward the call to based result of `UseMockDatabase`.

Example:

``` c#
public class UseMockOrNotDbAdapterProxy<T> : IDbAdapter<T>
{
    public UseMockOrNotDbAdapterProxy(MockDbAdapter<T> mock, SqlServerAdapter<T> real) { ... }

    // implement IDbAdapter<T> methods here
    public object SomeMethod(object value) => this.GetAdapter().SomeMethod(value);

    private IDbAdapter<T> GetAdapter() => UseMockDatabase ? this.mock ? this.real;
}
```

**Comment by maulwuff** [comment]
thanks a lot :)
