### ISSUE TITLE
Question: Is this design correct for data access layer (using EF)

### ISSUE THREAD

**Issue by jigneshkvp** [simpleinjector/SimpleInjector#488]
``` c#
// Model class - created automatically by EF, but IDataContext is manually created
public partial class DataContext : DbContext, IDataContext{
    public DataContext() : base("name=datacontext"){}
    
    public virtual DbSet<Customer> Customers{get;set;}
}

// IDataContext is copy of DataContext and is used as shown below
public IDataContext : IDisposable{
    DbSet<Customer> Customers{get;set;}
}

// public interface for accessing data
public interface IDataAccesor{
    string GetCustomerName(int customerId);
}

// Implementation of IDataAccesor
public class DataAccessor : IDataAccesor
{
    private readonly IDataContext _dataContext;
    
    public DataAccessor(IDataContext dataContext)
    {
        _dataContext = dataContext;
    }
    
    public string GetCustomerName(int customerId)
    {
        return _dataContext.GetCustomerName(customerId);
    }
}

// LifetimeScoping of DataAccessor
public class LifetimeScopingDataAccessor : IDataAccesor{
    private readonly Func<IDataAccessor> _decorateeFactory;
        private readonly Container _container;
    
    public LifetimeScopingDataAccessor(Func<IDataAccessor> decorateeFactory, 
            Container container)
    {
        _decorateeFactory = decorateeFactory;
        _container = container;
    }
    
    public string GetCustomerName(int customerId)
    {
         using (ThreadScopedLifestyle.BeginScope(_container))
        {
            var dataAccessor = _decorateeFactory.Invoke();
            return dataAccessor.GetCustomerName(customerId);
        } 
            
}

public class Bootstrapper
{
    // Registration under composition root
    var container = new Container();
    
    container.Options.DefaultScopedLifestyle = new ThreadScopedLifestyle();
    
    container.Register<IDataAccessor, DataAccessor>(Lifestyle.Scoped);
    container.RegisterDecorator<IDataAccessor, LifetimeScopingDataAccessor>();
    
    container.Register<IDataContext, DataContext>(Lifestyle.Scoped);
}

// The WCF REST service behavior is configured as follows: 
// [ServiceBehavior(InstanceContextMode = InstanceContextMode.PerCall, 
//     ConcurrencyMode = ConcurrencyMode.Multiple)]

// Multi-threaded application, hence need DbContext instance per web service operation
```

**Queries:**

- Is the registration and the lifestyle correct based on the service behavior?
- Do I need to implement IDisposable explicitly in DataAccessor to dispose the IDataContext?
- If I do not implement IDisposable in DataAccessor, then will SimpleInjector via the LifetimeScopingDataAccessor dispose the DataContext/ProductDataContext
- I request your input/comments and suggestion for better design.

**Comment by dotnetjunkie** [comment]
> Is the registration and the lifestyle correct based on the service behavior?

Nope. You will notice this when calling `container.RegisterWcfServices(assemblies)`. It will throw an exception explaining that Simple Injector does _not_ support `ConcurrencyMode = ConcurrencyMode.Multiple`.

When using DI, you typically resolve an object graph per thread. This ensures that each thread gets its own set of services, and prevents multi-threading issues. From that perspective, it doesn't make sense to configure a WCF service using `ConcurrencyMode.Multiple`. A WCF service is the top of an object graph, and reuse of that graph over threads is a bad idea.

> Do I need to implement IDisposable explicitly in DataAccessor to dispose the IDataContext?

No. In case you register a disposable class as `Lifestyle.Scoped`, Simple Injector will ensure its disposal.

> If I do not implement IDisposable in DataAccessor, then will SimpleInjector via the LifetimeScopingDataAccessor dispose the DataContext/ProductDataContext?

Absolutely. You configured the `Scoped` lifestyle to be `ThreadScopedLifestyle` and resolved the `IDataAccessor` using a factory inside a newly created scope. Any scoped instances created during that scope, will get disposed when that scope ends, which is at the end of the `GetCustomerName` method, since the C# compiler will call `Dispose` on `Scope` for you.

> I request your input/comments and suggestion for better design.

One tip: Do _not_ implement `IDisposable` on abstractions. Therefore: do not implement `IDisposable` on `IDataContext`. That just complicates its API and allows consumers to dispose it, while only the Container/Composition Root should dispose it. Instead, implement `IDisposable` directly on the implementation. This way Simple Injector can dispose that type, but consumers of the abstraction can't.

**Comment by jigneshkvp** [comment]
Thanks a lot Steven for your quick response and valuable comments, much appreciated!

I need your further help and insight. Based on your comments, I perceive, I need to make some architectural changes for my service in order to use Simple Injector the correct way! 

I need my API to be stateless and hence I would go ahead doing the following changes:

- Set the service behavior as
`[ServiceBehavior(InstanceContextMode = InstanceContextMode.PerCall,  ConcurrencyMode = ConcurrencyMode.Single)]`
Also read through the comments on this blog [https://stackoverflow.com/questions/9323443/does-wcf-service-use-multiple-threads-to-process-incoming-requests](https://stackoverflow.com/questions/9323443/does-wcf-service-use-multiple-threads-to-process-incoming-requests)

- Next, regarding IDisposable on DataAccessor, instead of IDataContext
```
// Remove IDisposable here
public IDataContext 
{
    DbSet<Customer> Customers{get;set;}
}

// LifetimeScoping of DataAccessor
public class LifetimeScopingDataAccessor : IDataAccesor{
    private readonly Func<IDataAccessor> _decorateeFactory;
        private readonly Container _container;
    
    public LifetimeScopingDataAccessor(Func<IDataAccessor> decorateeFactory, 
            Container container)
    {
        _decorateeFactory = decorateeFactory;
        _container = container;
    }
    
    public string GetCustomerName(int customerId)
    {
        using (ThreadScopedLifestyle.BeginScope(_container))
        {
            var dataAccessor = _decorateeFactory.Invoke();
            return dataAccessor.GetCustomerName(customerId);
        } 
            
}

// Do I still need IDisposable here? 
// since SimpleInjector will call Dispose for each implementation of DataAccessor
// when every method executed under LifetimeScopingDataAccessor is under a new container scope
public class DataAccessor : IDataAccesor, IDisposable
{
    private readonly IDataContext _dataContext;
    
    public DataAccessor(IDataContext dataContext)
    {
        _dataContext = dataContext;
    }
    
    public string GetCustomerName(int customerId)
    {
        return _dataContext.GetCustomerName(customerId);
    }

   public void Dispose()
    {
         GC.SuppressFinalize(this);
    }
}
```
**My query here is:**
- Since I need my DataContext to be disposed everytime, C# compiler will call the Dispose method for each implementation used in ProductDataAccessor when the scope ends(in LifetimeScopingDataAccessor), then do I still need to have IDisposable on ProductDataAccessor?

- Is the use of ThreadScopedLifestyle correct for the this kind of API setup (stateless) or should I use AsyncScopedLifeStyle? or any other lifestyle (extensions etc.) What factors should decide choosing a lifestyle for such an API (stateless WCF REST or Web API)

- Do I need to write a custom WCF service host factory, that will instantiate the service instance for each service operation? If yes, it would be very helpful if could you provide me an example on the usage of it.

Your help and insight is very much appreciated. Looking forward for your reply.

**Comment by dotnetjunkie** [comment]
> I need to make some architectural changes for my service in order to use Simple Injector the correct way!

It's not so much that you should try to use Simple Injector correctly, but that you should try to _design_ your application correctly (according to SOLID). If you do that, you'll see that this typically works much better with DI Containers, like Simple Injector.

> do I still need to have IDisposable on ProductDataAccessor?

You _only_ need to implement `IDisposable` if the class _itself_ contains some unmanaged resources that need to be cleaned up. Do _not_ implement `IDisposable` because its _dependencies_ require disposal. The rule around disposable i
_only_ need to implement `IDisposable` if the class _itself_ contains some unmanaged resources that need to be cleaned up. Do _not_ implement `IDisposable` because its _dependencies_ require disposal. The rule around disposable is:

> _**he who creates a resource, should dispose it.**_

So if `ProductDataAccessor` doesn't create the dependency (but instead gets an existing instance injected), it should _not_ dispose it. Since dependencies are typically created by your container, it should make sure it is disposed. Simple Injector will do that once you register it as `Scoped`.

> C# compiler will call the Dispose method for each implementation used in ProductDataAccessor when the scope ends

This is absolutely not what will happen. The C# compiler will _not_ call `Dispose` when a method ends. There are only a handful of scenarios where the C# compiler calls `Dispose` and that's when:
- You explicitly call `Dispose` yourself (duh)
- When you wrap a disposable in a `using` block
- When the disposable is an `Enumerator()` that is iterated over using foreach.

So don't expect the C# compiler to do anything.

With the `LifetimeScopingDataAccessor`, since you wrap the `Scope` instance inside a `using` block, the C# compiler will dispose the `Scope`. Simple Injector will at that point ensure that all scoped instances that are created during that scope are disposed.

> Is the use of ThreadScopedLifestyle correct for the this kind of API setup (stateless) or should I use AsyncScopedLifeStyle? or any other lifestyle (extensions etc.) What factors should decide choosing a lifestyle for such an API (stateless WCF REST or Web API)

The use of `AsyncScopedLifestyle` is only required when you wrap the scope around an asynchronous operation. In other words, in case there is a `await` statement in between the creation and disposal of the scope, that's when `AsyncScopedLifestyle` is required. If the operation is guaranteed to be single-threaded, this is when you _can_ use `ThreadScopedLifestyle`.

Do note though that even for single-threaded operations, `AsyncScopedLifestyle` is still perfectly fine to use and in the future we will promote `AsyncScopedLifestyle` as the default scoped lifestyle. Reason for this is that more applications are becoming asynchronous and even for synchronous applications, this lifestyle works fine. Using this lifestyle might save you some bugs when in the future your application becomes asynchronous, but you forget to change the `ThreadScopedLifestyle` as well.

> What factors should decide choosing a lifestyle for such an API (stateless WCF REST or Web API)

The coming guidance will be to always use `AsyncScopedLifestyle` whenever possible:
- Web API already uses this lifestyle behind the covers.
- WCF integration will use it from v4.1 and beyond. 
- For ASP.NET Core, there is no custom lifestyle anymore.

Unfortunately there are some cases where `AsyncScopedLifestyle` does not fit, which is:
- When running < .NET 4.5, since `AsyncScopedLifestyle is not compatible with .NET 4.0.
- In some cases with MVC and OWIN, where async state is cleared during the request. In that case, `WebRequestLifestyle` is preferred.

> Do I need to write a custom WCF service host factory, that will instantiate the service instance for each service operation? If yes, it would be very helpful if could you provide me an example on the usage of it.

Hard to say. Do the [documentation](https://simpleinjector.org/wcf) point you into the right direction?

**Comment by jigneshkvp** [comment]
Thanks a lot Steven! Appreciate all your help and advise.
