### ISSUE TITLE
RegisterUnresolvedType event exception - explicit registration works

### ISSUE THREAD

**Issue by tynor88** [simpleinjector/SimpleInjector#49]
I am trying to use the [RegisterUnresolvedType](http://simpleinjector.readthedocs.org/en/latest/advanced.html#unregistered-type-resolution) event, but I am getting an exception when calling ``` container.Verify()```.

If i register my messagehandlers explicitly, it works fine. The following code demonstrates the problem:

``` c#
public interface IMessageHandler<TMessage> { }
public class Message1 { }
public class Message2 { }
public class Service1 { public Service1(IMessageHandler<Message1> message1) { } }
public class Service2 { public Service2(IMessageHandler<Message2> message2) { } }
public class MessageHandlerBase<TMessage> : IMessageHandler<TMessage> { }

private static void Main(string[] args)
{
    Container container = new Container();

    container.RegisterSingle<Service1>();
    container.RegisterSingle<Service2>();

    container.ResolveUnregisteredType += (sender, e) =>
    {
        if (e.UnregisteredServiceType.IsGenericType &&
            e.UnregisteredServiceType.GetGenericTypeDefinition() == typeof(IMessageHandler<>))
        {
            var messageHandlerType = typeof(MessageHandlerBase<>).MakeGenericType(
                e.UnregisteredServiceType.GetGenericArguments());

            object messageHandler = container.GetInstance(messageHandlerType);

            // Register the instance as singleton.
            e.Register(() => messageHandler);
        }
    };

    container.Verify();
    DiagnosticResult[] results = Analyzer.Analyze(container);
}
```

The `Analyzer.Analyze` method throws a `NullReferenceException` with the following stack trace:

```
at SimpleInjector.Helpers.ToFriendlyName(Type type, Func`2 argumentsFormatter)
at SimpleInjector.Helpers.ToFriendlyName(Type type)
at SimpleInjector.Diagnostics.Analyzers.TornLifestyleContainerAnalyzer.BuildDescription(InstanceProducer diagnosedProducer, InstanceProducer[] affectedProducers)
at SimpleInjector.Diagnostics.Analyzers.TornLifestyleContainerAnalyzer.CreateDiagnosticResult(InstanceProducer diagnosedProducer, InstanceProducer[] affectedProducers)
at SimpleInjector.Diagnostics.Analyzers.TornLifestyleContainerAnalyzer.<Analyze>b__4(<>f__AnonymousType20`2 <>h__TransparentIdentifier0)
at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
at SimpleInjector.Diagnostics.Analyzers.TornLifestyleContainerAnalyzer.Analyze(IEnumerable`1 producers)
at SimpleInjector.Diagnostics.Analyzer.<>c__DisplayClassb.<Analyze>b__2(IContainerAnalyzer analyzer)
at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
at SimpleInjector.Diagnostics.Analyzer.Analyze(Container container)
at ConsoleApplication1.Program.Main(String[] args)
```

I am not sure what i am doing wrong?

**Comment by dotnetjunkie** [comment]
This is certainly a bug, because the library throws a NullReferenceException and that is always a bug. This NullReferenceException hides the real error that Simple Injector should have communicated clearly. I marked it as bug and assigned it to the coming v3 release.

What you are doing however is not the most optimal registration. Your `ResolveUnregisteredType` delegate makes the diagnostic system blind. It blinds the diagnostic system, because you call resolve a `MessageHandlerBase<T>` using `GetInstance(Type)` and register it as delegate. This disables effective diagnostics, because the `MessageHandlerBase<T>` type is unknown to the container, and the `GetInstance` call will implicitly register it as `Transient`, while your intention is to use it as singleton. If for instance the `MessageHandlerBase<T>` gets dependencies on its own with a lifestyle shorter than `Singleton`, this should cause the diagnostics to warn about a [Lifestyle Mismatch](https://simpleinjector.readthedocs.org/en/latest/PotentialLifestyleMismatches.html), but since the container things this registration is `Transient`, no warning will pop up.

The correct way of doing this is therefore the following:

``` c#
container.ResolveUnregisteredType += (sender, e) =>
{
    if (e.UnregisteredServiceType.IsGenericType &&
        e.UnregisteredServiceType.GetGenericTypeDefinition() == typeof(IMessageHandler<>))
    {
        var messageHandlerType = typeof(MessageHandlerBase<>).MakeGenericType(
            e.UnregisteredServiceType.GetGenericArguments());

        Registration registration = Lifestyle.Singleton.CreateRegistration(
            e.UnregisteredServiceType, messageHandlerType, container);

        e.Register(registration);
    }
};
```
Here a `Singleton` `Registration` object is created and supplied to the `e.Register` method. This makes it completely clear to the container what the implementation type is, doesn't break the dependency graph, and doesn't blind the diagnostic system. Do note that this also removes the problem you encountered.

But for this specific scenario the library already contains a `RegisterOpenGeneric` extension method, so instead of using `ResolveUnregisteredType`, you can make the following registration instead:

``` c#
container.RegisterOpenGeneric(typeof(IMessageHandler<>), typeof(MessageHandlerBase<>),
    Lifestyle.Singleton);
```
The `RegisterOpenGeneric` method itself hooks onto the `ResolveUnregisteredType` event, so it behaves the same way; i.e. it becomes a fallback mechanism in case an explicit registration is missing.

Not only is this method call much more convenient, it fixes several problems that the previous code snippet still has, such as:
 - It is thread-safe; The previous snippet is not guaranteed to create one `MessageHandlerBase<T>` instance per closed-generic `T`, because multiple threads are allowed to call the `ResolveUnregisteredType` event concurrently, in which case multiple independent singleton registrations might be created.
 - It will ensure to work correctly in all complex and weird ways you can work with generic types and type constraints. In your current example this isn't an issue, but becomes an issue when you for instance define a type as follows: `MessageHandlerX<T> : IMessageHandler<UpdateMessage<T>>`.

**Comment by tynor88** [comment]
Awesome, i was not aware of the ```RegisterOpenGeneric``` method, i really need to learn, to read the whole documentation!

Thanks for the great explanation, this solved my problem.
