### ISSUE TITLE
DatabaseConfig

### ISSUE THREAD

**Issue by smarteez** [simpleinjector/SimpleInjector#492]
Hi was using Autofac before but I need to convert it using Simple Injector. I check the document I can't fine any information on this. Please can you advise 

Do I still need to do the following below? 

When I change `IContainerProvider` to `Container` I get an error on this line:

``` C#
using (var dbContext = _containerProvider.**ApplicationContainer**.Resolve<DbContext>())
```

How do I Register it?

``` c#
//Register DatabaseConfiguration
containerBuilder.RegisterType(typeof(DatabaseConfig)).InstancePerRequest();

public class DatabaseConfig
{
    public static void Initialize(IContainerProvider _containerProvider)
    {
        Database.SetInitializer(
            new MigrateDatabaseToLatestVersion<SmarteezMediaDBContext, Configuration>());
            
        using (var dbContext = _containerProvider.ApplicationContainer
            .Resolve<DbContext>())
        {
            if (!dbContext.Database.Exists())
            {
                dbContext.Database.Initialize(true);
            }
        }
    }
}
```

Here is the `Configuration` Class 

``` c#
public class Configuration : DbMigrationsConfiguration<SmarteezMediaDBContext>
{
    public Configuration()
    {
        AutomaticMigrationsEnabled = true;
        AutomaticMigrationDataLossAllowed = true;
    }

    protected override void Seed(SmarteezMediaDBContext context)
    {
        base.Seed(context);
    }
}
```

**Comment by dotnetjunkie** [comment]
The Simple Injector to Autofac's `InstancePerRequest` is `Lifestyle.Scoped`:

``` c#
container.Register<DatabaseConfig>(Lifestyle.Scoped);
```

As the documentation [describes](https://simpleinjector.org/lifestyles#scoped), to be able to use `Lifestyle.Scoped`, you will have to set the container's default scoped lifestyle, which will for most applications be `AsyncScopedLifestyle`:

``` c#
var container = new Container();
// Set the scoped lifestyle one directly after creating the container
container.Options.DefaultScopedLifestyle = new AsyncScopedLifestyle();
```

Please follow the Simple Injector integration guide for your particular application type to find out what the best scoped lifestyle is.

A `DbContext` is typically registered as `Scoped` as well:

``` c#
container.Register<DbContext>(Lifestyle.Scoped);
```

When you resolve an object graph that contains a `Scoped` dependency, Simple Injector will _force_ you to wrap the operation in an active scope, because it could otherwise lead to [Captive Dependencies](http://blog.ploeh.dk/2014/06/02/captive-dependency/). Your `Initialize` method should therefore be rewritten to:

``` c#
public class DatabaseConfig
{
    public static void Initialize(Container container)
    {
        Database.SetInitializer(
            new MigrateDatabaseToLatestVersion<SmarteezMediaDBContext, Configuration>());
            
        // Assuming AsyncScopedLifestyle is the configured Scoped lifestyle
        using (AsyncScopedLifestyle.BeginScope(container))
        {
            var dbContext = container.GetInstance<DbContext>();
            
            if (!dbContext.Database.Exists())
            {
                dbContext.Database.Initialize(true);
            }
            // note: dbContext doesn't need to be disposed, this will be done automatically
            // when the created scope is disposed.
        }
    }
}
```
Do note that just as Simple Injector, Autofac works with scopes as well. In Autofac this concept is called "lifetime scope" and you should typically wrap an operation in a scope to prevent getting Captive Dependencies.

**Comment by smarteez** [comment]
thanks DatabaseConfig can you tell me all the using you used as AsyncScopedLifestyle is giving me an error  and so is Container

**Comment by dotnetjunkie** [comment]
> is giving me an error

Since I'm still working on my psychic powers, I haven't got to the point to be able to look into peoples minds. So would you be so kind to post the error as well? With it, describe whether it is a compile error or runtime error. In case of a runtime error, please post the stack trace of the exception and all inner exceptions as well.

**Comment by smarteez** [comment]
Sorry I found the problem I was missing a using
