### ISSUE TITLE
Multiple Containers in a Single Application

### ISSUE THREAD

**Issue by brajarajan** [simpleinjector/SimpleInjector#496]
@dotnetjunkie  - Can we have multiple containers in a single application, the need for such thing is my application loads different modules on threads and they are isolated modules and need their own set of containers.

**Comment by dotnetjunkie** [comment]
> Can we have multiple containers in a single application

Absolutely. If your application has highly isolated modules, you can certainly have a single container per module.

The rule of thumb with DI Containers (and this typically holds for all DI libraries) is to only create a finite number of container instances. So you should not create a new container instance per (web) request, because that will give a tremendous performance penalty. The same holds for spinning off background threads: you should not create a new container instance every time you start an operation on a background thread.

But if your application contains 5 isolated modules, it is perfectly fine to create 5 container instances.

Do be aware however that sharing instances between container instances is difficult. So if those modules are not that highly isolated, it is typically better to have one container instance per application.

**Comment by brajarajan** [comment]
Thanks, it helps.
