### ISSUE TITLE
Use with Xamarin.Forms getting exception

### ISSUE THREAD

**Issue by TheConservativeCoder** [simpleinjector/SimpleInjector#498]
Hi,

I've started using SimpleInjector in a Xamarin Forms application and I am getting the exception 

`The PlayerRepository is registered as 'Thread Scoped' lifestyle, but the instance is requested outside the context of an active (Thread Scoped) scope.`?

Here is the code used to set this up.

```C#
public partial class App : Application
{
    private Container _container;
    public Container Container
    {
        get
        {
            return _container;
        }
    }
    public App (Container container)
    {
        InitializeComponent();

        _container = container;

        Bootstrapper.RegisterIoc(container);

        using (ThreadScopedLifestyle.BeginScope(Container))
        {
            MainPage = new NavigationPage(container.GetInstance<MainPage>());
        }
    }
}
```

Here is how I register my services in my bootstrapper class
```C#
public static class Bootstrapper
{
    public static void RegisterIoc(Container container)
    {
        //Register our service here
        container.Register<IDbConnection>(() =>
        {
            return new SqliteConnection();
        }, Lifestyle.Scoped);

        container.Register<IGameRepository, GameRepository>(Lifestyle.Scoped);
        container.Register<IPlayerRepository, PlayerRepository>(Lifestyle.Scoped);

        container.Verify();
    }
}
```

Then in my page the exception occurs in the `Handle_NewPlayer_Clicked` handler when trying to push a modal dialog for display.

```C#
public partial class GamePlayersPage : ContentPage
{
    public GamePlayersPage()
    {
        InitializeComponent();

    }

    void Handle_NewPlayer_Clicked(object sender, EventArgs e)
    {
        App app = (App) Application.Current;
        var container = app.Container;

        Navigation.PushModalAsync(container.GetInstance<NewPlayerPage>());
    }
}
```

**Comment by dotnetjunkie** [comment]
You only seem to wrap the initial creation of the MainPage inside a scope (and destroy the scope and its scoped dependencies directly after). You need to make sure that you wrap any call to GetInstance, and during the usage of the resolved instance, with a scope.

**Comment by TheConservativeCoder** [comment]
So I should create a new scope every time I push a new page just like I did for main page? I thought it was already within scope of the first one?

**Comment by dotnetjunkie** [comment]
>  I thought it was already within scope of the first one?

A `Scope` ends when you call `Dispose` on it. When a `Scope` gets disposed, _all_ instances registered with `Lifestyle.Scoped`, and created within that scope, will be disposed as well.

In your example code, you do the following:

``` c#
using (ThreadScopedLifestyle.BeginScope(Container))
{
    MainPage = new NavigationPage(container.GetInstance<MainPage>());
}
```

What this means is that, although the `MainPage` (with its dependencies) is created inside the just created `Scope`, that `Scope` will be disposed directly after the `using` block ends (since a `using` block will call `Dispose` for you), which means that all Scoped dependencies will be disposed directly after the `MainPage` property is assigned, but before the `App` constructor ends.

> So I should create a new scope every time I push a new page just like I did for main page?

You can't create a new scope, just for resolving instances, because, as I said, all disposable instances will be disposed.

Instead, you should typically create a scope for a longer period of time. Not only should a scope wrap the creation of an object graph, it should wrap _its complete lifetime_. This means that you should:
- Create a scope
- Resolve an object graph
- Use the object graph
- Dispose the scope when you're finished using that object graph

That said, do note that scoping is typically hard to get right in client applications, because object graphs tend to live for a long time, while scoped instances typically need to live for a relatively short duration.

Here are some alternative approaches to try:

- Make all your components immutable, stateless and thread-safe. This allows them to be registered as singleton and means you don't have to resolve them. If you have any disposable objects, such as database connections or O/RM unit of work instances (like Entity Framework's `DbContext`), it does mean that they should not outlive a single method call. This might not always be feasible though.
- You can also consider to only use `Transient` and `Singleton` lifestyles, with the consequence of having no dependencies in your object graph that get shared.
- Create Proxy implementations for dependencies that would otherwise need to be resolved by the container, and create and dispose a `Scope` within the Proxy's methods. An example of such can be found [here](https://simpleinjector.readthedocs.io/en/latest/aop.html) in the Simple Injector documentation. See the `ThreadScopedCommandHandlerProxy<T>` class. This might not always be feasible, because it might force the creation of many Proxy classes.
- To mitigate that, consider changing your application design. When you use generic, one-membered abstractions, as described [here](https://cuttingedge.it/blogs/steven/pivot/entry.php?id=91), it will be trivial to implement a Proxy class, such as the previously noted `ThreadScopedCommandHandlerProxy<T>`.

I hope this helps.
