### ISSUE TITLE
Scoped lifestyle usage for Console/Windows Service and writing UTs

### ISSUE THREAD

**Issue by rajarajanb** [simpleinjector/SimpleInjector#500]
I have a requirement to create multiple long running threads inside a windows service, which is inturn will create short running threads based on request.

**As per Simple Injector documents**
> "Web Request and WCF Operation implement scoping implicitly, which means that the user does not have to start or finish the scope to allow the lifestyle to end and to dispose cached instances. The Container does this for you."
> 

For other normal console or windows service type application, we have to use either Thread Scoped or Async Scoped lifestyles.
Here I end up writing DI specific code inside a library rather on the top layer of the application, which makes it difficult to write Unit Tests for library.

Example:  Windows Service Library code would be 
```
LoadModules(IEnumerable<IModule> modules)
{
	foreach(var module in modules)
	{
		module.Start();
	}
}


```
Library X

```
IModule
-Start
-Stop

Class A : IModule
-Start
-Stop

Class B : IModule
-Start
-Stop
```

Class B's Start is a long running thread, which will spawn new thread per request.

In the long running thread I do the following 
```
using (AsyncScopedLifestyle.BeginScope(MyBootstrap.Container))
{ 
       ....
	Task.Run(() =>
	{
	using (AsyncScopedLifestyle.BeginScope(MyBootstrap.Container))
	{ ... }
	}
       ...
 }
```

I have to do this because as I want different scope for the long running thread and the newly spawned threads inside.

The functionality works fine but I am not able to write Unit Tests, as I have to mock the **AsyncScopedLifestyle.**

Also, not comfortable using DI specific code inside a library. Is there a better way to setup in the bootstrap which will cascade it inside the library.

**Comment by dotnetjunkie** [comment]
> Is there a better way to setup in the bootstrap which will cascade it inside the library

Absolutely. You should move the creation and managing of scopes and the resolving of instance _into_ the Composition Root (CR); your library should have no notion of the existence of a DI Container.

How to do this depends on your application and application design, but the most obvious thing to do is to define an abstraction for your request operations  (if you didn't already have that) and create a decorator for that abstraction _inside_ the Composition Root that will manage the scope for you.

For instance, such abstraction might look like this:

``` c#
public interface IRequest
{
    void Run();
}
```

Now you can define a decorator inside the CR:

``` c#
public class ScopeRequestDecorator : IRequest
{
    Container container;
    IRequest decoratee;

    public ScopeRequestDecorator(
        Container container, IRequest decoratee)
    {
        this.container = container;
        this.decoratee = decoratee;
    }

    public void Run()
    {
        using (AsyncScopedLifestyle.BeginScope(this.container))
        {
            this.decoratee.Run();
        }
    }
}
```

Now how to apply this decorator depends on your design. Perhaps you can resolve the IRequest type from Simple Injector, in which case it can wrap the decorator for you. Otherwise you will have to do this manually, which is obviously also something you want to do in the CR.

I hope this helps.

**Comment by Der-Inder** [comment]
Hello @dotnetjunkie 👍 . Thank you very very much for your valuable feedback and guidance.
i was also struggling for more than weeks or  months  with the same issue :(
Now my code has no knowledge at all about the  DI container, after implementing the decorator pattern, as a result the testing ,  mocking etc. will be very easy during the unit testing.
Also i followed your following advice, felt do not need to reinvent the wheel :) (Since the awesome DI container) will do the same for me.
Perhaps you can resolve the IRequest type from Simple Injector, in which case it can wrap the decorator for you.
Best Regards
Der-Inder
