### ISSUE TITLE
CrossWire between Simple Injector and Microsoft DI in Katana / Web API

### ISSUE THREAD

**Issue by Kahbazi** [simpleinjector/SimpleInjector#504]
I have a ASP.NET WebAPI 2 project on owin/katana, and I'm using Simple Injector. Also I'm using almost all of Microsoft.Extensions packages (ex Logging, Configurations, Options, Caching, Localization) and since theses packages use Microsoft.Extensions.DependencyInjection, I have two IoC Container, almost like [this sample](https://simpleinjector.readthedocs.io/en/latest/aspnetintegration.html) but instead of ASP.NET Core, I'm using owin/katana and ASP.Net WebApi 2. For some reasons I can't use ASP.Net Core MVC.

So I register Simple Injector as `DependencyResolver` for WebApi, my problem is for dependencies which is on Microsoft IoC container, in your sample for ASP.NET Core Integration we have `CrossWire` method which works for this senario, but it needs `IApplicationBuilder`.

So do you have plan to add a `CrossWire` method which get `IServiceCollection` as input instead of `IApplicationBuilder`?

**Comment by dotnetjunkie** [comment]
A `CrossWire` based on `IServiceCollection` will not be added, because for cross-wiring to work reliably, an 'closed' `IServiceCollection` is required. This is why Simple Injector has an `EnableSimpleInjectorCrossWiring` that captures the `IServiceCollection` internally, and has a `CrossWire` that takes in an `IApplicationBuilder`, because at the point in time where `IApplicationBuilder` exists, the `IServiceCollection` will not change (since `IApplicationBuilder` is built using the `IServiceCollection`.

Creating a `CrossWire` that accepts an `IServiceCollection`, might cause Simple Injector to cross-wire a component that is replaced later on, since the `IApplicationBuilder` hasn't been built yet.

What you can do, if there is no `IApplicationBuilder` available, is to create your own instance. Simple Injector's `CrossWire` functionality actually only uses the `ApplicationServices` property of `IApplicationBuilder`, so your implementation can leave the rest of its properties and methods unimplemented.

**Comment by Kahbazi** [comment]
> Creating a CrossWire that accepts an IServiceCollection, might cause Simple Injector to cross-wire a component that is replaced later on, since the IApplicationBuilder hasn't been built yet.

well this is a good point, but now that I know this, can I just take the responsibility to make sure that `IServiceCollection` would not change!?

> What you can do, if there is no IApplicationBuilder available, is to create your own instance.

I really don't want to add packages for ASP.Net Core. Are you saying that if I create my own implementation of `IApplicationBuilder` and just return my own `IServiceProvider` which I'm gonna create with `ServiceCollection.BuildServiceProvider()`, there would be no problem?

Also I look at the source of `CrossWire` methods and see that it uses `IHttpContextAccessor`,  (I know this is not related to SimpleInjector) do you know that if this will cause any problem in Katana environment or not?

**Comment by dotnetjunkie** [comment]
I must admit I haven't got any experience what so ever with your combination of tools. I've worked with both Web API and with ASP.NET Core with its new container, but not mixed the two as you are doing. So I'm not sure how that container is used when you do this on top of Web API / Karana, but in case those external libraries make their registrations in `IServiceCollection`, it would be of no use, unless those services are resolved somewhere.

So somewhere there must already be a built container (possibly using `BuildServiceProvider`), otherwise you could as well ignore them completely?

Also note that you are not _forced_ to use the built-in container. If you only have a few registrations for those external libraries, you might as well register them directly into Simple Injector, and you don't need any cross-wiring at all. But this does all depend on the library you are using. If it requires the registration of a whole chain of dependencies, just to work with the top most dependency that you are using, things become different. It would force you to duplicate that whole set of registrations, which is not advisable.

> Are you saying that if I create my own implementation of IApplicationBuilder and just return my own IServiceProvider which I'm gonna create with ServiceCollection.BuildServiceProvider(), there would be no problem?

Exactly. I'm not implying you use ASP.NET Core, or depend on its packages. You are however already depending on `IApplicationBuilder`, because of the Simple Injector packages you use. So you can create your own implementation.

**Comment by Kahbazi** [comment]
It seems that `CrossWire` depends on `IHttpContextAccessor` which would register on ASP.Net Core, so I can't use both of the containers on mu project.

> Also note that you are not forced to use the built-in container

You are right. The only reason that I used Microsoft DI is that I didn't want to take time to understand how each package (Logging, Caching, Configuration, Options) are registering their services and I also have to know their Lifestyle. I guess I have no other choice than registering Microsoft packages my self on SimpleInjector container, and I hope none of those services depends on internal classes.

**Comment by dotnetjunkie** [comment]
For the most part, it is quite easy to cross-wire components, without support from Simple Injector. The Simple Injector `CrossWire` functionality does some things like figuring out what the lifestyle of a dependency is and suppressing diagnostic warnings, but you might not need this at all.

In case the cross-wired library-components are singletons, cross-wiring is very simple: just resolve them and register them as singleton in Simple Injector.

**Comment by Kahbazi** [comment]
I modify 'CrossWire' method and replace 'IHttpContextAccessor' with my own 'ScopeAccessor'. I would really appreciate it if you could take a look at my code. I would like to know your opinion. Thanks

[Integrating SimpleInjector and Microsoft DI in ASP.Net Web API 2](https://gist.github.com/Kahbazi/4cad9602fe9381f2b598c4c570a95e5f)

**Comment by dotnetjunkie** [comment]
I don't see any problems with this code.
