### ISSUE TITLE
Injecting Dependencies into ASP.NET Core View Model objects

### ISSUE THREAD

**Issue by TheConservativeCoder** [simpleinjector/SimpleInjector#515]
Hi Steven,

Can Simple Injector work with Razor Pages? The instructions for Aspnet Core only mentions MVC.

Thanks

**Comment by dotnetjunkie** [comment]
Can you be more specific? What is it you are trying to achieve?

**Comment by TheConservativeCoder** [comment]
I have registestered this service with simple injector
```c#
_container.Register<IEmailSender, EmailSender>(Lifestyle.Singleton);
```

Then on the page model I have these being injected
```c#
public class RegisterModel : PageModel
{
	private readonly SignInManager<ApplicationUser> _signInManager;
	private readonly UserManager<ApplicationUser> _userManager;
	private readonly ILogger<LoginModel> _logger;
	private readonly IEmailSender _emailSender;

	public RegisterModel(
		UserManager<ApplicationUser> userManager,
		SignInManager<ApplicationUser> signInManager,
		ILogger<LoginModel> logger,
		IEmailSender emailSender)
	{
		_userManager = userManager;
		_signInManager = signInManager;
		_logger = logger;
		_emailSender = emailSender;
	}
}
```
When I then navigate to the Register page I get this exception.
`Unable to resolve service for type 'CompanyName.CaseManagement.Web.Services.IEmailSender' while attempting to activate 'CompanyName.CaseManagement.Web.Pages.Account.RegisterModel'.`

I'm guessing that Simple Injector is not fully integrated with Razor pages yet?

**Comment by dotnetjunkie** [comment]
Please show the full stack trace of the exception and show where you resolve `RegisterModel`.

**Comment by TheConservativeCoder** [comment]
I can't get it to break on the exception but I am getting the developer exception page with this stack trace.

```

    Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, bool isDefaultParameterRequired)
    lambda_method(Closure , IServiceProvider , Object[] )
    Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.DefaultPageModelActivatorProvider+<>c__DisplayClass1_0.<CreateActivator>b__0(PageContext context)
    Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.DefaultPageModelFactoryProvider+<>c__DisplayClass3_0.<CreateModelFactory>b__0(PageContext pageContext)
    Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.CreateInstance()
    Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
    Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker+<InvokeInnerFilterAsync>d__22.MoveNext()
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__22.MoveNext()
    Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
    Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
    Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__17.MoveNext()
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__15.MoveNext()
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
    Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext()
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware+<Invoke>d__4.MoveNext()
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware+<Invoke>d__6.MoveNext()
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware+<Invoke>d__6.MoveNext()
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()
```

RegisterModel would be resolved by the inbuilt system that is provided by default I believe.

**Comment by dotnetjunkie** [comment]
Ah, I think I begin to understand what you are trying to do. You are injecting dependencies into your MVC view model classes. This is a very bad idea, because view models should be simpe data containers. They should contain _no_ behavior and neither expose nor hold any dependencies. This forces the Razor views to be simple and stupid. Experience has taught that this makes your application most maintainable.

When you follow that practice, only the controller will (and should) have dependencies. A view model is, and should be, a mere data container.

Because Simple Injector tries to steer its users into follows best practices, the integration packages lack any features that allow Simple Injector to compose Razor view models for you and we would strongly advise against doing this.

But if you insist, you can always plug in this behavior yourself. The stacktrace already gives some hints about how to go about. It will probably mean creating a custom `IPageModelActivatorProvider` and registering it in the ASP.NET configuration system.

**Comment by TheConservativeCoder** [comment]
This is how Razor Pages works out the box from MS, still it would be good if it could work.

I have been looking at the `IPageModelActivatorProvider` and comparing to `IControllerActivator` and your implementation `SimpleInjectorControllerActivator`.

**Comment by dotnetjunkie** [comment]
> This is how Razor Pages works out the box from MS

True, but not all that MS enables promotes good practice :)

> still it would be good if it could work.

You can make it work, but please don't expect any features from our side to help you with this.

**Comment by guy-lud** [comment]
@TheConservativeCoder  Hi,
According to [https://github.com/aspnet/Mvc/issues/7024](this) Microsoft will allow us to override it in milestone 2.2 (if i understood them correctly). But as @dotnetjunkie  said try to separate the layers of the Domain, services and the view

**Comment by claytondus** [comment]
@dotnetjunkie I wholly agree with you regarding MVC views, but this is not what @TheConservativeCoder was trying to do.  MVC view model != MVVM Razor Pages PageModel.  With Razor Pages there is no controller except for the PageModel (preferably in a code-behind file) and so it functions as the MVC Controller and view model in one class.  IMHO it is the apotheosis of a Controller, since it follows SRP and prevents Controllers from accumulating dependencies over time.  All Razor Pages is doing is consolidating the MVC view model and Controller when it makes sense.  Now it is possible to get into a mess with Razor Pages using the implicit page model (doing data access in a @functions {} block), but I wouldn't support that either.

Someone has written a sample SimpleInjectorPageModelActivatorProvider [here: https://stackoverflow.com/questions/50065258/simple-injector-inject-into-pagemodel-asp-net-core-razor-pages](https://stackoverflow.com/questions/50065258/simple-injector-inject-into-pagemodel-asp-net-core-razor-pages). However, I have not tested it.

**Comment by dotnetjunkie** [comment]
@TheConservativeCoder, @claytondus,

I just released [v4.5.0-beta1](https://github.com/simpleinjector/SimpleInjector/releases/tag/v4.5.0-beta1) that adds Razor Page integration. There is a new `SimpleInjectorPageModelActivatorProvider` that can be registered as `IPageModelActivatorProvider`. Feel free to check this beta release out and give feedback on that feature.

**Comment by claytondus** [comment]
@dotnetjunkie Looking good so far, thanks.

**Comment by TheConservativeCoder** [comment]
@dotnetjunkie Thank you so much for this!
