### ISSUE TITLE
Any news about full integration with ASP.NET Core ?

### ISSUE THREAD

**Issue by guy-lud** [simpleinjector/SimpleInjector#522]
Hi @dotnetjunkie 

I read yesterday (again) the whole corresponding with David and the Asp team about Simple Injector or any non-conforming  "easy" integration with ASP Core.

Do you have any news about planed changes ?

**Comment by dotnetjunkie** [comment]
The big change from Simple Injector's perspective is that in [v4.1](https://github.com/simpleinjector/SimpleInjector/milestone/22) we are introducing an [AutoCrossWireAspNetComponents](https://github.com/simpleinjector/SimpleInjector/issues/442) extension method on the container, that would automatically pull in ASP.NET components using unregistered type resolution.

This will hopefully severely simplify the non-conforming container model, since it prevents users from having to cross-wire all framework components that manually that are needed by your application components.

What else has changed is that Microsoft more actively acknowledges the existence of non-conforming containers and have written 'some' documentation about this. Still however, they haven't addressed the [elephant in the room](https://github.com/aspnet/Mvc/issues/5403), and I don't think we have to expect any progress in that.

That's a shame, but from perspective of Simple Injector, we're doing all we can to make it easy to plug in our non-conforming container into the ASP.NET Core pipeline.

**Comment by guy-lud** [comment]
Will in your opinion it will allow us to override the `IServiceProvider` with a new `SimpleInjectorServiceProvider` after creating Asp's ServiceProvider and using the AutoCrossWire ? 

I want to have one Ring to rule them all. 

The main issue of course is while `SimpleInjector` has CrossWire `ServiceCollection` will not have it thus all things infrastructure are still handled by the MS ServiceProvider

**Comment by dotnetjunkie** [comment]
> in your opinion it will allow us to override the IServiceProvider with a new SimpleInjectorServiceProvider after creating Asp's ServiceProvider and using the AutoCrossWire ?

No, this is something you should **absolutely not** do, because this will simply _not_ work. You might _think_ you get this working in your demo project, but it will certainly fail later on down the road, especially when you start using other reusable libraries that add their registrations to the `IServiceCollection`.

> The main issue of course is while SimpleInjector has CrossWire ServiceCollection will not have it thus all things infrastructure are still handled by the MS ServiceProvider

That's true, but should not be a big problem, because having ServiceCollection need Simple Injector components is not that common, and something that can be quite effectively worked around, as we always did in the past with other frameworks like MVC and Web API.

**Comment by guy-lud** [comment]
> as we always did in the past with other frameworks like MVC and Web API.

Yes, yet i would love once not to have workaround (not your fault of-course).

I thought i almost was able to figure a way but apparently MS `ServiceProvider` resolve missing collection as Empty Enumerable and `SimpleInjector` throws exception as it should :(

**Comment by dotnetjunkie** [comment]
> I thought i almost was able to figure a way but apparently MS ServiceProvider resolve missing collection as Empty Enumerable and SimpleInjector throws exception as it should

Simple Injector v2.x actually resolved unregistered collections as empty lists, but this behavior was quite implicit, and caused quite a lot of confusion with users, when they forgot to register their collections. That's why with the introduction of [Simple Injector v3](https://simpleinjector.org/blog/2015/08/simple-injector-v3-is-here/), we changed this behavior. Simple Injector now throws an exception, indeed, as it should.

This behavior is one of the many reasons why Simple Injector in incompatible with the ASP.NET Core DI abstraction, and that's why `AutoCrossWireAspNetComponents` will not resolve collections. That would only cause confusion.
