### ISSUE TITLE
Question: Changing parameter injection behavior

### ISSUE THREAD

**Issue by CasperWSchmidt** [simpleinjector/SimpleInjector#526]
Hi

I'm new to using DI in C# and had a look at Windsor, Ninject, Autofac, Unity and Simple Injector. I originally discarded Simple Injector because I needed value-type injection (fx. connection strings) but found the blogpost linked from http://simpleinjector.readthedocs.io/en/latest/extensibility.html#overriding-parameter-injection-behavior. Unfortunately the blogpost is outdated since IDependencyInjectionBehavior.BuildExpression is deprecated in version 4.x and GetInstanceProducer has been introduced instead.
I'm not sure how to do what the blogpost describes with the new InstanceProducer. Is it possible to either make a new blogpost and link it from the docs or update the docs to include an example directly?

**Comment by dotnetjunkie** [comment]
Can you please post an example of what it is you want to achieve? What kind of value type do you need injected and in what kind of class?

**Comment by CasperWSchmidt** [comment]
Hi

Sure. I currently do poor man's DI and have the following settings:
```// Settings
            var conLocal = ConfigurationManager.ConnectionStrings["APIPortMan"].ConnectionString;
            var con = ConfigurationManager.ConnectionStrings["PortMan"].ConnectionString;
            var conAzure = ConfigurationManager.ConnectionStrings["Azure"].ConnectionString;
            var conSitecore = ConfigurationManager.ConnectionStrings["Sitecore"].ConnectionString;
            var azureStorageAccount = ConfigurationManager.AppSettings.Get("StorageConnection");
            var reportUploadPath = ConfigurationManager.AppSettings.Get("ReportUploadPath");
            var PfsmlPath = ConfigurationManager.AppSettings.Get("PfsmlPath");
            var reloadCounter = int.Parse(ConfigurationManager.AppSettings.Get("transactionServiceReloadCounter"));
            var systemStartDate = DateTime.Parse(ConfigurationManager.AppSettings.Get("holdingServiceStartDate"));
            var semaphoreCount = `int.Parse(ConfigurationManager.AppSettings.Get("semaphoreCount"));
```

Then I have some repositories consuming these settings:
```// Repositories
            var _accountRepository = new AccountRepository(con, conAzure);
            var _aggregatedPortfolioRelationshipRepository = new AggregatedPortfolioRelationshipRepository(conAzure);
            var _aggregatedClientRelationshipRepository = new AggregatedClientRelationshipRepository(con, conAzure);
            var _assetBondRepository = new AssetBondRepository(con, conAzure);
            var _assetClassRepository = new AssetClassRepository(con, conAzure);
            var _assetDerivativeRepository = new AssetDerivativeRepository(con, conAzure);
            var _assetRepository = new AssetRepository(con, conAzure);
            var _benchmarkRepository = new BenchmarkRepository(con, conAzure);
            var _benchmarkWeightRepository = new BenchmarkWeightRepository(con, conAzure);
            var _clientRepository = new ClientRepository(con, conAzure);
            var _defaultPriceRepository = new DefaultPriceRepository(con, conAzure);
            var _emailRepository = new UpdateEmailOutput(conAzure);
            var _exchangeRateRepository = new ExchangeRateRepository(con, conAzure);
            var _failedHoldingRepository = new FailedHoldingRepository(conLocal);
            var _GICSRepository = new GICSRepository(con, conAzure);
            var _holdingRepository = new HoldingRepository(conAzure);
            var _limitLineRepository = new LimitLineRepository(con, conAzure);
            var _PFSMLRepository = new PFSMLRepository(PfsmlPath);
            var _portfolioRepository = new PortfolioRepository(con, conAzure);
            var _sitecoreReportRepository = new SitecoreReportRepository(conSitecore, reportUploadPath);
            var _systemInfoRepository = new SystemInfoRepository(conAzure);
            var _transactionRepository = new TransactionRepository(con, conAzure);
```
And later some services consuming the repositories.

Since most of the repositories share a common interface IRepository<T> (besides an individual interface like IAssetRepository that extends IRepository<Asset>) I would like to be able to use batch creation /auto-wiring. Also I would like to avoid changing the DI setup every time a change is made to my main code (ie. new constructor parameter, new repository interface/class etc.).

I have already adopted the convention mentioned in the blogpost (using AzureConnectionString, PortManConnectionString etc.) in the constructors. All I need to do now is make sure Simple Injector handles value type parameters according to the conventions :)

**Comment by dotnetjunkie** [comment]
Personally, I'm in favor of that particular convention based approach, as described in [this](https://cuttingedge.it/blogs/steven/pivot/entry.php?id=94) blogpost (note that this is *my* own blog post). Reason for this is that it couples the DI Container's configuration directly to the configuration file, which makes it very hard to verify the container's configuration in isolation. When you want to verify the correctness of the configuration as part of an automated test, for instance, you will be required to keep the test project's configuration file in sync with that of the application. This gives a lot of overhead, and eventually leads to false positives, when a test invalidly succeeds, because test and app config's differ.

But if you really want this type of convention, `InstanceProducer.FromExpression` is indeed the way to fix this. You'll find a workable version [here](https://github.com/simpleinjector/SimpleInjector/blob/v4.0.x/src/SimpleInjector.CodeSamples/ParameterConventionExtensions.cs) in the repository.

Instead of using this convention based approach that couples your DI Container to the configuration file, is to use conditional registrations to apply this convention. This allows you to keep your current design as-is, but also allows you to separate the reading of the configuration file from object composition.

To achieve this, you still need a custom `IDependencyInjectionBehavior`, but this one is simpler. Its implementation will only prevent the container from throwing an exception when using `string` dependencies. Here it is:

``` c#
internal class AllowStringsInjectionBehavior : IDependencyInjectionBehavior
{
    private IDependencyInjectionBehavior original;

    public AllowStringsInjectionBehavior(Container c) => 
        original = c.Options.DependencyInjectionBehavior;
    public InstanceProducer GetInstanceProducer(InjectionConsumerInfo c, bool t) => 
        original.GetInstanceProducer(c, t);
    public void Verify(InjectionConsumerInfo c)
    {
        if (c.Target.TargetType != typeof(string)) original.Verify(c);
    }
}
```

This behavior is added as follows:

``` c#
container.Options.DependencyInjectionBehavior = new AllowStringsInjectionBehavior(container);
```

Using conditional registrations you can now add your connection strings based on the convention you already have in place. You can simplify this by moving the registration into an extension method:

``` c#


public static class Ext
{
    public static void RegisterConnectionString(this Container ctr, string prefix, string value)
    {
        var reg = Lifestyle.Singleton.CreateRegistration(() => value, ctr);
        ctr.RegisterConditional(typeof(string), reg, 
            c => c.Consumer.Target.Name.StartsWith(prefix));
    }
}
```

You can use this `RegisterConnectionString` method ad follows:

``` c#
var conLocal = ConfigurationManager.ConnectionStrings["APIPortMan"].ConnectionString;
var con = ConfigurationManager.ConnectionStrings["PortMan"].ConnectionString;
var conAzure = ConfigurationManager.ConnectionStrings["Azure"].ConnectionString;

container.RegisterConnectionString(prefix: "local", value: conLocal):
container.RegisterConnectionString(prefix: "port", value: con):
container.RegisterConnectionString(prefix: "azure", value: conAzure):
```

Although this approach allows separating configuration and object composition, it is still not my preferred way of working.

My preferred way is to extract the values into their own configuration type. I do this even if such configuration class contains just one value.

For instance, since most repositories seem to use `con` and `conAzure`, those values seem closely related and likely belong together in one configuration class:

``` c#
public sealed class AzureConnectionConfig
{
    public readonly string AzureConnectionString;
    public readonly string PortConnectionString;

    public AzureConnectionConfig(string azureConnectionString, string portConnectionString) ...
}
```

Besides this configuration class, there will be others, tailored to their implementation(s).


This allows the repository implementations to depend on `AzureConnectionConfig` and therefore only depend on the configuration values they use. Registration of such class is simple:

``` c#
// NOTE: RegisterInstance is new in v4.1 and replaces RegisterSingleton<T>(T)
container.RegisterInstance(
    new AzureConnectionConfig(azureConnectionString: azureCon, portConnectionString: con));
```

Either way, with all approaches however, you can auto/batch register your implementations as follows:

``` c#
container.Register(typeof(IRepository<>), repositoryAssemblies);
```

**Comment by CasperWSchmidt** [comment]
Hi

Your blog was the one I referred to in the first place and I could tell from the domain and your username that it was your blog :)

Thank you for the suggestions. I have decided to go with the last option (using settings objects that I register manually) instead of the convention-based approach. As you said this decouples the DI setup from the app configuration
