### ISSUE TITLE
Bootstrapper for Prism

### ISSUE THREAD

**Issue by DkAngelito** [simpleinjector/SimpleInjector#53]
Hi,

I've been using Simple Injector for a while and I really like it, but now I'm starting a Prism project and I want to use Simple Injector as  the DI Container. I though it was simple but it wasn't. Have you ever done that? Can you please make a new NuGet package for this as there are several other for different DI Container?

Thanks

**Comment by dotnetjunkie** [comment]
Only a small group of developers is using Prism, so that makes the investment pretty high for us to build an official integration package for Prism.

But perhaps we can still support you by helping you with your integration problems. What problems are you having with integrating Simple Injector with Prism?
