### ISSUE TITLE
A question about lifeStyle default selection

### ISSUE THREAD

**Issue by guy-lud** [simpleinjector/SimpleInjector#534]
Hi @dotnetjunkie,

I could not find in the doc why have you chosen Transient LifeStyle as the Default one.

Can you please state your reasons if you can ?

**Comment by dotnetjunkie** [comment]
What lifestyle did you want to have as the default?

**Comment by guy-lud** [comment]
I prefer to use Singleton as default but that just me, it forces the team to think on wider solution for a problem. Never use state, less GC work, using scope should be something to thought about not just use it and so on.

What were your thought on  by making this choice?

**Comment by dotnetjunkie** [comment]
I prefer my object graphs to consist solely of Singletons, with the exception of the root types, since they are often application framework classes (e.g. MVC Controllers) and are stateful.

This practice simplifies development, because it pushes you towards statelessness and immutability and prevents many of the common DI pitfalls; such as Captive Dependencies.

Because of this view, Singleton could easily have been the default lifestyle in Simple Injector, but it is because of two reasons that the default lifestyle is actually Transient:

- Transient was (and still is) the default lifestyle for most DI Containers and I copied this when I started working on S.I., because this seemed a reasonable thing.
- Because of backwards compatibility, I can't easily change the default lifestyle.
- But even if I could change it, the practice of having Singleton object graphs is not a common, nor well-understood practice. This means some really good guidance needs to be written, which should describe how to deal with the consequences of such design. For instance, it's not always immediately clear how to 'flow state' through an Singleton object graph.

That's why the default lifestyle still is Transient, but you can change this with a single line of code:

``` c#
container.Options.DefaultLifestyle = Lifestyle.Singleton;
```

**Comment by guy-lud** [comment]
Thank you, just the answer i wanted to hear
