### ISSUE TITLE
Problem after updating

### ISSUE THREAD

**Issue by JackyBoyRoy** [simpleinjector/SimpleInjector#535]
I've just updated SimpleInjector, I had multiple warnings in my Global.asax about methods being obsolete.

Lines I've changed:
`container.Options.DefaultScopedLifestyle = new WebApiRequestLifestyle();`  OLD
`container.Options.DefaultScopedLifestyle = new AsyncScopedLifestyle();` NEW

and then I had lots of warnings about this kind of thing:
`container.RegisterPerWebRequest<IUnitOfWork, UnitOfWork>();` OLD
`container.Register<IUnitOfWork, UnitOfWork>(Lifestyle.Scoped);` NEW

The above is in a method called `SetupDependencies()`. After this I fetch a service that one of my global filters needs: 

`ILoggedErrorService loggedErrorService = _container.GetInstance<ILoggedErrorService>();`
`GlobalConfiguration.Configuration.Filters.Add(new LogExceptionFilter(loggedErrorService));`

When fetching the service I get an error saying that: 

> UnitOfWork is registered as 'Async Scoped' lifestyle, but the instance is requested outside the context of an active (Async Scoped) scope.

Do I have the wrong default scope set here? My guess is that the previous version allowed me to do this kind of thing without any major drama, but now I need to do things a little safer perhaps? Maybe need a hybrid scope?

I've move from version: 3.1.2 -> 4.2.1

Any help or advice would be great.

**Comment by dotnetjunkie** [comment]
> I've move from version: 3.1.2 -> 4.2.1

TIP: Always upgrade to the latest minor release of your current major release, before upgrading to the next major release. Thus:

- Migrate to v3.3.2 first and fix all warnings and compile errors
- Migrate to v4.0.0 and fix all warnings and compile errors
- Migrate to the latest v4 version.

> When fetching the service I get an error

That's super awesome that you are now getting this error, because it indicates a bug in your application that already existed.

You are resolving your `ILoggedErrorService` during application startup, while it contains dependencies that are `Lifestyle.Scoped`. For this to work, there must be an active scope. `AsyncScopedLifestyle` however requires a scope to be started, while you didn't create a scope.

Although you can create a scope, that would be problematic, because all filters in `GlobalConfiguration.Configuration.Filters` are Singletons; they are kept alive for the duration of the application. Since your `ILoggedErrorService` (or one of its dependencies) is `Scoped`, it is _not_ intented to live as long as the application, and caching such dependency for the duration of the application, and allowing parallel access to it, it typically a _very bad_ idea. It can cause concurrency bugs.

So you should either:

- If possible, register `ILoggedErrorService` and _all_ its dependencies as `Singleton`.
- If you need scoped dependencies in `ILoggedErrorService` graph, either inject a `Func<ILoggedErrorService>` into the `LogExceptionFilter` or create a Proxy filter class, much like [the documentation](https://simpleinjector.readthedocs.io/en/latest/webapiintegration.html#injecting-dependencies-into-web-api-message-handlers) shows with Delegating Handlers.

**Comment by JackyBoyRoy** [comment]
Thanks for the tip, I'll definitely do that in future.

I needed to keep the the dependencies of `ILoggedErrorService` the same, so I went down the `Func<ILoggedErrorService>` route like you suggested.

Thank you.
