### ISSUE TITLE
Use simpleinjector on Azure Function

### ISSUE THREAD

**Issue by aferrandiz1** [simpleinjector/SimpleInjector#536]
How can I use simpleinjector on Azure Function?

**Comment by dotnetjunkie** [comment]
Any problems in particular that you're troubled with?

**Comment by aferrandiz1** [comment]
I want to know if we have some extension or a way to integrate simple injector on Azure Function like **Autofact** does.

Thanks

**Comment by dotnetjunkie** [comment]
Can you point me to the Autofac documentation that describes what you like to achieve with Simple Injector?

**Comment by aferrandiz1** [comment]
https://github.com/introtocomputerscience/azure-function-autofac-dependency-injection

**Comment by dotnetjunkie** [comment]
My advice is to use Azure Functions as [Humble Objects](http://xunitpatterns.com/Humble%20Object.html) being part of your [Composition Root](https://freecontent.manning.com/dependency-injection-in-net-2nd-edition-understanding-the-composition-root/). Instead of injecting services into a Azure Function, move all the business logic out of the Azure Function, into an application component. The function's dependencies can become arguments of the component's constructor. This component can be resolved and called from within the Azure function.

Here's an example.

You can use the following static class that sets up the Container:

``` c#
public static class DIConfig
{
    public static readonly Container Container;

    static DIConfig()
    {
        Container = new Container();
        
        // Example registrations
        Container.Register<ILogger, AzureLogger>(Lifestyle.Singleton);
        Container.Register(typeof(IHandler<>), typeof(IHandler<>).Assembly);
        
        Container.Verify();
    }
}
```

Using the `DIConfig` class, you can let your Azure function call into the `Container` to resolve a service and invoke it with the Function's input arguments:

``` c#
[StorageAccount("AzureWebJobsStorage")]
public class CardGenerator
{
    [FunctionName("GenerateCard")]
    public static void GenerateCard([QueueTrigger("%input-queue%")] GenerateCard command)
    {
        // Resolve the service
        var service = DIConfig.Container.GetInstance<IHandler<GenerateCard>>();
        
        // Invoke the service
        service.Handle(command);
    }
}
```

So instead of injecting dependencies into the Azure function, dependencies are simply injected into the service implementation, as you are used to do. For instance:

``` c#
public class GenerateCardHandler : IHandler<GenerateCard>
{
    private readonly ILogger logger;
    public GenerateCardHandler(ILogger logger)
    {
        this.logger = logger;
    }
    
    public void Handle(GenerateCard command)
    {
        // This is where your original Azure Function logic would sit.
        // In a sense, this IS your function.
    }
}
```

If you set up your application design cleverly, e.g. by introducing generic abstractions such as the `IHandler<T>`, you can simplify many tasks, such as:

- Registering all 'function' component implementations in a single call to `Register`, as shown above.
- You can easily wrap cross-cutting concerns, like the usual validation and tracing, in a way that prevents polluting _all_ Azure Functions.

You can even simplify your Azure Function code by introducing a simple method in the `DIConfig` class:

``` c#
public static void Handle<TCommand>(TCommand command) =>
    Container.GetInstance<IHandler<TCommand>>().Handle(command);
```

This reduces the Azure Function to the following:

``` c#
[FunctionName("GenerateCard")]
public static void GenerateCard([QueueTrigger("%input-queue%")] GenerateCard command) 
    => DIConfig.Handle(command);
```

I hope this helps.

**Comment by aferrandiz1** [comment]
thanks so much, this help a lot.

**Comment by dotnetjunkie** [comment]
@aferrandiz1 I added a link to [the integration page](https://simpleinjector.org/integration) of the documentation to this issue.

**Comment by dotnetjunkie** [comment]
I created a new [Azure Functions Integration](https://simpleinjector.org/azurefunctions) page. This demonstrates how to integrate Simple Injector with  Azure Functions v3.
