### ISSUE TITLE
Main page: top menu doesn't work

### ISSUE THREAD

**Issue by AdaskoTheBeAsT** [simpleinjector/SimpleInjector#538]
Hi,

I am not sure if only I have that issue but top menu on https://simpleinjector.org doesn't work.

**Comment by dotnetjunkie** [comment]
Which browser do you use?

**Comment by AdaskoTheBeAsT** [comment]
Chrome 66.0.3359.117
also on Opera doesn't work
IE 11, Edge, Firefox, Safari on win  works

**Comment by dotnetjunkie** [comment]
This used to work on Chrome in the past. Seems they introsuced a breaking change. I'll try to update the used javascript library.

**Comment by dotnetjunkie** [comment]
I assumed the bug was in the retina.js library, but this actually wasn't the problem. Retina allows loading high-res images automatically, but since all images on the site are SVGs, Retina had no function. I therefore removed it.

But the question remains, why the site suddenly breaks on Chrome. The site hasn't been changed for more than a year.

If anyone has a clue about how to fix this issue, please let me know.

**Comment by jounsss** [comment]
It seems that on Chrome (67.0.3396.62) all the in-page links are broken. I did some digging and it may have something to do with the scroll-libraries used on the page.

**Comment by jounsss** [comment]
Ok, I might have figured it out. Try updating jquery.scrollto.js library. The lastest version at [https://github.com/flesler/jquery.scrollTo](https://github.com/flesler/jquery.scrollTo) is 2.1.2. However I could only get the scroll to work with the non-minified version.

**Comment by dotnetjunkie** [comment]
@jounsss I've tried putting in the newest scrollTo 2.1.2, both with the minified and full version, but in that case it seems to break on all browsers.

**Comment by jounsss** [comment]
How about if you update both [https://github.com/flesler/jquery.localScroll](https://github.com/flesler/jquery.localScroll) and [https://github.com/flesler/jquery.scrollTo](https://github.com/flesler/jquery.scrollTo)?

**Comment by dotnetjunkie** [comment]
Awesome. That did the trick.
