### ISSUE TITLE
Question about registering delegate with context

### ISSUE THREAD

**Issue by valeriob** [simpleinjector/SimpleInjector#550]
Hi,
i'm wondering how can i do something like this

``` c#
  container.Register<MyClass>(ctx =>
            {
                var someParameter = ctx.Resolve<AnotherClass>();
                return new MyClass(someParameter);
            });
```

basically i would like to register a delegate with the possibility to access the current resolution context, to be able to execute some code before creating the instance

Thanks

**Comment by dotnetjunkie** [comment]
In Simple Injector, you can always resolve directly from the `Container` itself, so this is the equivalent to your example:

``` c#
  container.Register<MyClass>(() =>
            {
                var someParameter = container.GetInstance<AnotherClass>();
                return new MyClass(someParameter);
            });
```

However, please note that you should prevent registering delegates that call back into the container whenever possible, because it blinds Simple Injector's [diagnostic abilities](https://simpleinjector.org/diatl).

**Comment by valeriob** [comment]
Thanks @dotnetjunkie
