### ISSUE TITLE
How to register all type in the current assembly?

### ISSUE THREAD

**Issue by srinathgnath** [simpleinjector/SimpleInjector#575]
How to register all type in teh current assmebly using simple injector?

**Comment by dotnetjunkie** [comment]
See: https://simpleinjector.readthedocs.io/en/latest/advanced.html#batch-registration

**Comment by srinathgnath** [comment]
Thanks for sharing the link. I tried this but throwing exceptions on exception classes. How do we skip exception from registration?

**Comment by dotnetjunkie** [comment]
Please provide some code that demonstrates the problem. I'm no psychic :)

**Comment by srinathgnath** [comment]
Below is the code:

         var otestType = typeof(testType).Assembly;
            var registrations =
                from type in otestType.GetExportedTypes()
                where type.IsClass && !type.Name.ToLower().EndsWith("exception")
                where type.Namespace.StartsWith("***.**.***Service")
                where type.GetInterfaces().Any()
                select new { Service = type.GetInterfaces().First(), Implementation = type };

            foreach (var reg in registrations)
            {
                    container.Register(reg.Service, reg.Implementation, Lifestyle.Transient);
            }

This is not skipping exception classes and not registering multiple classes implementation with single interface like class1: testinterface, class2:: testinterface

**Comment by dotnetjunkie** [comment]
> This is not skipping exception classes

If this is what you want, you should filter out the classes you're not interested in.

> not registering multiple classes implementation with single interface like class1: testinterface, class2:: testinterface

That won't work anyway in Simple Injector, since Simple Injector strictly separates the [registration of collections from one-to-one mappings](https://simpleinjector.readthedocs.io/en/latest/decisions.html#separate-collections). For more info on registering collections, see: https://simpleinjector.org/collections.

**Comment by srinathgnath** [comment]
So are you saying everything has to be explicitly register? Does below line of code register all types from the assmebly?

container.RegisterPackages( AppDomain.CurrentDomain.GetAssemblies());
or 
container.RegisterPackages(new[] { Assembly.GetExecutingAssembly() });

**Comment by dotnetjunkie** [comment]
> So are you saying everything has to be explicitly register?

No, absolutely not. You should typically not make all your registrations manually. You should either use Auto-Registration for the bulk of your types, or use no container at all (a.k.a. [Pure DI](http://blog.ploeh.dk/2014/06/10/pure-di/)).

Since different types require different kinds of registrations, however, trying to register everything with one single LINQ query or Auto-Wiring API call will hardly ever work. For instance, different types need different lifestyles, you need to apply decorators, wrap types in composites, have specific order of registration, etc. Besides, there are many types that you don't want to end up in the container,  because that would prevent you from being able to verify the container.

Instead, use Auto-Registration on a particular group of types. For instance, you can register all *Services in one call, and you can do the same with *Repositories, etc. What will be left is a handful of types that don't belong to a group. Things like `ITimeProvider`, for instance.

**Comment by guy-lud** [comment]
Hey Guys,

I Hope it's not an issue here but I've created a lib that auto register services using `SimpleInjector` named `Shepherd`. It could be found [here](https://github.com/existall/Shepherd). 
The main purpose is to orchestrate the registration process and not to be bothered with registration unless you need to do it explicitly.

@dotnetjunkie  if you think this post is rude, please let me know i will remove it
