### ISSUE TITLE
Passing runtime parameter?

### ISSUE THREAD

**Issue by omares** [simpleinjector/SimpleInjector#58]
Is it possible to pass a parameter at runtime to the constructor when using `.GetInstance`?

We have the case that the parameters of a to be injected view model are not known at compile time, because the input is dependent on the user input.

Some meta code for explanation:

``` c#
    class SuperService {
    }

    class HyperSuperViewModel {
        public HyperSuperViewModel(String name, String other) {}
    }

    class SomePage {
        public SomePage(SuperService service, HyperSuperViewModel vm) {}
    }

    container.Register<SuperService>();

    // how to pass instance of HyperSuperViewModel?
    container.GetInstance<SomePage>();
```

**Comment by dotnetjunkie** [comment]
Simple Injector doesn't have built-in support for this, but technically, there are [ways](https://stackoverflow.com/questions/15123515/pass-runtime-value-to-constructor-using-simpleinjector) to achieve this, but I would highly recommend you to change the design instead.

You should prevent mixing application components (a.k.a. [injectables](http://misko.hevery.com/2008/09/30/to-new-or-not-to-new/)) with runtime data. The object graphs that you build using your DI container, should solely consist of application components, and those components should be stateless. State should be passed through the object graph after it is constructed.

Not following this rule leads to complications. For instance, building object graphs using runtime data makes it much harder to [verify the correctness](https://simpleinjector.readthedocs.org/en/latest/howto.html#verify-the-container-s-configuration) of the object graph, and leads to an overly complicated DI configuration.

**Comment by omares** [comment]
So basically you are saying either we do not use SimpleInjector in this scenario by using `new ...` or we apply some hard to maintain workaround?

**Comment by dotnetjunkie** [comment]
No, what I'm saying is: change your design. Because even if you switch to a different IoC container, you will have the same problems with verifiability and complexity of your DI configuration.

**Comment by omares** [comment]
I understand, after reading the article would you agree that following solution is a good way to go?

    // injectable
    class SuperService {
    }

    // newable
    class HyperSuperViewModel {
        public HyperSuperViewModel(String name, String other) {}
    }

    // injectable
    class SomePage {
        public SomePage(SuperService service) {}
        public DoWork(HyperSuperViewModel vm) {}
    }

    container.Register<SuperService>();

    var page = container.GetInstance<SomePage>();
    page.DoWork(hyperSuperViewModel);

**Comment by dotnetjunkie** [comment]
Exactly! Now your `HyperSuperViewModel` (newable) is passed through the existing object graph (of injectables) as a message using method calls.

**Comment by omares** [comment]
Thanks for clarification. I hope that principle is fully applicable in our project as some of the internals are given by the framework.

What about cases where an injectable depends on a newable before it can do its work. A service requiring a configuration as example. Following the newable/injectable principle one has to check in every method if the configuration is set and throw an error?

**Comment by dotnetjunkie** [comment]
Well, configuration values are different from runtime values. Configuration values never change after the application has started, and you can safely inject them into a constructor. You would usually do this using a construct such as this following:

``` c#
string connectionString = AppSettings.ConnectionStrings["MyApp"].ConnectionString;
container.RegisterSingle<IConnectionFactory>(new SqlConnectionFactory(connectionString));
```

About the limitations that frameworks give us, always keep the SOLID principles in mind. The Dependency Inversion Principle (the guiding principle for doing Dependency Injection) states that "the abstracts are owned by the upper/policy layers". In other words, your application components should not depend on framework types, even if those types are abstractions. Doing so is a violation of the DIP and in my experience this often leads to complications and maintainability issues.

So what you should usually do is hide framework code behind abstractions that are tailored for the application's need (so don't mimic some framework API but define an abstraction that follows SOLID and solves the application's needs). Of course you will have to call framework code somewhere and this is where adapters are for. An adapter is an implementation of your application specific interface and it forwards the call to the framework API. This forwarding could be simple, but this code could become quite complex, with the eventual goal of keeping the rest of the application code simple.

Sometimes however, frameworks are real PITAs and force us upon SOLID principle violations. This for instance happens when frameworks force us to use their abstractions. What helps here is making those implementations into [humble objects](http://xunitpatterns.com/Humble%20Object.html) and moving the bulk of the logic into application components that don't require this dependency on the framework. Doing this makes your code way more testable and maintainable.

**Comment by omares** [comment]
Again, thanks for your input - you should add those facts to the documentation to clarify a few decisions. ;)

About the frameworks. You are also right but there are always cases where you can't abstract everything away. And how often do people change they framework they opt for? I never ever saw someone changing their ORM even if they could because at the end there is to much risk involved. Just sayin we are not in a perfect world and never will be :)

**Comment by dotnetjunkie** [comment]
You are correct; with many frameworks it is impossible to abstract everything. Especially with UI frameworks, there is a lot of coupling. But please be aware that abstracting away from a framework is not just to allow the framework from being replaced; it's about applying the SOLID principles correctly, because this results in applications that are much more maintainable.

The documentation contains a [list of decisions](https://simpleinjector.readthedocs.org/en/latest/decisions.html), but your particular case is not something you can spot easily in this list. Improving the documentation is something we are constantly trying to do, but writing good documentation is hard :-(. And some information is too verbose and is better suited for blog posts. But we're working on that; we are working on the Simple Injector blog with the goal of bringing some extra information (especially about application design and DI best practices) that we couldn't fit in the documentation.

Stay tuned and thank you for flying Simple Injector airways ;-)

**Comment by omares** [comment]
10/10 would fly again ;)

**Comment by MyEidos** [comment]
Just additional questions. 
@dotnetjunkie what do you think about creating separate method, something like Init(runtimeArgs)?
So it will be 
`    class SomePage {
        public SomePage(SuperService service) {}
        public Init(HyperSuperViewModel vm){}
        public DoWork() {}
    }
`

Thanks.
