### ISSUE TITLE
ASP.NET Webforms in combination with MVC 5

### ISSUE THREAD

**Issue by MIKEPArA** [simpleinjector/SimpleInjector#592]
Is it recommended to register simple injector dependency resolver in the Application_Start method with the global.asax file upon start up or can i register it in Session_Start method within global.asax file for .NET application?

Reason is i would like to set a user object in the session_start method and register it to my SI since user credentials are sent via httpcontext request header. This way i don't have to retrieve this value during every mvc controller call? 

Thank You.

**Comment by dotnetjunkie** [comment]
The [docs](https://simpleinjector.readthedocs.io/en/latest/using.html) state:

> Tip: You should typically create a single Container instance for the whole application (one instance per app domain); Container instances are thread-safe.
>
>Warning: Do not create an infinite number of Container instances (such as one instance per request). Doing so will drain the performance of your application. The library is optimized for using a very limited number of Container instances. Creating and initializing Container instances has a large overhead, but resolving from the Container is extremely fast once initialized.

Having one container per session is equal to an infinite number of container instances, this should be prevented. You should create the container at app startup instead.

**Comment by dotnetjunkie** [comment]
I would like to add that a container instance can allocate a considerate amount of memory. Sessions can stick around for hours. This can easily blow up the applications memory usage in production, causing the application to crash and recycle.

On top of that, container instances are *not* serializable. So once you start scaling out using multiple machines, you will have to move the session state out of process. You can do this using SQL Server, for instance. But once you do so, storing a Container instance in the session will fail, since it can't be serialized; it wouldn't make sense for it to be.

**Comment by dotnetjunkie** [comment]
> Reason is i would like to set a user object in the session_start method and register it to my SI since user credentials are sent via httpcontext request header. This way i don't have to retrieve this value during every mvc controller call?

Prevent from doing this. In effect you are making registrations that are scoped around the lifetime of a session.

Instead, make the registration singleton and let tge implementation internally request the data from the session when one of its methods is being called.

Important rule is to keep object construction free of any runtime data. In other words, do not inject runtime data into a constructor, nor load runtime data during the execution of a constructor.

For more info on this, see https://cuttingedge.it/blogs/steven/pivot/entry.php?id=99

**Comment by MIKEPArA** [comment]
Hi @dotnetjunkie thanks for help.
