### ISSUE TITLE
EnableSimpleInjectorCrossWiring question

### ISSUE THREAD

**Issue by vitidev** [simpleinjector/SimpleInjector#601]
As I understand in this case, when I call `container.GetInstance` the si container resolve missing dependencies from cross-wired ms-container. But si does not require an explicit registration. How does he understand when it must resolve dependency from ms-container, but not yourself?

``` c#
var services = new ServiceCollection();
var container = new Container();
services.AddSingleton<TestSingleton>();
services.EnableSimpleInjectorCrossWiring(container);

var x = container.GetInstance<TestSingleton>();
var y = container.GetInstance<TestSingleton>();
ReferenceEquals(x, y); //False
```
Perhaps he should be able to automatically resolve to avoid such situations?

Perhaps Simple Injector should be able to disable automatically resolving non-registered types to avoid such situations?

**Comment by dotnetjunkie** [comment]
You allow Simple Injector to automatically cross-wire MS services by calling `AutoCrossWireAspNetComponents`. Under the covers, this is done by hooking onto Simple Injector's `ResolveUnregisteredType` event, as can be seen in the [source code](https://github.com/simpleinjector/SimpleInjector/blob/master/src/SimpleInjector.Integration.AspNetCore/SimpleInjectorAspNetIntegrationExtensions.cs#L282).

In the given example, however, you only *set-up* cross-wiring, but you will have to call `AutoCrossWireAspNetComponents` to let Simple Injector automatically find missing dependencies in the MS container, or, alternatively, you have to call `CrossWire<T>(app)` on a per-dependency basis.

`EnableSimpleInjectorCrossWiring` just sets things up for both `CrossWire` and `AutoCrossWireAspNetComponents` to work, as explained in [the documentation](https://simpleinjector.org/aspnetcore).

Since you didn't `CrossWire` or 'auto-cross-wire' `TestSingleton`, Simple Injector will not go to the MS DI Container, but instead try to create and resolve the type itself. Since it is a concrete type, it will be able to create that type, but in that case, the type is resolved as `Transient`.

In case `TestSingleton` is an *application component*, prevent registering it in the MS DI container. Use Simple Injector for application components, and MS DI for components that MS needs to be aware of.

**Comment by vitidev** [comment]
AutoCrossWireAspNetComponents  works [only for asp.net](https://github.com/simpleinjector/SimpleInjector/issues/584) but [will be](https://github.com/simpleinjector/SimpleInjector/issues/585)

And yet, as an additional protection, it is useful to be able to turn off si auto-resolving of non-registered types.

**Comment by dotnetjunkie** [comment]
> AutoCrossWireAspNetComponents works only for asp.net 

Not exactly, but until Simple Injector v4.4 is released, you will have to define your own `IApplicationBuilder` implementation that wraps your `IServiceProvider`. For instance:

``` c#
public class ApplicationServicesWrapper : IApplicationBuilder
{
    public IServiceProvider ApplicationServices { get; set; }

    IFeatureCollection IApplicationBuilder.ServerFeatures => throw new Exception();
    IDictionary<string, object> IApplicationBuilder.Properties => throw new Exception();
    RequestDelegate IApplicationBuilder.Build() => throw new Exception();
    IApplicationBuilder IApplicationBuilder.New() => throw new Exception();
    IApplicationBuilder IApplicationBuilder.Use(Func<RequestDelegate, RequestDelegate> middleware) 
        => throw new Exception();
}
```

Using this wrapper, you can call `AutoCrossWireAspNetComponents` as follows:

``` c#
container.AutoCrossWireAspNetComponents(
    new ApplicationServicesWrapper { ApplicationServices = serviceProvider });
```

> And yet, as an additional protection, it is useful to be able to turn off si auto-resolving of non-registered types.

You can disallow resolving unregistered concrete types by hooking onto the `ResolveUnregisteredType` event, as shown in [this example](https://github.com/simpleinjector/SimpleInjector/issues/377#issuecomment-324857943). In a future version, we will simplify this and allow disabling this using a configuration option, as discussed [here](https://github.com/simpleinjector/SimpleInjector/issues/377).

**Comment by vitidev** [comment]
mmm...something does not work

    var services = new ServiceCollection();
    services.AddSingleton<TestSingleton>();

    var container = new Container();
    container.Options.DefaultScopedLifestyle = new AsyncScopedLifestyle(); //required
    container.ResolveUnregisteredType += (s, e) =>
    {
        if (!e.Handled && !e.UnregisteredServiceType.IsAbstract)
        {
            throw new InvalidOperationException(
                e.UnregisteredServiceType.ToFriendlyName() + " has not been registered.");
        }
    };

    services.EnableSimpleInjectorCrossWiring(container);
    container.AutoCrossWireAspNetComponents(
        new ApplicationServicesWrapper {ApplicationServices = services.BuildServiceProvider()});

    var x = container.GetInstance<TestSingleton>();
    var y = container.GetInstance<TestSingleton>();
    ReferenceEquals(x, y);

in ResolveUnregisteredType handler: System.InvalidOperationException: 'TestSingleton has not been registered.'
