### ISSUE TITLE
Can i shoot myself in the foot? Aka force resolving/releasing a graph outside a scope. 

### ISSUE THREAD

**Issue by thomaslazar** [simpleinjector/SimpleInjector#619]
Hi. 

I have a question. 

We recently changed certain registrations to have a scoped lifestyle and changed the important bits in most parts of our applications to either manually creating a scope or having it be handle by WCF or WebAPI. 

The problem now is that we have one horrible piece of code that boggles the mind and is driven by black magic that does stuff with threads and other bad things so we cannot trivially just wrap a scope around the bit that resolves an object graph, because the resolved object gets handed of to another thread and lots and lots of horrible things. 

But we have dedicated "create this graph here, and get rid of it there" points in the code. The problem is they reside in different threads. 

Is there a way in SimpleInjector when using `.GetInstance(...)` to force it to create the graph, even though some registrations have a scoped lifestyle and then later on release it manually? 

I have used CastleWindsor DI before and there are dedicated methods for `.Release(...)`. But the problem starts with not being able to use `.GetInstance(...)` in the first place due to no scope being active. 

I'm currently thinking of creating a scope and handing that off to the thread as well to be disposed there when the work is done. 

Please refrain from telling me that you shouldn't do this kind of stuff... i know you shouldn't. And we don't in general. But changing the black magic box of pandora code to make it possible to have a clean scope has potentially more repercussions then resolving and getting rid of the graph manually in the proper places.

**Comment by dotnetjunkie** [comment]
Castle Windsor's `Release` method is almost identical to what happens when you dispose a `Scope` in Simple Injector (and Autofac for that matter). `Scope.Dispose` as Simple Injector's `Release` method. Difference being that with with `Scope.Dispose` you clean up everything that belongs to that scope, while with `Release` every released root object can be seen as its own scope. In fact, with Castle, you rather release the _graph_ instead of a scope.

With Simple Injector, scopes are typically ambient. They operate ambiently and every piece of code in that context (typically a thread or an asynchronous operation) 'knows' it runs in that context, similar to how a `TransactionScope` works. Scoping with recent versions of Castle Windsor works identically btw.

This ambient behavior, however, only becomes important when you start to resolve from the container in the middle of the lifetime of a scope, compared to when you resolve the entire object graph directly after the scope is created. A scope can be happily disposed on a completely different thread or asynchronous operation than it was created, and as long as you resolve just once from that scope, it is irrelevant how many parallel threads, tasks and background operations you spin off of that parent operation, as long as you don't dispose the scope before the complete operation has finished using its dependencies.

To illustrate this, you can happily do this:

``` c#
var scope = AsyncScopedLifestyle.BeginScope(container);

var root = container.GetInstance<RootObject>(); // Resolve complete graph here

var operation = Task.Factory.StartNew(() =>
{
    try {
        root.Operate();
    } finally {
        Task.WaitAll(Task.Factory.StartNew(() => scope.Dispose()));
    }});
Task.WaitAll(operation);
```

I hope this helps

**Comment by thomaslazar** [comment]
Thanks a lot! It not only helps, it's the exact answer I was hoping/looking for.
