### ISSUE TITLE
Does SimpleInjector support injection using [FromServices] attribute?

### ISSUE THREAD

**Issue by voroninp** [simpleinjector/SimpleInjector#623]
It looks like enabling injector's controller activator breaks injection of the services in actions via [`[FromServices]`](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/dependency-injection?view=aspnetcore-2.1#action-injection-with-fromservices) attribute.

```
System.InvalidOperationException: No service for type 'Connect.Device.BusinessModel.Services.IDeviceTypeService' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ServicesModelBinder.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
`IDeviceTypeService` is registered with container: `_container.Register<IDeviceTypeService, DeviceTypeService>(Lifestyle.Scoped);`

Constructor injection works fine.

**Comment by dotnetjunkie** [comment]
Why do you want to use [FromServices] opposed to normal constructor injection?

**Comment by voroninp** [comment]
@dotnetjunkie =D Good question. 

Well, I do not think method injection is that awfully bad thing. Yes, it may let you happily live with broken SRP, yet I am not sure this principle should be applied to controllers.
I am just playing with asp.net core and trying all its bells and whistles, and it took me a while to understand what was the reason for exception.

**Comment by dotnetjunkie** [comment]
The Simple Injector integration package does not have built-in support for this scenario, because, even though it might be something ASP.NET Core supports, we feel it it's not good practice. Reason for this is the following:

- This is a form of method injection that requires special attributes to get working
- This for of injection is typically used to prevent constructor over-injection, but as you already noted, it is a signal that that class is doing too much (SRP violation). This guidance applies as well as much on controllers as it does on any other part of your system.
- This type of injection prevents Simple Injector (or any other tool) from verifying object graphs. It prevents the application from failing fast if a dependency is missing. In a general sense, this form of injection leads to [Temporal Coupling](http://blog.ploeh.dk/2011/05/24/DesignSmellTemporalCoupling/).

The fact, however, that we haven't got OOTB support for this, doesn't mean it isn't possible. You can plug this in yourself by creating a custom `IModelBinderProvider` implementation that returns a custom `IModelBinder` that resolves instances from the Simple Injector container. This can be done in a few lines of code.

**Comment by voroninp** [comment]
@dotnetjunkie I see, thanks.

**Comment by voroninp** [comment]
@dotnetjunkie I will add a note to the documentation.

**Comment by Ahmed-Raouf** [comment]
Thanks @dotnetjunkie for your reply.
We need to inject instances through action instead of constructor. I work in large solutions that manipulate with lot of classes instances reaches more than 30 instances in the single controller. These instances are distributed on the controller actions. Some actions don't need to manipulate with any instances or need small number of these 30 instances. So when you call these actions, the constructor is called also and all controller instances are instantiated even if the action doesn't need them.
These leads to poor performance in large solutions. We performed a heavy load test using jMeter, Blazemeter and newrelic. We had a bad performance. One solution to resolve this issue is to transfer the instantiation of objects from constructor to the action.

**Comment by Ahmed-Raouf** [comment]
Instead of [FromServices], I used inside the action:

 ITest obj2 = SimpleInjectorContainer.MyContainer.GetInstance<ITest>();
- SimpleInjectorContainer is a static class

    public static class SimpleInjectorContainer
    {
        private static Container container;

        public static Container MyContainer {
            get
            {
                if (container == null)
                    return new Container();
                else
                    return container;
            }
            set
            {
                container = value; 
            }
        }
    }

- In startup.cs I ported the container object after registering all services
    container.Verify()
    SimpleInjectorContainer.MyContainer = container;

**Comment by dotnetjunkie** [comment]
Hi @Ahmed-Raouf,

Please reconsider your solution. Having 30 dependencies in a single controller is a sure sign of a Single Responsibility Principle violation. Please take note of the arguments against using [FromService] as I [stated](https://github.com/simpleinjector/SimpleInjector/issues/623#issuecomment-429390182) above.

A much more effective solution is to make Controllers much, much smaller. If the routing scheme can't be impacted, ASP.NET Core is very flexible in configuring routes to certain controllers.

But even with 30 constructor arguments, you should not see any performance problems when using Simple Injector. If you do, this means your constructors [do too much](https://blog.ploeh.dk/2011/03/03/InjectionConstructorsshouldbesimple/). This is something that should be fixed regardless of which injection method you use.

Please refrain from using the [Service Locator anti-pattern](https://blog.ploeh.dk/2010/02/03/ServiceLocatorisanAnti-Pattern/) as your last comment shows you are currently doing. It exhibits the same downsides as using the [FromService] attribute, and would even be worse.

And again, as I stated previously, in case you absolutely want to use [FromServices], this can be done by creating a custom `IModelBinderProvider`. This shouldn't be that hard, but because method injection is not a practice we endorse, we won't be including such solution in our integration packages.

**Comment by dotnetjunkie** [comment]
I added information about this to the documentation: https://simpleinjector.org/aspnetcore#using-fromservices-in-asp-net-core-controllers

**Comment by voroninp** [comment]
@dotnetjunkie 

> This is by design and adheres to our design guidelines, as explained below.
> 
> We will explain why this is below.

Is second sentence really needed here?

**Comment by dotnetjunkie** [comment]
Thanks for noticing. This indeed is an error. Went wrong with editing.
