### ISSUE TITLE
Does ASP.NET Core crosswiring work only one way?

### ISSUE THREAD

**Issue by voroninp** [simpleinjector/SimpleInjector#632]
The summary for `AutoCrossWireAspNetComponents` method says:

> Allows registrations made using the `IServiceCollection` API to be resolved by Simple Injector

But does it work the other way arroand? Will dependencies registered via Simple Injector be resolved, if instance is aked via services?
<br/>
I added one more parameter of type `IBeforeCommitEventsDispatcher` to `DbContext`'s constructor. 
Dispatcher was registered with Simple Injector and context is registered with:

```CSharp
services.AddDbContext<DeviceContext>(o =>
{
    o.UseSqlServer(connectionStr);
});
```

At runtime everything works fine, but when I tried to `Add-Migration`, EF complained that it could not resolve `IBeforeCommitEventsDispatcher` dependency.

[Docs](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dbcontext-creation) say that EF accesses `IWebHost.Services`.
When I registered dispatcher via services, it was able to add migration:

```CSharp
services.AddScoped<IBeforeCommitDomainEventsDispatcher<IDomainEvent>,BeforeCommitEventsDispatcher>();
```

**Comment by dotnetjunkie** [comment]
> But does it work the other way arroand?

No. The documentation [states](https://simpleinjector.org/aspnetcore#cross-wiring-asp-net-and-third-party-services):

> Cross-wiring is a one-way process. By using AutoCrossWireAspNetComponents, ASP.NET’s configuration system will not automatically resolve its missing dependencies from Simple Injector. When an application component, composed by Simple Injector, needs to be injected into a framework or third-party component, this has to be set up manually by adding a ServiceDescriptor to the IServiceCollection that requests the dependency from Simple Injector. This practice however should be quite rare.

Reasons for this are the following:

* ASP.NET Core's configuration system lacks a feature called _unregistered type resolution_ making it impossible to do a call back into Simple Injector in case a missing registration is requested.
* This means that the only way to solve this problem is by pre-registering all Simple Injector registrations into the ASP.NET Core configuration system, but this would lead to complications due to the unbridgable gap between both containers, as explained [here](https://simpleinjector.org/blog/2016/06/whats-wrong-with-the-asp-net-core-di-abstraction/).

In case a .NET Core-built component needs a Simple Injector dependency, you should cross-wire it the other way around manually. This can be done by either registering a delegate, or use the Proxy pattern. This means that you create a Proxy implementation of the injected abstraction. The Proxy than wraps the Simple Injector container and resolves the _real_ implementation from Simple Injector when one of its methods are called. The latter seems the most reasonable approach in your case, since you're dealing with generic types. In your case, the `BeforeCommitEventsDispatcher` already seems a sort of Proxy, as it already wraps a Simple Injector `Container`.

Also think about preventing injecting dependencies into your `DbContext`. Especially with the design you already have, it would be trivial to move a call to `DbContext.SaveChanges` into a decorator, which would also be the ideal place to trigger the before commit events.

**Comment by voroninp** [comment]
Agree with the last point, but temporarily postponed this.=)

I will add the quoute to `<remarks>` section of `AutoCrossWireAspNetComponents` method.
