### ISSUE TITLE
Add instructions for using Simple Injector with ASP.NET Core 2.0 IHostedService

### ISSUE THREAD

**Issue by greyseal96** [simpleinjector/SimpleInjector#633]
Steven has a great answer to a question on [StackOverflow](https://stackoverflow.com/questions/50394666/injecting-simple-injector-components-into-ihostedservice-with-asp-net-core-2-0/50395957#50395957) about how to implement an IHostedService adapter and register it with Simple Injector and ASP.NET Core's service container.  I think that it would be really helpful to add this to the documentation.  I'd be willing to do this too.  Just tell me where (which section) I should add it and I can create a documentation page and do a pull request.

**Comment by dotnetjunkie** [comment]
Feel free to cook up PR for this. The most obvious page to add this information to is the [aspnetintegration.rst](https://github.com/simpleinjector/Documentation/blob/4.0/source/aspnetintegration.rst). You can use the 4.0 branch.

**Comment by greyseal96** [comment]
To prep for making the addition, I was just reading through the aspnetintegration page again and I saw the `UseMiddleware<T>` extension method and that gave me an idea that I wanted to run past you...

I was looking at the [source code](https://github.com/aspnet/Hosting/blob/master/src/Microsoft.Extensions.Hosting.Abstractions/ServiceCollectionHostedServiceExtensions.cs) for the `AddHostedService<T>` extension method and it is really simple.  It just adds the hosted service to the IServiceCollection like so: `services.AddTransient<IHostedService, THostedService>();`

That made me wonder if it would be possible to create an extension method similar to what is being done with `UseMiddleware<T>`.  But, since I'm not super familiar with the `InstanceProducer` class, I don't know if this would be a good idea or not.  Just as a rough idea, I'm talking about an extension method sort of like this:
```C#
public static class HostedServiceExtensions
{
    public static IServiceCollection AddHostedServiceFromContainer<THostedService>(this IServiceCollection services, SimpleInjector.Container container)
        where THostedService : class, IHostedService
    {
        //The AddHostedService<T> extension method adds the services as transient so this would
        //be consistent with that.
        var lifestyle = SimpleInjector.Lifestyle.Transient;
        //Or would this be better?  It's similar to what the UseMiddleware extension method is doing...
        //var lifestyle = container.Options.LifestyleSelectionBehavior.SelectLifestyle(typeof(THostedService));

        SimpleInjector.InstanceProducer<THostedService> producer = lifestyle.CreateProducer<THostedService>(typeof(THostedService), container); 

        return services.AddTransient<IHostedService, THostedService>(svcProvider => producer.GetInstance());
    }
}
```
Would something like this work?

Also, I had a question about the recommendation from the SO question.  In other things that you've written I've like how you've stressed the importance of making sure that classes clearly state their dependencies in their constructors.  But, just having the hosted service implementation take a dependency on the Container seems like an exception to this rule; kind of like a service locator sort of thing.  Is the reasoning behind this because it's something that we're forced to do because of Microsoft's decision to go with their design of the conforming container?  Just curious.  I've learned a lot about DI by using Simple Injector and reading what you and Mark Seemann have written so I was just wondering for my own personal knowledge.

**Comment by dotnetjunkie** [comment]
Your extension method is pretty good. It does take a different approach than [my Stack Overflow answer](https://stackoverflow.com/questions/50394666/injecting-simple-injector-components-into-ihostedservice-with-asp-net-core-2-0/50395957#50395957), but the two are not mutually exclusive.

The SO answer pushes towards writing _application-specific_ abstractions (e.g. `IMyJob`) and implementing the `SimpleInjectorJobProcessorHostedService` as an _adapter_. Your extension method instead lets hosted services implement `IHostedService`. That's not bad per see, and you could even register the `SimpleInjectorJobProcessorHostedService` using that extension method.

Do be warned, however, about your extension method. Even though the `AddHostedService<T>` extension method of ASP.NET Core, registers the services as `Transient`, hosted services are in fact singletons!! That's because they are resolved _once_ from the framework and their `StartAsync` is called once soon after started, and `StopAsync` is called once at shutdown.

What this means is that while the hosted service can start a timer that runs periodically, that code will _always_ use the same dependencies that were injected into the constructor. In other words, it would be an error to inject scoped (or transient) dependencies into the constructor of the hosted service (but ASP.NET Core doesn't protect you against this at all).

In other words, you should **always** register your hosted services as `Singleton`. This way Simple Injector can protect you from accidental Lifestyle Mismatches (a.k.a. Captive Dependencies).

So, I would suggest changing the extension method to the following:

``` c#
public static IServiceCollection AddHostedServiceFromContainer<THostedService>(
    this IServiceCollection services, Container container)
    where THostedService : class, IHostedService
{
    var producer = Lifestyle.Singleton.CreateProducer<THostedService, THostedService>(container); 
    return services.AddSingleton<IHostedService, THostedService>(c => producer.GetInstance());
}
```

I thought about changing the `CreateProducer` call to the following:

``` c#
var producer = Lifestyle.Singleton.CreateProducer<IHostedService, THostedService>(container); 
```

Advantage of such change is that it would allow hosted services to be decorated easily by registering a decorator (e.g. `RegisterDecorator<IHostedService, LoggingHostedServiceDecorator>`). However, this can cause problems when the decorator is registered as `Transient` or `Scoped`, because Simple Injector would be unable to detect that a Transient Decorator (with its dependencies) would be accidentally kept alive by ASP.NET Core.

Alternatively to the previous, the following code would have an identical effect:

``` c#
container.RegisterSingleton<THostedService>();
return services.AddSingleton<IHostedService, THostedService>(c => container.GetInstance<THostedService>());
```

**Comment by dotnetjunkie** [comment]
> In other things that you've written I've like how you've stressed the importance of making sure that classes clearly state their dependencies in their constructors. But, just having the hosted service implementation take a dependency on the Container seems like an exception to this rule; kind of like a service locator sort of thing. Is the reasoning behind this because it's something that we're forced to do because of Microsoft's decision to go with their design of the conforming container?

In general, you don’t want to depend on the Container. That is absolutely correct. This has to do with the risk of it becoming a Service Locator, which is, as you understand, an anti-pattern. However, it is important to realize that not every usage of a Container is an implementation of the Service Locator anti-pattern.

What we are trying to achieve with dependency injection is loose coupling. This means that a class declares its required dependencies and pushes the responsibility of creating that dependencies up into the Composition Root. Result is that a class can become loosely coupled. The [Composition Root](https://mng.bz/0W7l), however, will _always_ be tightly coupled. It knows about all classes in the system and if you use a DI Container, the Composition Root _knows_ about the DI Container.

This is why Mark and I state in [our book](https://manning.com/seemann2) (also see Mark’s [blog post](https://blog.ploeh.dk/2011/08/25/ServiceLocatorrolesvs.mechanics/) about this subject) that the use of a Container _inside_ the Composition Root is _not_ a Service Locator. In the book we state:
> Because the *Composition Root* already depends on everything else in the system […], it's impossible for it to drag along [the Container as] an extra *Dependency*. By definition, it knows about every *Dependency* already. And it's impossible for the *Composition Root* to hide its *Dependencies*—from whom does it hide them? Its role is to build object graphs; it doesn't need to expose those *Dependencies*.

And this is why the `SimpleInjectorJobProcessorHostedService` can take a dependency on the Container. It’s because that class _is part of_ the Composition Root. Or at least, when you let a class depend on the Container (or an abstraction there over), you’d better place that class inside the Composition Root.

So this ‘exception’ has nothing to do with how Microsoft designed their system. The same thing would happen when you create an `IControllerActivator` implementation. It will wrap a Container to be able to resolve instances. Only difference is that we decided to create an implementation on your behalf, which is why you don’t have to implement it. The `SimpleInjectorControllerActivator` is an adapter, just like the `SimpleInjectorJobProcessorHostedService`. Since we will never implement all possible adapters for you, you will always have some adapters in your system, and when they depend on the Container, the right location to put them is your Composition Root. It has been this way with all frameworks that came before ASP.NET Core, and it will be this way with all frameworks them will come after ASP.NET Core.

**Comment by dotnetjunkie** [comment]
I updated my [original Stack Overflow answer](https://stackoverflow.com/questions/50394666/injecting-simple-injector-components-into-ihostedservice-with-asp-net-core-2-0/50395957#50395957) with this second use case. Notice that I simplified the case by removing the extension method. This is useful because it simplifies the code even more and makes it easier to follow. The answer now also explains the difference between the two methods. You might want to use this answer as input for the documenation. Basically the difference is:

* The first method enables a simplified model that relies on cross-wiring.
* It forces application code to depend on the ASP.NET Core `IHostedService` abstraction
* It is limited to the use of dependencies that are Singletons.
* The second method uses a decoupled model where application services use an application-specific abstraction.
* It allows the application-specified hosted services to have any lifestyle and their dependencies as well.
* It gives full control over management of the scope. You can let all services run in a single scope (as shown in the answer), or decide to give each service its own isolated scope (not shown in the answer).

**Comment by greyseal96** [comment]
I liked the update to your answer.  It distilled the guidance down to the most essential points quickly and easily.  After adding the preferred method to the help documentation, I started to add the extension method information but, when I did, it didn't seem as good as doing it in the recommended way so I took it out.  

But, based on what you wrote in the Stack Overflow answer, I'm going back and putting some of the information back in but I noticed something that seems to be a problem.  It has to do with the difference between where the ASP.NET Core configuration system initializes and sets up its container and where the Simple Injector container is being initialized and set up.  The ASP.NET Core configuration system sets up its container in the ConfigureServices method of the Startup class and this is also the place where the hosted services are added.  ConfigureServices only takes an IServiceCollection parameter.  Simple Injector's container is initialized and set up in the Configure method of the Startup class which takes an IApplicationBuilder parameter at the very least.

If we cross-wire the IHostedService implementation, we call GetInstance on the Simple Injector container.  If I'm not mistaken, this means that we would have to initialize and set up the Simple Injector container in the ConfigureServices method before cross-wiring so that we don't throw an exception for missing dependencies.  It also means that we can't add any more dependencies to the Simple Injector container so we'd have to get all of our dependencies for the whole application added before cross-wiring as well.  But, if we set up the Simple Injector container in the ConfigureServices method, we lose the ability to register MVC controllers and view components with the Simple Injector container because we don't have access to the IApplicationBuilder object yet and the extension methods to register the controllers and view components require an IApplicationBuilder parameter.

On the other hand, if we keep the Simple Injector initialization and set up in the Configure method, we lose the ability to cross-wire the IHostedService implementation because the ASP.NET Core configuration system is already set up and we can't add any more service registrations.  

So, unless I'm missing something, this seems like a catch 22.  Am I missing something?  I just wanted to run this by you before I go too much further.  If I'm understanding all of this correctly, I think that I'll just remove the option for cross-wiring the IHostedService implementation and just leave the preferred option.

**Comment by dotnetjunkie** [comment]
> If we cross-wire the IHostedService implementation, we call GetInstance on the Simple Injector container. If I'm not mistaken, this means that we would have to initialize and set up the Simple Injector container in the ConfigureServices method before cross-wiring so that we don't throw an exception for missing dependencies.

This would have been the case if we weren't registering a delegate:

    services.AddSingleton<IHostedService>(
        c => container.GetInstance<TimedService>());

Because of the `c =>` the call to `GetInstance` is not executed at that point in time. Only when ASP.NET Core starts resolving `IHostedService` instances, would that cause a call to Simple Injector and therefore a lockdown of the container.

**Comment by greyseal96** [comment]
Oh wow, sorry about that.  I totally forgot about that overload.  I've been using the other one (which takes an instance of the hosted service) so much that I forgot about that other one.  

Just out of curiosity, is there anything wrong with using that constructor (with the func delegate) in the preferred solution or would that change the semantics of it being an adapter? It seems like it's six of one half dozen of the other but maybe I'm missing something.

**Comment by dotnetjunkie** [comment]
> Just out of curiosity, is there anything wrong with using that constructor (with the func delegate) in the preferred solution or would that change the semantics of it being an adapter? It seems like it's six of one half dozen of the other but maybe I'm missing something.

I'm not sure I follow you. When you say "using that constructor (with the func delegate," do you mean using the `AddSingleton` method overload that takes in a delegate? I'm unsure what you are proposihng that would change the semantics of the adapter? Can you elaborate?

**Comment by thulani-chivandikwa** [comment]
I would hook onto the ConfigureContainer method of the HostBuilder and setup simpleinjectore there likke this:

```
                       IHostBuilder()
                       .ConfigureContainer<ServiceCollection>((builder, services) =>
                       {
                           var container = new Container();

                           container.RegisterSingleton<IJobRepository, JobRepository>();
                           services.AddTransient<IHostedService, TimedService>();

                       })
                       .ConfigureServices((hostContext, services) =>
                       {
                           // Originally we would have done this
                           //services.AddHostedService<Service>();
                       })
                       .Build();
```

While you could use your IHostedService implementation indeed I think it may hide what is going on. I believe the infrastructure bootstrapping should be done in one place or orchestrated at least in one place. I consider the container to be infrastructure and would set it all up with the rest of the app via the HostBuilder methods.

An added advantage may also be that you do not entirely replace the ServiceCollection as it works well with doing other framework related things. An example of some stuff I would still do with the ServiceCollection:

```
                       IHostBuilder()
                       .ConfigureServices((hostContext, services) =>
                       {
                           services.AddLogging();
                           services.AddOptions();
                       })
```

This is in line with what is stated in the simpleinjector docs about setting the container up with ASP.NET Core:

> The practice with Simple Injector is to use Simple Injector to build up object graphs of your application components and let the built-in container build framework and third-party components,The practice with Simple Injector is to use Simple Injector to build up object graphs of your application components and let the built-in container build framework and third-party components

The same should apply with just .net core and the generic HostBuilder.

**Comment by dotnetjunkie** [comment]
Simple Injector 4.6 introduced new integration package for hosted services. The documentation can be found [here](https://simpleinjector.org/generichost).
