### ISSUE TITLE
Problem to inject service into a message handler with simple injector

### ISSUE THREAD

**Issue by danilosingh** [simpleinjector/SimpleInjector#637]
I'm starting with Rebus.
We are implementing an Event Bus, using Rebus.
The project is a Web API. In one of the services an event is added to perform an asynchronous workload.
We intend to handle the event in the same API project, because the goal is just not to let the user wait for this processing during the request and the volume of requests is small.
Now comes the questions:
We are having trouble injecting a service into the event handler.
We configured the Simple Injector with Hybrid Lifestyle, because we used the same dependency configuration for an integration and unit testing project.
When we try to instantiate the IHandleMessages injecting the service we have the error:

> The InvoiceAppService is registered as 'Hybrid Async Scoped / Thread Scoped' lifestyle, but the instance is requested outside the context of an active.

I saw this issue
https://github.com/simpleinjector/SimpleInjector/issues/253

But in our context, we wanted to have all event handlers in the same scope.

This is because we have a UnitOfWork class that is injected into the services, which controls the data transaction.

Could someone help us?

**Comment by dotnetjunkie** [comment]
> We configured the Simple Injector with Hybrid Lifestyle, because we used the same dependency configuration for an integration and unit testing project.

I don't consider it to be a good practice to configure a hybrid lifestyle to be able to do integration and unit testing.

First of all, unit tests should _not_ involve using a DI Container. For integration tests this is different, as they cut across many classes in the application, which means it becomes useful to use _the same_ DI configuration to build up the object graphs.

But when it comes to integration testing, it is typically better to make the construction of the DI Container configurable. For instance:

``` c#
// Part of start-up project
public static Container BuildContainer(ScopedLifestyle scopedLifestyle)
{
    var container = new Container();
    container.Options.DefaultScopedLifestyle = scopedLifestyle;
    // Registrations here
    return container;
}

// Part of Web API
protected void Application_Start() {
    var container = BuildContainer(new AsyncScopedLifestyle());

    container.Verify();

    GlobalConfiguration.Configuration.DependencyResolver =
        new SimpleInjectorWebApiDependencyResolver(container);
}

// Part of integration test project
public static Container GetContainer()
{
    var container = Composer.BuildContainer(new ThreadScopedLifestyle());

    // add and replace registrations specific to integration tests

    return container;
}
```

Yet another thing to note is that in environments where Asynchronous Scoping (.NET 4.5 and up, .NET Core, .NET Standard 1.3 and up) is supported, there is no need for using the `ThreadScopedLifestyle`. You can use `AsyncScopedLifestyle` in scenarios where the operation is single threaded.

Last, the exception message is thrown because there is no active scope. If you are running the operation outside a web request, you will have to manually create a scope, as explained [here](https://simpleinjector.org/lifetimes#async-scoped-async-await) in the documentation.

I hope this helps.

**Comment by danilosingh** [comment]
Thanks for the quick reply.

I understood and I found your position very valid regarding the DI configuration. Because it avoids a policy that would always fail to create the instance.
But the point at issue of our difficulty is precisely the question of scope. I do not know if you can help us with this, but the problem is that when we add a message in the queue, Rebus adds an IHandleMessage. Our IHandleMessage implementation needs to receive a service. I can not open a scope before, because whoever stays the IHangleMessage is Rebus himself.

To solve this we did this:

public class BatchReceivedEventHandler : IHandleMessages<BatchReceived>
    {
        public BatchReceivedEventHandler()
        { }

        public Task Handle(BatchReceived message)
        {
            return Task.Run(() =>
            {
                using (var scope = IoC.Container.BeginScope())
                {
                    var invoiceService = scope.GetService<IInvoiceAppService>()
                    invoiceService.UpdateStatusBatch(message.BatchId);
                }
            });
        }
    }

But we would like to do that:

  public class BatchReceivedEventHandler : IHandleMessages<BatchReceived>
    {
        public BatchReceivedEventHandler(IInvoiceAppService invoiceService)
        { }
}

**Comment by dotnetjunkie** [comment]
Is the use of `Task.Run` inside `BatchReceivedEventHandler` an example, or is this really the intend of that handler to spawn a background operation.

The reason I'm asking this is that you should _never_ move injected services from thread to thread outside the composition root. This, however, is exactly what you seem to wish to achieve inside `BatchReceivedEventHandler`. You inject `IInvoiceAppService`, but than move it to a background thread using `Task.Run`.

This is problematic, because the `BatchReceivedEventHandler` does not know whether it is safe to reuse the `IInvoiceAppService` across threads.

**Comment by dotnetjunkie** [comment]
We've written about [Work with dependency injection in multi-threaded applications](https://simpleinjector.org/howto#work-with-dependency-injection-in-multi-threaded-applications) in the documentation. That text might be of interest to you.

**Comment by danilosingh** [comment]
In fact, the interface IHangleMessages of Rebus, has this method with the return Task.

`namespace Rebus.Handlers
{
    //
    // Summary:
    //     Message handler interface. Implement this in order to get to handle messages
    //     of a specific type
    public interface IHandleMessages<in TMessage> : IHandleMessages
    {
        //
        // Summary:
        //     This method will be invoked with a message of type TMessage
        Task Handle(TMessage message);
    }
}`

This is a problem. :(

**Comment by dotnetjunkie** [comment]
Could it be you are misinterpreting what it means to return a `Task`? 

`Task` doesn't mean you need to do things on background threads at all. `Task` just means that you can run things asynchronously, if you want to. As I see it, you should write your `BatchReceivedEventHandler` as follows:

``` c#
public class BatchReceivedEventHandler : IHandleMessages<BatchReceived>
{
	private readonly IInvoiceAppService invoiceService;
	public BatchReceivedEventHandler(IInvoiceAppService invoiceService)
		=> this.invoiceService = invoiceService;

	public Task Handle(BatchReceived message)
	{
		this.nvoiceService.UpdateStatusBatch(message.BatchId);
		return Task.FromResult(1);
	}
}
```

This makes the `BatchReceivedEventHandler` run synchronously, while still returning a `Task`.

**Comment by dotnetjunkie** [comment]
But that's what [the decorator](https://github.com/simpleinjector/SimpleInjector/issues/253#issuecomment-226970690) of issue #253 will help you with. If we rewrite that decorator to using the new `AsyncScopedLifestyle`, you can decorate your handlers with the following decorator:

``` c#
public class ScopedHandleMessagesDecorator<TMessage> : IHandleMessages<TMessage>
{
    private readonly Container container;
    private readonly Func<IHandleMessages<TMessage>> decorateeFactory;
    
    // NOTE: Both the Contrainer and the decoratee factory are singletons.
    public ScopedHandleMessagesDecorator(
        Container container, Func<IHandleMessages<TMessage>> decorateeFactory)
    {
        this.container = container;
        this.decorateeFactory = decorateeFactory;
    }

    public async Task Handle(TMessage message)
    {
        using (AsyncScopedLifestyle.BeginScope(this.container))
        {
            // The decoratee will be resolved using the active scope
            var decoratee = _decorateeFactory.Invoke();
            await decoratee.Handle(message);
        }
    }
}
```

You can apply this decorator as follows:

``` c#
container.RegisterDecorator(
    typeof(IHandleMessages<>), typeof(ScopedHandleMessagesDecorator<>),
    Lifestyle.Singleton);
```
