### ISSUE TITLE
Is VerifyAndDiagnose overly sensitive?

### ISSUE THREAD

**Issue by bitbonk** [simpleinjector/SimpleInjector#64]
Consider the following code.     
       
    this.container = new Container();
    this.container.Register<IEventAggregator, EventAggregator>(Lifestyle.Singleton);
    this.container.RegisterDecorator(
        typeof(IEventAggregator),
        typeof(EventAggragatorLoggingDecorator));
      
    // ShellViewModel gets IEventAggregator ctor-injected
    this.container.Register<IShell, ShellViewModel>(Lifestyle.Singleton);

    // Error: ShellViewModel (Singleton) depends on IEventAggregator (Transient).
    this.container.Verify(VerificationOption.VerifyAndDiagnose);

Is it really necessary that `VerifyAndDiagnose` complains about *ShellViewModel (Singleton) depends on IEventAggregator (Transient)* ?

Shouldn't a decorator's lifetime (by default) be bound to the lifetime of its decoratee?

Couldn't the container be more clever and know that there is no issue in this case because due to the dependencygraph the IEventAggregator will *always* be singleton lifetime?

**Comment by dotnetjunkie** [comment]
Your question is related to issue #63. This issue is about improving the message of the warning, but not about the sensitivity.

To answer your question: No, the container is not overly sensitive and a decorator should not automatically get the lifestyle of the decoratee. Just like any component, a decorator can have some state. For instance, you can create a decorator that caches some request based state, or it can depend on an IUserContext that requires a Scoped lifestyle. Even if the decoratee is Singleton, the decorator should not become singleton. Either loosening up the verification of giving a decorator a different lifestyle would either lead to confusion, because the API will start to behave inconsistently, or it will cause configuration errors to keep hidden.

The source of your trouble might be that it took some time for you to figure out that the decorator was causing this warning. This is something we will address in v3.0 and that's where the linked issue #63 is about.

One pro tip: consider making your complete object graph consist solely of singletons. This means that you make every component that is part of your object graph stateless, and everything that contains state (messages, DbContexts, etc) can be passed through the object graph using method calls. This removes the risk of causing lifestyle mismatches completely and although it forces you to 'think differently', it can make your DI configuration much easier to grasp, because it removes some of the common pitfalls (such as lifestyle mismatches) that we come across.

**Comment by bitbonk** [comment]
@dotnetjunkie That pro tip would definitely deserve a blog post on its own.

**Comment by dotnetjunkie** [comment]
I'm working on a blog post, but a short version of that post can be found in [this stackoverflow answer](https://stackoverflow.com/questions/32032771/using-dependency-injection-without-any-di-framework/32033648#32033648).
