### ISSUE TITLE
Cannot auto-register MediatR handler and decorator for it using open generic

### ISSUE THREAD

**Issue by abatishchev** [simpleinjector/SimpleInjector#651]
I'm using version 4.4.3.

Here's the interfaces I'm using from [MediatR](https://github.com/jbogard/MediatR):

```c#
public interface IRequestHandler<in TRequest> : IRequestHandler<TRequest, Unit> where TRequest : IRequest<Unit>
{
}

public interface IRequestHandler<in TRequest, TResponse> where TRequest : IRequest<TResponse>
{
    Task<TResponse> Handle(TRequest request, CancellationToken cancellationToken);
}

public struct Unit : IEquatable<Unit>, IComparable<Unit>, IComparable
{
}
```

And here's my class:

```c#
public sealed class CancelJobsInRolloutHandler : IRequestHandler<CancelJobsInRolloutCommand>
{
    public CancelJobsInRolloutHandler(IMediator mediator) { }
}
```

and a decorator for it:

```c#
public class MultiUsageCancelJobsInRolloutHandlerDecorator : IRequestHandler<CancelJobsInRolloutCommand>
{
    public MultiUsageCancelJobsInRolloutHandlerDecorator(IRequestHandler<CancelJobsInRolloutCommand> handler, IMediator mediator) { }
}
```

Please note that `IRequestHandler<CancelJobsInRolloutCommand>` is basically the same as `IRequestHandler<CancelJobsInRolloutCommand, Unit>`.

But when I auto-register both:

```c#
var asm = typeof(Handlers.Properties.AssemblyInfo).Assembly;
container.Register(typeof(IRequestHandler<>), asm, Lifestyle.Singleton);
container.Register(typeof(IRequestHandler<,>), asm, Lifestyle.Singleton);
```

I'm getting this exception:

>In the supplied list of types or assemblies, there are 2 types that represent the same closed-generic type IRequestHandler<CancelJobsInRolloutCommand, Unit>. Did you mean to register the types as a collection using the Container.Collection.Register method instead? Conflicting types: CancelJobsInRolloutHandler and MultiUsageCancelJobsInRolloutHandlerDecorator.

However when I register only the `<,>` interface and make the class and the decorator to implement it then everything works just fine.

**Comment by dotnetjunkie** [comment]
I think the behavior of Simple Injector is correct, or at least 'by design', although somewhat confusing. This is caused by the interface-inheritance model you are using.

Simple Injector's `Container.Register(Type, Assembly[])` method scans the supplied assemblies for compatible types and will automatically filter out any found decorators. The problem, however, is that, because of interface inheritance, it is unable to spot that `MultiUsageCancelJobsInRolloutHandlerDecorator` is intended to be used as a decorator.

Simple Injector tries to register `MultiUsageCancelJobsInRolloutHandlerDecorator`, because:

* `MultiUsageCancelJobsInRolloutHandlerDecorator` implements `IRequestHandler<TRequest, TResponse>` (through the implementation of `IRequestHandler<TRequest>`)
* `MultiUsageCancelJobsInRolloutHandlerDecorator` is non-generic (as generic types will be skipped)
* `MultiUsageCancelJobsInRolloutHandlerDecorator` is not considered to be a decorator for `IRequestHandler<TRequest, TResponse>`, because it doesn't accept the exact `IRequestHandler<TRequest, TResponse>` type in its constructor.

The following call fails for the same reason:

``` c#
container.RegisterDecorator(
    typeof(IRequestHandler<,>), 
    typeof(MultiUsageCancelJobsInRolloutHandlerDecorator));
```

This will fail with the following exception:

> For the container to be able to use MultiUsageCancelJobsInRolloutHandlerDecorator as a decorator, its constructor must include a single parameter of type IRequestHandler<CancelJobsInRolloutCommand, Unit> (or Func<IRequestHandler<CancelJobsInRolloutCommand, Unit>>) - i.e. the type of the instance that is being decorated. The parameter type IRequestHandler<CancelJobsInRolloutCommand, Unit> does not currently exist in the constructor of class MultiUsageCancelJobsInRolloutHandlerDecorator.

Although one might argue that `MultiUsageCancelJobsInRolloutHandlerDecorator` could in fact be used as decorator for `IRequestHandler<CancelJobsInRolloutCommand, Unit>`, this is not a scenario that Simple Injector considers. In fact, I think that allowing this could potentially open up a can of worms.

I don't think this is something that can be fixed easily, and I'm not sure I want to go with that root. You might want to try changing your design a bit.

**Comment by abatishchev** [comment]
> MultiUsageCancelJobsInRolloutHandlerDecorator implements IRequestHandler<TRequest, TResponse> (through the implementation of IRequestHandler<TRequest>)

Would it be beneficial for other users with similar scenarios to add an overload that accepts `bool considerInheritance` which would change the scanning behavior to look only for explicit implementations, rather than include inherited implementations as well?

>You might want to try changing your design a bit

Can you please elaborate?

For now I'm going to stick with `IRequestHandler<TRequest, TResponse>` as the only interface used, pretend that `IRequestHandler<TRequest>` doesn't exist. As I don't see any difference anywhere. Moreover it's a bit more readable.

**Comment by dotnetjunkie** [comment]
> Would it be beneficial for other users with similar scenarios to add an overload that accepts bool considerInheritance 

I rather not. What you are hitting seems to be a corner case. I never experienced anyone running into this before. So, I rather not add overloads that are confusing to 99.9% of the users.

> Can you please elaborate?

Sure. What I find confusing about your design starts here:

```c#
container.Register(typeof(IRequestHandler<>), asm, Lifestyle.Singleton);
container.Register(typeof(IRequestHandler<,>), asm, Lifestyle.Singleton);
```

This is confusing to me, because:

* As every `IRequestHandler<TRequest>` is an `IRequestHandler<TRequest, Unit>`, you'll find that registrations are duplicated. All `IRequestHandler<TRequest>` are also registered using the second registration. 
* There are two ways to register command handlers. You can implement `IRequestHandler<TRequest>` or implement `IRequestHandler<TRequest, Unit>`.
* A decorator for `IRequestHandler<TRequest>`, can never be wrapped around a class that implements `IRequestHandler<TRequest, Unit>`, even though they are in fact the same thing.

In other words, to me there seems to be some ambiguity in the design because of this.

I understand that the sole reason for you to have this extra `IRequestHandler<TRequest>` interface is to be simplify the common use case where a command handler does not return any data. However, it might be simpler to keep the two interface unrelated:

``` c#
// Do not inherit from IRequestHandler<TRequest, Unit>
// Also remove contravariance (the 'in' keyword) as it makes no sense when dealing with commands:
public interface IRequestHandler<TRequest> where TRequest : IRequest<Unit>
{
    Task Handle(TRequest request, CancellationToken cancellationToken);
}
```

If that's not an option, I suggest the following:

* Let *all* decorators solely decorate `IRequestHandler<TRequest, TResponse>` and *never* `IRequestHandler<TRequest>`. A decorator can still decorate `IRequestHandler<TRequest, Unit>`, but never `IRequestHandler<TRequest>`.
* [optionally] let command handlers always implement `IRequestHandler<TRequest, Unit>` instead of `IRequestHandler<TRequest>` (not required)
* implement a proxy for IRequestHandler<TRequest>` that will forward the request to IRequestHandler<TRequest, Unit>` and register it as open-generic type.

This proxy can look as follows:

``` c#

public sealed class CommandHandlerProxy<TRequest> : IRequestHandler<TRequest>
    where TRequest : IRequest<Unit>
{
    private readonly IRequestHandler<TRequest, Unit> handler;

    public CommandHandlerProxy(IRequestHandler<TRequest, Unit> handler) =>
        this.handler = handler;

    public Task<Unit> Handle(TRequest request, CancellationToken cancellationToken)
        => this.handler.Handle(request, cancellationToken);
}
```

Your registration will be as follows:

``` c#
var asm = typeof(Handlers.Properties.AssemblyInfo).Assembly;
container.Register(typeof(IRequestHandler<,>), asm, Lifestyle.Singleton);
container.Register(typeof(IRequestHandler<>), typeof(CommandHandlerProxy<>));
container.RegisterDecorator(typeof(IRequestHandler<,>), typeof(...), Lifestyle.Singleton);
container.RegisterDecorator(typeof(IRequestHandler<,>), typeof(...), Lifestyle.Singleton);
```

**Comment by maulwuff** [comment]
MediatR is very similar to SolidServices approach with Query- and Commandhandlers. The only "advantage" (my pain) it has, is a list of Pre- and PostProcessors which make up some sort of Pipeline with the actual handler.
