### ISSUE TITLE
Azure Functions with Execution Context

### ISSUE THREAD

**Issue by stevengopmo** [simpleinjector/SimpleInjector#652]
hi SimpleInjector team,

I'm looking for some clarification on integration with Azure Functions.  In #536 you show a static DIConfig class where most of the configuration is done in the static constructor.  However, I have a need to use some configuration and that comes from the function Execution context.  Is there a way to register the Execution Context in the container somehow for retrieval later?

**Comment by dotnetjunkie** [comment]
When it comes to handling runtime data, there are typically [two good ways of handling this](https://cuttingedge.it/blogs/steven/pivot/entry.php?id=99), independently of which container you are using:

1. pass runtime data through method calls of the API or
2. retrieve runtime data from specific abstractions that allow resolving runtime data.

The second option is valuable in case passing that data through method calls on the public API would cause ripple effects polluting the API and leak information details about that runtime data to consumers that are otherwise uneffected.

Scoping seems an ideal solution to your case, as it helps you pass that runtime data using option 2. Here's an example:

``` c#
// Defined in an application layer
public interface IContextProvider { Context Current { get; } }

// Composition Root
private class CachedContextProvider : IContextProvider { public Context Current { get; set; } }

// configuration
container.Register<IContextProvider , CachedContextProvider>(Lifestyle.Scoped);
container.Register<CachedContextProvider>(Lifestyle.Scoped);

// Usage
using (AsyncScopedLifestyle.BeginScope(container))
{
    // Set your runtime data at the start of the scope
    container.GetInstance<CachedContextProvider>().Current = value;

    // Resolve an object graph that that depends on IContextProvider and invoke the root object.
    container.GetInstance<SomeHandler>().Handle();
}
```

**Comment by stevengopmo** [comment]
oh, I think I get it, you are actually SETTING the value during the Scope execution so that when it gets injected in my handler the value will be set.  That works but it feels a little dirty but it's because Azure functions is a little dirty

**Comment by dotnetjunkie** [comment]
> it's because Azure functions is a little dirty

Agreed. Azure functions are quite dirty. That's why I prefer making the Azure functions [as thin as possible](https://github.com/simpleinjector/SimpleInjector/issues/536#issuecomment-382438219). They become Humble Objects and can, in that case, be considered part of the [Composition Root](https://freecontent.manning.com/dependency-injection-in-net-2nd-edition-understanding-the-composition-root/).

**Comment by stevengopmo** [comment]
Thanks, @dotnetjunkie I was able to solve using this technique thank you.

**Comment by dotnetjunkie** [comment]
I created a new [Azure Functions Integration](https://simpleinjector.org/azurefunctions) page. This demonstrates how to integrate Simple Injector with  Azure Functions v3.
