### ISSUE TITLE
JIT Compiler encountered an internal limitation when Intellitrace Enabled

### ISSUE THREAD

**Issue by JarrodJ83** [simpleinjector/SimpleInjector#66]
If I turn Intellitrace on I start receiving this error from SimpleInjector v.2.8.0

Microsoft Visual Studio Ultimate 2013
Version 12.0.31101.00 Update 4
Microsoft .NET Framework
Version 4.5.51650

The registered delegate for type IMyType threw an exception. Error occurred while trying to build a delegate for type IMyType using the expression "new MyType()". JIT Compiler encountered an internal limitation.

Stack:
   at SimpleInjector.InstanceProducer.GetInstance()
   at SimpleInjector.Container.GetInstance[TService]()

**Comment by dotnetjunkie** [comment]
This issue has been reported before [here](https://simpleinjector.codeplex.com/workitem/20677). That discussion also describes how to fix this.

**Comment by JarrodJ83** [comment]
Thanks! I did a search for this previously reported issues of this but came up empty handed. Sorry for the redundancy. 

Setting intellitrace to collect events only did the trick! 

- Jarrod

**Comment by dotnetjunkie** [comment]
No problem @JarrodJ83. The fact that your search result didn't bring up any useful results, is an indication that the old issues are not easily found. It's good to have this issue here on Github. This makes it more visible and hopefully others with the same problem will find the fix much quicker now.
