### ISSUE TITLE
Implicit Registration Explication

### ISSUE THREAD

**Issue by nrubiano** [simpleinjector/SimpleInjector#660]
Hi everyone, 

Currently i'm trying to understand what an implicit registration is?

If i'm asking for a dependency that have no been registered explicitly, what simple injector does in that case? 

Maybe this is a trivial question, but better to ask.

Thanks for you clarifications.

**Comment by dotnetjunkie** [comment]
Simple Injector can resolve unregistered types for you in case the type is concrete and all its dependencies can be resolved. In that case the type will be registered by Simple Injector the moment you resolve it for the first time. Such registration is considered to be implicit because the user didn't register it explicitly.

**Comment by nrubiano** [comment]
@dotnetjunkie thanks 👍

**Comment by TheBigRic** [comment]
@nrubiano 
In addition to the answer of @dotnetjunkie know that an implicit made registration js done with the
`container.Options.DefaultLifestyle` which by default is `Transient`. 

Implicit registrations may therefore sometimes bite you from another angle. They will cause a `Lifestyle Mismatch` diagnostic exceptions in case a implicitly registered component is injected into a component that is registered with the `scoped` or `singleton` lifestyle.

To be in control of the lifestyle it is therefore advised to not depend on implicitly registered components.
