### ISSUE TITLE
register/inject conditional on demand

### ISSUE THREAD

**Issue by gorums** [simpleinjector/SimpleInjector#672]
I have N implementations for the same interface, but I want to resolve only one in the Controller base in my subdomain.

if my subdomain(multitenant instance) is one.mysite.com I want to inject in the controller the interface IMyService with the implementation OneMyService, if my subdomain is two.mysite.com I want the implementation TwoMyService

Thx

**Comment by dotnetjunkie** [comment]
Does each sub domain get its own AppDomain instance or do all sub domains run in the same physical AppDomain?

**Comment by gorums** [comment]
same physical AppDomain

**Comment by dotnetjunkie** [comment]
In that case, it means that you are making decisions of which implementation to use based on runtime conditions, i.e. during the course of the same running application, different implementations are used.

Because changing the structure of resolved object graphs based on runtime data is [not advised](https://blogs.cuttingedge.it/steven/posts/2015/code-smell-injecting-runtime-data-into-components/), the typical solution in this case is to create a proxy implementation of that `IMyService` interface. That proxy, when its public methods are called, forward the call to the right implementation.

There are many ways you can implement such proxy. Which solution to pick depends on the design at hand. A possible solution, for instance, is to inject the proxy with a list of all available implementations and select the right implemention from the list based on the runtime data (the sub domain). Another option is to inject the proxy with a factory of some sort (for instance the `Container` instance), which allows the proxy to resolve the correct implementation from the factory.

If you need help in creating this proxy and adding the right registrations, please provide more information about your design. Show the interface, show some implementations, describe how those implementations are loaded, do decorators need to be applied, show how the sub domain information is being read, describe or show on what conditions the implementations are chosen. etc

**Comment by gorums** [comment]
thanks for your answer. Right now I'm using some kind of proxy, I'll continue to do it that.

**Comment by dotnetjunkie** [comment]
I think what you need is something similar to the following:

``` c#
var assemblies = new[] { typeof(IMyService).Assembly };

Dictionary<string, Func<IMyService>> serviceFactories = (
    from type in container.GetTypesToRegister<IMyService>(assemblies)
    where type != typeof(MyServiceProxy)
    let subDomain = type.Name.Replace("MyService", string.Empty)
    let producer = Lifestyle.Transient.CreateProducer<IMyService>(type, container)
    let serviceFactory = (Func<IMyService>)producer.GetInstance
    select new { subDomain, serviceFactory })
    .ToDictionary(p => p.subDomain, p => p.serviceFactory, StringComparer.OrdinalIgnoreCase);

container.RegisterInstance<IMyService>(new MyServiceProxy(serviceFactories));
```

With `MyServiceProxy` being:

``` c#
public class MyServiceProxy : IMyService
{
    private readonly Dictionary<string, Func<IMyService>> factories;

    public MyServiceProxy(Dictionary<string, Func<IMyService>> factories) =>
        this.factories = factories;

    // IMyService methods
    public object DoSomething(object value) => this.Service.DoSomething(value);

    private IMyService Service => this.factories[this.SubDomain].Invoke();
    private string SubDomain => HttpContext.Current.Request.Url.Host;
}
```

This effectively registers all `IMyService` implementations during start-up (using Auto-Registration), while postponing the selection of which implementation to use until the `MyServiceProxy.DoSomething` method is called.

**Comment by gorums** [comment]
Nice, I think this is a good solution for me.

Thx
