### ISSUE TITLE
How do I remove registration from container?

### ISSUE THREAD

**Issue by voroninp** [simpleinjector/SimpleInjector#679]
Along with overriding registrations I would like to completely remove some of them.

I use `TestServer` for testing end-to-end functionality of my asp.net core application, but the environment is set to `Testing`. Some settings of external libraries throw at construction when used with invalid parameters. As test settings do not always contain required parameters container verification fails. Moreover, these settings are not needed in tests at all because I mock the dependencies which use them in production code.

```CSharp
private class TestStartup : Startup
{
    public readonly Mock<IPipedriveReconciler> Reconciler =
        new Mock<IPipedriveReconciler>(MockBehavior.Strict);
    public readonly Mock<IGoogleSheetsClient> GoogleSheetsClient =
        new Mock<IGoogleSheetsClient>(MockBehavior.Strict);

    public TestStartup(IConfiguration configuration, IHostingEnvironment environment)
        : base(configuration, environment)
    {
        Reconciler.Setup(r => r.ReconcileOrganizationAndProductsAsync(It.IsAny<OrganizationId>()))
            .Returns(Task.CompletedTask);
    }

    protected override void RegisterServices()
    {
        base.RegisterServices();

        Container.Options.AllowOverridingRegistrations = true;

        Container.RegisterInstance(Reconciler.Object);
        Container.RegisterInstance(GoogleSheetsClient.Object);
    }
}
```

And here are registrations in base `Startup` class:

```CSharp
Container.RegisterSingleton(() =>
{
    var login = Configuration.GetValue<string>("Integrations:GoogleSheets:Login");
    var privateKey = Configuration.GetValue<string>("Integrations:GoogleSheets:PrivateKey");
    return new GoogleSheetsClient.Settings(login, privateKey);
});
Container.Register<IGoogleSheetsClient, GoogleSheetsClient>(Lifestyle.Scoped);
```

`GoogleSheetsClient` expects `GoogleSheetsClient.Settings` and settings throw if private key is not in correct format. I could put some random valid private key in `appsetting.Testing.json`, but I feel that unregistering is a cleaner way.

**Comment by dotnetjunkie** [comment]
Removing registrations is not possible in Simple Injector and there are no plans in supporting such feature in the future.

There are several ways to achieve your goals, though.

First of all, I typically advise to split container registration and loading of the configuration. This allows your container registrations to be verified in the absence of a real configuration file. On top of that I advise the use of a typed, application-specific configuration object that groups individual configuration values. This object is solely used inside the Composition Root (and never injected into application components). It can then be supplied to the method that builds the container. This allows the container to be built with a fake configuration during testing, as you will supply a fake, typed configuration object at that time, while constructing a real instance when the application starts. When you make that application-specific configuration object immutable, you allow the compiler to notify when a new configuration value is missing, both during testing and at application startup. 

In your case, however, you have the problem that creating valid configuration values is hard. But removing the registration would leave the container in an unverifiable state as there are other registrations that still depend on that object. If, however, validity of the container is not a concern (e.g. because these values are not needed in a particular set of tests and you don’t call `Verify()` at that point), the trick is to split the registration into two separate parts: one part containing the registration of the hard-to-construct configuration values, and a second part that registers all ‘normal’ registrations. When starting the application you ensure that both parts are called, while during testing you only call the second part. In other words, with this model you construct a partly configured container, where additional registrations are added in an extra step.

``` c#
private class TestStartup : Startup
{
    ...
    public TestStartup(IConfiguration configuration, IHostingEnvironment environment)
        : base(configuration, environment) ...

    protected override void RegisterConfigurationValues()
    {
        // prevent unneeded configuration values from being registered
    }

    protected override void RegisterServices()
    {
        base.RegisterServices();

        Container.Options.AllowOverridingRegistrations = true;

        Container.RegisterInstance(Reconciler.Object);
        Container.RegisterInstance(GoogleSheetsClient.Object);
    }
}
```

There are several ways you can structure your code around this concept. You could even consider moving the registration of the `GoogleSheetsClient` into the overridden part. This way you don’t have to override that registration at all. You can even mix this with the application-specific configuration object, where you make the `GoogleSheetsClientSettings` object optional in the application’s configuration class, allowing the registration of both the settings and the client to be skipped. This saves you from having to provide a valid settings object during testing.

**Comment by voroninp** [comment]
> But removing the registration would leave the container in an unverifiable state as there are other registrations that still depend on that object.

Nope, because I override these dependencies.

Anyway, last option seems fine.
