### ISSUE TITLE
Question about registering types specified in app.config custom section

### ISSUE THREAD

**Issue by sgrassie** [simpleinjector/SimpleInjector#682]
I have created a custom application configuration section, which I'm using to allow different providers to be registered in the app, each with various different settings, and the type of the provider is given as a type parameter which obviously when combined with the correct TypeConverter gets turned into a proper .net Type for me, and a provider type can be duplicated, as long as the key parameter is not.

The custom configuration section is loaded from the app.config in the usual manner, and registered in the container.

Based the configuration, I want to construct instances of the given types, so that the Container can provide them with a whole slew of service classes and such like, and then give them the additional configuration parameters they need (e.g. `provider.Accept(...config...)`, and return them to the main calling class in order to be used.

I also want them to be run on separate threads, as there is a bunch of async code and some database access that should be kept separate from each provider instance, so I'm using a nested scope, which I've wrapped in a decorator object based on the excellent documentation for this project.

In order to facilitate this, I've got a factory class which takes in the Container and the Configuration settings object and simply iterates through the collection of providers and does `_container.GetInstance(configItem.Type)`. It then hands off the additional config settings using the `.Accept(config.Thing1, config.Thing2)` and yields the new instance of the provider.

The interface for the providers is not generic, and I register all the implementations using the usual `Container.Collection.Register(etc, etc)`, and I register the decorator as the docs say to register it.

This is where we get to the crux of my question: In my factory class where I'm iterating through the config to get the specified types I was initially expecting that after I called `container.GetInstance(config.Type)` that it would be wrapped with the decorator I've registered, but it's not. I understand why it's not, and I understand that if I ask the container for all instances of the interface then the collection that comes back has them all wrapped in the decorator.

I could get around this limitation by manually newing up an instance of the decorator in my factory class, but the ability to easily register additional decorators via the container is really nice and would be very handy in the future.

Here is a very stripped down version of what I'm trying to do, minus the app config stuff and the factory class:

```C#
namespace ConsoleApp1
{
    public interface IResponder
    {
        string Response();
    }

    public class FooResponder : IResponder
    {
        public string Response()
        {
            return "Foo";
        }
    }

    public class BarResponder : IResponder
    {
        public string Response()
        {
            return "Bar";
        }
    }

    public class FooBarDecorator : IResponder
    {
        private readonly Container _container;
        private readonly Func<IResponder> _responderFactory;

        public FooBarDecorator(Container container, Func<IResponder> responderFactory)
        {
            _container = container;
            _responderFactory = responderFactory;
        }

        public string Response()
        {
            using (AsyncScopedLifestyle.BeginScope(_container))
            {
                var decoratee = _responderFactory();

                //in reality do something involving running some async code on a background thread, or, some kind of transactional database thing

                return $"FooBar{decoratee.Response()}";
            }
        }
    }

    public class RootType
    {
        private readonly IResponder _responder;

        public RootType(IResponder responder)
        {
            _responder = responder;
        }

        public void Run()
        {
            var response = _responder.Response();
            Console.WriteLine(response);
        }
    }

    class Program
    {
        static readonly Container container;

        static Program()
        {
            container = new Container();

            container.Collection.Register(typeof(IResponder), typeof(IResponder).Assembly);
            container.RegisterDecorator(typeof(IResponder), typeof(FooBarDecorator));

            container.Verify();
        }

        static void Main()
        {
            // This happens in the factory class
            var type = typeof(FooResponder); // in reality this comes a Type specified in the custom app.config section
            var instance = container.GetInstance(type) as IResponder;

            //Was expecting the instance to be the decorated instance
            var isDecorated = instance.GetType() == typeof(FooBarDecorator);
            Console.WriteLine($"Is decorated: {isDecorated}");
            //But it's not.
            var r = new RootType(instance);
            r.Run();
            Console.ReadKey();
        }
    }
}
```
Is there anything that I'm missing which can be done to achieve my goal?

**Comment by dotnetjunkie** [comment]
Since you are calling `container.GetInstance(typeof(FooResponder))`, Simple Injector has to return you a `FooResponder` or a sub type thereof. It is unable to wrap the type in a decorator, as that decorator is not castable to a `FooResponder`. This gets more obvious when you call `container.GetInstance<FooResponder>()` as the return type of `GetInstance<FooResponder>` is `FooResponder`.

Generally speaking, in order to allow Simple Injector to apply the decorator(s), you will have to resolve the type by its abstraction (i.e. `IResponder`). There are multiple ways to do this. Which solution is best, depends on the context.

For instance, although there might be multiple `IResponder` implementations, it seems that there is only one implementation used while the application is running (ignoring the decorators for a moment). In that case, you can simply do the following registration:

``` c#
// Register
container.Register(typeof(IResponder), configItem.Type);

// Resolve
container.GetInstance<RootType>();
```

In case you need to have all implementations, however, you can add them to a dictionary:

``` c#
// Register
container.RegisterDecorator<IResponder, SomeDecorator>();

var dictionary = (
    from type in container.GetTypesToRegister<IResponder>(assemblies)
    select { type, prod = Lifestyle.Transient.CreateProducer<IResponder>(type, container) })
    .ToDictionary(p => p.type, p => p.prod);

// Will also verify the created producers
container.Verify();

// Will be the decorated instance.
IResponder responder = dictionary[configItem.Type].GetInstance();
```
In a similar way, you could also 'abuse' the registration of collections to do the same:

``` c#
// Register
var types = container.GetTypesToRegister<IResponder>(assemblies);
container.Collection.Register<IResponder>(types);

// Resolve
IEnumerable<IResponder> responders = container.GetAllInstances<IResponder>();

int index = types.IndexOf(configItem.Type);
IResponder responder = responders.ElementAt(index);
```

There's a lot going on in this example:

* It registers all found `IResponder` implementations as collection of responders
* Simple Injector guarantees the order of types in the collection
* A resolved `IEnumerable<T>` is a singleton in Simple Injector and acts as a stream. You can safely inject the `IEnumerable<IResponder>` into a singleton consumer.
* Because the order of items is preserved you can grab the item from a specific index.
* This is done by getting the index of the `configItem.Type` from the array and using `ElementAt` using that index.
* Because Simple Injector streams implement `IList<T>`, LINQ's `ElementAt` is an optimized call and will only cause that single element to be resolved (and created), much like the dictionary approach.

I hope this helps.

**Comment by sgrassie** [comment]
Steven, thanks very much for your reply. I knew that I had to resolve my type by the interface in order to get an instance with the decorator applied, I just was not at all certain about how to actually do this.

You've given me (more than) enough detail to solve my problem. I've gone with the dictionary approach, as I need all implementations. If I have some time I'll write a blog post about how this all works.
