### ISSUE TITLE
Remove support for .NET 4.0

### ISSUE THREAD

**Issue by dotnetjunkie** [simpleinjector/SimpleInjector#692]
.NET 4.0 is over 9 years old and has been superseded by .NET 4.5 for 6.5 years. With the introduction of Simple Injector v5.0 we should remove support for .NET 4.0, as this simplifies parts of the core library which is littered with compilation switches in order to support .NET 4.0 as well.

When development of Simple Injector v5.0 is started, we will assess what minimum version of .NET we should support. My first impression is that we can easily support v4.5.

**Comment by dotnetjunkie** [comment]
Should we remove support for netstandard1.0 and netstandard1.3 as well?

**Comment by TheBigRic** [comment]
Well I don't think so.  
Looking at the [comparison](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) dropping .net standard 1.3 is virtually the same as dropping support for .Net Framework 4.6. Which is a bridge too far if you ask me. 

.Net Standard 1.0 however is a different ball game, because afaik 1.0 not fully implements .Net Framework 4.5.

The recommendation is to target as low as possible. So do you have to go to hoops to support .Net Standard 1.3?

**Comment by dotnetjunkie** [comment]
There are a few compiler directives in the code that enable .NET Standard 1.0 support, but the most prominent thing is `AsyncScopedLifestyle`. It is only available under .NET Standard 1.3 and up and .NET 4.5 and up. With the removal of both .NET Standard 1.0 and .NET 4.0 support, we can make `AsyncScopedLifestyle` the default scoped lifestyle.

It might still be useful to run Simple Injector in a .NET Standard 1.0 environment and developers might actually depend on this. This is that I have no idea what kind of use cases these are. Perhaps someone can enlighten me?

**Comment by TheBigRic** [comment]
Somebody still has to explain this to me. Why does the comparison show .net standard 1.0 and .net framework 4.5 while you clearly state that in practice 4.5 can do more. Is .net standard the most common denominator? It still dazzles me although the idea for .net standard seems appealing.

I can't give you a use case. I only use the full .Net Framework until now when I also use Simple Injector. 

I see however that there are a lot of packages only supported .Net Standard 1.3 and up. Seems like .Net Standard 1.3 is something like Entity Framework 4. The first thing that exactly really works?

If that is the case, drop it. Otherwise, well.... others have to answer to that.

**Comment by dotnetjunkie** [comment]
[feature-692](https://github.com/simpleinjector/SimpleInjector/tree/feature-692) branch created.
