### ISSUE TITLE
How to use SimpleInjector with NHibernate

### ISSUE THREAD

**Issue by Zpecter** [simpleinjector/SimpleInjector#71]
I'm trying to hook up Simple Injector in an ASP.NET MVC project with NHibernate with my own implementation for Unit of work and repositories. I have this project working with entityframework, but with NHibernate I need to inject the ISession and the ISessionFactory on my repositories and my unit of work, but I can't make it work, because the ISession object is always null when I try to use it in my repos.

Any clues?

**Comment by dotnetjunkie** [comment]
I might have some clues if you would show some code.

**Comment by Zpecter** [comment]
Ok, sorry. This is my Repository implementation:

public class Repository<T> : IRepository<T> where T : class {
        public Repository(ISession session) {
            if (session == null)
                throw new ArgumentNullException("session");
            Session = session;
        }

        protected ISession Session { get; set; }

        public IQueryable<T> GetAll() {
            return Session.Query<T>();
        }

        public virtual T GetById(int id) {
            return Session.Get<T>(id);
        }

        public void Add(T entity) {
            Session.Save(entity);
        }

        public void Update(T entity) {
            Session.Update(entity);
        }

        public void Delete(T entity) {
            Session.Delete(entity);
        }

        public virtual void Delete(int id) {
            T entity = GetById(id);
            if (entity != null)
                Delete(entity);
        }
    }

And this is my Unit of work:
public class UnitOfWork : IUnitOfWork {
        private ISession Session { get; set; }
        private IRepositoryProvider RepositoryProvider { get; set; }
        private ISessionFactory SessionFactory { get; set; }

        public UnitOfWork(ISessionFactory sessionFactory, IRepositoryProvider provider) {
            SessionFactory = sessionFactory;
            RepositoryProvider = provider;
            Session = SessionFactory.OpenSession();
            BeginTransaction();
        }

        #region IUnitOfWork Members

        public void Commit() {
            try {
                CommitTransaction();
            }
            catch (Exception) {
                RollbackTransaction();
            }
        }

        private void BeginTransaction() {
            Session.BeginTransaction();
        }

        private void CommitTransaction() {
            var session = Session;
            if (session.Transaction.IsActive) {
                session.Transaction.Commit();
                return;
            }
            session.BeginTransaction();
            session.Transaction.Commit();
        }

        private void RollbackTransaction() {
            var session = Session;
            if (session.Transaction.IsActive)
                session.Transaction.Rollback();
        }

        #endregion

        #region Repositories
        
        public IRepository<User> Users { get { return GetStandardRepo<User>(); } }
        
        #endregion

        private T GetRepo<T>() where T : class {
            return RepositoryProvider.GetRepository<T>();
        }

        private IRepository<T> GetStandardRepo<T>() where T : class {
            return RepositoryProvider.GetRepositoryForEntityType<T>();
        }

        public void Dispose() {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        #region IDisposable Members
            protected virtual void Dispose(bool disposing) {
                if (disposing) {
                    if (Session != null) {
                        Session.Dispose();
                    }
                }
            }
        #endregion
    }

**Comment by dotnetjunkie** [comment]
How does your `IRepositoryProvider` implementation look like? And if you think this is related to your use of Simple Injector, please add the lated code that you use to configure Simple Injector.

**Comment by Zpecter** [comment]
This is my IRepositoryProvider implementation:

 public class RepositoryProvider : IRepositoryProvider {
        private readonly IRepositoryFactory repositoryFactory;
        private Dictionary<Type, object> Repositories { get; set; } 

        public RepositoryProvider(IRepositoryFactory repositoryFactory) {
            this.repositoryFactory = repositoryFactory;
            Repositories = new Dictionary<Type, object>();
        }

        public ISession Session { get; set; }

        public virtual T GetRepository<T>(Func<ISession, object> factory = null) where T : class {
            object repoObj;
            Repositories.TryGetValue(typeof (T), out repoObj);
            if (repoObj != null)
                return (T)repoObj;
            return MakeRepository<T>(factory, Session);
        }

        private T MakeRepository<T>(Func<ISession, object> factory, ISession session) where T : class {
            var f = factory ?? repositoryFactory.GetRepositoryFactory<T>();
            if (f == null)
                throw new NotImplementedException();
            var repo = (T)f(session);
            SetRepository(repo);
            return repo;
        }

        public IRepository<T> GetRepositoryForEntityType<T>() where T : class {
            return GetRepository<IRepository<T>>(repositoryFactory.GetRepositoryFactoryForEntityType<T>());
        }

        public void SetRepository<T>(T repository) {
            Repositories[typeof(T)] = repository;
        }
    }

And this is my configuration:

container.Register<ISessionFactoryProvider, SessionFactoryProvider>(Lifestyle.Singleton);
            container.Register<ISessionProvider, SessionProvider>(Lifestyle.Transient);

            container.RegisterSingle(() => container.GetInstance<ISessionFactoryProvider>().CreateInstance());
            container.RegisterPerWebRequest(() => container.GetInstance<ISessionProvider>().CreateInstance(container.GetInstance<ISessionFactoryProvider>()));

And this is my ISessionProvider:

public class SessionFactoryProvider : ISessionFactoryProvider {
        private static readonly IPersistenceConfigurer SqlServer2008Configuration = MsSqlConfiguration.MsSql2012.ConnectionString(c => c.FromConnectionStringWithKey("ConnectionString"));
        public ISessionFactory CreateInstance() {
           try {
                var config = Fluently.Configure().Database(SqlServer2008Configuration)
                    .ProxyFactoryFactory<DefaultProxyFactoryFactory>()
                    .Mappings(m => m.FluentMappings.AddFromAssemblyOf<AddressConfiguration>())
                    .ExposeConfiguration(c => c.SetProperty("current_session_context_class", "web"))
                    .ExposeConfiguration(c => c.SetProperty("hbm2ddl.auto", "update"));
                return config.BuildConfiguration().BuildSessionFactory();
            }
            catch (Exception ex) {
                throw new Exception("Failed/Denied of Access/Database does not exist: " + ex.Message);
            }
        }
    }

And my ISessionProvider:

   public class SessionProvider : ISessionProvider {
        public ISession CreateInstance(ISessionFactoryProvider sessionFactory) {
            var sessionF = sessionFactory.CreateInstance();
            if (sessionF != null) {
                var session = sessionF.OpenSession();
                session.FlushMode = FlushMode.Commit;
                return session;
            }
            return null;
        }
    }

**Comment by dotnetjunkie** [comment]
The `RepositoryProvider` contains a public `Session` property, but it is set nowhere. This is probably causing the trouble.

Another thing that strikes me is the complexity of your code. You should seriously considering simplifying your code; your problems are clearly caused by the complexity of this code. Here are some pointers:

- Only inject what you need directly. UnitOfWork doesn't need a ISessionFactory; it needs an ISession.
- Only use constructor injection; don't use property injection.
- Good use of dependency injection reduces the need for factories; You currently have a `ISessionProvider`, `ISessionFactory`, `ISessionFactoryProvider`, `IRepositoryFactory`, `IRepositoryProvider`, and a `DefaultProxyFactoryFactory`. That's an awful lot of factories and providers for such a simple task.
- Your design seems to closely mimic NHibernate. Try defining am API that more suits your application instead.
- Do not execute complex logic that can fail inside a constructor; [injection constructors should be simple](http://blog.ploeh.dk/2011/03/03/InjectionConstructorsshouldbesimple/).
- There should be no need to do an explicit rollback; not committing a database transaction implies it is rolled back. This should also hold for NHibernate, otherwise it would be seriously flawed.
- Don't cache services yourself; the DI container is specialized in handling caching of services based on a certain lifetime. The `RepositoryProvider` contains a `Dictionary` for storing repositories. You can let your DI container do this.
- Instead of injecting an `ISessionProvider`, inject a `ISession` into any consumer that needs it (your unit of work and repositories) and let Simple Injector manage the lifetime of this session object using one of its scoped lifestyles (such as `WebRequestLifestyle` or `LifetimeScopeLifestyle`).
- Only dispose what you create yourself (don't dispose the `ISession` yourself, let Simple Injector do this).

**Comment by Zpecter** [comment]
Thanks a lot, injecting the ISession into the RepositoryProvider solved my problem, and thanks for the tips.
