### ISSUE TITLE
StackOverflowException in WebApi project

### ISSUE THREAD

**Issue by MichaelSagalovich** [simpleinjector/SimpleInjector#73]
All I know for now is described here: http://stackoverflow.com/questions/31263501/stackoverflowexception-inside-simpleinjector-in-mvc-webapi-project

Please let me know if a more formal description is required. 

I will try to narrow down the sample to give a more analyzable context, but I am not yet sure how I do that.

**Comment by qujck** [comment]
Hi @MichaelSagalovich,

I encountered a comparable issue back in Feb, `Verify` works OK but `var result = Analyzer.Analyze(container)` causes a stackoverflow exception and injecting the `container` made the problem go away.

**Comment by dotnetjunkie** [comment]
@MichaelSagalovich, could you try to reproduce the problem with [Simple Injector 3-beta1](https://www.nuget.org/packages/SimpleInjector/3.0.0-beta1)? The bug that @qujck  describes has been fixed in the v3 branch. Hopefully it solves your problem as well.

**Comment by MichaelSagalovich** [comment]
@dotnetjunkie I will try, thank you. How soon is it going to be released, though? I'd prefer not using betas in production system.

**Comment by dotnetjunkie** [comment]
It will be released when it is done :-). We're are currently waiting for feedback [from our beta testers](https://simpleinjector.org/blog/2015/06/beta-testers-wanted/) and after we collected enough feedback, we will decide when to release it.

**Comment by MichaelSagalovich** [comment]
did not help, unfortunately

**Comment by dotnetjunkie** [comment]
You mean that upgrading to v3-beta1 did not help? In that case we really need to have a some code to reproduce the issue. Hopefully you'd be able to supply us with this, otherwise it will be impossible for us to find the bug.

**Comment by MichaelSagalovich** [comment]
yeah, trying to do that

**Comment by qujck** [comment]
Here's the first clue, the code seems to be endlessly calling `Analyzer.GetSelfAndDependentProducers` (there are a couple of hundred more lines)
![silooping](https://cloud.githubusercontent.com/assets/4510990/8615819/35c5c598-26ee-11e5-99c5-d92c1488b515.png)

**Comment by dotnetjunkie** [comment]
@qujck, are you running v3-beta1?

**Comment by qujck** [comment]
No, not yet. Currently using 2.8.

**Comment by dotnetjunkie** [comment]
Can you test this with v3-beta1?

**Comment by qujck** [comment]
What version of Visual Studio are we using for V3?

**Comment by dotnetjunkie** [comment]
Visual Studio Community 2013.

**Comment by qujck** [comment]
I can confirm that v3 does have the problem I was getting in 2.8.

**Comment by dotnetjunkie** [comment]
With this we can conclude that @MichaelSagalovich's issue is a different bug than yours.

**Comment by dotnetjunkie** [comment]
I just ended researching a bug in Simple Injector 2.8. When a type with a cyclic dependency is registered using `RegisterOpenGeneric`, the container is unable to spot this cyclic dependency and you might end up with a stackoverflow exception. This bug might be related to @MichaelSagalovich although the bug does not exist in v3-beta2. Unfortunately, the bug is too hard to fix in the v2.8 branch.

**Comment by dotnetjunkie** [comment]
Hi @MichaelSagalovich,

The problem you are experiencing might be caused by the size of the object graph. I just experienced this in a solution of another Simple Injector user. You can check if this is the case by doing the following:
 - Revert the changes you made that work around the problem.
 - Call `var r = container.GetRegistration(typeof(YourProblemType))` to get `InstanceProducer` instance of the registration that is causing the stackoverflow.
 - Call `var e = r.BuildExpression()` on that `InstanceProducer` instance. If this call throws a stackoverflow exception, the problem is probably else :-(.
 - Inspect the `Expression` `e` in the debugger and check the size of it. If it is huge (over a thousand lines), we might have found the problem.

If your application contains immensely big object graphs mainly consisting of transient objects, Simple Injector will try to construct almost the complete object graph by compiling it down to one delegate. There is however a limitation in what the CLR can handle when it comes to compiling down big expression trees. Unfortunately, when that limit is reached, the CLR throws a stackoverflow exception.

If you are in doubt about what the size of your object graphs are, please run this code:

``` c#
var q = (
    from producer in container.GetCurrentRegistrations()
    let expression = producer.BuildExpression()
    let nodeCount = TreeSizeCounter.Count(expression)
    orderby nodeCount descending
    select new { nodeCount, producer.ServiceType })
    .Take(20)
    .ToArray();

public class TreeSizeCounter : ExpressionVisitor {
    public int ExpressionCount { get; private set; }
    public static int Count(Expression node)  {
        var counter = new TreeSizeCounter();
        counter.Visit(node);
        return counter.ExpressionCount;
    }
    public override Expression Visit(Expression node) {
        this.ExpressionCount++;
        return base.Visit(node);
    }
}
```

I can't give a hard limit of the maximum size of object graphs, because this might differ from machine to machine and the shape of the tree might be of influence as well, but with the other application there was an expression tree with 4500 nodes causing a stackoverflow. 

If your object graphs exceed 3000 nodes, you might be troubled by the same problem.

Could you confirm whether this is the case?

**Comment by MichaelSagalovich** [comment]
@dotnetjunkie thank you very much for the update. Unfortunately, I did not have enough time recently to get back to this. I will try to allocate a couple of minutes to make the tests you suggest soon. 
Generally, our graph is indeed big, and the issue appeared after we introduced a few more dependences (so, probably, "crossed the line"), so your explanation looks really plausible.

**Comment by MichaelSagalovich** [comment]
DebugView property for e gives 17555 lines. Looks like that's it. Please note, however, that my issue does not reproduce in debug mode. Does the issue you mentioned above behave the same way?

**Comment by dotnetjunkie** [comment]
The case I've been debugging contained a graph with 36,395 lines in the DebugView, so I think it's likely that you are witnessing the same problem. The bug is described in issue #91. The environment you're running your code in code influence at what point the stack overflow occurs. I can imagine that when running in debug (inside VS) there's more memory and you'll need a bigger object graph to reproduce the issue.

Either way, I'm working on a fix for this problem as we speak. I'm hoping to release a beta release later today for this. I would be really grateful if you would be able to check to see if that beta solves your problem. I keep you updated.

**Comment by dotnetjunkie** [comment]
I just pushed Simple Injector 3.0.0-beta4 to NuGet. Can you check if this solves the problem?

**Comment by MichaelSagalovich** [comment]
Fixed, thanks! Shall I close the issue now, or when the code is released to production (not beta)?

**Comment by dotnetjunkie** [comment]
Reallllly soon :-)

**Comment by dotnetjunkie** [comment]
Duplicate of #91.
