### ISSUE TITLE
Lifestyle.CreateHybrid lifestyleSelector not being called for constructor injected service.

### ISSUE THREAD

**Issue by malylemire1** [simpleinjector/SimpleInjector#733]
Lifestyle.CreateHybrid lifestyleSelector not being called for constructor injected service.
There is also a problem with following example. Transient instances created in Verifify are reused in constructor injection even if the lifestyle has been set to Singleton.

The singleton instance should be used for constructor injection.

For now the lifestyleSelector is not called on constructor injection and the transient instance from verify is reused. The same problem occurs with AsyncScopedLifestyle.

Here is how to reproduce the problem 

``` c#
public interface ITest : IDisposable
{
    bool IsSingleton { get; set; }
}

public interface ITestParent : ITest
{
    ITest Test { get; set; }
}

public class Test : ITest
{
    public bool IsSingleton { get; set; }

    public void Dispose()
    {

    }
}

public class TestParent : Test, ITestParent
{
    public ITest Test { get; set; }

    public TestParent(ITest test)
    {
        Test = test;
    }
}
```

```c#
Container container = new Container();

Lifestyle unverifiedSingletonLifestyle = Lifestyle.CreateHybrid(
        lifestyleSelector: () => !container.IsVerifying,
        trueLifestyle: Lifestyle.Singleton,
        falseLifestyle: Lifestyle.Transient);

container.Register<ITest, Test>(unverifiedSingletonLifestyle);

container.Register<ITestParent, TestParent>(unverifiedSingletonLifestyle);

container.Verify();

ITest test = container.GetInstance<ITest>();

test.IsSingleton = true;

ITestParent testParent = container.GetInstance<ITestParent>();

if (!testParent.Test.IsSingleton)
{
    throw new Exception("Should be singleton.");
}
```

**Comment by dotnetjunkie** [comment]
Thank you for taking tge time to post this repro. I'll research a bit to try to understand why this is happening.

In the meantime, can you elaborate on wbat it is you are trying to achieve? Mixing lifestyles like this is not a common use case, and I'm wondering if there is a more convenient solution for your problem.

**Comment by malylemire1** [comment]
Hi,

Actually I'm trying to have the same lazy instantiation order in release mode as I have in debug mode. I'm only calling Verify() in debug.

I do not want to skip the verification process so I've managed to instantiate a dummy Singleton as AsyncScopedLifestyle while Verifiying using the Hybrid Lifestyle and came with this problem.

**Comment by dotnetjunkie** [comment]
Why is it so important for you to not create that Singleton during verification? What is so special with thay component that you don't want it created at that point in time?

**Comment by dotnetjunkie** [comment]
In the meantime, I narrowed down the problem to the following test:

``` c#

public class Dependency { }

public class Consumer
{
    public Dependency Dependency { get; }
    public Consumer(Dependency dependency) => this.Dependency = dependency;
}

[TestMethod]
public void MethodUnderTest_Scenario_Behavior()
{
    var container = new Container();

    Lifestyle hybrid = Lifestyle.CreateHybrid(
            lifestyleSelector: () => !container.IsVerifying,
            trueLifestyle: Lifestyle.Singleton,
            falseLifestyle: Lifestyle.Transient);

    container.Register<Dependency>(hybrid);
    container.Register<Consumer>(hybrid);

    container.Verify();

    var dependency1 = container.GetInstance<Dependency>();
    var dependency2 = container.GetInstance<Dependency>();

    Assert.AreSame(dependency1, dependency2, "Should be a singleton."); // Succeeds

    var consumer1 = container.GetInstance<Consumer>();
    var consumer2 = container.GetInstance<Consumer>();

    Assert.AreSame(consumer1, consumer2, "Should be a singleton."); // Succeeds

    Assert.AreSame(dependency1, consumer1.Dependency, "Should be same instance."); // Fails
}
```

**Comment by dotnetjunkie** [comment]
What is going on here, is the following:

* A hybrid lifestyle wraps two different lifestyles, e.g.:
    ```
    new HybridLifestyle(lifestyleSelector, trueLifestyle, falseLifestyle);
    ```
* The registration for a hybrid lifestyle wraps wraps registrations of the supplied lifestyles, e.g.:
    ```
    new HybridRegistration(
        typeof(TConcrete),
        lifestyleSelector,
        trueLifestyle.CreateRegistration<TConcrete>(container), // True-lifestyle Registration
        falseLifestyle.CreateRegistration<TConcrete>(container), // False-lifestyle Registration
        ...)
    ```
* When the expression for the hybrid registration is built, the expressions of the underlying registrations are built as well:
    ```
    public override Expression BuildExpression()
    {
        Expression trueExpression = this.trueRegistration.BuildExpression();
        Expression falseExpression = this.falseRegistration.BuildExpression();

        return Expression.Condition(
            test: Expression.Invoke(Expression.Constant(this.test)),
            ifTrue: Expression.Convert(trueExpression, this.ImplementationType),
            ifFalse: Expression.Convert(falseExpression, this.ImplementationType));
    }
    ```
* When the expression of a `Singleton` is built, the resulting expression is a `ConstantExpression`, which means that the building of a `Singleton` expression results in the creation of the singleton instance, at that point in time. So, what this means is that, **independently of the supplied `lifestyleSelector` delegate**, a singleton will **always** be created when the hybrid is resolved (or verified).
* Because the `Singleton` consumer will get created during verification, it needs to get injected with an instance of its dependency.
* This means that at that point in time, the dependency's `lifestyleSelector` delegate will be called.
* During verification, however, the dependency's `lifestyleSelector` delegate returns `false` meaning that the dependency will get created using the `Transient` lifestyle.
* That `Transient` instance is injected into the `Singleton` consumer and stored in the conditional expression tree (i.e. `Expression.Condition`).
* Later on, after verification, when the `lifestyleSelector` returns `true`, the branch of the condition is called that contains the `Singleton` consumer. This consumer, however, depends on the `Transient` dependency, instead of the `Singleton` dependency.

**Comment by dotnetjunkie** [comment]
Although I understand that this is not the behavior you like to see, this is not something that is easily fixed. Changing the behavior to fix this problem, can easily cause problems for other users.

My suggestion would therefore be to rethink your problem and fix it using a different construct. If you provide me with enough input, I might be able to help you with that.

**Comment by malylemire1** [comment]
Hi,
Sorry for the late response.
I've managed to resolve my problem without the custom lifestyle.

I had a configuration Singleton injected in another Singleton that was using updated values from the database right after the Verify call. Without verification, the parent Singleton was using database configuration in it's constructor since it was instantiated after the database load. With verification the parent Singleton was instantiated before the configuration load from the database.

I have simply added properties to the parent and kept the configuration instance instead of it's properties. Now on every access, the parent return the configuration instance values.

Thanks for the fast support.
