### ISSUE TITLE
Typo in project name SimpleInjector,Tests.Unit

### ISSUE THREAD

**Issue by kwlin** [simpleinjector/SimpleInjector#735]
**Describe the bug**
I think there is a typo in the project name "SimpleInjector,Tests.Unit"

**Expected behavior**
Should be "SimpleInjector.Tests.Unit" (a dot instead of comma)

**Comment by dotnetjunkie** [comment]
The typo is deliberate, although a but confusing as you're not the first to trip over this.

I changed the dot to a comma to allow Visual Studio to sort the test project in the Solution Explorer directly after the core project.

I did this because I was always looking for the test project. I like the tesy projects to be paired with their test subjects.

But there might be other, more effective solutions to this problem though. Feel free to suggest other options.

**Comment by kwlin** [comment]
Sounds legit reason :) but

> I like the tesy projects to be paired with their test subjects.

this doesn't really match with your current setup :) of SimpleInjector

Maybe you could split up your solution with [solution filters](https://docs.microsoft.com/en-us/visualstudio/ide/filtered-solutions?view=vs-2019) For example the following solution filters:
* Core SimpleInjector
* Codesamples
* Documentation
* Integration

**Comment by kwlin** [comment]
Never mind. I see what you mean :)
