### ISSUE TITLE
How to setup DBContext injection in WPF .NET Core 3.0 with Entity Framework and SQLite

### ISSUE THREAD

**Issue by JasonLandbridge** [simpleinjector/SimpleInjector#765]
Hi there, 

I'm pulling my hair out here because I can't seem to make this work. Most examples I have found use ASP.NET but I'm trying to get this working in WPF .NET Core 3.0. 

As the question states, I'm trying to provide DBContext injection in my WPF .NET Core 3.0 project with Entity Framework and SQLite. The following code is giving me a mismatch but I'm so lost here I would be happy to start over from a fresh example. 

``` c#
 // See Simple Injector integration guide
 // https://simpleinjector.readthedocs.io/en/latest/servicecollectionintegration.html
 var services = new ServiceCollection();
 services.AddDbContextPool<CalculationToolsDBContext>(options =>
     {
         options.UseSqlite("Data Source=./CalculationToolsDB.db");
     }).AddSimpleInjector(Container);

 // Save yourself pain and agony and always use "validateScopes: true"
 IServiceProvider provider = services.BuildServiceProvider(true).UseSimpleInjector(Container);

 // Ensures framework components are cross wired.
 provider.UseSimpleInjector(Container);


 // Register the database context
 Container.Register<ICalculationToolsDataStore, CalculationToolsDataStore>(Lifestyle.Singleton);
 Container.Register<CalculationToolsDBContext>(Lifestyle.Scoped);
```

The CalculationToolsDBContext

``` c#
public class CalculationToolsDBContext : DbContext
{
    public DbSet<Village> Villages { get; set; }

    public CalculationToolsDBContext(DbContextOptions<CalculationToolsDBContext> options) 
: base(options) { }
}
```

The CalculationToolsDataStore 

``` c#
public class CalculationToolsDataStore : ICalculationToolsDataStore
{
    private readonly CalculationToolsDBContext _context;

    public CalculationToolsDataStore(CalculationToolsDBContext context)
    {
        _context = context;
    }

    public void UpdateVillages(List<IVillage> villages)
    {
        using (_context)
        {
            _context.AddRange(villages);
            _context.SaveChanges();
        }
    }
}
```

The interface ICalculationToolsDataStore
``` c#
public interface ICalculationToolsDataStore
{
    void UpdateVillages(List<IVillage> villages);
}
```

Any help would be greatly appreciated!

**Comment by dotnetjunkie** [comment]
Hi Jason,

> The following code is giving me a mismatch

I'm trying to understand your question and missing some details. Would you mind adding the full exception details? Please include the complete stack trace including all exception details of the exception and all inner exceptions.

**Comment by JasonLandbridge** [comment]
Thank you for responding, basically my question is "How to setup DBContext injection in WPF .NET Core 3.0 with Entity Framework and SQLite?" an example to get me started or some reference would be much apprericated. 

The mismatch error:
```
The configuration is invalid. The following diagnostic warnings were reported:
-[Lifestyle Mismatch] CalculationToolsDataStore (Singleton) 
depends on CalculationToolsDBContext (Thread Scoped).
See the Error property for detailed information about the warnings. 
Please see https://simpleinjector.org/diagnostics how to fix problems
 and how to suppress individual warnings.
```

Full details:

```
SimpleInjector.DiagnosticVerificationException
  HResult=0x80131500
  Message=The configuration is invalid. The following diagnostic warnings were reported:
-[Lifestyle Mismatch] CalculationToolsDataStore (Singleton) depends on CalculationToolsDBContext (Thread Scoped).
See the Error property for detailed information about the warnings. Please see https://simpleinjector.org/diagnostics how to fix problems and how to suppress individual warnings.
  Source=SimpleInjector
  StackTrace:
   at SimpleInjector.Container.ThrowOnDiagnosticWarnings()
   at SimpleInjector.Container.Verify(VerificationOption option)
   at CalculationTools.App.App.RegisterDependencies() in I:\Projects\TribalWars2-CalculationTools\CalculationTools.App\App.xaml.cs:line 88
   at CalculationTools.App.App.OnStartup(StartupEventArgs e) in I:\Projects\TribalWars2-CalculationTools\CalculationTools.App\App.xaml.cs:line 28
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

```

**Comment by dotnetjunkie** [comment]
Did you follow the link to the documentation as promted in the exception message and especially read about the [Lifestyle Mismatch](https://simpleinjector.org/dialm)? What constraints do you have that lead you to the registration of `CalculationToolsDataStore` as a `Singleton`?

**Comment by JasonLandbridge** [comment]
Yes I have read it but maybe there aren't contraints in my case but I assumed it's better to have a single instance of a class and more safe than multiple instances spread out. This might be a architecture problem on my side which is why I would rather start over this specific implementation I have above. 

So the hierarchy is as follows:
PlayerData(Singleton) -> CalculationToolsDataStore (Singleton) -> CalculationToolsDBContext (Scoped)

These classes are in a seperate data project in my solution so any database requests comes in through PlayerData. When I change the CalculationToolsDataStore to Lifestyle.Transient, the mismatch is then moved to the following:
```
The configuration is invalid. The following diagnostic warnings were reported:
-[Lifestyle Mismatch] PlayerData (Singleton) depends 
on ICalculationToolsDataStore implemented by CalculationToolsDataStore (Transient).
See the Error property for detailed information about the warnings. 
Please see https://simpleinjector.org/diagnostics how to fix
problems and how to suppress individual warnings.

```

At some point I would have to change everthing away from a singleton if i go up the chain but certain viewmodels should definitly be a singleton as I would like there to be only 1 instance of each of them.

**Comment by dotnetjunkie** [comment]
BTW, here are some resources worth reading:

* [Simple Injector's WPF integration guide](https://simpleinjector.readthedocs.io/en/latest/wpfintegration.html) 
* [Section 7.2 on Composing UWP applications from Dependency Injection Principles, Practices, and Patterns](https://livebook.manning.com/book/dependency-injection-principles-practices-patterns/chapter-7/61). Integrating UWP is very similar to integrating WPF
* [The source code for section 7.2](https://github.com/DependencyInjection-2nd-edition/codesamples/tree/master/UWPProductManagementClient/src)

**Comment by JasonLandbridge** [comment]
Thank you for the suggestion, the first link I had read but looking at it again I might be overusing the Lifestyle.Singleton.

This is how I register my views and viewmodels:

```c#
// Register all dialog windows
DialogService dialogService = new DialogService(MainWindow);

dialogService.Register<UnitImportWindowViewModel, UnitImportWidow>();
dialogService.Register<ConnectionWindowViewModel, ConnectionWindow>();
dialogService.Register<SettingsWindowViewModel, SettingsWindow>();

IoC.Container.Options.DefaultScopedLifestyle = new ThreadScopedLifestyle();
IoC.Container.Options.AllowOverridingRegistrations = true;

// Register dependencies
IoC.Container.Register<IDialogService>(() => dialogService, Lifestyle.Singleton);

IoC.Container.Register<ApplicationViewModel>(Lifestyle.Singleton);

IoC.Container.Register<MainWindow>(Lifestyle.Singleton);
IoC.Container.Register<MainWindowViewModel>(Lifestyle.Singleton);

IoC.Container.Register<SettingsWindow>(Lifestyle.Scoped);
IoC.Container.Register<SettingsWindowViewModel>(Lifestyle.Singleton);

IoC.Container.Register<UnitImportWidow>(Lifestyle.Scoped);
IoC.Container.Register<UnitImportWindowViewModel>(Lifestyle.Singleton);

IoC.Container.Register<ConnectionWindow>(Lifestyle.Scoped);
IoC.Container.Register<ConnectionWindowViewModel>(Lifestyle.Singleton);

IoC.Container.Register<BattleSimulatorView>(Lifestyle.Singleton);
IoC.Container.Register<BattleSimulatorViewModel>(Lifestyle.Singleton);

IoC.Container.Register<AttackPlannerView>(Lifestyle.Singleton);
IoC.Container.Register<AttackPlannerViewModel>(Lifestyle.Singleton);

IoC.Container.Register<BattleInput>(Lifestyle.Singleton);
IoC.Container.Register<BattleInputViewModel>(Lifestyle.Singleton);
```

**Comment by JasonLandbridge** [comment]
Okay I now realize I would like to keep my singleton classes but still provide a DBContext. I have understood so far that I should supply a "scope factory" based on the following answer:

[How to use a database context in a singleton service?](https://entityframeworkcore.com/knowledge-base/51939451/how-to-use-a-database-context-in-a-singleton-service-)

But now I am stuck as I would need to register `IServiceScopeFactory`:
`            Container.Register<IServiceScopeFactory>(Lifestyle.Scoped);
`

but I get the following error:

`The given type IServiceScopeFactory is not a concrete type. Please use one of the other overloads to register this type. (Parameter 'TConcrete')`

I feel like I am missing something really simple, staring me straight in the face but I can't seem to figure it out. 

So now my question is, how do I setup this scope factory in Simple Injector to work with DBContext?

**Comment by dotnetjunkie** [comment]
Hi Jason,

Here are a few pointers:

* Unless you are using other reusable libraries that take a hard dependency on `IServiceCollection`, I would advice removing it. `IServiceCollection` is required when applying DbContext pooling, but its performance benefits will be neglectable for desktop applications. You can can register your `DbContext` directly into Simple Injector using the Scoped lifestyle.
* Prevent wrapping the use of a `DbContext` in a `using` block. As `CalculationToolsDataStore` did not create the `DbContext`, it is not the owner, and should not dispose it. Disposing injected dependencies will eventually cause `ObjectDisposedExceptions` down the lines.
* You can't inject statefull dependencies (such as `DbContext`) into Singleton consumers. This leads to all sorts of issues, such as concurrency bugs, but even in single-threaded applications, a DbContext will get stale pretty quickly when it is kept alive for the duration of the application.
* Working with Scoped components into desktop applications is always a tricky business because windows/screens/etc can live for a long time.
* Whether you're overusing the Singleton pattern is up for debate. It depends on which [Composition Model](https://blogs.cuttingedge.it/steven/p/compositionmodels/) you are using. In general, however, I would say that at least your Windows should *not* be Singleton, and probably neither should be your view models. Everything below that *could* be singleton, but that does require you to design things differently. Here are a few options:
   * Switch to a three-tier application model where the desktop not directly connects to the database but with a web API. The DbContext will then live inside the web api.
   * If you stick with two tiers, hide your service layer behind a few generic interfaces, such as [this](https://blogs.cuttingedge.it/steven/p/commands) and [this](https://blogs.cuttingedge.it/steven/p/queries/). This allows you to create [generic Lazy Proxy implementations](https://simpleinjector.readthedocs.io/en/latest/aop.html#decorators-with-func-t-decoratee-factories) for them and inject them into Singletons.
* Be careful with the use of `AllowOverridingRegistrations`. It's better not to have it enabled by default, and only temporarily switch it on in the care case you really want to override an existing registration.
* The "How to use a database context in a singleton service?" example will not work with Simple Injector. Although you can inject the Simple Injector `Container` into the class, you are not advised to do so. Any `Container` should only be used inside the startup path of your application; not inside your business code. 

I'm sorry to not being able to give you any practical real-use examples; time does not allow me to do so. I still hope these pointers help.

**Comment by JasonLandbridge** [comment]
Thank you for your awesome and helpful reply! 

I'm currently reading you book, Dependency Injection: Principles, Practices, and Patterns, and have finished half of it this past weekend. The book is amazing, very clear and well put together. I will need to read a bit more but I have come to realize that I need more knowledge on the subject so give me some time and I will get back to you.
