### ISSUE TITLE
Question: Simple injector tracking

### ISSUE THREAD

**Issue by generik0** [simpleinjector/SimpleInjector#777]
HI

I have always used Castle Windsor, and have been very happy. But looks like ASP.NET Core 3 is far off for Windsor. Sad but true. I have previously used Autofac, but I thought i might give Simple Injector a shot.

In Windsor, I have been used to "Release" objects that a factory or the container was asked to resolve directly. I.e. tracked items (not ctor injected). I know it goes against many peoples thoughs about an IoC, but i do love my factories. Windsor was so good at them :-)

Do I need to think about this at all in Simple Injector (also is there a short name for Simple Injector, like simple or something?)

As mentioned i have used the Autofac, for both ASP.NET Core and Generic Host. I had issues here once with a leak due to my Entity Framework Core factory. I did not set the `ExternallyOwned()` for items resolved by the autofac factory/container.

Any thoughts, any memory pitfalls I should be worried about?

Thanks for time and patients :-)

**Comment by dotnetjunkie** [comment]
The rule in Simple Injector is that [the user is never forced to release what they resolve](https://simpleinjector.readthedocs.io/en/latest/decisions.html#never-force-release). In Simple Injector you:
* Resolve directly from the `Container`, because [Scope](https://simpleinjector.org/lifetimes#scoped-lifestyle) instances are *ambient*
* You can never resolve `Scoped` instances without an active `Scope`
* Automatically release all resolved `Scoped` instances by disposing the `Scope`.

This is typical usage of Simple Injector:

``` c#
using (AsyncScopedLifestyle.BeginScope(container))
{
    container.GetInstance<MyComponent>().DoWork();
}
```


This is similar to how other DI Containers work:
* Autofac works with `LifetimeScopes`
* Although Windsor allows releasing instances, newer versions use ambient scopes, similar to Simple Injector, with prevent you from having to release instances

However, there are difference between Simple Injector and other DI Containers:
* In Autofac scopes are not ambient
* Autofac allows you to (accidentally) resolve instances from the root container, which can easily cause memory leaks
* Autofac tracks all Disposable components; Simple Injector, on the other hand, does not track Transients, and will warn you about a disposable transient when you [verify the container](https://simpleinjector.org/howto#verify-configuration).
* Windsor allows you to explicitly release instances

Memory leaks will be very rare in Simple Injector, because:
* Transients are not tracked
* Scoped instances can never be resolved from the root container
* Verification prevents common pitfalls such as [Captive Dependencies / Lifestyle Mismatches](https://simpleinjector.org/dialm).

**Comment by generik0** [comment]
Hi @dotnetjunkie that’s really great. Thanks!!
I’ll give it a go. 
I have not been using scopes (other
than the web request scope) for castle/autofac.
I know i should, and i will get there :-)

Regarding the tracking, I actually don’t mind the releasing. I like keeping control. But I also think only worrying about the disposable is great.

I like the Verity() function. Very nice. Thanks for the tip!

Looking forward to see if the diagnostics are good like in Windsor :-)

**Comment by dotnetjunkie** [comment]
As long as you are running all your operations from within a web request, in most cases you don't have to do anything. Simple Injector's integration (for WCF, ASP.NET MVC, ASP.NET Web API, and ASP.NET Core) will wrap a web request in a scope for you. So it's certainly not that you *should* do extra scoping. It can come handy from time to time, but again, within a web request, typically not needed.
