### ISSUE TITLE
Having issue iterating over collection, throws NRE

### ISSUE THREAD

**Issue by chrisagay** [simpleinjector/SimpleInjector#782]
I am attempting to utilize a factory to generate which implementation to provide. I have registered the collection of interface implementations, and that is successfully passed to the constructor of the factory to be used when generating the proper implementation. I have tried using foreach, Where (LINQ) and SingleOrDefault with boolean function (LINQ).
In my case I have 2 implementations, and I can step through and get the information on first element. As the enumerator calls MoveNext( ) it throws an NRE. Can someone help explain what I might be doing wrong?

Thanks in advance!

**Comment by dotnetjunkie** [comment]
Hi @chrisagay,

Can you please provide the nessisary details for us to reproduce the issue? This means:
 
Anything that helps us to reproduce your issue would be, such as:

* a complete stack trace including all exception details of the exception and all inner exceptions if an exception is thrown.
* a Minimal, Complete, and Verifiable example that reproduces the problem. (see: https://stackoverflow.com/help/mcve) 
* Add any other context about the problem here. e.g.: Library versions (version of Simple Injector and all affected integration packages).
* If you aren't using the latest version of Simple Injector, have you tried to reproduce the bug on the latest version of Simple Injector?

**Comment by chrisagay** [comment]
This was initially found on 4.7.1, and I just upgraded to 4.8.1. Upgrading
provided additional information that was causing on of my instances to not
be activated, thereby having a null in the collection. I have corrected
this and everything is working correctly now.
Here is a an example of how the issue was generated:

In a class library (not the main application):
interface A { }
class B : A {
}
class C : A {
    public string foo = "Something that will throw an exception"; //
Application.Current.Resources["bar"].ToString();
}

In application:
var assemblies = new[] { typeof(A).Assembly };
container.Collection.Register<A>(assemblies);
container.Verify(); // Exception here

**Comment by dotnetjunkie** [comment]
When a NullReferenceException is thrown from inside one of your constructors that is called by Simple Injector, the exception can be cryptic. This happens because Simple Injector constructs a single delegate with compiled code that creates a complete object graph of possibly many objects. This could make it unclear that the exception originates from your own code, especially if the exception originates from an instance initializer of your class, although the stack trace would give some clues.

Although it is technically possible to improve the exception information and wrap the original exception in a Simple Injector exception that explains that your type threw the exception, it is not feasible to achieve this without introducing a big  performance penalty, because instead of having one single delegate that creates an entire graph, every creation of a single object must be wrapped in code that would catch any exception. This effectively means wrapping object creation in a new delegate, for every created object in the graph.
