### ISSUE TITLE
What Method Replaces .InjectPoperties(instance)?

### ISSUE THREAD

**Issue by MDBonafe** [simpleinjector/SimpleInjector#784]
In older versions (specifically 2.4.1), I used a call to InjectProperties inside a Bootstrapper override class.  What replaces this method?

**Comment by dotnetjunkie** [comment]
You can read all about that [here](https://simpleinjector.readthedocs.io/en/2.8/injectproperties-is-deprecated.html?highlight=injectproperties).

Do note that you are adviced to migrate one major version at a time. Since you are currently using v2, you should:
* Upgrade to the latest v2.x release. Fix warnings and errors, and run and test the application.
* Upgrade to v3.0.0. Fix warnings and errors, and run and test the application.
* Upgrade to the latest v3.x release. Fix warnings and errors, and run and test the application.
* Updrade to v4.0.0. Fix warnings and errors, and run and test the application.
* Updrade to the latest v4.x release. Fix warnings and errors, and run and test the application.
