### ISSUE TITLE
Singleton registration can be injected with 2 different types which creates 2 instances.

### ISSUE THREAD

**Issue by christophedemey** [simpleinjector/SimpleInjector#786]
## Describe the bug
First i had this

``` c#
container.Register<AlarmService>(Lifestyle.Singleton);
```
Then because of testing reasons i had to create an abstraction so i could mock the object.

``` c#
container.Register<IAlarmService, AlarmService>(Lifestyle.Singleton);
```
I changed the injections in my constructors to use `IAlarmService`.
But i forgot 1.
This caused the existence of 2 instances of `AlarmService`, one as `IAlarmService` and one as `AlarmService`.
The service is responsible for some thread starting/stopped and ofcourse since they were 2 different instances, this went horribly wrong.

What i was expecting to happen ->
Exception from Simple Injector stating that `AlarmService` cannot be injected since it is not registered, only `IAlarmService` was registered with a concrete implementation of `AlarmService`.

Hope this makes sense but i believe this is a bug.

Kind Regards

**Comment by dotnetjunkie** [comment]
Are you calling `Container.Verify()`? And if so, does it throw an exception? If not, please update to the latest version and try again. If this doesn't throw, please post a repro.

**Comment by dotnetjunkie** [comment]
But eitherway, what you are experiencing is a combination of a

* [Ambiguous Lifestyle](https://simpleinjector.org/diaal), and a
* [Short-Circuited Dependency](https://simpleinjector.org/diasc)

Both problems are detected by Simple Injector, but only when the configuration is verified. You can do that, for instance, by calling `Container.Verify()`.

Simple Injector v4, however, does not detect these problems upon resolve by default, and this is by design. What you are experiencing is, therefore, *not* a bug. To ensure that your configuration is correct, you should always call `Container.Verify` or set `Container.Options.EnableAutoVerification` to `true`. The latter option will cause complete verification of the container on the very first resolve.

Do note that in v5, `Container.Options.EnableAutoVerification`'s default value will be `true`, which will remove the problem completely. This is, however, a breaking change, which is why v4 has it disabled by default.
