### ISSUE TITLE
Some useful features to make SI more awesome! 

### ISSUE THREAD

**Issue by jdahan91** [simpleinjector/SimpleInjector#804]
- Allow registration of collections as singleton by accepting a lifestyle parameter.

- Allow to register an instace (and collections) with more than one definition (interface)

**Comment by dotnetjunkie** [comment]
Can you elaborate on these feature requests by giving some examples? It's currently unclear to me what you're exactly trying to achieve.

**Comment by jdahan91** [comment]
> Can you elaborate on these feature requests by giving some examples?

`container.Collection.Register<Interface>(Collection, **Lifestyle** Parameter);`

> It's currently unclear to me what you're exactly trying to achieve.

I'm trying to achieve code simplicity. Currently to make a collection singleton I have to iterate over the instances and create a registration instance by instance as singleton and then register the collection. I think having a single parameter for the register api would be sufficient.

**Comment by dotnetjunkie** [comment]
> `container.Collection.Register<Interface>(Collection, **Lifestyle** Parameter);`

And what for type is `Collection` in this case?

**Comment by jdahan91** [comment]
> > `container.Collection.Register<Interface>(Collection, **Lifestyle** Parameter);`
> 
> And what for type is `Collection` in this case?

The type of implemented interface.

**Comment by dotnetjunkie** [comment]
Hi @jdahan91,

I've been reading both your comments a few times in trying to understand your problem. Unfortunately, it's unclear to me what you need. That's the problem with natural languages; they tend to be ambiguous. So let's revert to an exact language instead: can you post a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) in C# that demonstrates what it is you are trying to do (for both feature requests)?

Please post the classes and interfaces with their inheritance relationships, add any dependencies to the classes if that demonstrates the problem. Also show how you are registering things now, or show *manually constructed object graphs* of class instances of the structure you are trying to achieve (as demonstrated [here](https://github.com/simpleinjector/SimpleInjector/issues/new?assignees=&labels=question&template=question-and-feature-request.md&title=) in the tip).

**Comment by jdahan91** [comment]
OK, the examples i'm going to show are use cases from one of my open source projects (Telebot).

OK, so lets say I have this hierarchy:

```
    public abstract class IBattery : IDevice
    {

    }

    public abstract class IProcessor : IDevice
    {

    }

    public abstract class IDisplay : IDevice
    {

    }

    public abstract class IDrive : IDevice
    {

    }

    public abstract class IMainboard : IDevice
    {

    }
```

Now imagine a scenario where you have a collection of IDevice instances that you want to receive instances based on base or child interfaces.

For example, lets say i'm creating an array of IProcessor and IMainboard classes (they're both a device, IDevice), concating them and registering as IDevice collection.

I can easily call GetAllInstances<IDevice> and get those classes. 

**But** what if I want only those who are IProcessor or IMainboard? this is the problem.

**Comment by dotnetjunkie** [comment]
> The problem is i have to register each collection with their unique interface instead of registering once

Aaahhh... now I see. Normally, you would do the following:

``` c#
container.Collection.Register<IDevice>(assembly);
container.Collection.Register<IBattery>(assembly);
container.Collection.Register<IDisplay>(assembly);
container.Collection.Register<IDrive>(assembly);
container.Collection.Register<IMainboard>(assembly);
```

But this is not a maintainable solution for you. I can see that this is the case when you add new abstract `IDevice` sub types on a regular basis. That would force you to go back to the Composition Root and add a new collection call for that new sub type, for instance `IMonitor`:

``` c#
container.Collection.Register<IMonitor>(assembly);
```

Now, I'm going to disappoint you: I consider this scenario so rare that I will not consider adding new overloads or features that make this scenario easier. But, Simple Injector does already contains quite some extension points that allow you to reduce the burden on your Composition Root, although that does mean there is a bit more wiring to do. Here are a few examples.

What you can do, for instance, is determine the available device abstractions and loop through them to make a collection registration per abstraction:

``` c#
var devices = container.GetTypesToRegister<IDevice>();

var deviceAbstractions = devices.Select(d => d.BaseType).Distinct();

foreach (Type deviceAbstraction in deviceAbstractions)
{
    container.Collection.Register(
        deviceAbstractions,
        devices.Where(d => d.IsSubTypeOf(deviceAbstraction)));
}
```

Another option is to make use of unregistered type resolution although, admittedly, that is more complex in your case. But here's an example anyway:

``` c#
foreach (Type type in container.GetTypesToRegister<IDevice>(assembly))
{
     // Register type as its concrete type
     container.Register(type, type);
}

// Handle unregistered IEnumerable<Device> resolves
container.ResolveUnregisteredType += (s, e) =>
{
    Type type = e.UnregisteredServiceType;
    if (!type.IsClosedTypeOf(typeof(IEnumerable<>))) return;

    Type elementType = type.GetGenericArguments().Single();

    if (!typeof(IDevice).IsAssignableFrom(elementType)) return;

    // Find all device registrations for the given element type
    var registrations = (
        from registration in container.GetCurrentRegistrations()
        where elementType.IsAssignableFrom(registration.ServiceType)
        select registration)
        .ToArray();

    // Construct a stream that returns all filtered devices
    IEnumerable<object> devices =
        from registration in registrations
        select registration.GetInstance();

    // We need to cast the IEnumerable<object> to IEnumerable<{elementType}>
    var castMethod = typeof(Enumerable).GetMethod("Cast").MakeGenericMethod(elementType);

    e.Register(Expression.Constant(castMethod.Invoke(null, new[] { devices }), type));
};
```

Personally, I think option 1 is simpler. Go with option 1 :)

**Comment by dotnetjunkie** [comment]
Here's a 3rd option that just came to mind. You can define the following extension method:

``` c#
public static void AppendForAllImplementedInterfaces(
    this ContainerCollectionRegistrator registrator, Type implementationType)
{
    foreach (var @interface in implementationType..GetInterfaces())
        registrator.Append(@interface, implementationType);
}
```

This allows you to do the registrations as follows:

``` c#
var options = new TypesToRegisterOptions { IncludeComposites = false };
foreach (Type deviceType in container.GetTypesToRegister<IDevice>(options))
{
    container.Collection.AppendForAllImplementedInterfaces(deviceType);
}
```

**Comment by jdahan91** [comment]
Looks interesting, thank you. But I still encourage you do add this type of behavior to SI.

**Comment by dotnetjunkie** [comment]
Hi Jonathan,

A feature never stands on its own. A feature must always take the existing API and philosophy of the library into consideration. But as you probably know, it's hard to build, design, and maintain reusable libraries that can stand the test of time. You need to design your API in such way that [simple use cases become easy, while complex use cases are still possible](https://simpleinjector.org/principles+make-simple-easy). You always try to strike a balance between defining an API that is simple to use (without overloading users with many methods) while on the other hand giving users an API with what they can get the job done. But it is not an easy thing to do.

Designing and implementing a new feature works best when we have multiple use cases as input. I typically wait until there are enough requests or questions raised by multiple people before I start implementing a new feature. This gives me a good grasp of what the best API would be. For this, I typically use the "rule of three," which means that I don't implement a feature before I have *at least* three different use cases (preferably from different people) before I start implementing a new feature. Implementing a feature too early (not following the rule of three), often results in bad APIs. This is a painful error I made myself many times in the past.

A feature such as the one you are proposing, is one that would need considerable time to design and test, because there are so many ways one might want to auto-register these collections. For instance, do you only register them by interfaces, by their base type, by their chain of base types, or a combination thereof? And there are likely many other variables to consider, for instance naming, placing, use of method overloads. And don’t forget documenting.

The use case you are proposing is quite specific. This is, as far as I can remember, the first time someone ever asked for this specific feature (where a myriad of related collections is registered in one single API call). This means that it will take a considerable amount of time before the rule of three is satisfied. But jumping right in, on the other hand, can cause Simple Injector’s API to deteriorate at a must faster pace, which is something I’m very careful in, because it is my intention to maintain Simple Injector for many years to come.

Simple Injector, however, is flexible and mature enough to allow most specific use cases to be implemented with just a few lines of code; I demonstrated that this is true for your use case in my comments above. This is where the Simple Injector Contributors and the rest of the community comes into play. When you raise a well-written question here on GitHub or on Stack Overflow, you typically get a satisfying answer within the hour. And you get that for free. This is one of the great things about open source and a living community. You don’t always get all your features baked in, but great questions almost always result in great answers.

I know I can’t make everybody happy, and you are likely disappointed by my stance. But don’t forget that at the end of the day, a library needs to be maintained and sustained. As maintainer I have to be careful and err on the side of sustainability to ensure as many developers can use Simple Injector for as long as possible.
