### ISSUE TITLE
IServiceScopeFactory is not automatically cross-wired in ASP.NET Core

### ISSUE THREAD

**Issue by thePmr** [simpleinjector/SimpleInjector#814]
For ASP.NET Core 3.1 Web API.

I'm trying to run some task on DB asynchronously in controller action. For that purpose I'm injecting `IServiceScopeFactory` to create scope: 

```c#
public IActionResult Post()
{
    Task.Run(async () =>
    {
        using var scope = _serviceScopeFactory.CreateScope();
        var myService = scope.ServiceProvider.GetService<IMyService>();
        // ...
    }
	
    return Ok();
}
```

ASP.NET Core DI works fine, but when I set up simple injector, it throws exception:

> SimpleInjector.ActivationException: The constructor of type RunnerController contains the parameter with name 'serviceScopeFactory' and type IServiceScopeFactory, but IServiceScopeFactory is not registered. For `IServiceScopeFactory` to be resolved, it must be registered in the container.

But adding `options.CrossWire<IServiceScopeFactory>()` to SI set-up, solves the issue:

```c#
public void ConfigureServices(IServiceCollection services)
{
	services.AddControllers();

	services.AddSimpleInjector(container, options =>
	{
		options.AddAspNetCore()
			.AddControllerActivation();

		options.CrossWire<IServiceScopeFactory>();
	});
}
```

So, first question: is it an expected behavior? 

And generally, should I use`IServiceScopeFactory` in such scenario or I should go for something like `AsyncScopedLifestyle.BeginScope(...)` ?

**Comment by dotnetjunkie** [comment]
> So, first question: is it an expected behavior?

Wellll.... This is behavior is more accidental than intentional. Simple Injector's auto cross wiring works by finding registrations for services in the `IServiceCollection`. Only services that have a corresponding `ServiceDescriptor` in the `IServiceCollection` can be resolved. There is one exception, though, (or perhaps a few), which is the `IServiceScopeFactory`. A `IServiceScopeFactory` isn't part of the `IServiceCollection` definition, but can always implicitly be resolved. This means that `IServiceScopeFactory` is about the one thing that you will have to explicitly cross wire by calling the `CrossWire<T>` extension method.

But you shouldn't inject `IServiceScopeFactory` in the first place, which brings me to your second question:

> should I use `IServiceScopeFactory` in such scenario

You are running a isolated operation on a background thread. In that case you should *not* create a framework's `IServiceScope` using the `IServiceScopeFactory`, because Simple Injector will create its own `IServiceScope` for you when you resolve from a Simple Injector `Scope`. In your background thread you should, therefore, do the following instead:

``` C#
Task.Run(async () =>
{
    using (var scope = AsyncScopedLifestyle.BeginScope(_container))
    {
        _container.GetInstance<IMyService>();
        // etc
    }
}
```
When the object graph for `IMyService` requires some framework component, that is resolved from the built-in configuration system (a.k.a. MS.DI), Simple Injector will—in the absence of a web request—automatically create a new `IServiceScope` instance using the framework's `IServiceScopeFactory` (by calling `ApplicationServices.GetRequiredService<IServiceScopeFactory>()`). From that `IServiceScope`, Simple Injector will pull in any required framework component.

This framework `IServiceScope` than becomes `Scoped` within the active Simple Injector `Scope`, and can even be resolved directly:

``` c#
using (SimpleInjector.Scope scope = AsyncScopedLifestyle.BeginScope(_container))
{
    // Same instance as Simple Injector uses to resolve framework components
    var serviceScope =
        _container.GetInstance<Microsoft.Extensions.DependencyInjection.IServiceScope>();
}
```

Disposing the Simple Injector `Scope`, will also automatically dispose the `IServiceScope`.

**Comment by thePmr** [comment]
Thank you for detailed response!

In your examples I need to have an instance of the container in controller. So, I assume that it is OK to inject it in constructor, right?

**Comment by dotnetjunkie** [comment]
> In your examples I need to have an instance of the container in controller. So, I assume that it is OK to inject it in constructor, right?

You need to be careful with that. You would typically only let you [Composition Root](https://freecontent.manning.com/dependency-injection-in-net-2nd-edition-understanding-the-composition-root/) have a dependency on your DI Container  because it would otherwise lead to the [Service Locator anti-pattern](https://freecontent.manning.com/the-service-locator-anti-pattern/).

I would, therefore, say that a more maintainable solution would be to the code that deals with resolving from the container and starting background operations, should be extracted from the controller, and possibly hidden behind an abstraction. The documentation contains [some information](https://simpleinjector.org/howto+multi-threading) about this.

**Comment by thePmr** [comment]
Thank you for the clarifications!
