### ISSUE TITLE
ASP.NET MVC integration: custom InstanceProducer needed for ViewPage injection?

### ISSUE THREAD

**Issue by Bouke** [simpleinjector/SimpleInjector#826]
When upgrading to v5 the most important change to our codebase is having to register all concrete types. I've read the reasoning behind this change and can agree with the reasoning. So I've set on a quest to find all concrete types missing a registration. However I think I'm now running into the [last bullet point](https://simpleinjector.readthedocs.io/en/latest/resolving-unregistered-concrete-types-is-disallowed-by-default.html) regarding generated view pages.

Say I'm using the following ViewPage:
```c#
public abstract class MyViewPage<TModel> : WebViewPage<TModel>
{
    [DependencyInjection]
    public MyDependency MyDependency { get; set; }
}
```

Where `DependencyAttribute` is used for property injection and `MyDependency` is registered:
```c#
container.Options.PropertySelectionBehavior = new DependencyInjectionAttributeBehaviour();
container.Register<MyDependency>();
container.Verify();
DependencyResolver.SetResolver(new SimpleInjectorDependencyResolver(container));
```
```c#
private class DependencyInjectionAttributeBehaviour : IPropertySelectionBehavior
{
    public bool SelectProperty(Type implementationType, PropertyInfo propertyInfo)
    {
        return propertyInfo.GetCustomAttributes(typeof(DependencyInjectionAttribute)).Any();
    }
}
```

Now when `ResolveUnregisteredConcreteTypes` is set to v5 behaviour (`false`), `MyDependency` is `null` and a NRE is thrown whenever my razor view tries to use it. `MyDependency` however is non-`null` when set to pre-v5 behaviour (`true`).

So first the `null` threw me off here, as `MyDependency` is a registered type. But I think the problem is with the view page itself: `ASP._Page_Views_Shared__TopMenu_cshtml`. It is not registered and therefor the container cannot resolve the view page, and something in ASP.NET MVC decides to new the view page itself, but doesn't know about property injection and hence my property is left at the default (`null`). I'm somewhat speculating here as I'm not familiar with the inner workings of ASP.NET MVC and SimpleInjector's MVC integration package.

So what I need (I think) is to implement an `InstanceProducer` that provides view page instances? I'm somewhat at a loss here as to how this should work, what safeguards to put in place etc. As it is quite a common theme for upgraders to v5, it would be great to have a reference implementation. Or maybe even, but I don't know whether that's possible, to ship a good producer tailored for view pages with the integration package?

**Comment by dotnetjunkie** [comment]
I will respond later to the question about InstanceProducers, but first, I'm very intrigued by your first issue. The exception message you are getting is misleading and this might be a bug. For some reason, however, I'm unable to reproduce this. What I'm getting is the following message:

> No registration for type MyViewPage<object> could be found. Make sure MyViewPage<object> is registered, for instance by calling 'Container.Register<MyViewPage<object>>();' during the registration phase. An implicit registration could not be made because Container.Options.ResolveUnregisteredConcreteTypes is set to 'false', which is now the default setting in v5. This disallows the container to construct this unregistered concrete type. For more information on why resolving unregistered concrete types is now disallowed by default, and what possible fixes you can apply, see https://simpleinjector.org/ructd.

Can you provide me with an minimal reprodible example?

**Comment by Bouke** [comment]
I've reproduced the issue from a new empty MVC project. I've build up the example commit by commit so you can easily follow along. When running, the [header on the homepage](https://github.com/Bouke/SimpleInjector826/blob/54cccac24de22e6ec61b45cd795c82557b4e02ac/SimpleInjector826/Views/Home/Index.cshtml#L6) provides a hint on whether the dependency was injected. The repository: https://github.com/Bouke/SimpleInjector826.

**Comment by dotnetjunkie** [comment]
Ah.. I think I see what's going on. The behavior you are seeing is 'by design'. As the page is not registered in Simple Injector, the call to `Container.GetService`, which the `SimpleInjectorDependencyResolver` does, returns `null`. This behavior is forced upon us by the `IDependencyResolver` abstraction. And because Simple Injector returns null, the WebViewPage is created by MVC itself, but it knows nothing about the property you want to have injected. That's why do you don't get an exception at all.

**Comment by dotnetjunkie** [comment]
The solution here is, therefore, to implement a custom `IViewPageActivator` and replace the default activator with your custom one:

``` c#
public sealed class SimpleInjectorViewPageActivator : IViewPageActivator
{
    private readonly Container container;
    private readonly ConcurrentDictionary<Type, InstanceProducer> producers =
        new ConcurrentDictionary<Type, InstanceProducer>();

    public SimpleInjectorViewPageActivator(Container container) => this.container = container;

    public object Create(ControllerContext controllerContext, Type type) =>
        this.producers.GetOrAdd(type, t => this.CreateProducer(t)).GetInstance();

    private InstanceProducer CreateProducer(Type type) =>
        Lifestyle.Transient.CreateProducer(type, type, this.container);
}
```

To replace the default MVC `IViewPageActivator` implementation, you can add your custom activator to Simple Injector:

``` c#
container.RegisterInstance<IViewPageActivator>(new SimpleInjectorViewPageActivator(container));
```

**Comment by Bouke** [comment]
That is indeed the solution to my problem, thank you so much!

Is this something you're considering to add to MVC integration package, or at least the docs? Because without this valuable insight I probably wouldn't have figured this out. Especially as there were no exceptions to go by.

**Comment by dotnetjunkie** [comment]
I was thinking about that actually. Including this in the MVC would be valuable.

**Comment by dotnetjunkie** [comment]
Please be aware that it still is important to register *all root types* explicitly in the container. The `SimpleInjectorViewPageActivator` might allow the creation of an unregistered type (which is important in this case because MVC derives a sub type from your ViewPage, which can't be registered up front), not registering your ViewPages in Simple Injector will blind its verification and diagnostic abilities. For instance, in case `MyDependency` is not registered, a lack of an explicit (closed-generic) registration for the view model will only cause an exception when your page is loaded, not during startup or inside an test.

In your case, however, the ViewPage is generic, this typically means your would register the type as follows:

``` c#
container.Register(typeof(MyViewPage<>));
```

Unfortunately, Simple Injector is unable to verify this root type, because it has no idea what actual closed versions you wish to create.

So instead, I'd advise to register (at least) one closed-generic version of this type in the container:

``` c#
container.Register<MyViewPage<Customer>>();
```

This allows Simple Injector to verify and diagnose this closed-generic version and in your case if the verification for this closed-generic type succeeds, it will for all other types as well. Of course this might not always be the case, for instance when the ViewPage has generic dependencies of its own (e.g. `ICommandHandler<T>`) or when the type contains static initialization using the generic type information. In such case it's better to register all needed closed-generic versions, which can typically be done using reflection.

**Comment by Bouke** [comment]
Thank you for the feedback, it has been a great help.

However note that `IViewPageActivator` is not responsible for creating Layout view page instances. I haven't found a way for injecting dependencies into Layouts. The instantiation stack trace looks like this:

```
>   MyWebProject.dll!MyWebProject.MyViewPage<object>.MyViewPage() Line 18 C#
    App_Web_25k1vt12.dll!ASP._Page_Views_Shared__Layout_cshtml._Page_Views_Shared__Layout_cshtml()  C#
    App_Web_25k1vt12.dll!__ASP.FastObjectFactory_app_web_25k1vt12.Create_ASP__Page_Views_Shared__Layout_cshtml()    C#
    System.Web.dll!System.Web.Compilation.BuildManager.CreateInstanceFromVirtualPath(System.Web.VirtualPath virtualPath, System.Type requiredBaseType, System.Web.HttpContext context, bool allowCrossApp)  Unknown
    System.Web.WebPages.dll!System.Web.WebPages.BuildManagerWrapper.CreateInstanceOfType<System.Web.WebPages.WebPageBase>(string virtualPath)   Unknown
    System.Web.WebPages.dll!System.Web.WebPages.VirtualPathFactoryManager.CreateInstanceOfType<System.Web.WebPages.WebPageBase>(string virtualPath) Unknown
    System.Web.WebPages.dll!System.Web.WebPages.WebPageBase.CreatePageFromVirtualPath(string virtualPath, System.Web.HttpContextBase httpContext, System.Func<string, bool> virtualPathExists, System.Web.WebPages.DisplayModeProvider displayModeProvider, System.Web.WebPages.IDisplayMode displayMode)   Unknown
    System.Web.WebPages.dll!System.Web.WebPages.WebPageBase.RenderPageCore.AnonymousMethod__0(System.IO.TextWriter writer)  Unknown
    System.Web.WebPages.dll!System.Web.WebPages.WebPageBase.Write(System.Web.WebPages.HelperResult result)  Unknown
    System.Web.WebPages.dll!System.Web.WebPages.WebPageBase.RenderSurrounding(string partialViewName, System.Action<System.IO.TextWriter> body) Unknown
    System.Web.WebPages.dll!System.Web.WebPages.WebPageBase.PopContext()    Unknown
    System.Web.Mvc.dll!System.Web.Mvc.ViewResultBase.ExecuteResult(System.Web.Mvc.ControllerContext context)    Unknown
```
