### ISSUE TITLE
Unexpectedly requiring ResolveUnregisteredConcreteTypes = true in WebApi (classic)

### ISSUE THREAD

**Issue by sgrassie** [simpleinjector/SimpleInjector#844]
After upgrading one of our Web Api classic apps to Simple Injector 5, I have a question regarding the sudden need I have to set `ResolveUnregisteredConcreteTypes  = true` when configuring the container, in order for it to successfully resolve a controller.

All our controllers inherit from a base class, which itself inherits from `ApiController`, and after upgrading to Simple Injector 5, I was presented with the classic "An error occurred when trying to create a controller of type 'FooView'". If I set RUCT to true, then it goes away. (Our controllers do not use the conventional 'Controller' suffix).

Here lies my confusion: I was under the impression that when configuring Simple Injector, `container.RegisterWebApiControllers(config);` would register the controllers automatically?

I'd like to try and understand what is happening before I upgrade some of our other apps to use SI 5.

Thanks!

**Comment by dotnetjunkie** [comment]
>  I was under the impression that when configuring Simple Injector, container.RegisterWebApiControllers(config); would register the controllers automatically?

It should. So this means that, for some reason, `RegisterWebApiControllers` does not register your controllers.

If this is the case, it's great that you're running into this exception, because it means that, up until now, not all controllers were registered, which gives you a false sense of security when calling `container.Verify()`.

Using only the information you gave me, however, it's unclear why `FooView` hasn't been registered by the Container. I need a full repro to examine this.

**Comment by sgrassie** [comment]
Sorry, this is my bad, I should have looked more closely at some of the changes which have been made in 5.x, before I blindly upgraded. You'd think after many years of doing this I'd know better by now :)

There is some internal framework code which involves using custom `IHttpControllerTypeResolver` and `IHttpControllerSelector` implementations, which get replaced in the `HttpConfiguration.Services`, and this always ran after SimpleInjector was configured. 

Ensuring that Simple Injector is configured _after_ the internal framework is bootstrapped resolves this situation.
