### ISSUE TITLE
Why has ExpressionBuiltEventArgs no readonly ImplementationType property?

### ISSUE THREAD

**Issue by GeraldLx** [simpleinjector/SimpleInjector#847]
I am currently experimenting with adding some monitoring to our codebase.

As a starting base I use the [interception extensions example](https://simpleinjector.readthedocs.io/en/latest/InterceptionExtensions.html).

Everything worked as expected until I stumbled at the first code relying on the types having specific custom attributes.
As the code is now confronted with a proxy not the real thing, this code does not work anymore.
Therefore I have to copy all custom attributes from the original type to my proxy.
I have an already working prototype, but it feels dirty.
To get the implementation type in the OnExpressionBuilt event handler, I currently use reflection to access the internal InstanceProducer property.
There must be a reason why this is not public. Is there a better way to achieve the desired result?

**Comment by dotnetjunkie** [comment]
> Everything worked as expected until I stumbled at the first code relying on the types having specific custom attributes.

This implies that your code is depending on the implementation itself instead of relying solely on the abstraction. Might it be that your code is tightly coupled?

> Is there a better way to achieve the desired result?

To answer that, I need a concrete example that demonstrates your problem.

**Comment by GeraldLx** [comment]
It took me some while to extract parts of our code into a simplyfied example.

Basically we have code relying on fixed interfaces, e.g. validation. But the actual implementation may vary between customers.

So we register concrete types multiple times for the same interface.

There is a factory resolving the right implementation. This factory shall not rely on concrete implementations therefore it needs some kind of logic to indentify the right one.

I decided to use an attribute for identification as the real system is not using a static bootstrapping mechanism as in the example. 

We write tests to verify that requirement and some of the implicit following consequences of this system, like having a default implementation and having not 2 types with the same attribute value.

In addition the constructor of the factory is written in a way that it "explodes" during the Verify call, if for whatever reason these tests did not work.

This system works quite well for some time now... until I started to experiment with monitoring interception. 

As written, I can solve this problem (as shown).

Of course I am open to better solutions for both use cases (the factory or the monitoring).

[InterceptionSample.zip](https://github.com/simpleinjector/SimpleInjector/files/5208659/InterceptionSample.zip)

**Comment by dotnetjunkie** [comment]
For completeness, I'd like to post the relevant part of your code, which is the `ArticleValidatorFactory` implementation:

``` c#
public sealed class ArticleValidatorFactory : IArticleValidatorFactory
{
    private readonly IDictionary<Customer, IArticleValidator> _validators;

    public ArticleValidatorFactory(IEnumerable<IArticleValidator> validators)
    {
        EnsureArg.IsNotNull(validators, nameof(validators));

        _validators = validators.ToDictionary(
            v => v.GetType().GetCustomAttribute<CustomerAttribute>().Customer,
            v => v);
    }

    IArticleValidator IArticleValidatorFactory.GetValidator(Customer customer)
    {
        if (_validators.TryGetValue(customer, out var validator))
        {
            return validator;
        }

        if (_validators.TryGetValue(Customer.Default, out var defaultValidator))
        {
            return defaultValidator;
        }

        throw new InvalidOperationException($"No validator found for {customer}!");
    }
}
```

The constructor of the `ArticleValidatorFactory` is where you have a problem, because the injected `IArticleValidator` instances are intercepted, which makes it impossible to get to the implementations.

Let met start by saying that there is *nothing wrong* with your design. The tight coupling I was earlier reffering to only exists within the `ArticleValidatorFactory`. I consider this factory to be part of your application's [Composition Root](https://freecontent.manning.com/dependency-injection-in-net-2nd-edition-understanding-the-composition-root/).

You can solve this problem by making use of Simple Injector's Dependency Metadata feature. That feature lets you get access to both the instance as the implementation type. You can change your constructor to the following to:


``` c#
public ArticleValidatorFactory(
    IEnumerable<SimpleInjector.DependencyMetadata<IArticleValidator>> validators)
{
    EnsureArg.IsNotNull(validators, nameof(validators));

    _validators = validators.ToDictionary(
        v => v.ImplementationType.GetCustomAttribute<CustomerAttribute>().Customer,
        v => v.GetInstance());
}
```

This does mean, though, that your factory implementation requires a dependency on Simple Injector. This, however, shouldn't be a problem because, as I already noted, the factory is part of your Composition Root. You might want to move the implementation closer to the startup code of your application, in case its now located in a different assembly.

In case moving is not an option, there are other options (such as sub typing) to keep the dependency to Simple Injector inside the Composition Root. If you're interested, I can cook up an example for you.
```
