### ISSUE TITLE
ActivationException for a Per Web Request item inside a Parallel.For loop

### ISSUE THREAD

**Issue by simmohall** [simpleinjector/SimpleInjector#85]
Hi folks,
Sorry if this is a basic question, but still pretty new to these concepts.
I've managed to hook up an existing web forms system with simpleinjector, but just ran into this issue. The majority of the pages work nicely following the web forms integration. But just had this error on a page and couldn't find anything specifically.

"ActivationException
The registered delegate for type IQueryHandler<IsElementInCategoryQuery, Boolean> threw an exception.
The 'EFContext' is registered as 'Web Request' lifestyle, but the instance is requested outside the context of a web request."

Looking into the application code the only thing that stuck out was that it was executing inside a Parallel.For loop.

Is this something that I can easily overcome? Should I not be making use of the injected services with a Parallel.For loop? Or do I need to do additional registration with different scope?

Any pointers would be much appreciated!

Thanks,
Simon

**Comment by dotnetjunkie** [comment]
If you execute code inside a `Parallel.For` you are basically running on a background thread. So there is no active `HttpContext.Current`, which means that if you try to resolve object graphs that contain instances that are registered as per-web-request, this won't work; there is no web request.

It's hard to say exactly what you should do, because it depends a lot on the exact details, but here is some guidance:
 - Don't move resolved dependencies from thread to thread. Request dependencies again at the start of a new thread from your composition root / container, so that the composition root is in control of when to supply you with a new dependency.
 - Try to extract parallelization constructs that affect dependencies into a service that you implement inside the composition root. This way the application code is unaware of any such optimizations. This makes your application code clean and centralizes this knowledge about handling of threads in one single place in the application.
 - Take a look at the [How To Work with dependency injection in multi-threaded applications](https://simpleinjector.readthedocs.org/en/latest/howto.html#multi-threaded-applications) guidance in the documentation.

I hope this helps.

**Comment by simmohall** [comment]
Ok great - clear now.

Thanks
