### ISSUE TITLE
Provided SignalR integration doesn't work

### ISSUE THREAD

**Issue by lneshev** [simpleinjector/SimpleInjector#851]
The provided integration for SignalR, described here: https://github.com/simpleinjector/SimpleInjector/issues/631, doesn't seem to work.

I created two projects in two repos:
- ASP.NET Core 3.1 Web API: https://github.com/lneshev/TestSignalRWebApi
- React Web App: https://github.com/lneshev/TestSignalRWebApp

Versions I used (and tried): ASP.NET Core 3.1, SimpleInjector: from 4.9.1 to 5.0.0, @microsoft/signalr: 3.1.5

My problem is that the connection is established, but when I send a message from the server to the clients, the clients do not receive anything. If I remove just this line of code: ".AddControllerActivation();", it starts working, but then a controller might throw an exception if there is a dependency just in SimpleInjector container, but not in .NET Core's DI container.

@dotnetjunkie (or anybody), could you assist?

**Comment by dotnetjunkie** [comment]
I don't have the time to run and debug your provided example, my apologies for that. But there is one piece of code that strikes my as peculiar, which might be part of the problem, which is the line of code where you call `BuildServiceProvider` ([here](https://github.com/lneshev/TestSignalRWebApi/blob/master/TestSignalRWebApi/Infrastructure/SimpleInjectorConfiguration.cs#L45)):

``` c#
services
    .BuildServiceProvider(validateScopes: true)
     .UseSimpleInjector(container);
```

This call might have unintented consequences, because you are building a service provider that will *not* be used by ASP.NET Core itself, while you instruct Simple Injector to use this built service provider. This will cause trouble because:

* This second service provider will have its own cache of singleton instances, not shared from the singleton framework instances that ASP.NET Core uses. Simple Injector will typically use this instance when resolving singleton framework types.
* Within a web request (using a typical Simple Injector configuration), Simple Injector will pull in the Service Provider from the active HttpContext. This will be the framework-built version -- not your second provider. This will resolve scoped and transient instance from the framework's service provider, while those services might also depend on singletons; those are resolved from that service provider as well. This means that these are other instances than the singletons you reference directly.
* But still, a single web request could get 2 scoped instances for the same ASP.NET Core service: one for the provider ASP.NET Core uses, and one for this provider used by Simple Injector.

The solution is to *not* build your own Service Provider. You should, therefore, *remove* the call to `BuildServiceProvider` and `UseSimpleInjector` from your `SimpleInjectorConfiguration` class and instead follow the Simple Injector documentation, which explains you should call `UseSimpleInjector`  inside the `Startup.Configure` method (without calling `BuildServiceProvider`).

If this doesn't solve (all) your problems, please let me know. If possible, post exception details of all exceptions you get.

**Comment by lneshev** [comment]
Thank you. I think this fixed the issue. I'll keep testing.
I also commended the code from https://github.com/simpleinjector/SimpleInjector/issues/631 in my example and everything seems to be working. Then I wonder, why do we need to add this integration?

**Comment by dotnetjunkie** [comment]
> Then I wonder, why do we need to add this integration?

Can you elaborate? What do you mean by "this integration?"
