### ISSUE TITLE
Separate scopes for each element of container.GetAllInstances

### ISSUE THREAD

**Issue by gitcob** [simpleinjector/SimpleInjector#853]
I'm currently refactoring some event handling code. I have an interface `IIntegrationEventHandler<TEvent>` with a simple (async) "Handle" method, and for each event type there can be any number of handler implementations.

I registered them using `container.Collection.Register(typeof(IIntegrationEventHandler<>), integrationEventHandlerTypes)`. With some minimal reflection magic, it was pretty easy to use Simple Injector to create an async scope, call `container.GetAllInstances(eventHandlerType)` and then issue the event to each one. 

I'm now considering changing the behavior a bit, and giving each handler its own async scope - because for integration events, I don't think individual handlers should share any (non-singleton) data with each other just because they happen to be handling the same event. Especially since I'm not controlling the order in which they are handling the event. In fact, I'd like to execute them concurrently, which, if I understand correctly, would not work very well with an async scope.

So I'd like to have a new scope for each instance. Unfortunately I don't see how - I can't resolve individual elements of a collection, only all of them at once. The closest I could get would be to call GetAllInstances, count how many elements I get, throw all but the first one away, then call it *again*, but this time throw away all except for the second, and so on. But unless there is some serious magic in that IEnumerable, I'm assuming that all instances along with all their dependencies will be created every time, even if I do something like Skip() to skip the first few and then stop enumerating after taking one element.

Is there some solution I'm missing? Or would it be possible to implement one, like GetAllInstancesWithScopes or something?

**Comment by dotnetjunkie** [comment]
With Simple Injector, collections are streams. This means that elements of an injected collection are not populated all at once, but at demand. This gives endless possibilities. For instance when it comes to scoping.

When it comes to giving each collection dependency it's own scope, there are two options.

Option 1 requires to enumerate the collection's `Enumerator`. Calling `Enumerator.Current` under the covers calls `InstanceProducer.GetInstance()`. In other words, this triggers a resolve. Here's an example:

``` c#
class Composite<TEvent> : IIntegrationEventHandler<TEvent>
{
    private readonly Container container;
    private readonly IEnumerable<IIntegrationEventHandler<TEvent>> handlers;

    public async Task Handle(TEvent e)
    {
        using (var enumerator = this.handlers.GetEnumerator())
        {
            while (enumerator.MoveNext())
            {
                using (AsyncScopedLifestyle.BeginScope(this.container))
                {
                    IIntegrationEventHandler<TEvent> handler = enumerator.Current;

                    await handler.Handle(e);
                }
            }
        }
    }
}
```
Option 2 requires Simple Injector v5's new metadata feature, but simplifies your use case significantly:

``` c#
class Composite<TEvent> : IIntegrationEventHandler<TEvent>
{
    private Container container;
    private IEnumerable<DependencyMetadata<IIntegrationEventHandler<TEvent>>> handlers;

    public async Task Handle(TEvent e)
    {
        foreach (var metadata in this.handlers)
        {
            using (AsyncScopedLifestyle.BeginScope(this.container))
            {
                IIntegrationEventHandler<TEvent> handler = metadata.GetInstance();

                await handler.Handle(e);
            }
        }
    }
}
```

Both options run the handlers sequentially; not parallel. Running handlers parallel is another ballgame of its own. It's certainly possible, and as long as you're not interested in guaranteed execution of handlers, you can simply do the following:

``` c#
class Composite<TEvent> : IIntegrationEventHandler<TEvent>
{
    private Container container;
    private IEnumerable<DependencyMetadata<IIntegrationEventHandler<TEvent>>> handlers;

    public Task Handle(TEvent e) =>
        Task.WhenAll(this.handlers.Select(metadata => this.AsTask(metadata, e)).ToArray());

    private async Task AsTask(
        DependencyMetadata<IIntegrationEventHandler<TEvent>> metadata, TEvent e)
    {
        using (AsyncScopedLifestyle.BeginScope(this.container))
        {
            IIntegrationEventHandler<TEvent> handler = metadata.GetInstance();

            await handler.Handle(e);
        }
    }
}
```

When it comes to event handlers, you typically want to ensure that all handlers run to completion, event though they might fail for the first time, especially because any parallel operations can't run in the same transaction. This means you have to implement retry. But what will you do when it is still failing after 5 retries. Will you continue retrying when the main operation finishes? And what if the process gets recycled? This means you will have to start thinking about using durable queues, but in this case, connecting everything together with Simple Injector will not be your main issue any longer. Although you can implement durable queues yourself (as I did myself multiple times), it might be better to start using frameworks such as NServiceBus or MassTransit.

I hope this helps.

**Comment by gitcob** [comment]
This is pretty amazing! Just when I thought Simple Injector could not surprise me anymore. Thanks for the detailed reply, that definitely helps!

As for the parallel event handlers, I'm currently exploring a solution can be configured either way, including durable queues (it's the first time I'm implementing that, and to me that's just how I learn, gotta make it myself...). I'll have to deal with that optimistic locking problem anyway.

By the way, kudos for being an exemplary project maintainer! And the book is pretty great too!

**Comment by dotnetjunkie** [comment]
I updated the documentation and added [a new section](https://simpleinjector.readthedocs.io/en/latest/lifetimes.html#collections-and-lifetime-management) describing how to implement this use case.
