### ISSUE TITLE
Context-based injection reports service type as implementation type when used with property injection.

### ISSUE THREAD

**Issue by fsoikin** [simpleinjector/SimpleInjector#86]
In the below code, the `RegisterWithContext` callback receives `A` as `ctx.ImplementationType`, whereas I would expect it to be `C`, because that's the implementation type.

Note that this only works in combination with property injection. If I change class `C` to use constructor injection, the callback will correctly see that `ctx.ImplementationType == typeof(C)`.

```
	static partial class Program {
		static void Main() {

			var c = new Container(new ContainerOptions { PropertySelectionBehavior = new Props() } );
			c.Register(typeof(A), typeof(C));
			c.RegisterWithContext( ctx => {
				Console.WriteLine( "Injecting B into " + ctx.ImplementationType );
				return new B();
			} );

			c.GetInstance<A>(); // Prints "Injecting B into A" instead of "Injecting B into C"
		}
	}

	interface A { }
	class B { }
	class C : A { public B b { get; set; } }

	class Props : IPropertySelectionBehavior
	{
		public bool SelectProperty( Type serviceType, PropertyInfo propertyInfo ) {
			return true;
		}
	}
```

**Comment by dotnetjunkie** [comment]
Thanks for reporting this. This bug is caused by a limitation in the `DependencyContextRewriter.ImplementationType` property of the `RegisterWithContext` example in the documentation. That code is unable to detect the implementation type in case the consuming type gets properties injected into, because it naively expects a `NewExpression` as root node in the expression tree, while in case of property injection, the expression is wrapped with a 'property initializer' delegate that wraps the `NewExpression`.

What you are seeing is one of the reasons why the `RegisterWithContext` extension method is provided as documentation example instead of being part of the core library. It contains several limitations and it uses a user supplied delegate that can create the type, making the construction unverifiable by Simple Injector and its diagnostic sub system.

With Simple Injector v3, there will be built-in support for contextual injection using the `RegisterConditional` overloads. These overloads do not contain the bug as described above. The `RegisterWithContext` extension method example will be removed from the v3 documentation, because the use of `RegisterConditional` is preferred. Do note that `RegisterConditional` does not change existing expression trees. Instead it is completely integrated with the core library, removing the limitations and bugs that the `RegisterWithContext` extension method has.

Because of this, I decided to not fix the `RegisterWithContext` example in the 2.8 documentation.

Still I would like to thank you for taking the time to report this. I added a new unit test for this particular case to verify that v3's `RegisterConditional` methods are not affected by this bug and the test ensures that they will never get affected by this bug in the future.
