### ISSUE TITLE
Would it be possible to regard factory-created InstanceProducers as childs of that factory?

### ISSUE THREAD

**Issue by AroglDarthu** [simpleinjector/SimpleInjector#865]
Sometimes it is handy to create a factory that is able to create dependencies based on runtime parameters. Often the complete set of these dependencies is known beforehand. So what we do is:
1. Register a factory, i.e. `container.Register<IMyFactory, MyFactory>`
2. Create a dictionary of `TKey` and `InstanceProducer`
3. Have the `factory.Create(TKey key)` method use the corresponding `InstanceProducer` to return the correct dependency.

Now when we ask the container for all root registrations, all of these factory bound `InstanceProducer`s are returned as well. It feels more concise that these registrations would _live_ under the factory registration instead.

I don't think it is currently possible to achieve this, so my feature request is:
Would it be possible to have Simple Injector regard these registrations as childs of the factory registration as mentioned in 1)?

**Comment by dotnetjunkie** [comment]
`InstanceProducer` instances can't be hid from the list returned from `GetCurrentRegistrations()`.

But... if that's of any help, you can remove them from the list of _root registrations_ (returned from `Container.GetRootRegistrations()`) by hooking them to the factory as _known registration_.

The following example demonstrates this:

``` c#
var container = new Container();
container.Options.DefaultScopedLifestyle = new AsyncScopedLifestyle();

// Create the child registrations of the factory
var loggers = new Dictionary<int, InstanceProducer<ILogger>>
    {
        { 0, Lifestyle.Scoped.CreateProducer<ILogger, ConsoleLogger>(container) },
        { 1, Lifestyle.Transient.CreateProducer<ILogger, NullLogger>(container) }
    };

// Register the factory
container.RegisterInstance<IMyFactory>(new MyFactory(loggers));

// Let the diagnostic sub system know about the factory's childs by adding them as
// known relationships. The only way to (currently) do this is by using the
// ExpressionBuilt event. It allows the KnownRelationships of the Registration to
// be updated.
container.ExpressionBuilt += (s, e) =>
{
    if (e.RegisteredServiceType == typeof(IMyFactory))
    {
        foreach (var dependency in loggers.Values)
        {
            // HACK: Even though MyFactory is a Singleton, in the KnownRelationship
            // we state it is Transient. This prevents the Diagnostic Sub System to
            // (incorrectly) trip as it expects the dependency to be kept alive by
            // the consumer, which isn't the case with the factory.
            e.KnownRelationships.Add(
                new KnownRelationship(
                    typeof(MyFactory),
                    Lifestyle.Transient,
                    dependency));
        }
    }
};

container.Verify();

Assert.AreEqual(3, container.GetCurrentRegistrations().Length);
Assert.AreEqual(1, container.GetRootRegistrations().Length);
```

Perhaps this helps?

**Comment by AroglDarthu** [comment]
Awesome! Never used these events, yet...
The API documentation on the `ExpressionBuilt` event warns about thread-safety. Should I safeguard the above example from being executed multiple times?

**Comment by dotnetjunkie** [comment]
> Should I safeguard the above example from being executed multiple times?

Typically, an `ExpressionBuilt` event will go off once, but there is no protection to prevent is goes off twice in case of multi-threading. That's why this warning exists. So the code you are running inside your `ExpressionBuilt` event should be thread safe. The calls you're making to the Simple Injector API from within `ExpressionBuilt`, however, will (mostly) be thread safe. 

In this case, the only thing that is happening is the addition to the `KnownRelationships` collection. In the unlikely case that this event is called in parallel, the known relationships will be added twice to the `Registration`. `Registration`, however, de-duplicates `KnownRelationship` instances (`KnownRelationship` overrides `Equals`).

There are cases, however, where special care should be taken, for instance when implementing some custom cache. In that case the cache should likely be thread safe.

I must admit that the fact that these events can run in parallel, can certainly complicate things and might certainly not be a design that makes things "simple." I apologize for this. Fortunately, this is not an API that is used often.
