### ISSUE TITLE
Implementations with both resolvable dependencies and concrete parameters

### ISSUE THREAD

**Issue by jtheisen** [simpleinjector/SimpleInjector#886]
This is a question that likely concerns all IoC containers and I admit I'm still new to following the whole DI paradigm.

Take this class that is constructed from some service as well as some piece of configuration:

``` c#
public record FooConfig(...);

public class Foo
{
    public Foo(IService service, FooConfig config) { ... }
}
```

Let's say I want to construct multiple `Foo`s from an array `FooConfig[] configs` but with the same `IService`.

So let's say I register an implementation for `IService` but not `FooConfig` and ideally, I would then want to be able to resolve a factory of type `Func<FooConfig, Foo>` with Simple Injector understanding that this works because the only missing dependency is given as a factory parameter.

But such factories can't be resolved by default and [the generic factory example in the docs](https://simpleinjector.readthedocs.io/en/latest/howto.html#register-factory-delegates) only talks about the simple case where no additional parameters are required, and I don't think that can be generalized with the existing API.

It seems that I have to manually write a factory

``` c#
public class FooFactory
{
    IService service;
    
    public FooFactory(IService service)
    {
        this.service = service;
    }
    
    public Foo CreateFoo(FooConfig config) => new Foo(service, config);
}
```

and then use that.

But that code doesn't add any information on top of what the types imply anyway, and whenever a resolvable dependency on `Foo` is changed, I need to change the factory too. Isn't that the kind of boilerplate we use an IoC container for to avoid?

So my questions are:

- Am I missing something feature-wise?
- Can this be build on top of Simple Injector after all?
- Has this been discussed before under a certain buzzword I can search for?
- Are there other IoC containers that can do this?

**Comment by dotnetjunkie** [comment]
This exact scenario is likely not easy to configure with Simple Injector, without either using a factory, or changing the design. Most things can actually be built on top of the existing library, but the question is whether you should do this.

Your example, unfortunately, is very generic in nature. This makes it impossible for me to review the design. This is useful, because it could be that there are design imperfections that, when improved, also solved your registration issues.

Would you mind providing me with the actual design. I'm not interested in seeing *all* your code, but there are a few things that are really useful in understanding what you're building, and why you need this design, such as:
* Actual interface and class names (especially, what is `Foo`)
* Complete constructor signatures (including perhaps dependency properties that you currently removed)
* What kind of configuration values and changes do you put in `FooConfig`?
* Where does this array of `FooConfig` objects come from and how volatile is it? Is it loaded from the app.config and does it only change during an app restart? Is it configuration data coming from the database and might it change while the application is running? Is it sent by a user in a (web) request, and might it change on each request?
* How is Foo used? Can you show some code of `Foo`'s consumer(s)? Is it injected as a collection?
* Can you show a [Pure DI](https://blog.ploeh.dk/2014/06/10/pure-di/) version of the (relevant) parts of the object graphs you want to build. In other words, demonstrate how you wish your classes are composed by showing plain old C# code with `new` statements, e.g.
  ``` c#
  var service = new MyService();
  new MyController(new[]
  {
      new Foo(service, new settings[0]),
      new Foo(service, new settings[1]),
      new Foo(service, new settings[2]),
  })
   ```

Hopefully this gives me a clearer picture of what it is you are trying to achieve, which would hopefully allow me to provide you with the way to configure this, or otherwise suggest you with change in design that would allow you to easily configure this.

**Comment by jtheisen** [comment]
Thanks for responding so quickly.

`Foo` stands for a class in my app that is parameterized by a connection string to a database and a name. Those come from a configuration file and don't change at run time. Other than that, it is similar to an application root, ie. if I had only one of those I'd just call it the application root and it would be a singleton.

The single service is meant to be a representative for all the services that the root may need.

The whole thing is a web application and requests are delegated to those roots by their name. The delegation logic would be in a class that would need to depend on a collection of those roots.

The sample code you gave is just what I meant.

All that being said, I'm more motivated by curiousity and getting a feel for the ups and downs of using IoC containers in general and SimpleInjector in particular than just somehow working around a problem in this instance only.

So as soon as you think you've given me all you have to say on the matter, feel free to close this question - you give awesome support and I don't want to abuse that.

**Comment by dotnetjunkie** [comment]
In this comment, I'll go into two possible ways to wire things up with Simple Injector. In a future comment I'll try to say something about the ups and downs of using DI Containers.

Given the Pure DI code:

``` c#
var service = new MyService();
new MyController(new[]
{
    new Foo(service, new settings[0]),
    new Foo(service, new settings[1]),
    new Foo(service, new settings[2]),
})
```

There are several ways to register this with Simple Injector.

One option is to register each `Foo` using a delegate, where `Foo` is created manually, where its `IService` is resolved from the container. For instance:

``` c#
var configs = new[] { new FooConfig("A"), new FooConfig("B"), new FooConfig("C") };
container.Register<MyController>();
container.Register<IService, MyService>();

foreach (var config in configs)
    container.Collection.Append(
        () => new Foo(container.GetInstance<IService>(), config),
        Lifestyle.Transient);
```

You would typically apply a similar solution when using different DI Containers. Most DI Containers will require the use of delegates in order to do this.

This method does, however, prevent the use of Auto-Wiring and does not allow Simple Injector to diagnose the relationship between `Foo` and `IService`. You can enable both Auto-Wiring and diagnostics, but this does require adding some new types to your [Composition Root](https://freecontent.manning.com/dependency-injection-in-net-2nd-edition-understanding-the-composition-root/). For instance:

``` c#
public interface IConfigWrapper { FooConfig Config { get; } }

// A generic version of Foo.
public class Foo<TConfig> : Foo where TConfig : IConfigWrapper
{
    public Foo(IService service, TConfig config) : base(service, config.Config) { }
}

// Type per configuration
public record FooConfigA(FooConfig Config) : IConfigWrapper { }
public record FooConfigB(FooConfig Config) : IConfigWrapper { }
public record FooConfigC(FooConfig Config) : IConfigWrapper { }
```

Using this extra type information, you can now make the following registrations:

``` c#
container.Register<MyController>();
container.Register<IService, MyService>();

container.RegisterInstance(new FooConfigA(new FooConfig("A")));
container.RegisterInstance(new FooConfigB(new FooConfig("B")));
container.RegisterInstance(new FooConfigC(new FooConfig("C")));

container.Collection.Append<Foo, Foo<FooConfigA>>();
container.Collection.Append<Foo, Foo<FooConfigB>>();
container.Collection.Append<Foo, Foo<FooConfigC>>();
```

Simple Injector works best when it can match on exact types. In this case, you are making three registrations of `Foo<T>`, where each `T` is different. The `T` refers to the typed configuration object, which is also the constructor argument. So this way, Simple Injector can map `FooConfigA` to `Foo<FooConfigA>`. The constructor of `Foo<FooConfigA> unpacks the `FooConfigA` and sends the wrapped `FooConfig` to the base constructor, which is the constructor of (the ungeneric) `Foo`.

**Comment by dotnetjunkie** [comment]
>  I'm more motivated by curiousity and getting a feel for the ups and downs of using IoC containers in general and SimpleInjector in particular than just somehow working around a problem in this instance only.

There's a lot written about this, which I won't repeat:

* [When to use a DI Container](https://blog.ploeh.dk/2012/11/06/WhentouseaDIContainer/) by Mark Seemann
* [When should you use a container?](https://blog.simpleinjector.org/2015/12/when-should-you-use-a-container/) by me, which is written from the context of Simple Injector
* In [Section 12.3](https://livebook.manning.com/book/dependency-injection-principles-practices-patterns/chapter-12/section-12-3?) of [Dependency Injection Principles, Practices, and Patterns](https://mng.bz/BYNl), Mark and I spend 7 pages on this topic.

**Comment by jtheisen** [comment]
Ok, thanks for your time. I'm closing this now.
