### ISSUE TITLE
How to use SimpleInjector to handle ServiceFilters's DI in ASP.NET 5 (vnext)?

### ISSUE THREAD

**Issue by Asshiah** [simpleinjector/SimpleInjector#89]
Hello,

I am currently using SimpleInjector as my DI container for an application based on ASP.NET 5 (vnext).

The example provided in issue #41 as to how to make it work is working really great for me so far.

At least for controllers.

I would like to use simple injector for `ServiceFilters` too.

For instance, I have defined a `LogFilter` that internally uses a `LogService` that is registered in Simple Injector's container. I want to use this `LogFilter` with a `ServiceFilter` like this:

``` c#
[ServiceFilter(typeof(LogFilter))]  
[HttpGet("")]
public IEnumerable<Item> Get()
{
    return this.repository.GetAll();
}
```

I need the DI to be resolved with SimpleInjector as the `LogService` is also used in other parts of my application and thus registered with SimpleInjector. As this service should be Singleton, I do not want to register the same service twice, once with the native DI container, once with SimpleInjector's container.

How can I specify ASP.NET 5 Service Filters to use Simple Injector's container for DI?

Thanks in advance for any insights.

**Comment by dotnetjunkie** [comment]
The use of the `ServiceFilterAttribute` in ASP.NET 5 is a bit problematic, because it statically depends on an existing `IServiceProvider` that is supplied by the runtime. To make this work you should either:
 - create your own attribute that works like the `ServiceFilterAttribute` but instead calls into Simple Injector,
 - replace ASP.NET's default `IServiceProvider` (but that would lead us again in the rabbit hole as described in #41), 
 - or you should stay away from using the `ServiceFilterAttribute`.

The last option seems weird, but is actually quite a good solution, because by marking your code with `[ServiceFilter(typeof(LogFilter))]`, you still make your controller statically dependent on the logging cross-cutting concern and on one particular implementation. This is a violation of the Dependency Inversion Principle and can cause maintainability problems in your application, simply because later on you might need to make sweeping changes throughout your application.

Instead, the use of [passive attributes](http://blog.ploeh.dk/2014/06/13/passive-attributes/) makes much more sense. Passive attributes are just attributes with data and no behavior, and an example of how to hook this into both the 'old' Web API and MVC and the new ASP.NET 5 pipeline can be found [here](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=98).

**Comment by Asshiah** [comment]
Thank you very much for this detailed answer and the links!
This was quite instructive!

I agree with your statement that using ServiceFilters make our controllers dependent on particular implementations of our cross-cutting concerns. This should be avoided for maintainability reasons.

Thus, I opted for the third option and followed the approach presented in your blog article.

Thank you for your time and your great work on this DI Framework!

**Comment by dotnetjunkie** [comment]
Since `ServiceFilterAttribute` is tightly coupled to the built-in configuration system, using it while resolving Simple Injector-registered filters requires the use of a wrapper object. For instance:

``` c#
[ServiceFilter(typeof(SimpleInjectorFilterWrapper<LogFilter>))]
[HttpGet("")]
public IEnumerable<Item> Get()
{
    return this.repository.GetAll();
}
```

This wrapper can be implemented as follows:

``` c#
public sealed class SimpleInjectorFilterWrapper<TFilter> : IFilterFactory
    where TFilter : class, IFilterMetadata
{
    private readonly Container container;
    public SimpleInjectorFilterWrapper(Container container) =>
        this.container = container;
    public bool IsReusable { get; }
    public IFilterMetadata CreateInstance(IServiceProvider serviceProvider) =>
        this.container.GetInstance<TFilter>();
}
```

And it must be registered as follows:

``` c#
services.AddSingleton(typeof(SimpleInjectorFilterWrapper<>));
```

Notes:

* Make sure you register the filter itself in Simple Injector, e.g. `container.Register<LogFilter>()`.
* This wrapper works with both `[ServiceFilter]` and `[TypeFilter]` but does not support supplying `Arguments` to the `TypeFilter`.
