### ISSUE TITLE
Use UseServiceProviderFactory or IControllerActivator?

### ISSUE THREAD

**Issue by aa-infr** [simpleinjector/SimpleInjector#892]
I've seen people using `UseServiceProviderFactory` like in the following code

``` c#
public static IHostBuilder CreateHostBuilder(string[] args)
{
    var container = new Container();

    return Host.CreateDefaultBuilder(args)
        .UseServiceProviderFactory(context => new DryIocServiceProviderFactory(container))
        .ConfigureWebHostDefaults(webBuilder =>
....
```

but I've also seen people using `IControllerActivator` like in the following code

``` c#
public void ConfigureServices(IServiceCollection services)
{
    var controllerActivator = new CommerceControllerActivator(
        configuration: new CommerceConfiguration(
            connectionString: this.Configuration.GetConnectionString("CommerceConnectionString"),
            productRepositoryTypeName: appSettings.GetValue<string>("ProductRepositoryType")));

    services.AddSingleton<IControllerActivator>(controllerActivator);
}
...
public class CommerceControllerActivator : IControllerActivator
{
    private readonly CommerceConfiguration configuration;

    // Singletons
    private readonly IUserContext userContext;

    public CommerceControllerActivator(CommerceConfiguration configuration)
    {
        if (configuration == null) throw new ArgumentNullException(nameof(configuration));

        this.configuration = configuration;

        // Create singletons
        this.userContext = new AspNetUserContextAdapter();
    }

    public object Create(ControllerContext context) => 
        this.Create(context.ActionDescriptor.ControllerTypeInfo.AsType());

    public void Release(ControllerContext context, object controller) =>
        (controller as IDisposable)?.Dispose();

    public Controller Create(Type type)
    {
        // Create Scoped components
        var context = new CommerceContext(this.configuration.ConnectionString);

        // Create Transient components
        switch (type.Name)
        {
            case nameof(HomeController):
                return new HomeController(
                    new ProductService(
                        this.CreateProductRepository(context),
                        this.userContext));

            //case nameof(AccountController):
            //    return new AccountController(...);

            //case nameof(UserController):
            //    return new UserController(...)

            //case nameof(LoginController):
            //    return new LoginController(...);

            default: throw new InvalidOperationException($"Unknown controller {type}.");
        }
    }

    // --- Start code Listing 5.16 ----
    private IProductRepository CreateProductRepository(CommerceContext context) =>
        (IProductRepository)Activator.CreateInstance(this.configuration.ProductRepositoryType, context);
    // --- End code Listing 5.16 ----
}
```

What is the difference between the two?

**Comment by dotnetjunkie** [comment]
Your first listing:

* Uses a DI Container
* Uses ASP.NET Core's [conforming container](https://blog.ploeh.dk/2014/05/19/conforming-container/) model.

Your second listing:

* Applies [Pure DI](https://blog.ploeh.dk/2014/06/10/pure-di/)
* Replaces just one factory abstraction (the `IControllerActivator`) provided by ASP.NET Core, because the code is only interested to intercept the creation of Controller classes (with their dependencies).

**Comment by aa-infr** [comment]
Hi Steven,

Are you the author of the book Dependency Injection Principles, Practices, and Patterns? Great honour to meet you here.

Like you are mentioning the second listing is using pure Pure DI (it is an example of the book)
But I wonder with the IControllerActivator you could use also a container or not?
In most applications (at least in my application) you only need controllers.
So I don't understand when you should use the first code listing with UseServiceProviderFactory?

**Comment by dotnetjunkie** [comment]
> Are you the author of the book Dependency Injection Principles, Practices, and Patterns?

Yes, I am.

> But I wonder with the IControllerActivator you could use also a container or not?

Certainly. As a matter of fact, this is exactly how the Simple Injector integration works. It implements a custom `IControllerActivator` and when using the integration package, Simple Injector replaces the default controller activator.

> So I don't understand when you should use the first code listing with UseServiceProviderFactory?

When you want to use a DI Container (other than the built-in MS.DI container), Microsoft’s standard guidance is to completely replace that built-in Container with your custom one. There are pros and cons to this idea; Both Mark and I blogged about the negative consequences of this model, so I won’t repeat that here:
* [Conforming Container](https://blog.ploeh.dk/2014/05/19/conforming-container/)
* [What’s wrong with the ASP.NET Core DI abstraction?]( https://blog.simpleinjector.org/2016/06/whats-wrong-with-the-asp-net-core-di-abstraction/)

Downside of *not* replacing the built-in Container is that this can be more complicated to implement, but that is especially because Microsoft completely focused on this new Conforming Container model, causing its developers to forget defining proper abstractions.

**Comment by aa-infr** [comment]
I've created a slimmed down version of an ASP.NET core api application which uses a framework.
[SampleDI](https://github.com/aa-infr/SampleDI)

This application is using the _UseServiceProviderFactory_ method which is not probably the best way.
If I'm correct you prefer more implementing _IControllerActivator_.

With _UseServiceProviderFactory_ I don't think you replace the built-in container from Microsoft because the services collection still contains 83 registrations related to Microsoft stuff.
![image](https://user-images.githubusercontent.com/78545777/107389721-4f031300-6af7-11eb-9cc3-d18cc2498f47.png)


The core piece of the implementation of a DI container you can find here:
![image](https://user-images.githubusercontent.com/78545777/107390174-b91bb800-6af7-11eb-90ea-ca80dbc3f6b5.png)

But if you want to replace this with the IControllerActivator, I don't see how we can replace the different LoadModules.
These LoadModules are belonging to the framework, but I have a suspicion that it is not good that the client (project Api) needs to take care these registrations which are belonging to the framework. 

So I'm struggling how to implement this correctly?

**Comment by dotnetjunkie** [comment]
> With UseServiceProviderFactory I don't think you replace the built-in container from Microsoft because the services collection still contains 83 registrations related to Microsoft stuff.

That assumption is incorrect. In your example, the built-in container is replaced with DryIoc. In that case, however, DryIoc gets populated with the `IServiceCollection`, which will still contain all Microsoft registations. `IServiceCollection` is part of the Conforming Container abstraction.

When using `IControllerActivator`, you should still be able to use those `LoadModule` calls. That would look something like this:

``` c#
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllersWithViews();

    var container = DryIocBootstrapper.GetInstance()
        .Initialize(container, ...)
        .LoadModule(...);

    // Replace the built-in IControllerActivator with a custom one that forwards the call to DryIoc.
    services.AddSingleton<IControllerActivator>(new DryIocControllerActivator(container));
}
```
```

**Comment by aa-infr** [comment]
I've now the following code:  
I've moved the code from the method 
     public static IHostBuilder CreateHostBuilder(string[] args)
to  
     public void ConfigureServices(IServiceCollection services)

```
 public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllersWithViews();

            var container = new Container();
            DryIocBootstrapper.GetInstance()
                .Initialize(container, _optionsResolver, _connectionStringResolver)
                .LoadModules<Infrabel.ICT.Framework.RegistrationModule>()
                .LoadModules<Infrabel.ICT.Framework.Extended.AspNetCore.RegistrationModule>()
                .LoadModules<Infrabel.ICT.Framework.Extended.EntityFramework.RegistrationModule>()
                .LoadModules<ICT.Template.Api.RegistrationModule>()
                .BuildContainer();

....
```

And I have a DryIocControllerActivator 
```

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DryIoc;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Controllers;

namespace ICT.Template.Api
{
  public class DryIocControllerActivator : IControllerActivator
  {

    private readonly IContainer container;

    public DryIocControllerActivator(IContainer container)
    {
      if (container == null)
      {
        throw new ArgumentNullException("container");
      }

      this.container = container;
    }
    public object Create(ControllerContext context)
    {
      Type type = context.ActionDescriptor.ControllerTypeInfo.AsType();
      return this.container.Resolve(type);
    }

    public void Release(ControllerContext context, object controller)
    {
        //???
        //this.container.Release(controller);
    }
  }
}
```

But I get the following error:
Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Microsoft.AspNetCore.Authentication.IAuthenticationService Lifetime: Scoped ImplementationType: Microsoft.AspNetCore.Authentication.AuthenticationService': Unable to resolve service for type 'System.Func`1[Infrabel.ICT.Framework.Extended.AspNetCore.Authorization.IIdentityClaimRefiner[]]' while attempting to activate 'Infrabel.ICT.Framework.Extended.AspNetCore.Authorization.ClaimsRefinementTransformation'.) (Error while validating the service descriptor 'ServiceType: Microsoft.AspNetCore.Authentication.IClaimsTransformation Lifetime: Transient ImplementationType: Infrabel.ICT.Framework.Extended.AspNetCore.Authorization.ClaimsRefinementTransformation': Unable to resolve service for type 'System.Func`1[Infrabel.ICT.Framework.Extended.AspNetCore.Authorization.IIdentityClaimRefiner[]]' while attempting to activate 'Infrabel.ICT.Framework.Extended.AspNetCore.Authorization.ClaimsRefinementTransformation'.)

Is this because my custom container doesn't known anything about the Microsoft interfaces like IAuthenticationService ?

**Comment by dotnetjunkie** [comment]
> Is this because my custom container doesn't known anything about the Microsoft interfaces like IAuthenticationService ?

The exception is vague, but I think the exception happens because you are trying to resolve a `Scoped` instance outside the context of a Scope.

I must say that I'm not experienced with DryIoc, so you might want to move your questions about DryIoc to their forum, but you likely need something along the following lines:

``` c#
public class DryIocControllerActivator : IControllerActivator
{
    private readonly IContainer container;

    public DryIocControllerActivator(IContainer container) => this.container = container;

    public object Create(ControllerContext context)
    {
        var scope = this.container.OpenScope();
        context.HttpContext.Items[typeof(IScope)] = scope;
        return scope.Resolve(context.ActionDescriptor.ControllerTypeInfo.AsType());
    }

    public void Release(ControllerContext context, object controller)
    {
        var disposable = (IDisposable)context.HttpContext.Items[typeof(IScope)];
        disposable.Dispose();
    }
}
```

**Comment by aa-infr** [comment]
The solution you gave didn't solve the problem, but I want to give it a try with SimpleInjector
I’ve converted the sample application to a SimpleInjector container.

It is not yet working. I get a clean error which is not vague, so that is nice:
  
 ActivationException: The configuration is invalid. Creating the instance for type IRolePoliciesService failed. The constructor of type RolePoliciesService contains the parameter with name 'authorizationResolver' and type IOptionsResolver<AuthenticationAndAuthorizationOptions>, but IOptionsResolver<AuthenticationAndAuthorizationOptions> is not registered. For IOptionsResolver<AuthenticationAndAuthorizationOptions> to be resolved, it must be registered in the container. Verification was triggered because Container.Options.EnableAutoVerification was enabled. To prevent the container from being verified on first resolve, set Container.Options.EnableAutoVerification to false.
  
But I can’t solve this. 

In IoCBootstrapperBase I’ve the following registration concerning IOptionsResolver:

                _genericContainer.Register(typeof(OptionsResolver<>), RegistrationTarget.Interfaces, RegistrationLifeTime.Singleton);

The implementation for DryIoc is the following:  

```
        public IRegistrationContainer Register(Type concreteType, RegistrationTarget target,
            RegistrationLifeTime registrationLifeTime = RegistrationLifeTime.Transient, string key = null, bool shouldReplace = false)
        {
            var serviceTypeCondition = TargetResolver.Resolve(target);
            _container.RegisterMany(new[] { concreteType }, registrationLifeTime.ToContainerLifeTime(), serviceTypeCondition: serviceTypeCondition, serviceKey: ResolveKey(key), ifAlreadyRegistered: Map(shouldReplace));
            return this;
        }

```

But I don’t see how to implement this with SimpleInjector because RegisterMany doesn’t exist and something like serviceTypeCondition I don’t find also.

```
    public IRegistrationContainer Register(Type concreteType, RegistrationTarget target,
        RegistrationLifeTime registrationLifeTime = RegistrationLifeTime.Transient, string key = null, bool shouldReplace = false)
    {
      var serviceTypeCondition = TargetResolver.Resolve(target);

      _container.Register( concreteType);
      return this;
    }

```

**Comment by dotnetjunkie** [comment]
Try this:

```c#
container.Register(typeof(IOptionsResolver<>), typeof(OptionsResolver<>), Lifestyle.Singleton);
```

**Comment by aa-infr** [comment]
Thanks. This works.

In the definition of the framework I didn’t need to specify the interface IOptionsResolver<>, only the following
`_genericContainer.Register(typeof(OptionsResolver<>), RegistrationTarget.Interfaces, RegistrationLifeTime.Singleton);`

What would be the implementation of SimpleInjector for the following code?

```
        public IRegistrationContainer Register(Type concreteType, RegistrationTarget target,
            RegistrationLifeTime registrationLifeTime = RegistrationLifeTime.Transient, string key = null, bool shouldReplace = false)
        {
            var serviceTypeCondition = TargetResolver.Resolve(target);
            _container.RegisterMany(new[] { concreteType }, registrationLifeTime.ToContainerLifeTime(), serviceTypeCondition: serviceTypeCondition, serviceKey: ResolveKey(key), ifAlreadyRegistered: Map(shouldReplace));
            return this;
        }
```

How can I solve my next roadblock:
ActivationException: The constructor of type ConfigurationsFactory contains the parameter with name 'configurationsFactory' and type Func<IEnumerable<EntityBaseConfiguration>>, but Func<IEnumerable<EntityBaseConfiguration>> is not registered. For Func<IEnumerable<EntityBaseConfiguration>> to be resolved, it must be registered in the container.


The signature of the constructor for ConfigurationsFactory: 
`public ConfigurationsFactory(Func<IEnumerable<EntityBaseConfiguration>> configurationsFactory)`

This ConfigurationsFactory need to have a collection of all configuration mapping files related to Entity Framework
`	f.e. public class SampleConfiguration : EntityBaseConfiguration<Sample> `
(where Sample is the domain entity)
	
I suppose func is used to lazily load the collection IEnumerable<EntityBaseConfiguration>?
How can I register this with SimpleInjector?

**Comment by dotnetjunkie** [comment]
What other interfaces besides `IOptionsResolver<T>` does `OptionsResolver<T>` implement?

DryIoc's `Register({concrete type}, RegistrationTarget.Interfaces)` call performs some sort of Batch Registration where it registers the type based on all the interfaces it implements. This is only useful when a type has multiple interfaces and those interfaces tend to change over time. Such types of designs are a red flag, because it means that such a class in under constant change. This likely means the design violates [SRP](https://en.wikipedia.org/wiki/Single-responsibility_principle) and [OCP](https://en.wikipedia.org/wiki/Open%E2%80%93closed_principle) (which are explained in the book).

But because of that, Simple Injector has no convenient registration method to make these kinds of scenarios a one-liner.

If you need this, you have to bake such helper method yourself:

``` c#
public static void RegisterByInterfaces(this Container container, Type concreteType, Lifestyle lifestyle)
{
    foreach (Type iface in concreteType.GetInterfaces())
        container.Register(iface, concreteType, lifestyle);
}
```

DryIoc probably allows injecting `Func<IEnumerable<T>>` dependencies out of the box because `IEnumerable<T>` dependencies are pre-populated when their consumer is resolved. Simple Injector, however, works differently. Simple Injector considers most collection types (e.g. `IEnumerable<T>`, `ICollection<T>`, `IList<T>`, `Collection<T>`, `IReadOnlyCollection<T>`, etc) to be **streams**. This means that when injecting an `IEnumerable<EntityBaseConfiguration>` into an `ConfigurationsFactory`, no `EntityBaseConfiguration` component will be created. Only when the collection is iterated will Simple Injector start to construct them one by one.

This means that there is no need to inject a `Func<T>` to delay the creation of the collection; it is already delayed until iterated, which is why Simple Injector does, out of the box, not allow a `Func<IEnumerable<T>>` to be injected.

For more information about Simple Injector and collections, go [here](simpleinjector.org/collections).

If you don't want to change the constructor of your component, you can add the registration manually:

``` c#
container.RegisterInstance<Func<IEnumerable<EntityBaseConfiguration>>(
    () => container.GetAllInstances<EntityBaseConfiguration>());
```

**Comment by aa-infr** [comment]
All your suggestions solves the problems.

The next error:
`ActivationException: The constructor of type DbContextFactory contains the parameter with name 'namedResolvers' and type IList<KeyValuePair<string, Func<DbContextBase>>>, but IList<KeyValuePair<string, Func<DbContextBase>>> is not registered. For IList<KeyValuePair<string, Func<DbContextBase>>> to be resolved, it must be registered in the container. You can use one of the Container.Collection.Register overloads to register a collection of KeyValuePair<string, Func<DbContextBase>> types, or one of the Container.Collection.Append overloads to append a single registration to a collection. In case you intend to resolve an empty collection of KeyValuePair<string, Func<DbContextBase>> elements, make sure you register an empty collection; Simple Injector requires a call to Container.Collection.Register to be made, even in the absence of any instances. Please see https://simpleinjector.org/collections for more information about registering and resolving collections.`

I've tried with the following but it doesn't help:
`container.Collection.Register<IList<KeyValuePair<string, Func<DbContextBase>>>>(typeof(SampleDbContext).Assembly);`


The constructor of DbContextFactory is:
`public DbContextFactory(IList<KeyValuePair<string, Func<DbContextBase>>> namedResolvers, Func<DbContextBase> singleResolver, IDbContextResolver resolver)`
The purpose is to be able to work with multiple contexts from Entity Framework.

In DryIoc nothing had to be configured to let this work. What is needed for SimpleInjector?

**Comment by dotnetjunkie** [comment]
Hi @aa-infr,

It is unclear to me what it is you are trying to achieve, and how your code is structured. It seems that you are trying to plugin Simple Injector into a complex, existing application that was designed with a different DI Container in mind. It can be daunting switching from DI Containers as those libraries often have a different design philosophy, which might require different code structures and even a different way of approaching things. It’s hardly ever possible to swap DI Containers without having to change any of your code.

Since you are fixing one problem at the time, and working on a likely more complex application structure, you will probably find a dozen more issues that you need consulting on. But raising and answering these questions takes up a lot of time *for the both of us,* which I feel is not productive for me.

Don't get me wrong, I love to help developers helping out getting to know and understand Simple Injector, and showing how to do things "the Simple-Injector way." But there is an unfortunately a limit to the amount of time I can spend (and am willing to spend). Please keep in mind: I don't get paid for this work and am doing to do this all in my spare time. For the person asking the questions, it often seems as if I just whip up an answer in a matter of minutes, but that's unfortunately not the case. I already spent several hours on this thread in the past 7 days, reading and understanding your questions, testing code out in the IDE, and formulating and posting answers.

I really hate saying this, but I need to stop helping you.

As I see it you have three options: either you stick with DryIoc as it seems to meet your demands or, switch to yet another DI Container or, in case you really want to use Simple Injector, invest in understanding it by reading [its documentation](https://simpleinjector.org/wiki). There's a lot to go through, that’s for sure, but it is certainly worth your time if you feel that Simple Injector is the right tool for you.

Good luck.

**Comment by aa-infr** [comment]
I've first read your very interesting book Dependency Injection Principles, Practices, and Patterns.
Now I want to put this in practice so it does not only stay with theory.
It took me some time to extract just a part of the framework to a smaller example which I put https://github.com/aa-infr/SampleDI
It is only the part related to Entity Framework.

Apparently this seems not so an easy task.
I discover the errors one by one. I was thinking that the analysis feature of SimpleInjector could provide a list of all problems at once, but this seems not the case. But the errors provided by SimpleInjector are clear and that is what attracks me.
My end goal is to have in the framework an adapter for SimpleInjector. (same like it exists now for DryIoc).
Normally the task is only to provide a concrete implementation for the following interface:
```
using System;
using System.Linq;

namespace Infrabel.ICT.Framework.Ioc
{
    public interface IRegistrationContainer
    {
        IRegistrationContainer RegisterDecorator<TAbstract, TConcrete>(TConcrete instance, string key = "", bool shouldReplace = false) where TAbstract : class where TConcrete : class, TAbstract;

        IRegistrationContainer RegisterDecorator<TAbstract, TConcrete>(RegistrationLifeTime registrationLifeTime = RegistrationLifeTime.Transient, string key = "", bool shouldReplace = false) where TAbstract : class where TConcrete : class, TAbstract;

        IRegistrationContainer RegisterDecorator(Type abstractType, Type decorator,
            RegistrationLifeTime registrationLifeTime = RegistrationLifeTime.Transient, string key = "", bool shouldReplace = false);

        IRegistrationContainer Register<TAbstract, TConcrete>(TConcrete instance, Action<TAbstract> cleanupAction = null, string key = null, bool shouldReplace = false) where TAbstract : class
            where TConcrete : class, TAbstract;

        IRegistrationContainer Register<TAbstract, TConcrete>(RegistrationLifeTime registrationLifeTime = RegistrationLifeTime.Transient, Action<TAbstract> cleanupAction = null, string key = null, bool shouldReplace = false) where TAbstract : class
            where TConcrete : class, TAbstract;

        IRegistrationContainer RegisterFactory<TAbstract>(Func<IResolutionContainer, TAbstract> factoryFunc, RegistrationLifeTime registrationLifeTime = RegistrationLifeTime.Transient, string key = null, bool shouldReplace = false) where TAbstract : class;

        IRegistrationContainer Register(Type abstractType, Type concreteType, RegistrationLifeTime registrationLifeTime = RegistrationLifeTime.Transient, string key = null, bool shouldReplace = false);

        IRegistrationContainer Register(Type concreteType, RegistrationTarget target, RegistrationLifeTime registrationLifeTime = RegistrationLifeTime.Transient, string key = null, bool shouldReplace = false);

        IRegistrationContainer Register<TConcrete>(RegistrationTarget target, RegistrationLifeTime registrationLifeTime = RegistrationLifeTime.Transient, string key = null, bool shouldReplace = false);

        IRegistrationContainer BulkRegisterByMatchingType<TMatchingType>(ILookup<RegistrationInfo, Type> lookup, RegistrationTarget target);

        IRegistrationContainer BulkRegisterByMatchingType(Type matchingType, ILookup<RegistrationInfo, Type> lookup, RegistrationTarget target);

        IRegistrationContainer BulkRegisterByMatchingNamespace(ILookup<RegistrationInfo, Type> lookup, string matchingNamespace, RegistrationTarget target);

        IRegistrationContainer BulkRegisterByMatchingNamespaceWithChildren(ILookup<RegistrationInfo, Type> lookup, string matchingNamespace, RegistrationTarget target);

        IRegistrationContainer BulkRegisterByMatchingEndName(ILookup<RegistrationInfo, Type> lookup, string matchingEndName, RegistrationTarget target);

        IRegistrationContainer BulkRegisterByPredicate(ILookup<RegistrationInfo, Type> lookup, Func<Type, bool> predicate, RegistrationTarget target);
    }
}
```
When I see the implementation done for DryIoc I see that the class DryIocContainerAdapter only contains 193 lines of code.
Which is not so much in my opinion.
With SimpleInjector I think I'm nearly at the finish with the great help of you.
I've investigated a little bit further the last problem and I think that DryIoc is solving a constructor like the following all at its own:
`public DbContextFactory(IList<KeyValuePair<string, Func<DbContextBase>>> namedResolvers, Func<DbContextBase> singleResolver, IDbContextResolver resolver)
`

I've this suspicion by seeing the following code
https://github.com/dadhi/DryIoc/blob/master/src/DryIoc/Container.cs
![image](https://user-images.githubusercontent.com/78545777/107749940-9669e900-6d1b-11eb-8293-8c1bc011187b.png)

So my last question is:
How can a IList of KeyValuePairs of classes which have DbContextBase as a base class been injected. The key for the KeyValuePair is just the name of the concrete class. I don't mind if this is not done automatically but how could I register this than with SimpleInjector?
 
Hopefully you will just spend some time to this last question? Many thanks already!
