### ISSUE TITLE
Is it possible to compose collection items between them ?

### ISSUE THREAD

**Issue by t-dambacher** [simpleinjector/SimpleInjector#902]
I'm not sure how to sumarize this in a few words beside from what the title says, so let's just show some code:

I have the following settings classes that I use when configuring SimpleInjector, in the `Startup` class of an ASP.NET Core project:
``` c#
class AccountSettings {
    public string ApiKey { get; set; }
}

class AppSettings {
    public AccountSettings[] Accounts { get; set; }
}
```
From this list of `AccountSetting` objects, I'd like to register multiple collections of multiple services:

``` c#
interface IApiClient { }
class ApiClient : IApiClient 
{
    public ApiClient(AccountSettings settings) { }
}

interface IServiceA { }
class ServiceA : IServiceA 
{
    public ServiceA(IApiClient apiClient) { }
}

interface IServiceB { }
class ServiceB : IServiceB 
{
    public ServiceB(IServiceA, ILogger<ServiceB> logger) { }
}
```

I would like to have as many instances of `ApiClient`, `ServiceA`, and `ServiceB` as I have of `AccountSettings`, and each `AccountSettings` instance should have its own decicated object graph, its own `ApiClient`, `ServiceA` and `ServiceB`. Also, the number of `AccountSettings` that will be configured is unknown at compile time and can change through a configuration file.

In Pure DI, what I'm expecting would look like this, assuming that I have 3 instances of `AccountSettings`:

``` c#
AppSettings settings;
 
IEnumerable<IServiceB> servicesB = new[]
{
    new ServiceB(new ServiceA(new ApiClient(settings.Accounts[0])), new Logger<ServiceB>()),
    new ServiceB(new ServiceA(new ApiClient(settings.Accounts[1])), new Logger<ServiceB>()),
    new ServiceB(new ServiceA(new ApiClient(settings.Accounts[2])), new Logger<ServiceB>())
};
```
Note that the `Logger<ServiceB>` is coming from ASP.NET Core logging layer, I'm not sur that those are registered as transient instances. But at some point in my object graph, I have to interact with a logger cross wired from ASP.NET Core's DI.

I'm then basically attempting to inject a collection of `IServiceB` somewhere in my application, so I would need to have this working: `IEnumerable<IServiceB> services = container.GetAllInstance<IServiceB>();`

For now, I haven't been able to go further than the registration of the `ApiClient` objects. Those are singletons and, as I have seen in an other issue, should probably be registered with a delegate:

``` c#
container.Collection.Register<IApiClient>(
    settings.Accounts.Select(account => new ApiClient(account))
);
```
But I don't know how to go further than that, and I'm not even sure if what I'm asking is possible. What are your thoughts on this?

Thank you very much for you help. I'm sure you get this a lot, but I really appreciate your work and talk often about it.

**Comment by dotnetjunkie** [comment]
Thank you for posting the Pure DI version; that makes your question crystal clear.

Designs like these are problematic for Simple Injector, and likely most DI Containers. That's because in essence, a DI Container works with unique mappings. In your case, on the other hand, you have a collection that returns the same type (`ServiceB`) multiple times.

Simply registering `ServiceB` multiple times in a collection, however does not work with Simple Injector. It tries to "de-duplicate" registrations in order to prevent [Torn Lifestyles](https://simpleinjector.org/diatl). But having one registration also a single expression tree that describes the shape of the service. In your case that would result in a list of `ServiceB` instances that all point to the same `ApiKey`, which is the opposite of what you are trying to achieve.

Another limitation is that Simple Injector only allows determining a dependency on its direct parent. This allows, for instance, for a `Logger<X>` to be injected in `X`, and a `Logger<Y>` injected in `Y`. But you can't make a decision based on the parent of `X` for instance. Although some other DI Containers (e.g. Ninject) do allow this, with Simple Injector we explicitly decided to limit this, because this only works when that complete part of the object graph contains of Transient registrations. With any other lifestyle, you could easily see the wrong objects getting injected. There are multiple Stack Overflow questions about this problem in the context of Ninject.

Although the `AccountSettings` could be registered as a contextual dependency, it is always injected in an `ApiClient`, which means it is impossible to differentiate.

What this means is that your design touches the limitations of Simple Injector, and likely most DI Containers. This doesn't mean that your design is wrong, it's just a case that is less suited to be wired up automatically by a DI Container.

But there are a few workarounds you can apply:

1. Redesign these classes. For instance, it might be possible to inject the list of `AccountSettings` into `ServiceB` and iterate the list from inside `ServiceB`, while passing it along to `ServiceA` and `ApiClient`. This might break encapsulation of `ApiClient` and `ServiceA`. Whether that is acceptable is up to you.
2. Construct this part of your application by hand, similar to the code you demonstrated. For instance:
   ``` c#
   container.Register<IEnumerable<IServiceB>>(() =>
       from account in settings.Accounts
       select
           new ServiceB(
               new ServiceA(
                   new ApiClient(account)),
               container.GetInstance<ILogger<ServiceB>>()));
   ```

Your request is one that comes back from time to time. Although it's unlikely that Simple Injector will ever fully support your specific scenario, there are currently plans to reduce the pain in Simple Injector 6. See this [issue](https://github.com/simpleinjector/SimpleInjector/issues/889).

**Comment by t-dambacher** [comment]
Thank you for your detailed answer. 

I think I'll try to adapt the design so it's more adapted to be used with DI/auto wiring. My app only supported one instance of `AccountSettings` initially, and this new design would have allowed me to easily support multiple instances, but I'll admit that it might not be the best design in the long run. 

Again, many thanks for your help.
