### ISSUE TITLE
[Q] How to handle multiple scopes in parallel

### ISSUE THREAD

**Issue by maulwuff** [simpleinjector/SimpleInjector#907]
I have a MVVM WPF application, with a tabbed section, controlled by the main window viewmodel.
I let Simple Injector build the view models with `AsyncScopedLifestyle`, as they implement `IDisposable` (all of them).

Is this scope the right one to open multiple tabs? (So, one scope per tab page) What would be the right way to handle multiple scopes in such an interleaved way?
Each tab is allowed to open dialog views or sub-tabs on them, which need to go through Simple Injector, too. Of course each of them needs to sit in the right scope of the parent.

A valid workflow may be:
1. open tab 1  (start scope 1)
2. open tab 2  (start scope 2)
3. open subtab on tab 1  (needs to go to scope 1)
4. open subtab  on tab 2   (needs to go to scope 2)
5. close tab 1 (finishes every sub tab and itself, disposes of scope 1)

PS: is there a way to assign names or IDs to active scopes to get a better understanding in which scope an object was created?

**Comment by dotnetjunkie** [comment]
`AsyncScopedLifestyle` is not the right lifestyle for your use case. This lifestyle uses an ambient context, but with WPF, all your views/view models will run in the same context, which means the different scopes you create would interfere.

Instead, for this scenario, `ScopedLifestyle.Flowing` exists (the documentation is still a little sparse on this). With "flowing," Simple Injector will start to behave more like MS.DI and Autofac. This can be used as follows:

``` c#
var container = new Container();
container.Options.DefaultScopedLifestyle = ScopedLifestyle.Flowing;

using (var scope = new Scope(container))
{
   // NOTE: With Flowing, you resolve from the scope, not the container.
   var view = scope.GetInstance<MainView>();
}
```

The use of the flowing scoped lifestyle changes a few things internally:

* Collections containing `Transient` or `Scoped` components will no longer be injected as `Singleton` but as `Scoped`. This is needed because the collection now has to capture the current scope, where in ambient model, the scope is available, even when injected into a singleton.
* Decorators can't be injected with `Func<Decoratee>` delegates any longer, but instead need to be injected with `Func<Scope, Decoratee>` delegates.

> s there a way to assign names or IDs to active scopes to get a better understanding in which scope an object was created?

Sure:

``` c#
scope.SetItem("ID", Guid.NewGuid());

var id = (Guid)scope.GetItem("ID")
```

**Comment by maulwuff** [comment]
Thanks a lot. While researching I found the Flowing Scope, too, but no information in the documentation.
After your advice we sat down and managed to get rid of IDisposable for almost all cases :-)

**Comment by dotnetjunkie** [comment]
Documentation on this topic is still lacking behind.

**Comment by dotnetjunkie** [comment]
The documentation now contains information on [Flowing scopes](https://simpleinjector.org/lifestyles+flowing-scopes). If you have any comments on this new piece of text, let me know.
