### ISSUE TITLE
Cross wiring and concrete types

### ISSUE THREAD

**Issue by oruchreis** [simpleinjector/SimpleInjector#929]
Hi,
I've upgraded to v5 and I've added this event handler to check if there is unregistered concrete type:
```csharp
Container.ResolveUnregisteredType += (s, e) =>
{
    if (!e.Handled && !e.UnregisteredServiceType.IsAbstract)
    {
        _logger.Error($"UnregisteredServiceType: {e.UnregisteredServiceType}.");
    }
};
Container.Options.ResolveUnregisteredConcreteTypes = true;
```
Also, I have these setup in the startup.cs:
```csharp
//in ConfugureServices:
services.AddSimpleInjector(...);
services.AddDbContext<MembershipContext>();
services.AddIdentity().AddSignInManager<SignInManager>();

//in Configure
app.UseSimpleInjector(...);
```

When I try to resolve these instances via DI, it triggers the unregistered type handler:
```csharp
public class AccountController: Controller
{
    public AccountController(MembershipContext context, SignInManager manager)
    {
    }
}
```
It gives these logs:
```
UnregisteredServiceType: MembershipContext
UnregisteredServiceType: SignInManager
```

When I register these concrete types directly into the si container, it working well. But if I register via microsoft di, it doesn't cross wire these concrete types. Also if I set `ResolveUnregisteredConcreteTypes` option to false, then it throws unregistered type error when creating controller.

Is this a bug or expected behavior? How can I fix this instead of adding these types directly into the SI container?

**Comment by dotnetjunkie** [comment]
> if I set ResolveUnregisteredConcreteTypes option to false, then it throws unregistered type error when creating controller.

This likely happens because you didn't call `AddControllerActivation`. That call ensures that all controllers are registered in Simple Injector.

You probably followed the migration advise when going from v4 to v5. This caused you to add the  `ResolveUnregisteredType` event. Keep in mind that Simple Injector's cross-wiring feature depends on unregistered type resolution itself. If you move the hooking of the event to the end of the registration phase, it likely won't warn about those cross-wired services, because in that case they are already handled.
