### ISSUE TITLE
Drop WebActivator in favor of WebActivatorEx?

### ISSUE THREAD

**Issue by abatishchev** [simpleinjector/SimpleInjector#94]
Hi,
[WebActivator 1.0](https://www.nuget.org/packages/WebActivator/) is officially deprecated:

>The owner has unlisted this package. This could mean that the package is deprecated or shouldn't be used anymore. 

So there is [WebActivator 2.0 aka WebActivatorEx](https://www.nuget.org/packages/WebActivatorEx/) by the same author.

Additionally, more packages depend on [the later](http://nugetmusthaves.com/Dependencies/WebActivatorEx) rather than [the former](http://nugetmusthaves.com/Dependencies/WebActivator).

Doesn't it make sense to drop one in favor of another, please?

**Comment by dotnetjunkie** [comment]
The only Simple Injector packages that depend on WebActivator are the quick start packages. Those packages only contain a /content file which allows you to get started quickly with Simple Injector in a particular technology. With NuGet v3 content files are deprecated, which means that those quick start packages will loose their function. So from that perspective, upating those packages is a wast of time. Furthermore, although the old WebActivator package is unlisted, it still functions correctly and packages can not be removed from NuGet. From that perspective I don't see any reason to remove it.

Don't forget that those quick start packages are simply meant to get started quickly. Most (if not all) users will remove the quick start package later on, because when a project grows, you typically want to organize your code differently. This means removing the quick start package and this will also remove the dependency on the old WebActivator.
