### ISSUE TITLE
Using ExecutionContextScopeLifestyle / WebApiRequestLifestyle for async operations in MVC

### ISSUE THREAD

**Issue by dandcg** [simpleinjector/SimpleInjector#97]
Obviously async WebAPI registrations are set as WebApiRequestLifestyle and standard MVC registrations are set as WebRequestLifestyle. I'm looking for some guidance around async MVC methods. 
When using ConfigureAwait(false) the continuation may lose track of the original HttpContext - so WebRequestLifestyle doesn't seem to be best fit in this scenario. Or am I missing something?

Can you use WebApiRequestLifestyle or do you have to do some work around implementing ExecutionContextScopeLifestyle around a request etc?

**Comment by dotnetjunkie** [comment]
What you are seeing is described [here](https://simpleinjector.readthedocs.org/en/latest/lifetimes.html#web-api-request-lifestyle-vs-web-request-lifestyle). This behavior is 'by design' by ASP.NET.

What you can do is run async or background operations in their own execution context scope. This means that you will have to create an hybrid lifestyle as follows:

``` c#
container.Options.DefaultScopedLifestyle = Lifestyle.CreateHybrid(
    () => container.GetCurrentExecutionContextScope() != null,
    new ExecutionContextScopeLifestyle(),
    new WebRequestLifestyle());
```

and specific operations where this is important can be wrapped with the following:

``` c#
using (container.BeginExecutionContextScope())
{
    // wrapped operation here
}
```

Ideally you would obviously want to extract this `container.BeginExecutionContextScope()` call into some code that is part of your composition root, to ensure that your application code doesn't need a dependency on your DI container. You might need to extract an abstraction for this.

**Comment by dandcg** [comment]
Thanks for the prompt reply. This makes complete sense. So any places where this issue might occur create an explicit ExecutionContextScope around the lower awaited calls where they implement ConfigureAwait(false). Am I right in presuming by implementing the hybrid this new scope would supersede the current web request scope when created?

Out of interest is there a reason behind not having a specific scope that implements ExecutionContextScope per web request for MVC globally?

**Comment by dotnetjunkie** [comment]
> Am I right in presuming by implementing the hybrid this new scope would supersede the current web request scope when created?

Yes, the ExecutionContextScope superseeds a request scope. Note that inside the `BeginExecutionScope` block you should **resolve** a new object graph and use that!

> Out of interest is there a reason behind not having a specific scope that implements ExecutionContextScope per web request for MVC globally?

Multiple reasons. The `WebRequestLifestyle` existed since Simple Injector 2.0, where there was no good support for async await. The `WebRequestLifestyle` is therefore for .NET 4.0 and up, while the `ExecutionContextScopingLifestyle` is .NET 4.5 and up. For that reason allow, we can't just change the `WebRequestLifestyle`. Second reason, the behavior might change by doing this, which would be a breaking change. Third, no one ever asked us to do so.

You can build this yourself btw. This is actually quite easy to do. This would be the code to do so:

``` c#
[assembly: System.Web.PreApplicationStartMethod(typeof(ExecutionScopeHttpModule), "Initialize")]

public sealed class ExecutionScopeHttpModule : IHttpModule {
    public static void Initialize() {
        DynamicModuleUtility.RegisterModule(typeof(ExecutionScopeHttpModule));
    }

    void IHttpModule.Init(HttpApplication context) {
        context.BeginRequest += (sender, e) => {
            HttpContext.Current.Items["scope"] = Global.Container.BeginExecutionContextScope();
        };
        context.EndRequest += (sender, e) => {
            var scope = (Scope)HttpContext.Current.Items["scope"];
            if (scope != null) scope.Dispose();
        };
    }

    void IHttpModule.Dispose() { }
}
```

With this code, you can remove the dependency on SimpleInjector.Integration.Web.dll and your `DefaultScopedLifestyle` can be back to the following:

``` c#
container.Options.DefaultScopedLifestyle = new ExecutionContextScopeLifestyle();
```

WARNING: I have **NOT** tested this code in ANY way.

**Comment by dandcg** [comment]
Ideal - thanks for your detailed and clear response. I'll investigate these approaches. Would you have a view on recommended way - i.e. your personal preference?

**Comment by dotnetjunkie** [comment]
I've got no experience with this, and no personal preference. Use what works best for you :-)

**Comment by dandcg** [comment]
Ah ok cool. No worries. Thanks for your help.
